table E5_DIM_RISK_STATEMENT
	lineageTag: 9830b36b-e1d6-42cd-b5d1-d787bcb2e4cc

	column RISK_STATEMENT
		dataType: string
		lineageTag: 1b698c23-4727-4864-84a4-1617ac507409
		summarizeBy: none
		sourceColumn: RISK_STATEMENT

		annotation SummarizationSetBy = Automatic

	column RISK_STATEMENT_ID
		dataType: int64
		formatString: 0
		lineageTag: 1569f3f6-dbbc-45fd-8c17-48bf79ca0732
		summarizeBy: count
		sourceColumn: RISK_STATEMENT_ID

		annotation SummarizationSetBy = Automatic

	column RISK_STATEMENT_COLOR
		dataType: string
		lineageTag: e41cc630-513f-405f-a12e-ef05d7cba228
		summarizeBy: none
		sourceColumn: RISK_STATEMENT_COLOR

		annotation SummarizationSetBy = Automatic

	partition E5_DIM_RISK_STATEMENT = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zVbLcts2FP0VjLtxZuRYIvVcWqoz9Uw7ydjZpVnAxBWFGgRYAJSrrvIh6c/lS3ovCD4sUXG668aSKeKcc8994dOni8nbCbsHBXuuPeMWuGNmy/6orHRCZl4aTU+ZNp65aruVmQTt1YFJgZ9yK0FcjC4mE/zz03g8XS1mF59HhJqwTeW8KcCy36vxOJmzgtsnQI7cAhR42DGuBXMlZAiTcaJyw1xcyVyDYM/S75h9RSxiKsi5whf/rKTtUZ3gCpNV9HMdQ3IUQ9J3xkJeqahxayzzO2Dr9w+bX1hpjagyzy7hLw9WczViUtff3vyAdUm0bp6sbiJtcp7WVWWpJHpacuvPuPUSPjmBT8/DK5NL52Xm2DUToOQe7OFHSNIjkjRYF7ANIrzIxH9wT+pMvWXfvny90/uQpnD4V7mFb1/+GdYlwKJqEfKdYVio0+K/UgfOhq0vCKWnMQeL9WYc9SfswXMPVF50EN1mlw/G36AoN8S6lVSg16wqBa/rKU1OQHvOC8gUt8H6BhHF7VGuGHUlvjOFwZzUr12zDKxve6U5Zh49J3KiTE8op+yhKZmjxmuK///Tgen0RP6MfYgpy0yBYXCdQSiCLpMKNUBAj89IQ/N4KFncucrWhLMTwvkQIVZPhz1qO2PUqijMPkQZZHjLteNZP0fn+OdH/FPsm4/gPOX6kCnAODKTaxmw4hg1pZeF/JufxS8t7BtLp7GyV/PbZWRIqKHuAdPzbKwSiAd1HVJPYaR7zLXgfcbGTI/K3CshTZMjwhmGNGCpqBDPoHEYnLFS51RGjZ2heXdc5+BoRHEr6IW4P1pR3ej6vqRZ8GA2X4/fvYuSkiFJVNtdplsBr4AnJ+DpEHgXhpCuNI6raxwBpiikcxgD/dAGRqmnB68wpyfM08GwrO9mOZrsSurwsD9GzIHdS3ypXdE0fHVd9N9nnx6xzzHPNwzHwBOmj6uDw/P9aRH7thG46QTGEfthcxPHtLTsbvNA49tbo8KUaWckWEQpcBL1daGUeZ3k2/XPyyTqSdjHHcQ6seyKcc+ojqm8dMUVhoPPUCQoRZ+haa4ErQ+N6HYPh1CIbTSok8JzBPT+9gqjAjyoDGaK9AfLwXdLRuGeim082KZNKKQ+OVK/CG7iKwXXNFeMzbmOTY+d67xFBkxFUNjOY3QLousdFf7sTGUz6EY79jF/VNLtAvkiWLdYTG7xW02eDOWJAsT4NKKe2xJ7LhUiA6EmR6hLDOlOU8ix2wGRzQEI7NFUvmu8jjJcEL0FnaPDoUnI6cv45pv+q1mlgiEnVqOMZYhwPZmlN+uoBYvDYrETZIbD2/L8zNHk5Gg6ZM49lAaXc9e1XODyw6sA3ZWoMNott0yPEFdozGYH2VO9I3kl5LmrXb9mViGoyXKZLm4jToIGi3aRdyNnwFkcO1UvjXRVQr01y9YoZZ5BXFUl8SQnPCn7DRsJ3a5vcxifbRZgb4r389gU3nYLuBj35ArFCgN3KHr+0rFV2lfw+V8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RISK_STATEMENT = _t, RISK_STATEMENT_ID = _t, RISK_STATEMENT_COLOR = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RISK_STATEMENT", type text}, {"RISK_STATEMENT_ID", Int64.Type}, {"RISK_STATEMENT_COLOR", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

