table E5_LEVEL2_RISK
	lineageTag: cabe9268-5179-4022-b559-aaf552b73b4a

	column RISK_GROUP
		dataType: string
		lineageTag: be27304e-b7c1-4003-b7e2-1ff2bdac5605
		summarizeBy: none
		sourceColumn: RISK_GROUP

		annotation SummarizationSetBy = Automatic

	column RISK_CATEGORY
		dataType: string
		lineageTag: 26408e8c-35cc-4afa-a4c7-55d54bd0a7f0
		summarizeBy: none
		sourceColumn: RISK_CATEGORY

		annotation SummarizationSetBy = Automatic

	column RISK_STATEMENT
		dataType: string
		lineageTag: 19e7141f-2b15-4aa2-8743-220bed8bd179
		summarizeBy: none
		sourceColumn: RISK_STATEMENT

		annotation SummarizationSetBy = Automatic

	partition E5_LEVEL2_RISK = m
		mode: import
		source =
				let
				    Source = Oracle.Database("REDLake_ZeusD_OpsDevSup_CI.world", [HierarchicalNavigation=true, Query="#(tab)SELECT #(lf)#(tab)#(tab)DISTINCT RISK_STATEMENT#(lf)#(tab)#(tab), RISK_CATEGORY#(lf)#(tab)#(tab), RISK_GROUP #(lf)#(tab)FROM MARD_PCMS.X_IFR_EPIC5_BKMS_COM_CASE#(lf)"]),
				    #"Reordered Columns1" = Table.ReorderColumns(Source,{"RISK_STATEMENT", "RISK_CATEGORY", "RISK_GROUP"})
				in
				    #"Reordered Columns1"

	annotation PBI_ResultType = Table

