table 'DIA Brain Professional'
	lineageTag: 84c57f03-618b-4f6d-990d-5e7607eba963

	column 'Use Case Owner'
		dataType: string
		lineageTag: 232a3a27-3543-4a07-aa65-0d7e02d221da
		summarizeBy: none
		sourceColumn: Use Case Owner

		annotation SummarizationSetBy = Automatic

	column 'DIA Brain users for that use case'
		dataType: string
		lineageTag: d73e8f1a-d068-4e54-9876-b0e28a420fc4
		summarizeBy: none
		sourceColumn: DIA Brain users for that use case

		annotation SummarizationSetBy = Automatic

	column 'Use Cases'
		dataType: string
		lineageTag: 8ff16e0f-cc6a-4b55-937f-b57325f1fb31
		summarizeBy: none
		sourceColumn: Use Cases

		annotation SummarizationSetBy = Automatic

	column 'Number of DIA Brains'
		dataType: string
		lineageTag: a967efff-f2f1-48fc-924e-0060e38cddf7
		summarizeBy: none
		sourceColumn: Number of DIA Brains

		annotation SummarizationSetBy = Automatic

	column 'Status usage'
		dataType: string
		lineageTag: b4ee1f54-bf7b-48a9-809f-870a0cf9bbbd
		summarizeBy: none
		sourceColumn: Status usage

		annotation SummarizationSetBy = Automatic

	column 'Cost center'
		dataType: string
		lineageTag: a1f6e5b8-9b96-4be7-b249-73547c7492bf
		summarizeBy: none
		sourceColumn: Cost center

		annotation SummarizationSetBy = Automatic

	column 'Reason for cancellation'
		dataType: string
		lineageTag: bd0b4b53-37ed-4ab7-90e6-d62654da0d57
		summarizeBy: none
		sourceColumn: Reason for cancellation

		annotation SummarizationSetBy = Automatic

	column 'Month of cancellation'
		dataType: string
		lineageTag: 40282040-443c-4af5-912c-a2b2fae26b18
		summarizeBy: none
		sourceColumn: Month of cancellation

		annotation SummarizationSetBy = Automatic

	partition 'DIA Brain Professional' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bosch.sharepoint.com/sites/msteams_2839467/Shared%20Documents/General/Gen-AI Enablement/GenAI%20UseCase%20Tracking_BDVN%20DAD_2025-03-04.xlsx"), null, true),
				    #"new" = Source{[Item="DIA Brain Professional",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(new, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

