table Data
	lineageTag: 8522a337-dcc9-4fd2-806e-c99ef5de0758

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 91df5aec-c5bf-48a8-aa29-28f5de9bb0d4
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Seller ID'
		dataType: int64
		formatString: 0
		lineageTag: 745e0a4e-33af-43dc-8b9e-adf65f4859aa
		summarizeBy: count
		sourceColumn: Seller ID

		annotation SummarizationSetBy = Automatic

	column 'Buyer ID'
		dataType: int64
		formatString: 0
		lineageTag: f5722260-2c29-4c6c-97be-f22bb7f59476
		summarizeBy: count
		sourceColumn: Buyer ID

		annotation SummarizationSetBy = Automatic

	column 'Order value'
		dataType: int64
		formatString: 0
		lineageTag: 67d99c92-e75e-4c10-bf39-ed18bf25ced6
		summarizeBy: sum
		sourceColumn: Order value

		annotation SummarizationSetBy = Automatic

	column 'Seller Province'
		dataType: string
		lineageTag: 3eeb5b58-e1c8-41a2-ab88-99a4699888c3
		summarizeBy: none
		sourceColumn: Seller Province

		annotation SummarizationSetBy = Automatic

	column 'Buyer Province'
		dataType: string
		lineageTag: a6e39827-e3bb-4f4d-b43c-3af2ed0505f8
		summarizeBy: none
		sourceColumn: Buyer Province

		annotation SummarizationSetBy = Automatic

	column 'Seller Region'
		dataType: string
		lineageTag: 094ed87e-1506-460a-8b5d-45b0b61302c1
		summarizeBy: none
		sourceColumn: Seller Region

		annotation SummarizationSetBy = Automatic

	column 'Buyer Region'
		dataType: string
		lineageTag: d8c53164-7a01-495f-acf5-0ce86be50834
		summarizeBy: none
		sourceColumn: Buyer Region

		annotation SummarizationSetBy = Automatic

	column 'Recipient shipping address'
		dataType: string
		lineageTag: dbf82200-1a9f-4fe7-b087-5c2b08b355e5
		summarizeBy: none
		sourceColumn: Recipient shipping address

		annotation SummarizationSetBy = Automatic

	column 'Buyer Type'
		dataType: string
		lineageTag: f1fa3c50-c6f9-4ae4-85a4-858540275be3
		summarizeBy: none
		sourceColumn: Buyer Type

		annotation SummarizationSetBy = Automatic

	column Route
		dataType: string
		lineageTag: e3359de3-588a-4ef1-9524-dcc30b7aa754
		summarizeBy: none
		sourceColumn: Route

		annotation SummarizationSetBy = Automatic

	partition Data-97b75c5b-5fdd-421f-8ef3-d8bd50f63d17 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bosch-my.sharepoint.com/personal/dmo5hc_bosch_com/Documents/XAB3_TEAM/REFERENCE%20PROJECTS/_Shopee_Excel%20test_.xlsx"), null, true),
				    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", Int64.Type}, {"Seller ID", Int64.Type}, {"Buyer ID", Int64.Type}, {"Order value", Int64.Type}, {"Seller Province", type text}, {"Buyer Province", type text}, {"Seller Region", type text}, {"Buyer Region", type text}, {"Recipient shipping address", type text}, {"Buyer Type", type text}, {"Route", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

