table _MEASURES
	lineageTag: e8b63d90-4fcb-4ca5-bd4c-ef380279de88

	measure SUM_ASSESSMENT_NODE =
			CALCULATE (
			    COUNT ( E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_NODE_ID] ),
			    E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			)
		formatString: #,0
		lineageTag: c15a0820-cdca-45c3-b6a9-06e303954bea

	measure TOTAL_ASSESSMENT_NODE =
			CALCULATE (
			    COUNT ( E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_NODE_ID] ),
			    FILTER (
			        ALLEXCEPT (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[PRJ_REGION],
			            E8_X_IFR_ONEQ_EPIC8_HLCP[PRJ_COUNTRY],
			            E8_X_IFR_ONEQ_EPIC8_HLCP[OE_CODE],
			            E8_X_IFR_ONEQ_EPIC8_HLCP[BU_CODE],
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENT_MEETINGDATE]
			        ),
			        E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			    )
			)
		formatString: #,0
		lineageTag: 7dc5c6f8-baf0-484a-85c0-dffa6d03e9bd

	measure HLCP1_WORST_COLOR =
			VAR vHLCP = "HLCP 1"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: ae28bb3f-d973-4b82-bba5-973e27511984

	measure HLCP2_WORST_COLOR =
			VAR vHLCP = "HLCP 2"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: 581adcfc-c224-4ba6-be3a-871a19fd9075

	measure HLCP3_WORST_COLOR =
			VAR vHLCP = "HLCP 3"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: 7154299a-b0a7-40f2-b1da-b467f9d0dc0b

	measure HLCP4_WORST_COLOR =
			VAR vHLCP = "HLCP 4"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: ee6917b9-dfd4-430b-a9c5-b520407b1994

	measure HLCP5_WORST_COLOR =
			VAR vHLCP = "HLCP 5"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: 426d0ba3-666c-429f-9806-3af1656e848c

	measure HLCP6_WORST_COLOR =
			VAR vHLCP = "HLCP 6"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: 391685ff-e56f-4bd0-82c2-1cb19aade5a1

	measure HLCP7_WORST_COLOR =
			VAR vHLCP = "HLCP 7"
			VAR WORST_RATING =
			    CALCULATE (
			        MIN ( E8_DIM_RATINGNAME[ID_RATING] ),
			        FILTER (
			            E8_X_IFR_ONEQ_EPIC8_HLCP,
			            E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_TYPE] = "focus-area"
			                && E8_X_IFR_ONEQ_EPIC8_HLCP[HLCP_CODE] = vHLCP
			        )
			    )
			VAR RESULT = LOOKUPVALUE (
			        E8_DIM_RATINGNAME[RATING],
			        E8_DIM_RATINGNAME[ID_RATING], WORST_RATING
			    )
			RETURN
			    IF(ISBLANK(RESULT), "no data", RESULT)
		lineageTag: c1d81574-3f56-47e0-bc87-fad41ade1444

	measure TITLE_ASMT_PER_HLCP = REPT([WhiteSpace],2) & "Assessments per HLCP"
		displayFolder: TITLE
		lineageTag: 144558b6-0e86-4d2c-bc2e-562157c25dbe

	measure WhiteSpace = UNICHAR(8192)
		lineageTag: 3237b69d-76ea-4911-a3cd-1173ef3c0820

	measure TITLE_ASMT_PER_HLCP_SUB = REPT([WhiteSpace],3) & "Total number of assessments by rating per HLCP"
		displayFolder: TITLE
		lineageTag: 46822816-1f73-43c8-8e37-0efc89562112

	measure TITLE_ASMT_BY_RATING = REPT([WhiteSpace],2) & "Assessments by rating"
		displayFolder: TITLE
		lineageTag: cad46b25-23ec-4ac6-aad0-3c358836ef0b

	measure TITLE_ASMT_BY_RATING_SUB = REPT([WhiteSpace],3) & "Total number of assessments by rating status"
		displayFolder: TITLE
		lineageTag: 5398b633-48ed-4343-ba18-cb15c8b30d21

	measure TITLE_ASMT_RATING_PER_HLCP = REPT([WhiteSpace],4) & "Rating per HLCP"
		displayFolder: TITLE
		lineageTag: c070ec22-21b3-48c1-baa4-728e43a4aaac

	measure TITLE_ASMT_RATING_PER_HLCP_SUB = REPT([WhiteSpace],6) & "Percentage rating of assessments per HLCP"
		displayFolder: TITLE
		lineageTag: 4b6fdfa4-5fce-40f3-81f7-d3259ca05183

	measure SUM_ASMT_RISKCOUNT = SUM(E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_RISKSCOUNT])
		formatString: #,0
		lineageTag: 4f567f12-4e93-4838-9f7f-69053b131d4e

	measure SUM_ASMT_MEASURESCOUNT = SUM(E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_MEASURESCOUNT])
		formatString: #,0
		lineageTag: 53c6f993-cdf4-4b69-a00e-3cb9de348822

	measure SUM_ASMT_DOCUMENTSCOUNT = SUM(E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_DOCUMENTSCOUNT])
		formatString: #,0
		lineageTag: cdb7da7b-3e3e-403b-be4d-9c54871c3df7

	measure SUM_ASMT_OVERDUEMEASURESCOUNT = SUM(E8_X_IFR_ONEQ_EPIC8_HLCP[ASSESSMENTTREE_OVERDUEMEASURESCOUNT])
		formatString: #,0
		lineageTag: 48294eb4-1d68-4b0e-8c09-995d9b7f1a2c

	column MEASURES
		dataType: int64
		formatString: 0
		lineageTag: 08588f90-e6ce-4529-affc-ebf2bdd8cb6f
		summarizeBy: sum
		sourceColumn: MEASURES

		annotation SummarizationSetBy = Automatic

	partition _MEASURES-fa19d852-d440-4884-a977-a4a8c875474b = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MEASURES = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MEASURES", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

