table DIM_DATE
	lineageTag: 5d18dbb8-c8ee-45fa-9cf3-4174cf0dde7b

	column FullDateAlternateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: bbbd6d8a-dd56-487f-b747-66a982abbf49
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: double
		lineageTag: 3319b9cf-8128-4fc9-8a35-24eb45485ae4
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: double
		lineageTag: ab13b553-f624-4a0a-95af-2987375a31cb
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: e6f967fd-5a07-4524-8567-fc4185afdbd8
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: double
		lineageTag: 85141d5a-5768-4f01-bf20-dfd29dc96fb1
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year'
		dataType: double
		lineageTag: dce159d8-3389-40ba-b016-67d654f2b65d
		summarizeBy: sum
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Month'
		dataType: double
		lineageTag: 60c906ec-07a5-4e2e-838d-ca7ecd53af9f
		summarizeBy: sum
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: double
		lineageTag: 85dbcfe2-6a2a-4a56-83a7-4735ce3724c6
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: double
		lineageTag: 6fd6c71b-807b-4f33-a5a3-d4e922496c8e
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Year'
		dataType: double
		lineageTag: 1adf69c0-05b2-4670-8f05-777703b67d99
		summarizeBy: sum
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name'
		dataType: string
		lineageTag: 9406ec1b-3d76-4b96-9581-de8e835f3736
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Short Month Name'
		dataType: string
		lineageTag: 490a0b2e-1748-4cba-a23c-f2e2fc603eb6
		summarizeBy: none
		sourceColumn: Short Month Name

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE-60b1acf6-4be4-4e79-89f9-5ed27cb71e10 = m
		mode: import
		source =
				let
				    StartDate = #date(StartYear,1,1),
				    EndDate = #date(EndYear,12,31),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "FullDateAlternateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FullDateAlternateKey", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([FullDateAlternateKey]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([FullDateAlternateKey]), type number),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([FullDateAlternateKey]), type text),
				    #"Inserted Short Month Name" = Table.AddColumn(#"Inserted Month Name", "Short Month Name", each Text.Start(Date.MonthName([FullDateAlternateKey]),3), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Short Month Name", "Quarter", each Date.QuarterOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([FullDateAlternateKey]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([FullDateAlternateKey]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([FullDateAlternateKey]), type number),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([FullDateAlternateKey]), type text)
				in
				    #"Inserted Day Name"

	annotation PBI_ResultType = Table

