table E8_X_IFR_ONEQ_EPIC8_HLCP
	lineageTag: 6b36eb09-461c-4cfa-ac44-320339c9c85b

	column ASSESSMENTTREE_TYPE
		dataType: string
		lineageTag: a499c1e6-f887-4d54-85ad-2237f5e4cae6
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_TYPE

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_NODE_ID
		dataType: string
		lineageTag: 485c1192-f193-4e1a-b77b-dc26fd0b4ea8
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_NODE_ID

		annotation SummarizationSetBy = User

	column ASSESSMENTTREE_RATING_VALUE_NAME
		dataType: string
		lineageTag: e80d2097-260b-480c-be0e-f2d54e37d45e
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_RATING_VALUE_NAME
		sortByColumn: 'DIM_RATINGNAME.1.ID_RATING'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ASSESSMENT_MEETINGDATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 21faf11e-bee3-48e9-b47f-ee588983ba93
		summarizeBy: none
		sourceColumn: ASSESSMENT_MEETINGDATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PRJ_REGION
		dataType: string
		lineageTag: 77ca2af9-a6f1-4e78-a24d-bea7302997a3
		summarizeBy: none
		sourceColumn: PRJ_REGION

		annotation SummarizationSetBy = Automatic

	column PRJ_COUNTRY
		dataType: string
		lineageTag: 56edc00f-b7c3-43d8-baf5-81ddc04008ab
		summarizeBy: none
		sourceColumn: PRJ_COUNTRY

		annotation SummarizationSetBy = Automatic

	column ASSESSMENT_LEVEL_NAME
		dataType: string
		lineageTag: 4f36cfa2-0d3a-4046-ba56-d29f822f52d4
		summarizeBy: none
		sourceColumn: ASSESSMENT_LEVEL_NAME

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_MEASURESCOUNT
		dataType: int64
		formatString: 0
		lineageTag: 2af6ced7-e570-4eb6-827d-d07b30b9d427
		summarizeBy: sum
		sourceColumn: ASSESSMENTTREE_MEASURESCOUNT

		annotation SummarizationSetBy = Automatic

	column HLCP_CODE
		dataType: string
		lineageTag: 66e35811-2665-40d1-902b-8205fef0d35b
		summarizeBy: none
		sourceColumn: HLCP_CODE

		annotation SummarizationSetBy = Automatic

	column 'DIM_RATINGNAME.1.ID_RATING'
		dataType: int64
		formatString: 0
		lineageTag: 041101fc-d0ce-42b8-bb0f-78d7d6fa96ac
		summarizeBy: none
		sourceColumn: DIM_RATINGNAME.1.ID_RATING

		annotation SummarizationSetBy = Automatic

	column PRJ_NAME
		dataType: string
		lineageTag: 6e3b1e78-0aa4-4372-8fb6-31ece08c1e65
		summarizeBy: none
		sourceColumn: PRJ_NAME

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_CRITERION_NAME
		dataType: string
		lineageTag: d59e7ce6-78e7-465a-8b6f-e7acbdaadc8e
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_CRITERION_NAME

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_STATEMENT
		dataType: string
		lineageTag: d9e4cd3b-2a00-43bc-8acc-41ec02da278f
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_STATEMENT

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_CRITERION_QUESTION
		dataType: string
		lineageTag: a1c94ed0-e06b-4ccc-a890-ac0f93d41599
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_CRITERION_QUESTION

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_CRITERION_STATUS
		dataType: string
		lineageTag: 74b91253-da85-4ca3-9875-e1fb8abd913e
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_CRITERION_STATUS

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_RISKSCOUNT
		dataType: int64
		formatString: 0
		lineageTag: 1865737e-32f4-4146-848a-48aa298cabc2
		summarizeBy: sum
		sourceColumn: ASSESSMENTTREE_RISKSCOUNT

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_DOCUMENTSCOUNT
		dataType: int64
		formatString: 0
		lineageTag: daa60aae-7494-4e1a-8e1c-9be9c3e029ac
		summarizeBy: sum
		sourceColumn: ASSESSMENTTREE_DOCUMENTSCOUNT

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_OVERDUEMEASURESCOUNT
		dataType: int64
		formatString: 0
		lineageTag: 6b96dea1-e4e3-4117-ac43-60863a47e2c7
		summarizeBy: sum
		sourceColumn: ASSESSMENTTREE_OVERDUEMEASURESCOUNT

		annotation SummarizationSetBy = Automatic

	column PRJ_RESPONSIBLE_DEPARTMENT
		dataType: string
		lineageTag: 78588fd0-b095-4dee-bb8d-72840e20052d
		summarizeBy: none
		sourceColumn: PRJ_RESPONSIBLE_DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column PRJ_CUSTOMER_CODE
		dataType: string
		lineageTag: 8b4f87c0-321a-4150-83cb-d40eb7bedbe7
		summarizeBy: none
		sourceColumn: PRJ_CUSTOMER_CODE

		annotation SummarizationSetBy = Automatic

	column PRJ_CUSTOMER_DESCRIPTION
		dataType: string
		lineageTag: a6cf8897-8f9e-4f73-b4e0-1bfce4f0855e
		summarizeBy: none
		sourceColumn: PRJ_CUSTOMER_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column PRJ_SOPCUSTOMER
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1aa301a4-dd65-4c78-8bae-e00c11c9fff5
		summarizeBy: none
		sourceColumn: PRJ_SOPCUSTOMER

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRJ_MCRID
		dataType: string
		lineageTag: 7601442c-baf4-4307-bec8-63be42e72d4c
		summarizeBy: none
		sourceColumn: PRJ_MCRID

		annotation SummarizationSetBy = Automatic

	column PRJ_IGPMPROGRAM_NAME
		dataType: string
		lineageTag: 2d29d542-bdc1-4663-9de0-a19d42046769
		summarizeBy: none
		sourceColumn: PRJ_IGPMPROGRAM_NAME

		annotation SummarizationSetBy = Automatic

	column PRJ_ORDERCATEGORY_DESCRIPTION
		dataType: string
		lineageTag: a031811a-d5da-43c4-8f8d-3852ac21d294
		summarizeBy: none
		sourceColumn: PRJ_ORDERCATEGORY_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column PRJ_ORDERTYPE_DESCRIPTION
		dataType: string
		lineageTag: 4d983881-0e12-46d8-a033-70246c89370e
		summarizeBy: none
		sourceColumn: PRJ_ORDERTYPE_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column PRJ_IMPACTCATEGORY_CODE
		dataType: string
		lineageTag: 7134b6c0-a5ed-44dd-8512-07f33227500b
		summarizeBy: none
		sourceColumn: PRJ_IMPACTCATEGORY_CODE

		annotation SummarizationSetBy = Automatic

	column PRJ_INNOVATIONCOMPLEXITY_CODE
		dataType: string
		lineageTag: dd345e6a-cc05-4e07-a1a9-3e4a108584ff
		summarizeBy: none
		sourceColumn: PRJ_INNOVATIONCOMPLEXITY_CODE

		annotation SummarizationSetBy = Automatic

	column ASSESSMENT_CATALOG_DESCRIPTION
		dataType: string
		lineageTag: f3fe2f1c-9af2-4c59-ab96-e30d72cc9987
		summarizeBy: none
		sourceColumn: ASSESSMENT_CATALOG_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column ASSESSMENT_CATALOG_DISPLAYNAME
		dataType: string
		lineageTag: d5e1573b-c6ad-4803-8803-67e6c4563b6e
		summarizeBy: none
		sourceColumn: ASSESSMENT_CATALOG_DISPLAYNAME

		annotation SummarizationSetBy = Automatic

	column ASSESSMENT_TYPE_DESCRIPTION
		dataType: string
		lineageTag: a418c4f2-ab5e-4609-9737-bbf797df5e27
		summarizeBy: none
		sourceColumn: ASSESSMENT_TYPE_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column PRJ_STATUS_CODE
		dataType: string
		lineageTag: a6f8ea4a-758a-405c-88f0-ee70b63195f5
		summarizeBy: none
		sourceColumn: PRJ_STATUS_CODE

		annotation SummarizationSetBy = Automatic

	column ASSESSMENTTREE_CRITERION_SHORTID
		dataType: string
		lineageTag: c73ed4ae-4674-42d1-b293-94217af6b0db
		summarizeBy: none
		sourceColumn: ASSESSMENTTREE_CRITERION_SHORTID

		annotation SummarizationSetBy = Automatic

	column PRJ_SHORTID
		dataType: string
		lineageTag: 10acbe93-a6cd-4ad4-baa4-4b2b587da9d5
		summarizeBy: none
		sourceColumn: PRJ_SHORTID

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 793f2716-b83c-455a-b43a-30af2d08ea23
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 9f231332-c73d-4a51-a2fb-dda0df46fe90
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: ac12806b-5ec6-4376-83a7-5b59075c2cec
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: dddd0d35-3713-4779-813f-44331bb69091
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column OE_CODE
		dataType: string
		lineageTag: 93c8800d-7707-43f8-817f-7ac2601beebd
		summarizeBy: none
		sourceColumn: OE_CODE

		annotation SummarizationSetBy = Automatic

	column BU_CODE
		dataType: string
		lineageTag: 5bee9c7f-02e7-423b-93aa-da3190158b7c
		summarizeBy: none
		sourceColumn: BU_CODE

		annotation SummarizationSetBy = Automatic

	partition E8_X_IFR_ONEQ_EPIC8_HLCP-7008b114-e3a6-46ee-a47d-1bbe49cc5ee0 = m
		mode: import
		source = ```
				let
				    TopRowsPara = if NumberOfRows > 0 then " FETCH FIRST " & Number.ToText(NumberOfRows) & " ROWS ONLY" else "",
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, 
				    Query="SELECT
				    CONTINENT_CODE, 
				    CONTINENT AS ""PRJ_REGION"", 
				    COUNTRY_GROUP_CODE, 
				    COUNTRY_GROUP, 
				    COUNTRY_ISO_CODE, 
				    COUNTRY_DISPLAY_TEXT AS ""PRJ_COUNTRY"",
				    OE_CODE,
				    BU_CODE,
				    PRJ_NAME,
				    ASSESSMENTTREE_TYPE,
				    ASSESSMENTTREE_NODE_ID,
				    ASSESSMENTTREE_RATING_VALUE_NAME,
				    ASSESSMENT_MEETINGDATE,
				    ASSESSMENT_LEVEL_NAME,
				    ASSESSMENTTREE_CRITERION_SHORTID,
				    ASSESSMENTTREE_CRITERION_NAME,
				    ASSESSMENTTREE_STATEMENT,
				    ASSESSMENTTREE_CRITERION_QUESTION,
				    ASSESSMENTTREE_CRITERION_STATUS,
				    ASSESSMENTTREE_RISKSCOUNT,
				    ASSESSMENTTREE_DOCUMENTSCOUNT,
				    ASSESSMENTTREE_OVERDUEMEASURESCOUNT,
				    ASSESSMENTTREE_MEASURESCOUNT,
				    HLCP_CODE,
				    PRJ_RESPONSIBLE_DEPARTMENT,
				    PRJ_CUSTOMER_CODE,
				    PRJ_CUSTOMER_DESCRIPTION,
				    PRJ_SOPCUSTOMER,
				    PRJ_MCRID,
				    PRJ_SHORTID,
				    PRJ_IGPMPROGRAM_NAME,
				    PRJ_ORDERCATEGORY_DESCRIPTION,
				    PRJ_ORDERTYPE_DESCRIPTION,
				    PRJ_IMPACTCATEGORY_CODE,
				    PRJ_INNOVATIONCOMPLEXITY_CODE,
				    PRJ_STATUS_CODE,
				    ASSESSMENT_CATALOG_DESCRIPTION,
				    ASSESSMENT_CATALOG_DISPLAYNAME,
				    ASSESSMENT_TYPE_DESCRIPTION
				    FROM MARD_PCMS.X_IFR_ONEQ_EPIC8_HLCP
				    WHERE ASSESSMENTTREE_CRITERION_STATUS = 'RELEASED'
				    OR ASSESSMENTTREE_CRITERION_STATUS IS NULL" & TopRowsPara]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ASSESSMENT_MEETINGDATE", type date}, {"ASSESSMENTTREE_RISKSCOUNT", Int64.Type}, {"ASSESSMENTTREE_DOCUMENTSCOUNT", Int64.Type}, {"ASSESSMENTTREE_OVERDUEMEASURESCOUNT", Int64.Type}, {"ASSESSMENTTREE_MEASURESCOUNT", Int64.Type}, {"PRJ_SOPCUSTOMER", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"ASSESSMENTTREE_RATING_VALUE_NAME", Text.Trim, type text}}),
				    #"Lowercased Text" = Table.TransformColumns(#"Trimmed Text",{{"ASSESSMENTTREE_RATING_VALUE_NAME", Text.Lower, type text}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Lowercased Text", {"ASSESSMENTTREE_RATING_VALUE_NAME"}, E8_DIM_RATINGNAME, {"RATING"}, "DIM_RATINGNAME.1", JoinKind.LeftOuter),
				    #"Expanded DIM_RATINGNAME.1" = Table.ExpandTableColumn(#"Merged Queries1", "DIM_RATINGNAME.1", {"ID_RATING"}, {"DIM_RATINGNAME.1.ID_RATING"})
				in
				    #"Expanded DIM_RATINGNAME.1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

