table 'Last Refreshed Date'
	lineageTag: 1c78ff48-79da-4bec-a1d0-b9ea7b4bf34f

	column 'Data Updated Text'
		dataType: string
		lineageTag: 525808b1-7370-462f-8d08-7067caa925ab
		summarizeBy: none
		sourceColumn: Data Updated Text

		annotation SummarizationSetBy = Automatic

	column LAST_REFRESH_END_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: e3af38f1-f593-4be8-bffc-babf454477b8
		summarizeBy: none
		sourceColumn: LAST_REFRESH_END_TIME

		annotation SummarizationSetBy = Automatic

	partition 'Last Refreshed Date-1de845a3-781d-4287-9846-ba8d6533875e' = m
		mode: import
		source =
				let
				    Source = Oracle.Database("REDLake_ZeusQ_OpsDevSup_CI.world", [HierarchicalNavigation=true, Query="SELECT#(lf)    LAST_REFRESH_END_TIME#(lf)FROM MARD_PCMS.X_IFR_PCMS_EPIC_REPORT_DETAILS#(lf)WHERE EPIC_ID = 8"]),
				    #"Added Custom" = Table.AddColumn(Source, "Data Updated Text", each "Data updated: " & DateTime.ToText([LAST_REFRESH_END_TIME], [Format="dd MMM yyyy HH:mm tt"]) & Character.FromNumber(160))
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

