table group
	lineageTag: 0484f0a0-a233-44ec-be02-cc2100fa9dd6

	column displayName
		dataType: string
		lineageTag: 00956285-fec8-4ec9-b830-fd3a18d35fec
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column 'group.member.userPrincipalName'
		dataType: string
		lineageTag: 22345fdf-5b2b-4c2b-a091-80edb5cb1efc
		summarizeBy: none
		sourceColumn: group.member.userPrincipalName

		annotation SummarizationSetBy = Automatic

	column 'securityPrincipal.sAMAccountName'
		dataType: string
		lineageTag: 46f25b93-2bde-4de6-bcf4-277030b641c4
		summarizeBy: none
		sourceColumn: securityPrincipal.sAMAccountName

		annotation SummarizationSetBy = Automatic

	column distinguishedName
		dataType: string
		lineageTag: ba266d32-8f44-490a-9c82-2c9883e5d768
		summarizeBy: none
		sourceColumn: distinguishedName

		annotation SummarizationSetBy = Automatic

	partition group = m
		mode: import
		source =
				let
				    Source = ActiveDirectory.Domains("apac.bosch.com"),
				    #"bosch com" = Source{[Domain="bosch.com"]}[Object Categories],
				    group1 = #"bosch com"{[Category="group"]}[Objects],
				    #"Expanded securityPrincipal" = Table.ExpandRecordColumn(group1, "securityPrincipal", {"sAMAccountName"}, {"securityPrincipal.sAMAccountName"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded securityPrincipal", each Text.Contains([securityPrincipal.sAMAccountName], "RB_C_PCO_PCMS_Project_Team")),
				    #"Expanded group" = Table.ExpandRecordColumn(#"Filtered Rows", "group", {"member"}, {"group.member"}),
				    #"Expanded group.member" = Table.ExpandListColumn(#"Expanded group", "group.member"),
				    #"Expanded group.member1" = Table.ExpandRecordColumn(#"Expanded group.member", "group.member", {"userPrincipalName"}, {"group.member.userPrincipalName"})
				in
				    #"Expanded group.member1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

