table X_IFR_EPIC6_TRAINING_RATE_UNPIVOT
	lineageTag: 70f6eef2-df92-4e83-bd2f-e6def869d583

	column ITEM_ID
		dataType: int64
		formatString: 0
		lineageTag: 6f834597-bea4-4dd2-acfa-71ef1c0b7751
		summarizeBy: count
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TYPE
		dataType: string
		lineageTag: 753f10de-91c6-4f0e-abd7-a6eb523f1ad4
		summarizeBy: none
		sourceColumn: ITEM_TYPE

		annotation SummarizationSetBy = Automatic

	column REGION
		dataType: string
		lineageTag: 9cc04656-43bc-48f8-8ec6-fb457b7cbf79
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: 7b4c888f-a7c7-4664-a804-c37aad572093
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column ORG_AREA
		dataType: string
		lineageTag: 82637877-9064-4971-8226-02027072ebe1
		summarizeBy: none
		sourceColumn: ORG_AREA

		annotation SummarizationSetBy = Automatic

	column ASS_STATUS
		dataType: string
		lineageTag: 96c8bd29-5557-44ba-a3d4-b3531fb62fd3
		summarizeBy: none
		sourceColumn: ASS_STATUS

		annotation SummarizationSetBy = Automatic

	column NUM_OF_ASS
		dataType: int64
		formatString: 0
		lineageTag: 1c84ec44-bfde-4226-9bcb-7702be5f279d
		summarizeBy: sum
		sourceColumn: NUM_OF_ASS

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 67800d1c-f94e-4401-b1b6-fb49d8bbb506
		summarizeBy: sum
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column ROWID
		dataType: string
		lineageTag: 400cb3ce-b8ca-4638-a3fe-054bda3b6c7c
		summarizeBy: none
		sourceColumn: ROWID

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d84915f-d8e9-442e-a5a1-3487347b77e9
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TITLE
		dataType: string
		lineageTag: fd78a61c-b668-4b8a-9ccd-8552a51a4fcd
		summarizeBy: none
		sourceColumn: TITLE

		annotation SummarizationSetBy = Automatic

	partition X_IFR_EPIC6_TRAINING_RATE_UNPIVOT = m
		mode: import
		source =
				let
				    Source = X_IFR_EPIC6_TRAINING_RATE,
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Source, {"EXPORT_DATE", "ITEM_ID", "TITLE", "ITEM_TYPE", "REGION", "COUNTRY", "ORG_AREA"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Columns", each ([Attribute] = "ASS_COMPLETED" or [Attribute] = "ASS_OVERDUE" or [Attribute] = "ASS_STILL_DUE")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Attribute", "ASS_STATUS"}, {"Value", "NUM_OF_ASS"}}),
				    #"Added Custom Column" = Table.AddColumn(#"Renamed Columns", "Year Month", each Text.Combine({Date.ToText([EXPORT_DATE], "yyyy"), Date.ToText([EXPORT_DATE], "MM")}), type text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom Column",{{"EXPORT_DATE", type date}, {"ITEM_ID", Int64.Type}, {"NUM_OF_ASS", Int64.Type}, {"Year Month", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","ASS_","",Replacer.ReplaceText,{"ASS_STATUS"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","_"," ",Replacer.ReplaceText,{"ASS_STATUS"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value1",{{"ASS_STATUS", Text.Proper, type text}}),
				    #"Added Custom Column2" = Table.AddColumn(#"Capitalized Each Word", "ROWID", each Text.Combine({Text.From([Year Month], "en-US"), Text.From([ITEM_ID], "en-US"), Text.Replace(Text.Upper([COUNTRY]), " ",""), [ORG_AREA]}), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom Column2",{{"TITLE", "TITLE"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

