table E5__MEASURES
	lineageTag: 38cd9a6f-3ba6-4214-b0e4-0f565848576f

	measure BLANK = BLANK()
		formatString: 0
		lineageTag: b37ba28a-18b9-4c6e-9c62-f87ab9108e6e

	measure 'Affected Level-2 Risks - Text' = ```
			"Affected 
			Level-2 Risks"
			```
		lineageTag: 6399a750-460a-4c4f-8c90-edec71229aef

	measure 'Outcome - Text' = "Outcome"
		lineageTag: 54927cfd-73df-4d48-a6a1-705367bb02c2

	measure 'Process Improvement - Text' = ```
			"Process 
			Improvement"
			```
		lineageTag: 5741c19c-2279-4d77-a9ce-efb043de4365

	measure 'Affected Product Class - Text' = ```
			"Affected 
			Product Class"
			```
		lineageTag: 18519359-33b5-431d-8be2-2857ece5c4cc

	measure 'Overview - Text' = "Overview"
		lineageTag: 8c6d0a69-b528-4582-a436-427c42c54530

	measure 'Closed label' = ```
			CONCATENATE(
			                CONCATENATE(
			                    "Closed (",
			                    [Closed]
			                ),
			                ")"
			            )
			
			```
		lineageTag: c6516ac1-a5bd-4ee9-8122-be9a43dbe882

	measure Closed = Calculate(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[PROCESS_STS]= "Closed") +0
		formatString: 0
		lineageTag: 0c08f78c-d52d-4595-b699-b7b8e49511a2

	measure 'Closing confirmed' = Calculate(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[PROCESS_STS]= "Closing Confirmed") +0
		formatString: 0
		lineageTag: ba41757d-1c2b-47b2-aed0-cbc2537e0547

	measure 'Closing Confirmed label' = ```
			concatenate(CONCATENATE("Closing Confirmed (",
			    [Closing confirmed]
			                ),
			                ")"
			            )
			
			```
		lineageTag: 1ea7d2e0-7df3-4680-8d07-3667e4498093

	measure Ccase = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[CASE_TYPE]="Compliance Case") + 0
		formatString: #,0
		lineageTag: 9b0a8050-cef0-4fb5-8ea3-d4aed932fffb

	measure 'Ccase label' = ```
			concatenate(CONCATENATE("Compliance Cases (",
			    [Ccase]
			                ),
			                ")"
			            )
			
			```
		lineageTag: 68554d57-5247-4afb-8c09-67918403729a

	measure MJcase = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[CASE_TYPE]="Major Compliance Case") +0
		formatString: #,0
		lineageTag: 2dc6c9f9-49a8-4800-9957-afbdc7d7acd7

	measure 'MJcase label' = ```
			concatenate(CONCATENATE("Major Compliance Cases (",
			    [MJcase]
			                ),
			                ")"
			            )
			
			```
		lineageTag: a520e9ea-b823-4d1f-b13f-ebce8cecd58a

	measure Mncase = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[CASE_TYPE]="Minor Compliance Case") +0
		formatString: #,0
		lineageTag: 0bf7458d-6b78-4fcb-926f-bebda4df73b7

	measure 'Mncase label' = ```
			concatenate(CONCATENATE("Minor Compliance Cases (",
			    [Mncase]
			                ),
			                ")"
			            )
			
			```
		lineageTag: 3390360f-1721-4de7-a222-6a7ce6c774d2

	measure Ncase = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[CASE_TYPE]="No Compliance Case") +0
		formatString: #,0
		lineageTag: bb0f2d41-f15f-419c-9dee-ca9ad4875c67

	measure 'Ncase label' = ```
			concatenate(CONCATENATE("No Compliance Cases (",
			    [Ncase]
			                ),
			                ")"
			            )
			
			```
		lineageTag: 5d534e43-ba27-46b4-a024-44fd221db2b7

	measure 'Division Selected filter' =
			
			If(ISFILTERED('E5_OVERVIEW_CASE'[DIVI_CODE]),
			    CONCATENATEX(
			        VALUES('E5_OVERVIEW_CASE'[DIVI_CODE]),
			        'E5_OVERVIEW_CASE'[DIVI_CODE],
			        ", ",
			        'E5_OVERVIEW_CASE'[DIVI_CODE]
			        ),
			    "All"
			)
		lineageTag: c5f5f908-9250-4c15-a297-b5e11aa04026

	measure 'Region Selected filter' =
			
			If(ISFILTERED('E5_OVERVIEW_CASE'[REGION_SHORT_TEXT]),
			    CONCATENATEX(
			        VALUES('E5_OVERVIEW_CASE'[REGION_SHORT_TEXT]),
			        'E5_OVERVIEW_CASE'[REGION_SHORT_TEXT],
			        ", ",
			        'E5_OVERVIEW_CASE'[REGION_SHORT_TEXT]
			        ),
			    "All"
			)
		lineageTag: fdee1a9c-e3c9-4f60-9947-c5e2459cb08e

	measure 'BU Selected filter' =
			
			If(ISFILTERED('E5_OVERVIEW_CASE'[BUSINESS_UNIT_CODE]),
			    CONCATENATEX(
			        VALUES('E5_OVERVIEW_CASE'[BUSINESS_UNIT_CODE]),
			        'E5_OVERVIEW_CASE'[BUSINESS_UNIT_CODE],
			        ", ",
			        'E5_OVERVIEW_CASE'[BUSINESS_UNIT_CODE]
			        ),
			    "All"
			)
		lineageTag: 1925ca6a-0fa2-4c42-8ac7-865c35e55864

	measure 'Country Selected filter' =
			
			If(ISFILTERED('E5_OVERVIEW_CASE'[COUNTRY_SHORT_TEXT]),
			    CONCATENATEX(
			        VALUES('E5_OVERVIEW_CASE'[COUNTRY_SHORT_TEXT]),
			        'E5_OVERVIEW_CASE'[COUNTRY_SHORT_TEXT],
			        ", ",
			        'E5_OVERVIEW_CASE'[COUNTRY_SHORT_TEXT]
			        ),
			    "All"
			)
		lineageTag: 1a65779b-7bf5-4e00-a271-0a8f60adb35b

	measure 'Hide Visuals' = ```
			IF(SELECTEDVALUE(ThemeFilter[Theme]) in {"Dark"},1,0)
			
			```
		formatString: 0
		lineageTag: f72638d4-bdc9-49e5-a3aa-3eef8061ce30

	measure L2R_Product = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[RISK_GROUP]="Product") +0
		formatString: 0
		lineageTag: 82e41584-9267-4997-82d4-ffc57f5d0f00

	measure L2R_Management = CALCULATE(COUNT('E5_OVERVIEW_CASE'[CASE_ID]), 'E5_OVERVIEW_CASE'[RISK_GROUP]="Management System") +0
		formatString: 0
		lineageTag: e96c05d1-6fb8-4375-a042-a27b063633e7

	measure 'Product label' = ```
			concatenate(CONCATENATE("Product (",
			    [L2R_Product]
			                ),
			                ")"
			            )
			
			```
		lineageTag: bd18be08-4a34-4f9f-a57d-ba11a5b29c9a

	measure 'Management label' = ```
			concatenate(CONCATENATE("Management System (",
			    [L2R_Management]
			                ),
			                ")"
			            )
			
			```
		lineageTag: b32abebd-9aa8-4b5c-9454-53bdc8fb6e6a

	measure %riskgroup = COUNT(E5_OVERVIEW_CASE[CASE_ID])/CALCULATE(COUNT(E5_OVERVIEW_CASE[CASE_ID]),ALLSELECTED(E5_LEVEL2_RISK[RISK_GROUP]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b40baf6f-48db-44eb-84c9-c487edd07cfb

	measure totalcase = CALCULATE(COUNT(E5_OVERVIEW_CASE[CASE_ID]),ALL(E5_OVERVIEW_CASE))
		formatString: 0
		lineageTag: 971cc7af-ab6b-45e8-ba81-5ab8e82f6a8e

	measure MEDIAN = PERCENTILE.INC(E5_OVERVIEW_CASE[PROCESSING_MONTH],0.50)
		lineageTag: 75eacb44-6eda-4765-9d9d-68abd67ebda7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Percentile_25 = PERCENTILE.INC(E5_OVERVIEW_CASE[PROCESSING_MONTH],0.25)
		lineageTag: 1217df26-4617-42df-a514-6dbdf961d6ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Percentile_75 = PERCENTILE.INC(E5_OVERVIEW_CASE[PROCESSING_MONTH],0.75)
		lineageTag: 9f197ed3-2758-41e0-aaa6-9908181bc97e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IQR_2550 = [MEDIAN] - [Percentile_25]
		lineageTag: 0118b249-d2ce-4316-b17e-dc3cfccfee1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IQR_5075 = [Percentile_75] - [MEDIAN]
		lineageTag: 989b1177-9526-45fc-a9dc-64756662e4a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _sorting =
			
			IF (
			    VALUES ('E5_OVERVIEW_CASE'[RESULT_TYPE]) = "Report Had Merit", 1
			    ,IF (
			        VALUES ('E5_OVERVIEW_CASE'[RESULT_TYPE]) = "Confirmed to be taken over by a specialist organizational unit", 2
			        , IF( VALUES ( 'E5_OVERVIEW_CASE'[RESULT_TYPE] ) = "Duplicate",3
			        , IF(VALUES ( 'E5_OVERVIEW_CASE'[RESULT_TYPE] ) = "Misuse", 4
			        , IF(VALUES ( 'E5_OVERVIEW_CASE'[RESULT_TYPE] ) = "Unable to verify", 5
			        , IF(VALUES ( 'E5_OVERVIEW_CASE'[RESULT_TYPE] ) = "No Violation Found", 6
			    )
			        ))))
			)
		formatString: 0
		lineageTag: fe47d56c-92e8-4648-91d6-dbb4d49f3ef6

	measure COUNT_CASE_ID = COUNT(E5_OVERVIEW_CASE[CASE_ID])
		formatString: #,0
		lineageTag: a2165fa2-6bb4-48e9-b81d-f72a5302c979

	measure SORT_NUM_CASES_BY_RISKSTATEMENT =
			IF(
			    SELECTEDVALUE(E5_SORT[SORT_NAME]) = "ASC",
			        SWITCH(
			        SELECTEDVALUE(E5_SORT_BY[MEASURE]),
			        "Number Of Cases", [COUNT_CASE_ID],
			        [MAX_RISK_STATEMENT_ID]),
			        SWITCH(
			        SELECTEDVALUE(E5_SORT_BY[MEASURE]),
			        "Number Of Cases",-[COUNT_CASE_ID],
			        -[MAX_RISK_STATEMENT_ID]))
		formatString: 0
		lineageTag: 3cc2953c-85ac-4a74-8ebb-7ba4f1f16ec1

	measure MAX_RISK_STATEMENT_ID = MAXX(E5_OVERVIEW_CASE,RELATED(E5_DIM_RISK_STATEMENT[RISK_STATEMENT_ID]))
		formatString: 0
		lineageTag: ede89fff-fda6-42c2-b832-021b5c0d6274

	measure '_test lable' = ```
			
			VAR OriginalNumber = [Mncase] // Replace [Ccase] with your actual measure
			VAR FormattedNumber = 
			    IF(
			        OriginalNumber >= 1000,
			        VAR ThousandsPart = QUOTIENT(OriginalNumber, 1000)
			        VAR HundredsPart = MOD(QUOTIENT(OriginalNumber, 100), 10)
			        RETURN
			            ThousandsPart & "k" & HundredsPart,
			        FORMAT(OriginalNumber, "0")
			    )
			RETURN
			    CONCATENATE(CONCATENATE("Minor Compliance Cases (", FormattedNumber), ")")
			
			```
		lineageTag: 6d691dd2-9a01-4a62-bbe1-0ef0fa4e5e97

	measure 'YAXIS MAX Processing' = MAX(E5_OVERVIEW_CASE[PROCESSING_MONTH])*1.1
		lineageTag: 5aae74b6-5742-4ad0-9a1a-a1ce1a239f07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRODUCT_AFFECTED_MAX_CASE_ID_MULTI_11 =
			
			MAXX(ALLSELECTED(E5_OVERVIEW_CASE[PRODUCT_AFFECTED]),CALCULATE(COUNT(E5_OVERVIEW_CASE[CASE_ID]))) * 1.1
		formatString: 0
		lineageTag: a7252d76-62af-4a2d-bcd9-82cb76182ec6

	column _MEASURES
		dataType: string
		lineageTag: d16ae15e-c064-42dc-80ff-0e6b934a21ec
		summarizeBy: none
		sourceColumn: _MEASURES

		annotation SummarizationSetBy = Automatic

	partition E5__MEASURES = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [_MEASURES = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"_MEASURES", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

