table E5_DIM_CASETYPE
	lineageTag: 6b2fbc93-b0f1-447d-b626-a4e41a5ce533

	column CASE_TYPE
		dataType: string
		lineageTag: fedc7cdc-4f19-48fd-95dc-b198dc544981
		summarizeBy: none
		sourceColumn: CASE_TYPE
		sortByColumn: CASETYPE_ID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CASETYPE_ID
		dataType: int64
		formatString: 0
		lineageTag: 4e30a0bf-fbd3-4d25-9608-0111cf7a32b3
		summarizeBy: none
		sourceColumn: CASETYPE_ID

		annotation SummarizationSetBy = Automatic

	partition E5_DIM_CASETYPE = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8k3Myi9ScM7PLcjJTMxLTlVwTixOVdJRMlSK1YlWwhQ3Aov7ZuZh1WUMlvXLxyJlohQbCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CASE_TYPE = _t, CASETYPE_ID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CASE_TYPE", type text}, {"CASETYPE_ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

