table _MEASURES
	lineageTag: 27410f2f-24ec-4dba-8178-701c4f8592df

	measure TOTAL_ASGMTS = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_OVERALL])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: 9cdf5f70-d10e-473d-86ec-58f11863b208

	measure TOTAL_ASGMTS_COMPLETED = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_COMPLETED])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: eca4bf23-3c27-407d-9b32-414eb482d35e

	measure TOTAL_ASGMTS_STILL_DUE = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_STILL_DUE])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: 9ff58dd7-2c43-4cb4-8c2f-cbc5b35f7ed6

	measure TOTAL_ASGMTS_OVERDUE = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: cb58f064-5709-44ae-a228-8ef56524e6d8

	measure WhiteSpace = UNICHAR(8192)
		lineageTag: a6ba6b56-4035-49ce-8171-5d5da39b366a

	measure %_COMPLETED = DIVIDE([TOTAL_ASGMTS_COMPLETED],[TOTAL_ASGMTS],0)
		formatString: 0%;-0%;0%
		displayFolder: NO_PIVOT
		lineageTag: 6e247c78-50ff-48fd-9ebc-6afd142115cc

	measure %_STILL_DUE = DIVIDE([TOTAL_ASGMTS_STILL_DUE],[TOTAL_ASGMTS],0)
		formatString: 0%;-0%;0%
		displayFolder: NO_PIVOT
		lineageTag: c46bb2c5-1f7b-4303-953b-bfd39b436de5

	measure %_OVERDUE = DIVIDE([TOTAL_ASGMTS_OVERDUE],[TOTAL_ASGMTS],0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: NO_PIVOT
		lineageTag: a69b7479-c130-413a-96b3-58673a29eccb

	measure ORG_AREA_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_ORG_AREA[ORG_AREA] ),
			    CONCATENATEX (
			        VALUES ( DIM_ORG_AREA[ORG_AREA] ),
			        DIM_ORG_AREA[ORG_AREA],
			        ", ",
			        DIM_ORG_AREA[ORG_AREA]
			    ),
			    "All"
			)
		lineageTag: 2092df0e-396b-4b32-8344-4c0dd932bfc2

	measure REGION_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_REGION[REGION] ),
			    CONCATENATEX (
			        VALUES ( DIM_REGION[REGION] ),
			        DIM_REGION[REGION],
			        ", ",
			        DIM_REGION[REGION]
			    ),
			    "All"
			)
		lineageTag: 9ea87ac1-71af-4f65-9b70-1510ac869e7f

	measure COUNTRY_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_COUNTRY[COUNTRY] ),
			    CONCATENATEX (
			        VALUES ( DIM_COUNTRY[COUNTRY] ),
			        DIM_COUNTRY[COUNTRY],
			        ", ",
			        DIM_COUNTRY[COUNTRY]
			    ),
			    "All"
			)
		lineageTag: b01c6cee-77c7-4c54-9934-7a7db11d3305

	measure TITLE_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_ITEM[TITLE] ),
			    CONCATENATEX (
			        VALUES ( DIM_ITEM[TITLE] ),
			        DIM_ITEM[TITLE],
			        ", ",
			        DIM_ITEM[TITLE]
			    ),
			    "All"
			)
		lineageTag: 52a4008f-1006-41ef-b1ec-bf70c987c97a

	measure TOTAL_ASGMTS_UPVT = SUM(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[NUM_OF_ASS])
		formatString: #,0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 99684a1c-02ca-40d6-ae0e-243f00dd8428

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TOTAL_ASGMTS_UPVT_ALL = ```
			CALCULATE (
			    [TOTAL_ASGMTS_UPVT], 
			    ALLSELECTED(
			        X_IFR_EPIC6_TRAINING_RATE[ORG_AREA]
			        ,X_IFR_EPIC6_TRAINING_RATE[BU_EXTENDED]
			        ,X_IFR_EPIC6_TRAINING_RATE[DEPARTMENT]
			        ,X_IFR_EPIC6_TRAINING_RATE[ORGANIZATION]
			        ,X_IFR_EPIC6_TRAINING_RATE[REGION]
			        ,X_IFR_EPIC6_TRAINING_RATE[COUNTRY]
			        ,X_IFR_EPIC6_TRAINING_RATE[Year Month]
			        ,X_IFR_EPIC6_TRAINING_RATE[TITLE]
			    )
			    ,ALL(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS])
			)
			```
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: e03c510b-6d5c-4b28-8a14-b885e5510890

	measure %_ASGMTS_TO_ALLSTATUS = DIVIDE ( [TOTAL_ASGMTS_UPVT], [TOTAL_ASGMTS_ALLSTATUS], 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: UNPIVOT_TABLE
		lineageTag: 50dfa4d6-ad1c-495a-9b96-7bc980e6d332

	measure 'Preset Value' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) >= 0, 1, 0 ),
			        "Overdue >=2%", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) >= 0.02, 1, 0 ),
			        "Overdue <2%", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) < 0.02, 1, 0 )
			    )
			RETURN
			    result
		formatString: 0
		lineageTag: 8924938f-ced9-45cc-bc2f-0b94a563c2db

	measure %_ASGMTS = DIVIDE([TOTAL_ASGMTS_UPVT],[TOTAL_ASGMTS_UPVT_ALL],0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: UNPIVOT_TABLE
		lineageTag: bd98ca8b-3eb5-4878-a264-f3902359e7b9

	measure TOTAL_ASGMTS_ALLSTATUS =
			CALCULATE (
			    [TOTAL_ASGMTS_UPVT],
			    ALLSELECTED ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] )
			)
		formatString: #,0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 9611adac-95ab-4f4c-8f26-194b490723c6

	measure 'Preset Value UNPVT' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All", IF ( _MEASURES[%_ASGMTS] >= 0, 1, 0 ),
			        "Overdue >=2%", IF ( _MEASURES[%_ASGMTS] >= 0.02, 1, 0 ),
			        "Overdue <2%", IF ( _MEASURES[%_ASGMTS] < 0.02, 1, 0 )
			    )
			RETURN
			    result
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 9625dae4-938b-4e8e-9eb6-8f4bac4e158f

	measure 'Preset Value UNPVT Pie-expand' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) >= 0.00,
			                1,
			                0
			            ),
			        "Overdue >=2%",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) >= 0.02,
			                1,
			                0
			            ),
			        "Overdue <2%",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) < 0.02,
			                1,
			                0
			            )
			    )
			RETURN
			    result
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 1e957410-1957-47d7-9810-6e89ef72f576

	measure 'Preset Value 2' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] >= 0
			            ),
			        "Overdue >=2%",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] >= 0.02
			            ),
			        "Overdue <2%",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] < 0.02
			            )
			    )
			RETURN
			    result
		formatString: 0
		lineageTag: bbc751df-02b9-4966-b62e-e801b57764a5

	measure TT_ASGMTS_CPLT =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Completed"
			        )
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: fcb5d15c-fc3e-4345-aea7-23d5a0e77277

	measure TT_ASGMTS_STDL =
			
			VAR FILTER_TB = FILTER (
			            ALL ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Still Due"
			        )
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 7fab11d0-bd0c-4b11-919b-aa9241a7a8df

	measure TT_ASGMTS_OVRD =
			
			VAR FILTER_TB = FILTER (
			            ALL ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			        )
			
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 1ce01f35-07b1-4824-b793-2a61c640f56c

	measure TT_ASGMTS_3_STS = ```
			
			"Completed: " & [TT_ASGMTS_CPLT] & " (" & [TT_ASGMTS_CPLT%] & ")" & UNICHAR(10) & 
			"Still Due: " & [TT_ASGMTS_STDL] & " (" & [TT_ASGMTS_STDL%] & ")" & UNICHAR(10) &
			"Overdue: " & [TT_ASGMTS_OVRD] & " (" & [TT_ASGMTS_OVRD%] & ")"
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: 3aa5aed7-ec75-4064-9e9f-9e394f26504a

	measure TT_ASGMTS_CPLT% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS]),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Completed"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: c4414e26-2a38-4b66-8ed9-ddfd9ecd2a3f

	measure TT_ASGMTS_STDL% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Still Due"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 0eed4453-51be-4c7c-8378-daad0aaa2adb

	measure TT_ASGMTS_OVRD% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: d0b8b9b1-d081-40a6-b55d-53fff85cc6ef

	measure TT_ASGMTS_%_3STS = ```
			
			"Completed: " & [TT_ASGMTS_CPLT%] & UNICHAR(10) & 
			"Still Due: " & [TT_ASGMTS_STDL%] & UNICHAR(10) &
			"Overdue: " & [TT_ASGMTS_OVRD%]
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: a48a8ff0-857a-4f47-9f82-bbbf2f2d5fa6

	measure TT_ASGMTS_%_3STS_NO_PIVOT = ```
			
			"Completed: " & FORMAT ( [%_COMPLETED], "Percent" ) & UNICHAR(10) & 
			"Still Due: " & FORMAT ( [%_STILL_DUE], "Percent" ) & UNICHAR(10) &
			"Overdue: " & FORMAT ( [%_OVERDUE], "Percent" )
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: c0445c48-d118-44ab-a89e-95716ee813f1

	measure 'Overview Text' = "Overview"
		lineageTag: 18d5b277-553f-4846-81f4-2847180dd6a3

	measure 'Training status' = "Training Status"
		lineageTag: f8cc4af6-cca0-4ee2-95ce-e585f2c3d32f

	measure 'Training Survey Text' = "Training Survey"
		lineageTag: 867b04ff-b948-4aa3-a8a7-939831189e1b

	measure 'Summary text' = ""
		lineageTag: c2a0df33-f886-4df4-a61a-ee7c597857ef

	measure 'OE specific training' = ""
		lineageTag: e2fb2410-4358-4bbe-bcd8-a3bb77958d8e

	measure OVERDUE_COLOR_TEXT = ```
			
			VAR overdue = CALCULATE([%_ASGMTS], X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS]="Overdue")
			RETURN 
			        SWITCH(TRUE(),
			                overdue>=0.02, "#FF5152",
			                SELECTEDVALUE(ThemeFilter[Font])
			        )
			```
		lineageTag: 6c66ccab-e537-4d38-bbaa-6b0b039d791e

	measure SURVEY_COMPLETION_RATE = ```
			
			            [TOTAL COMPLETED SURVEY]/[TOTAL SURVEY]
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SURVEY_MEASURES
		lineageTag: 748f9469-6a07-4fa7-9410-23a2b1277163

	measure _MEDIAN = ```
			PERCENTILE.INC(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS], 0.5)
			
			```
		formatString: 0.0
		lineageTag: 7ee4a095-b496-4cf6-aa31-d38b58469b2c

	measure 'SURVEY DUMMY 1' = 1
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: f6c3adc6-7efa-4eb1-b17e-0d994c26a0e8

	measure 'SURVEY DUMMY 2' = 1
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: d8f4ba33-1549-41b6-8245-8143b5f58420

	measure 'SURVEY DUMMY 3' = 1
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 46a956fe-57bf-4979-b8fc-35dcfb775dd0

	measure 'SURVEY DUMMY 4' = 1
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: fec64553-de25-48b7-a5ae-0df6196826dd

	measure 'SURVEY DUMMY 5' = 1
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 3e59a658-56df-46fd-abfd-53e4dd577b57

	measure 'TEXT MEAN SCORE' = ```
			
			VAR meanscore = [ITEM MEAN SCORE]
			var textscore = 
			SWITCH(TRUE(),
			        meanscore<1, "N/A",
			        meanscore=1, "Definitely True",
			        meanscore>1 && meanscore <2, "Definitely True - Mainly True",
			        meanscore=2, "Mainly True",
			        meanscore>2 && meanscore <3, "Mainly True - Not Really",
			        meanscore=3, "Not Really",
			        meanscore>3 && meanscore <4, "Not Really - Not At All",
			        meanscore=4, "Not At All",
			        "--"
			)
			    RETURN textscore    
			```
		lineageTag: 6985c5d5-bac5-4193-ab24-6a14fdbb6e07

	measure 'COUNT RATING' = ```
			
			            CALCULATE(COUNT(X_IFR_EPIC6_TRAINING_SURVEY[ANSWER])
			            ,X_IFR_EPIC6_TRAINING_SURVEY[QUESTION_TYPE]="RATING SCALE")
			```
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 192822d4-473b-4df6-9df7-dc665fc4cad7

	measure 'Approval Rating' = ```
			
			VAR isCOURSESelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "COURSE")) > 0
			VAR isDOCSelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "DOC")) > 0
			
			VAR isotherSelected = isCOURSESelected || isDOCSelected
			
			VAR countall = 
			    CALCULATE(
			        [COUNT RATING],
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			VAR countrating = 
			    CALCULATE(
			        [COUNT RATING],
			        X_IFR_EPIC6_TRAINING_SURVEY[RATING NUMBER] IN {"1", "2"},
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			RETURN countrating/countall
			```
		formatString: 0%;-0%;0%
		displayFolder: SURVEY_MEASURES
		lineageTag: 5ad26863-6fab-4c0e-a4b3-f4844ebc826f

	measure 'MEAN SCORE OVERDUE' = ```
			
			    CALCULATE(AVERAGE(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS])
			                    )
			```
		formatString: 0.00
		lineageTag: bc968c67-6df2-43e4-b5f2-4c82ec6d813f

	measure 'TOTAL SURVEY' = ```
			SUMX(SUMMARIZE(X_IFR_EPIC6_TRAINING_SURVEY, X_IFR_EPIC6_TRAINING_SURVEY[ROWID], X_IFR_EPIC6_TRAINING_SURVEY[TOTAL_SURVEYS]), X_IFR_EPIC6_TRAINING_SURVEY[TOTAL_SURVEYS])
			
			```
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 06dbfa08-c4db-4258-9617-f0aac792eab2

	measure 'TOTAL COMPLETED SURVEY' =
			
			SUMX(SUMMARIZE(X_IFR_EPIC6_TRAINING_SURVEY, X_IFR_EPIC6_TRAINING_SURVEY[ROWID], X_IFR_EPIC6_TRAINING_SURVEY[COMPLETED_SURVEYS]), X_IFR_EPIC6_TRAINING_SURVEY[COMPLETED_SURVEYS])
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 93a4cca6-b8ff-45b0-ab4a-153b2bc5b8da

	measure 'SURVEY NOT COMPLETED' = [TOTAL SURVEY] - [TOTAL COMPLETED SURVEY]
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: eedbe1cb-8240-4129-9b2a-35f9f1848fed

	measure _IQR50 = ```
			
			        [_Q3] -[_Q1]
			```
		lineageTag: 2c1c55d1-ba6f-41f2-b31f-0334e0edbed8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Q1 = PERCENTILE.INC(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS], 0.25)
		lineageTag: 049b0540-798f-402f-94dd-b97e99100ae6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Q3 = PERCENTILE.INC(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS], 0.75)
		lineageTag: 973cdbb8-f020-4ddb-9392-7ab8aa7a22fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _LOWER = MIN(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS])
		lineageTag: 65398873-86cc-4afe-b89b-5a2422ff8fdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _UPPER = MAX(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[OVERDUE_DAYS_PER_ASS])
		lineageTag: e3fea30c-ae15-4010-86f4-f3d3f65a38df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Disapproval Rating' = ```
			
			VAR isCOURSESelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "COURSE")) > 0
			VAR isDOCSelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "DOC")) > 0
			
			VAR isotherSelected = isCOURSESelected || isDOCSelected
			
			VAR countall = 
			    CALCULATE(
			        [COUNT RATING],
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			VAR countrating = 
			    CALCULATE(
			        [COUNT RATING],
			        X_IFR_EPIC6_TRAINING_SURVEY[RATING NUMBER] IN {"3", "4"},
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			RETURN countrating/countall
			```
		formatString: 0%;-0%;0%
		displayFolder: SURVEY_MEASURES
		lineageTag: ac3d82cb-4ec2-4f00-bf2b-f87df83eecbf

	measure 'N/A Rating' = ```
			
			VAR isCOURSESelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "COURSE")) > 0
			VAR isDOCSelected = COUNTROWS(FILTER(VALUES(X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID]), X_IFR_EPIC6_TRAINING_SURVEY[ITEM_TYPE_ID] = "DOC")) > 0
			
			VAR isotherSelected = isCOURSESelected || isDOCSelected
			
			VAR countall = 
			    CALCULATE(
			        [COUNT RATING],
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			VAR countrating = 
			    CALCULATE(
			        [COUNT RATING],
			        X_IFR_EPIC6_TRAINING_SURVEY[RATING NUMBER] = "N/A",
			        IF(
			            isotherSelected,
			            TRUE(),
			            NOT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION] IN {5, 6})
			        )
			    )
			
			RETURN countrating/countall
			```
		formatString: 0%;-0%;0%
		displayFolder: SURVEY_MEASURES
		lineageTag: f7802c09-669c-4870-a6ec-056c3edabc23

	measure 'COLOR MEAN SCORE' = ```
			
			VAR meanscore = [ITEM MEAN SCORE]
			RETURN
			                IF(meanscore>1.49, "#FF5152", SELECTEDVALUE(ThemeFilter[Font]))
			                
			```
		displayFolder: SURVEY_MEASURES
		lineageTag: 6de43c90-2d2d-4e9f-8af5-98865eb75244

	measure 'ITEM MEAN SCORE' =
			AVERAGEX(
			            SUMMARIZE(X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT
			            , X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[ROWID]
			            , X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[ITEM_MEAN_SCORE])
			            , X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[ITEM_MEAN_SCORE])
		formatString: 0.00
		displayFolder: SURVEY_MEASURES
		lineageTag: 309fc512-4a0e-4364-82c6-fc461abcfe36

	measure 'MEAN SCORE QUARTER' =
			
			VAR selectyear = MAX(X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[Year])
			VAR selectmonth = MAX(X_IFR_EPIC6_TRAINING_SURVEY[Month])
			var startdate = DATE(selectyear, 1, 1)
			var enddate = DATE(selectyear, 12, 1)
			var period = DATESINPERIOD (
			        X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[FROM_DATE],
			        startdate,
			        12,
			        MONTH
			    )
			var result =
			            CALCULATE(AVERAGE(X_IFR_EPIC6_TRAINING_SURVEY_UNPIVOT[ITEM_MEAN_SCORE])
			                , REMOVEFILTERS(X_IFR_EPIC6_TRAINING_SURVEY)
			                , KEEPFILTERS(period)
			                , KEEPFILTERS(DIM_ITEM)
			)
			RETURN result
		formatString: 0.00
		displayFolder: SURVEY_MEASURES
		lineageTag: c2a5d213-2712-4cf5-ae9b-303be2cced93

	measure 'RATING PERCENTAGE' =
			[COUNT RATING]/
			                    CALCULATE([COUNT RATING]
			                    , ALL(X_IFR_EPIC6_TRAINING_SURVEY[RATING NUMBER])
			                    , ALL(X_IFR_EPIC6_TRAINING_SURVEY[RATING TEXT])
			                    )
		formatString: 0%;-0%;0%
		displayFolder: SURVEY_MEASURES
		lineageTag: 71e468c0-f1d5-4b63-af2a-5b86bf991128

	measure 'ICON 1' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzIxXC8zMDYxM1wvYjVkNGFjMDRlZWM5OWNlNjJhZGYxYjQyMDZkOGEwN2UtMTU5NTMzODg2NS5zdmcifQ:bosch:9jFzdob7WtCxSLfIOAsr4GWqcoaprW1m2yDHyLYKAaI?width=2400&color=0,0,0,1",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzIxXC8zMDYxM1wvYjVkNGFjMDRlZWM5OWNlNjJhZGYxYjQyMDZkOGEwN2UtMTU5NTMzODg2NS5zdmcifQ:bosch:9jFzdob7WtCxSLfIOAsr4GWqcoaprW1m2yDHyLYKAaI?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 73180871-a9fa-469a-87c1-3b0b8e44b704

	measure 'ICON 2' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzFlXC8zMTMwOFwvZjljYzhmYjhlZjA0MDVlOTY1ZGE5ZTI5MDJjZjRhNGQtMTU5NTUxOTI2MC5zdmcifQ:bosch:EoTHXeRXlBuXdRf-OrIyBFjQ4epPFqF8IUkTcvUpN8U?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzFlXC8zMTMwOFwvZjljYzhmYjhlZjA0MDVlOTY1ZGE5ZTI5MDJjZjRhNGQtMTU5NTUxOTI2MC5zdmcifQ:bosch:EoTHXeRXlBuXdRf-OrIyBFjQ4epPFqF8IUkTcvUpN8U?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 4ca60dc6-fe2b-4412-8a9b-60d7087c19f9

	measure 'ICON 3' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcL2U5XC8zMDYwOFwvYzIwYTM2NWQyOGQwYzBjYjE4Y2YxYThiMDQzNWIyMmEtMTU0NTEzMDAzOS5zdmcifQ:bosch:27sjmnpJHxEqH3pzsuVK55tHc22KeJtjSLzkDnCf9uA?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcL2U5XC8zMDYwOFwvYzIwYTM2NWQyOGQwYzBjYjE4Y2YxYThiMDQzNWIyMmEtMTU0NTEzMDAzOS5zdmcifQ:bosch:27sjmnpJHxEqH3pzsuVK55tHc22KeJtjSLzkDnCf9uA?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 1038a358-16bd-4356-9267-d64ba9b813d8

	measure 'ICON 4' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2ZpbGVcL21GRlc3Q3dORVJkb1BVREI5ZHd0LnN2ZyJ9:bosch:zg_1qBocSfgbzWKLqlHnTIoN9o310Hg8GKj-WiDllKY?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2ZpbGVcL21GRlc3Q3dORVJkb1BVREI5ZHd0LnN2ZyJ9:bosch:zg_1qBocSfgbzWKLqlHnTIoN9o310Hg8GKj-WiDllKY?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 22683091-fa37-4ffe-9e3d-e270f36daff1

	measure 'ICON 6' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzBlXC8xMTQxOTVcLzc0NTEyYTBkOTMwNzQyYjc2NGI4ZmU5NTk1Y2ZjMDVhLTE1OTEyNzUxNTYuc3ZnIn0:bosch:dqjyrVz7ny2d6VrH3QdGUIhvzynQnCMszCmnuuYgdrQ?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzBlXC8xMTQxOTVcLzc0NTEyYTBkOTMwNzQyYjc2NGI4ZmU5NTk1Y2ZjMDVhLTE1OTEyNzUxNTYuc3ZnIn0:bosch:dqjyrVz7ny2d6VrH3QdGUIhvzynQnCMszCmnuuYgdrQ?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 3f7089af-5d7a-4e00-8df0-248b89037ee7

	measure 'ICON 7' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzhjXC8zNzg5OVwvZTZkN2E4NTZkNDI4MzVhOTAxMGEyOWEzNWE4Y2U0NDEtMTU1ODUyMjIxNi5zdmcifQ:bosch:Vg9y74o_iOkYgXu1W8tZjRoCViUjCYWsZVuBrfGb_4w?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzhjXC8zNzg5OVwvZTZkN2E4NTZkNDI4MzVhOTAxMGEyOWEzNWE4Y2U0NDEtMTU1ODUyMjIxNi5zdmcifQ:bosch:Vg9y74o_iOkYgXu1W8tZjRoCViUjCYWsZVuBrfGb_4w?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: e486cbe4-3776-4b9d-975d-6246ba6db257

	measure 'ICON 8' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzBhXC8zMDgyNFwvMzJhYjRlMTJiYjI3ZWViMzk5N2M2MTdkNTIzNDgyNGQtMTU5NTQyMDUyMS5zdmcifQ:bosch:ebBgbiJiKY4-BBesCT_abys432fRvNtUeAeuEHLgOhI?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzBhXC8zMDgyNFwvMzJhYjRlMTJiYjI3ZWViMzk5N2M2MTdkNTIzNDgyNGQtMTU5NTQyMDUyMS5zdmcifQ:bosch:ebBgbiJiKY4-BBesCT_abys432fRvNtUeAeuEHLgOhI?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: 16802fd3-084e-41dc-9cb3-301f97437b92

	measure 'ICON 5' =
			
			VAR theme = SELECTEDVALUE(E6_SpecificTheme[Theme])
			RETURN SWITCH(TRUE(),
			            theme = "Light", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzRmXC8zMTEwNlwvYTg3ZGVmZGYxYTlhMWMyYzU2NmE3OGI4ZWE2YWJkZDgtMTU5NTUwNDE5My5zdmcifQ:bosch:qy9fkEzOtbOQBRWEj3bjl-Xe4HIJarBVRqGXf6R0asc?width=2400",
			            theme = "Dark", "https://cdn-assets-eu.frontify.com/s3/frontify-enterprise-files-eu/eyJwYXRoIjoiYm9zY2hcL2FjY291bnRzXC9hNVwvNDAwMDA5OFwvcHJvamVjdHNcLzc4XC9hc3NldHNcLzRmXC8zMTEwNlwvYTg3ZGVmZGYxYTlhMWMyYzU2NmE3OGI4ZWE2YWJkZDgtMTU5NTUwNDE5My5zdmcifQ:bosch:qy9fkEzOtbOQBRWEj3bjl-Xe4HIJarBVRqGXf6R0asc?width=2400&color=255,255,255,1")
		displayFolder: SURVEY_MEASURES
		lineageTag: b3796183-7b67-482a-8596-c2096b8c86a6

	measure 'OVERDUE MEAN SCORE COLOR' =
			
			VAR meanscore = [MEAN SCORE OVERDUE]
			RETURN
			                IF(meanscore>4, "#FF5152", SELECTEDVALUE(ThemeFilter[Font]))
		lineageTag: 77fc80ed-10ea-4930-8422-ac246f0ca06b

	measure 'COUNT QUESTION' = COUNT(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION])
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 3593e60d-8cd5-44cf-8a27-d9d9e604b632

	measure 'COLOR BG RATING' = ```
			
			var rating = SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[RATING TEXT])
			return       IF(SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION_TYPE])="Rating Scale",
			                SWITCH(TRUE(),
			                rating="N/A", "#B3B3B3",
			                rating="Definitely true", "#00884A",
			                rating="Mainly true", "#33A06E",
			                rating="Not really", "#FFCF00",
			                rating="Not at all", "#FF5152"),
			                SELECTEDVALUE(ThemeFilter[Visual Background Color])
			)
			            
			
			```
		displayFolder: SURVEY_MEASURES
		lineageTag: 40006238-dbf3-440d-9fee-5a3dbd5e32d4

	measure 'COLOR TEXT RATING' =
			
			var rating = SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[RATING TEXT])
			return       IF(SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION_TYPE])="Rating Scale",
			                "white",
			                SELECTEDVALUE(ThemeFilter[Font]))
		displayFolder: SURVEY_MEASURES
		lineageTag: 668dd3f9-9294-470c-8cbf-c1b65ee94a46

	measure 'QUESTION ANSWER' =
			
			var question = SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[QUESTION_TYPE])
			RETURN
			        SWITCH(TRUE(),
			        question="Open Ended", SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[ANSWER]),
			        question="Rating Scale", SELECTEDVALUE(X_IFR_EPIC6_TRAINING_SURVEY[RATING TEXT])
			        )
		displayFolder: SURVEY_MEASURES
		lineageTag: 42b74a3e-62ca-4084-9650-24831ead18ef

	measure 'RATING SCALE MEANSCORE' = CALCULATE([ITEM MEAN SCORE], X_IFR_EPIC6_TRAINING_SURVEY[QUESTION_TYPE]="Rating Scale")
		displayFolder: SURVEY_MEASURES
		lineageTag: caf1937a-f8b5-4718-a6b8-05c875c77dfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DUMMY MEANSCORE 2' = 2
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: d5d91e44-bfb8-4aee-8626-d90b916d150f

	measure 'DUMMY MEANSCORE 3' = 3
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: c7cc1aa9-f8f5-4b61-9eb4-cf6b10c0212d

	measure 'DUMMY MEANSCORE 4' = 4
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 858d6aed-42a3-4d12-a7dc-36a58e009673

	measure 'DUMMY MEANSCORE UPPER' = 4.5
		displayFolder: SURVEY_MEASURES
		lineageTag: 1d866440-325d-4afa-ab51-452dc3b9318c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DUMMY MEANSCORE 0' = 0
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: dd41ecc3-3e5d-4e85-872e-0ab213429e69

	measure GENAI_OVERALL_SENTIMENT_NUMBER = ```
			
			VAR overall = SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_METRIC_OVERALL_SENTIMENT_VALUE])
			VAR result =
			SWITCH(TRUE(), 
			                ISBLANK(overall), "--",
			                overall =  4, "Very good",
			                overall =  3, "Good",
			                overall =  2, "Mixed",
			                overall =  1, "Bad",
			                overall =  0, "Very bad"
			                )
			                
			RETURN result
			```
		lineageTag: 912127fd-295e-43fd-83c2-f907f1a89fe1

	measure 'TOTAL VALID SURVEY' =
			
			CALCULATE(
			    SUMX(SUMMARIZE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS, X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_UNIQUE_ID], X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_NUMBER_OF_NOT_RUBBISH]), X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_NUMBER_OF_NOT_RUBBISH]),
			    CROSSFILTER(DIM_ITEM[TITLE], X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[ITEM_TITLE], None))
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: f9477f31-64a2-48e6-b281-5c22b065cb93

	measure 'TOTAL RUBBISH FEEDBACK' = [TOTAL COMPLETED SURVEY] - [TOTAL VALID SURVEY]
		formatString: 0
		displayFolder: SURVEY_MEASURES
		lineageTag: 39693ce8-b1bb-4299-a2ad-6c8eadb438ca

	measure _WRONGMISSING =
			
			VAR DelimiterPosition = SEARCH(";", SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[WRONG_OR_MISSING_CONTENT]),
			                                1, LEN(SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[WRONG_OR_MISSING_CONTENT])) + 1) - 1
			VAR result = LEFT(SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[WRONG_OR_MISSING_CONTENT]), DelimiterPosition)
			RETURN result
		lineageTag: 66f18b65-231d-4408-baa8-e475df57540a

	measure GENAI_SENTIMENT_INTERACT = SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_KEY_INTERACTIVITY_ENUM_VALUE])
		formatString: 0
		isHidden
		lineageTag: 3a162c35-d833-460b-8b82-015d5edfb576

		changedProperty = IsHidden

	measure GENAI_TOTAL_COMMENTS = "Base on " & SELECTEDVALUE(X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS[GENAI_METRIC_OVERALL_SENTIMENT_TOTAL_COMMENTS]) & " comments"
		lineageTag: 23e773f8-78a1-4a52-b0fb-8bd4db066880

	measure __0 = 0
		formatString: 0
		lineageTag: 79f5d54d-5b60-49eb-aa72-8fcf4f02d339

	measure __20 = 20
		formatString: 0
		lineageTag: 37eb6c2e-41e2-4d9a-bad3-85cb59e9f651

	measure __40 = 40
		formatString: 0
		lineageTag: fcd8ea1b-f9c8-4e7a-a158-1b3808a7ed6b

	measure __100 = 100
		formatString: 0
		lineageTag: 7f729c8f-a967-41eb-8c2a-bf294b8e975d

	measure __60 = 60
		formatString: 0
		lineageTag: d567be20-72d6-4514-a95a-264df2e77585

	measure __80 = 80
		formatString: 0
		lineageTag: 1fe28e9b-d2a0-412a-9047-0e5147229b18

	measure __70 = 70
		formatString: 0
		lineageTag: 20e7caff-7f71-4c19-b302-07b858db2f07

	measure __90 = 90
		formatString: 0
		lineageTag: ef5995f7-5cff-4434-8588-b24c857c9d74

	column MEASURES
		dataType: int64
		formatString: 0
		lineageTag: 940ddc61-1c79-4592-8516-8a24caed442e
		summarizeBy: sum
		sourceColumn: MEASURES

		annotation SummarizationSetBy = Automatic

	partition _MEASURES = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MEASURES = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MEASURES", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

