table DIM_COUNTRY
	lineageTag: 2482af0f-8a3a-4fb9-81d0-7a60bb7e1c7c

	column COUNTRY
		dataType: string
		lineageTag: 84be4bce-2220-4545-8882-430e0116b383
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_FIX_LEN
		dataType: string
		lineageTag: 0aaedde2-bdec-43dc-9dea-68f5af1b2fe6
		summarizeBy: none
		sourceColumn: COUNTRY_FIX_LEN

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 606a74c4-d38e-4c5f-8fe7-f16ecf07ea75
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT
		dataType: string
		lineageTag: 2f79428b-2125-4995-8510-ab3d8d403b27
		summarizeBy: none
		sourceColumn: CONTINENT

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 677036a8-3adf-4675-a353-02122cbc10ef
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: d34f55d7-e044-47a6-b1f6-713b9505285e
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: f3a459a5-5885-44a1-bbc7-bf85a0a88f28
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: bb22359b-47cc-4a54-9da2-03b78ffe65d3
		summarizeBy: none
		sourceColumn: COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	partition DIM_COUNTRY = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT #(lf)DISTINCT #(lf)    CONTINENT_CODE,#(lf)    CONTINENT,#(lf)    COUNTRY_GROUP_CODE,#(lf)    COUNTRY_GROUP,#(lf)    COUNTRY,#(lf)    COUNTRY_ISO_CODE,#(lf)    COUNTRY_DISPLAY_TEXT#(lf)FROM MARD_PCMS.X_IFR_TRAINM_ACE_EPIC6_TRAINING_RATE"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,null,"",Replacer.ReplaceValue,{"COUNTRY"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "COUNTRY_FIX_LEN", each if Text.Length([COUNTRY])> 18 then Text.Start([COUNTRY],18) else Text.End(Text.Repeat(Character.FromNumber (8192), 18) & [COUNTRY],18))
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

