table DIM_DATE
	lineageTag: 7ba9d138-dccd-4c53-bfa6-c9a798deafc7

	column FullDateAlternateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c4f715a-2249-4b42-bf55-3e5e1e1b46b1
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: double
		formatString: 0
		lineageTag: 6669ba4f-eb07-4155-9359-edb527a02cec
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: double
		lineageTag: 7f2df4bc-25ec-478c-b3c5-8e12324e0b28
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: 56acf260-f1f8-4c6b-8ec1-1c641199a246
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Short Month Name'
		dataType: string
		lineageTag: bbf0c4de-1480-488f-b89f-5c66f51e380e
		summarizeBy: none
		sourceColumn: Short Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: double
		lineageTag: 867d47b3-9cae-4b4c-851c-a93c1c655533
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year'
		dataType: double
		lineageTag: 9405fd3e-9375-4ced-a408-47461b9b5ec5
		summarizeBy: sum
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Month'
		dataType: double
		lineageTag: a4a13939-73c1-42ce-a68e-5fe8a74cf331
		summarizeBy: sum
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: double
		lineageTag: a4bd157d-a902-4713-bb2a-61ceda92b654
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: double
		lineageTag: 8a7488ec-2e66-48ce-ac66-bcf40f14976c
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Year'
		dataType: double
		lineageTag: 8e376e13-0cfe-48ae-85e4-dac268f0b0b1
		summarizeBy: sum
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name'
		dataType: string
		lineageTag: ef3ea5d2-3c7b-4416-98b9-a4806dc11c8b
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 06e0900c-aeef-4994-9e7b-8106590bcfde
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Year Month 2'
		dataType: string
		lineageTag: a51a5c14-ad9c-42b9-bd16-52b93046aa25
		summarizeBy: none
		sourceColumn: Year Month 2

		annotation SummarizationSetBy = Automatic

	column 'Year Month 3'
		dataType: string
		lineageTag: fff2907d-5c72-4f2e-b13f-26ede979842c
		summarizeBy: none
		sourceColumn: Year Month 3
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Quarter text'
		dataType: string
		lineageTag: d32b9a0f-e5dd-4f30-a65b-a294cd25d81a
		summarizeBy: none
		sourceColumn: Quarter text

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE = m
		mode: import
		source =
				let
				    StartDate = Date.From(SOM_MIN_IMPORTATION_DATE{0}),
				    EndDate = Date.From(EOM_MAX_IMPORTATION_DATE{0}),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "FullDateAlternateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FullDateAlternateKey", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([FullDateAlternateKey]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([FullDateAlternateKey]), type number),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([FullDateAlternateKey]), type text),
				    #"Inserted Short Month Name" = Table.AddColumn(#"Inserted Month Name", "Short Month Name", each Text.Start(Date.MonthName([FullDateAlternateKey]),3), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Short Month Name", "Quarter", each Date.QuarterOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([FullDateAlternateKey]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([FullDateAlternateKey]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([FullDateAlternateKey]), type number),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([FullDateAlternateKey]), type text),
				    #"Added Custom Column" = Table.AddColumn(#"Inserted Day Name", "Year Month", each Text.Combine({Date.ToText([FullDateAlternateKey], "yyyy"), Date.ToText([FullDateAlternateKey], "MM")}), type text),
				    #"Added Custom Column 2" = Table.AddColumn(#"Added Custom Column", "Year Month 2", each Text.Combine({Date.ToText([FullDateAlternateKey], "MM"),"." , Date.ToText([FullDateAlternateKey], "yyyy")}), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom Column 2",{{"Year Month", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Year Month 3", each if [Year Month]= List.Max(#"Changed Type1"[Year Month]) then "Latest Month" else [Year Month 2]),
				    #"Inserted Prefix" = Table.AddColumn(#"Added Custom", "Prefix", each "Q" & Text.From([Quarter], "en-US"), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Prefix",{{"Prefix", "Quarter text"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

