table DIM_SURVEY_RATING
	lineageTag: 47eb70e1-0f9d-4eb3-97f0-33df98be3db1

	column ORDER
		dataType: int64
		formatString: 0
		lineageTag: e26a83aa-b1e1-4d10-950a-6daca3b1a5f9
		summarizeBy: none
		sourceColumn: ORDER

		annotation SummarizationSetBy = Automatic

	column RATING
		dataType: string
		lineageTag: a0aed3e5-3d6e-46ae-bd45-ccdb7a6a670d
		summarizeBy: none
		sourceColumn: RATING

		annotation SummarizationSetBy = Automatic

	column TEXT
		dataType: string
		lineageTag: f510c29b-ab75-484c-b46d-74cd085ea979
		summarizeBy: none
		sourceColumn: TEXT

		annotation SummarizationSetBy = Automatic

	partition DIM_SURVEY_RATING = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSAWOX1LTMvMyS1JxKhZKi0lSlWJ1oJSOgOAj7JmbmIYsbA8VA2C+/RKEoNTEnpxIsbAIUMoEKJwJRTg5Y2BQkpO8IJWNjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ORDER = _t, RATING = _t, TEXT = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ORDER", Int64.Type}, {"RATING", type text}, {"TEXT", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

