table E6_SpecificTheme
	lineageTag: 1d1f968a-9a78-40a1-a7d6-ef117cf6e7c5

	column ThemeID
		dataType: int64
		formatString: 0
		lineageTag: 7ec4278c-3fee-4c51-847c-3cbf64d3a48d
		summarizeBy: count
		sourceColumn: ThemeID

		annotation SummarizationSetBy = Automatic

	column Theme
		dataType: string
		lineageTag: c296ca7d-4ec5-47d7-a838-27957afaafe3
		summarizeBy: none
		sourceColumn: Theme

		annotation SummarizationSetBy = Automatic

	column survey-checkmark
		dataType: string
		lineageTag: b2a78c27-c074-426a-9310-948ed709da24
		summarizeBy: none
		sourceColumn: survey-checkmark

		annotation SummarizationSetBy = Automatic

	column structure-organization
		dataType: string
		lineageTag: 2c2ebb35-bc03-4a66-b834-973949ce969d
		summarizeBy: none
		sourceColumn: structure-organization

		annotation SummarizationSetBy = Automatic

	column home
		dataType: string
		lineageTag: 093d39b4-5d1a-4000-8bd2-04423fd8f04e
		summarizeBy: none
		sourceColumn: home

		annotation SummarizationSetBy = Automatic

	column checklist
		dataType: string
		lineageTag: 42bee6e1-d517-48d9-9ae3-3e6d065182f8
		summarizeBy: none
		sourceColumn: checklist

		annotation SummarizationSetBy = Automatic

	partition E6_SpecificTheme = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("1dTbbuIwEAbgd+EainPqSapWEHMIzTgL6wBOt0LgAIkTExoCAT/9hu1WqirtfSprZI00vvn0e15eGlqj2XDjbVRUd1QU+8Nju83DXWt5OKyLQ2t9vNnk2a6IN5cbnsn2wWh/9K31rljn+zw+rFubOF1fh9vry6hk80nmiCxm8kExPeKu3hdMf9BWu4ma2w8RmZYngjsl4I7l9csTH45OSzkV4ZBwV3HzOsMNkr73fjm37xVR27+zRAeTqV4Js54BAxIR6WtkxiwiEhSIIGaCGUyfSDIYF0B9zcP+BWgHQWypUPJ4M35cZQcePT4vhyp1d9FoQvaubN2J3PCwpwGat1o2LPW4WAHBdKsFnR9lHBbRk24iVFckVr25PxPsWx7tVz0RMJhIwNfqJoQGaSBCAbRXBnRrggQDRCCBprFLezoI0K/AIJIjN4Kds0P/lLTN9Cz6WRj9mt4vwBvCc9oJ6N3+eWGm7JJ35aBMkbvpl5r5DZSIvEYJcHKBtDx5M8cKZswkOEoJ3lpMjEumfAWKI282Rkxxg9EeAgXXKFmEji8EJ4jYX6LUL8tQc8kpWXihz1Ye+0mNwYgvNByMczUvJmzbXU6MY2w6n5B+HxHSb3mWZvkTal6PVlM3nUTvbpVV9Q7EKGHS1wOcRh51TJiNpFd9FJBOZdVNAIPp0UgS7Hy4nauEneGrm51EdzGWiZq+2Ygxkr8xZ2rddorFmx+lvmUnxnEobZ5w+Byu1+ZLQ6+o8DJPaipWr6X1OWm6ZTU/qq55q9k2+3Z8tV1z30GvXsvu/3qvr38A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ThemeID = _t, Theme = _t, #"survey-checkmark" = _t, #"structure-organization" = _t, home = _t, checklist = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ThemeID", Int64.Type}, {"Theme", type text}, {"survey-checkmark", type text}, {"structure-organization", type text}, {"home", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

