table X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS
	lineageTag: d1c35ec6-2417-4fee-aef3-5c74088b5fce

	column GENAI_UNIQUE_ID
		dataType: int64
		formatString: 0
		lineageTag: 875c2d49-6d19-4289-9613-5fede5c6586c
		summarizeBy: none
		sourceColumn: GENAI_UNIQUE_ID

		annotation SummarizationSetBy = Automatic

	column RUN_CYCLE
		dataType: string
		lineageTag: 6deb3e2a-187f-4a73-ab84-b35014519f99
		summarizeBy: none
		sourceColumn: RUN_CYCLE

		annotation SummarizationSetBy = Automatic

	column ITEM_ID
		dataType: string
		lineageTag: 1e27b7fa-e86b-49f6-9732-5aaa58b8d1bc
		summarizeBy: none
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TITLE
		dataType: string
		lineageTag: 140f5f1c-585c-43b5-8ee6-278ec510bc97
		summarizeBy: none
		sourceColumn: ITEM_TITLE

		annotation SummarizationSetBy = Automatic

	column GENAI_EXECUTIVE_SUMMARY
		dataType: string
		lineageTag: 6c64b1e5-9841-4354-a0ee-2a9f58a32b39
		summarizeBy: none
		sourceColumn: GENAI_EXECUTIVE_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_NUMBER_OF_NOT_RUBBISH
		dataType: int64
		formatString: 0
		lineageTag: 080e393d-82e5-4dda-be7e-16257a688696
		summarizeBy: sum
		sourceColumn: GENAI_NUMBER_OF_NOT_RUBBISH

		annotation SummarizationSetBy = Automatic

	column ITEM_MONTH
		dataType: string
		lineageTag: c32ea502-a696-4c68-851f-e835cb03aa20
		summarizeBy: none
		sourceColumn: ITEM_MONTH

		annotation SummarizationSetBy = Automatic

	column GENAI_HINTS_FOR_IMPROVEMENT
		dataType: string
		lineageTag: 9bcd954c-99d5-45b0-98e0-9f07a4c6d297
		summarizeBy: none
		sourceColumn: GENAI_HINTS_FOR_IMPROVEMENT

		annotation SummarizationSetBy = Automatic

	column MONTH_YEAR
		dataType: string
		lineageTag: f84e9061-edc3-48cb-8ad1-2f75dca3b0e6
		summarizeBy: none
		sourceColumn: MONTH_YEAR

		annotation SummarizationSetBy = Automatic

	column FULL_DATE
		dataType: string
		lineageTag: 4f5a1439-a9d8-42e8-8636-3c745d06ff6f
		summarizeBy: none
		sourceColumn: FULL_DATE

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 50ef10e0-5cde-4c82-bfed-ecdcf2a75809
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column ROWID
		dataType: string
		lineageTag: 8c59abd0-967f-464c-bb10-1e31e3ed2d0e
		summarizeBy: none
		sourceColumn: ROWID

		annotation SummarizationSetBy = Automatic

	column 'Year Month 2'
		dataType: string
		lineageTag: d77cff9c-df3f-4a4b-b053-f60bf33fe340
		summarizeBy: none
		sourceColumn: Year Month 2

		annotation SummarizationSetBy = Automatic

	column BATCH_ID
		dataType: string
		lineageTag: ee7d06f1-4bf8-4fd0-ace1-e9fef2544868
		summarizeBy: none
		sourceColumn: BATCH_ID

		annotation SummarizationSetBy = Automatic

	column BATCH_YEAR
		dataType: int64
		formatString: 0
		lineageTag: c94ed9ca-3493-4e3c-9c1c-1ca617c1ecc7
		summarizeBy: sum
		sourceColumn: BATCH_YEAR

		annotation SummarizationSetBy = Automatic

	column BATCH_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 3225ed67-f4ec-4ec9-b01f-27370af835b5
		summarizeBy: sum
		sourceColumn: BATCH_MONTH

		annotation SummarizationSetBy = Automatic

	column RUN_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b50e41e-384e-433a-99c4-215ce1b21846
		summarizeBy: none
		sourceColumn: RUN_DATETIME

		annotation SummarizationSetBy = Automatic

	column GENAI_TOTAL_COMMENT
		dataType: int64
		formatString: 0
		lineageTag: a79e4c91-c327-4f3d-a348-e0e1cc067152
		summarizeBy: sum
		sourceColumn: GENAI_TOTAL_COMMENT

		annotation SummarizationSetBy = Automatic

	column GENAI_NUMBER_OF_RUBBISH
		dataType: int64
		formatString: 0
		lineageTag: 8f126334-fbd8-4f0e-bee2-2e80eb417c3c
		summarizeBy: sum
		sourceColumn: GENAI_NUMBER_OF_RUBBISH

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_OVERALL_SENTIMENT_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 4731c6c5-5f6d-49ad-8755-83e0807481a1
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_OVERALL_SENTIMENT_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_OVERALL_SENTIMENT_SUMMARY
		dataType: string
		lineageTag: a87524c8-e87c-4180-aa85-a122a73737eb
		summarizeBy: none
		sourceColumn: GENAI_METRIC_OVERALL_SENTIMENT_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_OVERALL_SENTIMENT_REF_COMMENTS
		dataType: string
		lineageTag: ea19aca3-7e2a-49c9-9404-8a82546a8efc
		summarizeBy: none
		sourceColumn: GENAI_METRIC_OVERALL_SENTIMENT_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_OVERALL_SENTIMENT_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: 25c0dfb2-b094-43b9-aed8-74d125475cd1
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_OVERALL_SENTIMENT_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CLARITY_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 8f0affbe-0a4b-471d-8245-3b43986d701a
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_CLARITY_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CLARITY_SUMMARY
		dataType: string
		lineageTag: 91e26d2f-d988-4456-b0be-1d59876fc88c
		summarizeBy: none
		sourceColumn: GENAI_METRIC_CLARITY_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CLARITY_REF_COMMENTS
		dataType: string
		lineageTag: 021884f7-1735-4bb1-a82a-1af39e41925c
		summarizeBy: none
		sourceColumn: GENAI_METRIC_CLARITY_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CLARITY_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: 6965846a-b922-4ef9-a4af-d1305afc0b8f
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_CLARITY_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_PRACTICAL_EXAMPLE_VALUE
		dataType: int64
		formatString: 0
		lineageTag: b822e0e9-5459-4d79-af58-8dcff13bd34b
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_PRACTICAL_EXAMPLE_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_PRACTICAL_EXAMPLE_SUMMARY
		dataType: string
		lineageTag: 4daeb72d-4064-48f1-a9ba-cf4ee99466c5
		summarizeBy: none
		sourceColumn: GENAI_METRIC_PRACTICAL_EXAMPLE_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_PRACTICAL_EXAMPLE_REF_COMMENTS
		dataType: string
		lineageTag: 17d7fd0e-af13-4287-828e-fa48635f67c5
		summarizeBy: none
		sourceColumn: GENAI_METRIC_PRACTICAL_EXAMPLE_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_PRACTICAL_EXAMPLE_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: e19cba34-4919-4658-97c1-77382fa0a016
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_PRACTICAL_EXAMPLE_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USE_OF_VISUALS_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 03ec9b37-4bb1-4950-950c-f221fbd5c4d4
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_USE_OF_VISUALS_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USE_OF_VISUALS_SUMMARY
		dataType: string
		lineageTag: cf3675a5-83b0-4ea4-9261-cd51f3e3ec98
		summarizeBy: none
		sourceColumn: GENAI_METRIC_USE_OF_VISUALS_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USE_OF_VISUALS_REF_COMMENTS
		dataType: string
		lineageTag: 9a777742-08a1-41b4-b994-70960eeeea9c
		summarizeBy: none
		sourceColumn: GENAI_METRIC_USE_OF_VISUALS_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USE_OF_VISUALS_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: 9e352907-a064-4be1-a435-520c0a55e380
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_USE_OF_VISUALS_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_FLEXIBILITY_VALUE
		dataType: int64
		formatString: 0
		lineageTag: b7017782-1748-451d-b0a7-c66329dd37ff
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_FLEXIBILITY_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_FLEXIBILITY_SUMMARY
		dataType: string
		lineageTag: a81a2e86-0d75-4b2f-b5af-0165afb2e799
		summarizeBy: none
		sourceColumn: GENAI_METRIC_FLEXIBILITY_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_FLEXIBILITY_REF_COMMENTSI
		dataType: string
		lineageTag: d4dfdfa3-4545-467a-9773-2d1ca926e72f
		summarizeBy: none
		sourceColumn: GENAI_METRIC_FLEXIBILITY_REF_COMMENTSI

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_FLEXIBILITY_TOTAL_COMMENTSI
		dataType: int64
		formatString: 0
		lineageTag: 660127da-9058-4f9b-8fe0-4045abe48231
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_FLEXIBILITY_TOTAL_COMMENTSI

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_ENGAGEMENT_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 365d81a1-9a2f-4619-a8a5-b004d2decb46
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_ENGAGEMENT_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_ENGAGEMENT_SUMMARY
		dataType: string
		lineageTag: 576afd1d-1abf-4983-9cf5-cf72e85026b0
		summarizeBy: none
		sourceColumn: GENAI_METRIC_ENGAGEMENT_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_ENGAGEMENT_REF_COMMENTS
		dataType: string
		lineageTag: 9dd70b8f-eab7-466d-a7c1-da49e3863d67
		summarizeBy: none
		sourceColumn: GENAI_METRIC_ENGAGEMENT_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_ENGAGEMENT_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: c7bb6b9c-8b21-4f7d-823c-bcdbaa4f1aa7
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_ENGAGEMENT_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_LENGTH_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 7cf09437-cc53-429e-b997-2cac67b8885c
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_LENGTH_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_LENGTH_SUMMARY
		dataType: string
		lineageTag: c5e03a9d-227c-48c2-b809-042094b77d5d
		summarizeBy: none
		sourceColumn: GENAI_METRIC_LENGTH_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_LENGTH_REF_COMMENTS
		dataType: string
		lineageTag: 0570a270-4141-49a3-9ae1-4245f6774609
		summarizeBy: none
		sourceColumn: GENAI_METRIC_LENGTH_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_LENGTH_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: 7f6f1398-fdc8-461d-9c2c-e00193320835
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_LENGTH_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CONTENT_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 865bca8c-7c37-45b5-a5a2-48b5e1bfccec
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_CONTENT_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CONTENT_SUMMARY
		dataType: string
		lineageTag: 06c6d231-ef8c-45e2-8b93-70011844b749
		summarizeBy: none
		sourceColumn: GENAI_METRIC_CONTENT_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CONTENT_REF_COMMENTS
		dataType: string
		lineageTag: 0e71f8ad-a8bb-43fc-8ce7-2a8839fd8f99
		summarizeBy: none
		sourceColumn: GENAI_METRIC_CONTENT_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_CONTENT_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: bc1c59d6-1bd9-4513-9bc1-a83b85b390d8
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_CONTENT_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_TECHNICAL_ISSUES_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 9b794ba9-3bd4-4a93-86e0-913351d3c60c
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_TECHNICAL_ISSUES_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_TECHNICAL_ISSUES_SUMMARY
		dataType: string
		lineageTag: d7201b9c-9d8b-48f3-adfd-f7535798821e
		summarizeBy: none
		sourceColumn: GENAI_METRIC_TECHNICAL_ISSUES_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_TECHNICAL_ISSUES_REF_COMMENTS
		dataType: string
		lineageTag: 0e9dc22d-790a-488f-bd8c-7524e674c95e
		summarizeBy: none
		sourceColumn: GENAI_METRIC_TECHNICAL_ISSUES_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_TECHNICAL_ISSUES_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: f3459b8c-980a-40fb-b142-801b7367178e
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_TECHNICAL_ISSUES_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USABILITY_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 062459e9-bd8b-4e7b-aefe-d907468d6ea8
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_USABILITY_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USABILITY_SUMMARY
		dataType: string
		lineageTag: 58afb23d-915e-41ad-9e50-0ab33769bab2
		summarizeBy: none
		sourceColumn: GENAI_METRIC_USABILITY_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USABILITY_REF_COMMENTS
		dataType: string
		lineageTag: 14d888cb-068f-4475-943b-67a54d9a2f1e
		summarizeBy: none
		sourceColumn: GENAI_METRIC_USABILITY_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_USABILITY_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: 78d8cacd-a72f-4794-a6a7-4e1a8f9445ef
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_USABILITY_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_INTERACTIVITY_VALUE
		dataType: int64
		formatString: 0
		lineageTag: 9f2b5f46-ee15-4266-854f-e407d51b6ad7
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_INTERACTIVITY_VALUE

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_INTERACTIVITY_SUMMARY
		dataType: string
		lineageTag: ea1f1e50-8b62-4804-a2b7-bd837f8b7113
		summarizeBy: none
		sourceColumn: GENAI_METRIC_INTERACTIVITY_SUMMARY

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_INTERACTIVITY_REF_COMMENTS
		dataType: string
		lineageTag: 488e476b-0037-4495-b280-bab69d318573
		summarizeBy: none
		sourceColumn: GENAI_METRIC_INTERACTIVITY_REF_COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_METRIC_INTERACTIVITY_TOTAL_COMMENTS
		dataType: int64
		formatString: 0
		lineageTag: e204dbb3-c7d9-4b75-bcaa-d3781ce7d90c
		summarizeBy: sum
		sourceColumn: GENAI_METRIC_INTERACTIVITY_TOTAL_COMMENTS

		annotation SummarizationSetBy = Automatic

	partition X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT * FROM MARD_PCMS.X_IFR_TRAINM_GENAI_EPIC6_ANALYSIS"]),
				    #"Inserted Text Between Delimiters2" = Table.AddColumn(Source, "ITEM_MONTH", each Text.BetweenDelimiters([BATCH_ID], "_", "_"), type text),
				    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Text Between Delimiters2", "Merged", each Text.Combine({Number.ToText([BATCH_MONTH]), Number.ToText([BATCH_YEAR])}, " - "), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "MONTH_YEAR"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "FULL_DATE", each Date.FromText("01" & [ITEM_MONTH] & Number.ToText([BATCH_YEAR]))),
				    #"Added Custom1" =  Table.AddColumn(#"Added Custom", "Year Month", each Text.Combine({Date.ToText([FULL_DATE], "yyyy"), Date.ToText([FULL_DATE], "MM")})),
				    #"Added Custom2" =  Table.AddColumn(#"Added Custom1", "ROWID", each Text.Combine({[Year Month],[Year Month], [ITEM_ID]})),
				    #"Added Custom3" =  Table.AddColumn(#"Added Custom2", "Year Month 2", each Text.Combine({Date.ToText([FULL_DATE], "MM"),".", Date.ToText([FULL_DATE], "yyyy")}))
				in
				    #"Added Custom3"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

