table X_IFR_EPIC6_TRAINING_RATE_UNPIVOT
	lineageTag: 70f6eef2-df92-4e83-bd2f-e6def869d583

	column ITEM_ID
		dataType: string
		lineageTag: 6f834597-bea4-4dd2-acfa-71ef1c0b7751
		summarizeBy: none
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TYPE
		dataType: string
		lineageTag: 753f10de-91c6-4f0e-abd7-a6eb523f1ad4
		summarizeBy: none
		sourceColumn: ITEM_TYPE

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: 7b4c888f-a7c7-4664-a804-c37aad572093
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column ORG_AREA
		dataType: string
		lineageTag: 82637877-9064-4971-8226-02027072ebe1
		summarizeBy: none
		sourceColumn: ORG_AREA

		annotation SummarizationSetBy = Automatic

	column ASS_STATUS
		dataType: string
		lineageTag: 96c8bd29-5557-44ba-a3d4-b3531fb62fd3
		summarizeBy: none
		sourceColumn: ASS_STATUS

		annotation SummarizationSetBy = Automatic

	column NUM_OF_ASS
		dataType: int64
		formatString: 0
		lineageTag: 1c84ec44-bfde-4226-9bcb-7702be5f279d
		summarizeBy: sum
		sourceColumn: NUM_OF_ASS

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 67800d1c-f94e-4401-b1b6-fb49d8bbb506
		summarizeBy: sum
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column ROWID
		dataType: string
		lineageTag: 400cb3ce-b8ca-4638-a3fe-054bda3b6c7c
		summarizeBy: none
		sourceColumn: ROWID

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d84915f-d8e9-442e-a5a1-3487347b77e9
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TITLE
		dataType: string
		lineageTag: 1dda7d0b-249e-4a6b-94d2-a7b02103dc2d
		summarizeBy: none
		sourceColumn: TITLE

		annotation SummarizationSetBy = Automatic

	column BU_EXTENDED
		dataType: string
		lineageTag: 0cec7b46-0397-4ff4-ac13-527902affef0
		summarizeBy: none
		sourceColumn: BU_EXTENDED

		annotation SummarizationSetBy = Automatic

	column DEPARTMENT
		dataType: string
		lineageTag: 7b9afad1-f6a5-4b8b-86a1-18427770d4b7
		summarizeBy: none
		sourceColumn: DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column REGION
		dataType: string
		lineageTag: 905a7b7a-15bb-457e-8147-c8caa7349638
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column TOTAL_OVERDUE_DAYS
		dataType: double
		lineageTag: 0677a0a2-ece8-4d11-8b52-f62c858ee2ec
		summarizeBy: sum
		sourceColumn: TOTAL_OVERDUE_DAYS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORGANIZATION
		dataType: string
		lineageTag: 24304f28-275c-4537-aec4-e5fa0d5c43c8
		summarizeBy: none
		sourceColumn: ORGANIZATION

		annotation SummarizationSetBy = Automatic

	column ORGID
		dataType: string
		lineageTag: f2550b96-ad5b-4918-86c0-4f15bbebe21f
		summarizeBy: none
		sourceColumn: ORGID

		annotation SummarizationSetBy = Automatic

	column OVERDUE_DAYS_PER_ASS
		dataType: double
		lineageTag: bbcdf84a-2d41-45df-9e11-2e7491176187
		summarizeBy: sum
		sourceColumn: OVERDUE_DAYS_PER_ASS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition X_IFR_EPIC6_TRAINING_RATE_UNPIVOT = m
		mode: import
		source =
				let
				    Source = X_IFR_EPIC6_TRAINING_RATE,
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Source, {"EXPORT_DATE", "ITEM_ID", "TITLE", "ITEM_TYPE", "REGION", "COUNTRY", "ORG_AREA", "BU_EXTENDED", "DEPARTMENT", "ORGANIZATION", "ORGID", "TOTAL_OVERDUE_DAYS"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Columns", each [Attribute] = "ASS_COMPLETED" or [Attribute] = "ASS_OVERDUE" or [Attribute] = "ASS_STILL_DUE"),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Attribute", "ASS_STATUS"}, {"Value", "NUM_OF_ASS"}}),
				    #"Added Custom Column" = Table.AddColumn(#"Renamed Columns", "Year Month", each Text.Combine({Date.ToText([EXPORT_DATE], "yyyy"), Date.ToText([EXPORT_DATE], "MM")}), type text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom Column",{{"EXPORT_DATE", type date}, {"ITEM_ID", type text}, {"NUM_OF_ASS", Int64.Type}, {"Year Month", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","ASS_","",Replacer.ReplaceText,{"ASS_STATUS"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","_"," ",Replacer.ReplaceText,{"ASS_STATUS"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value1",{{"ASS_STATUS", Text.Proper, type text}}),
				    #"Added Custom Column2" = Table.AddColumn(#"Capitalized Each Word", "ROWID", each Text.Combine({Text.From([Year Month], "en-US"), Text.From([ITEM_ID], "en-US"), Text.Replace(Text.Upper([COUNTRY]), " ",""),[REGION], [ORGANIZATION], [DEPARTMENT], [BU_EXTENDED], [ORG_AREA]}), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom Column2",{{"TITLE", "TITLE"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "OVERDUE_DAYS_PER_ASS", each if [ASS_STATUS] = "Overdue" and [NUM_OF_ASS]>0 then [TOTAL_OVERDUE_DAYS]/[NUM_OF_ASS] else null),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"OVERDUE_DAYS_PER_ASS", type number}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

