table Copyright
	lineageTag: 77e366c2-9d26-45d2-ae4f-6ce151fd945a

	column Declare
		dataType: string
		lineageTag: 340b1266-b8bc-40d7-9551-9933bfb5ab49
		summarizeBy: none
		sourceColumn: Declare

		annotation SummarizationSetBy = Automatic

	column Copyright
		dataType: string
		lineageTag: 4cdbd079-4569-4b55-bb83-01629c809831
		summarizeBy: none
		sourceColumn: Copyright

		annotation SummarizationSetBy = Automatic

	partition Copyright = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjIwMlEIyk9KLSpRcMovTs5QcM9N8tBRSMzJUSjKTM8oKVYoSi1OLSpLTVGKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Copyright = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Copyright", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Character.FromNumber(0169) & " " & [Copyright]),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Copyright", "Declare"}, {"Custom", "Copyright"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

