table ThemeFilter
	lineageTag: 05095a8c-3d4e-4887-8f3a-ce8e46115154

	column Theme
		dataType: string
		lineageTag: 4e3fa3fd-076f-46c2-824d-f5f9547b7483
		summarizeBy: none
		sourceColumn: Theme

		annotation SummarizationSetBy = Automatic

	column 'Bosch Logo'
		dataType: string
		lineageTag: b7b8268e-96f4-4049-9d06-d875a5323909
		summarizeBy: none
		sourceColumn: Bosch Logo

		annotation SummarizationSetBy = Automatic

	column ThemeID
		dataType: string
		lineageTag: 10a54921-ab64-41c7-a5ad-ae94f7865377
		summarizeBy: none
		sourceColumn: ThemeID

		annotation SummarizationSetBy = Automatic

	column Font
		dataType: string
		lineageTag: 5ebe1a7f-14e1-4b23-aeb9-af5f2e1b1605
		summarizeBy: none
		sourceColumn: Font

		annotation SummarizationSetBy = Automatic

	column 'Banner Color'
		dataType: string
		lineageTag: d8f28bb4-2625-469b-a1df-b161b9976b3a
		summarizeBy: none
		sourceColumn: Banner Color

		annotation SummarizationSetBy = Automatic

	column 'Background Color'
		dataType: string
		lineageTag: 5bcb536b-c9c4-4c63-b905-af60cca2f59e
		summarizeBy: none
		sourceColumn: Background Color

		annotation SummarizationSetBy = Automatic

	column 'Visual Background Color'
		dataType: string
		lineageTag: 1e48d3d3-9589-4bd6-80ce-c732c7e6fd57
		summarizeBy: none
		sourceColumn: Visual Background Color

		annotation SummarizationSetBy = Automatic

	column 'Visual Border Color'
		dataType: string
		lineageTag: 6ec15dc2-8a27-42ab-a0c2-45c762c7b452
		summarizeBy: none
		sourceColumn: Visual Border Color

		annotation SummarizationSetBy = Automatic

	column 'Shadow Color'
		dataType: string
		lineageTag: 922e964b-64fa-484d-b71e-862a111fc119
		summarizeBy: none
		sourceColumn: Shadow Color

		annotation SummarizationSetBy = Automatic

	column 'Theme Number'
		dataType: int64
		formatString: 0
		lineageTag: c6d0a597-7542-4e9a-a597-062907535dba
		summarizeBy: sum
		sourceColumn: Theme Number

		annotation SummarizationSetBy = Automatic

	column 'Theme Icon'
		dataType: string
		lineageTag: 36a824d0-2a15-4b87-8ea1-385004b158fd
		summarizeBy: none
		sourceColumn: Theme Icon

		annotation SummarizationSetBy = Automatic

	column 'Font Reverse'
		dataType: string
		lineageTag: 12b21805-c4be-47ce-8759-b52a2291e0a1
		summarizeBy: none
		sourceColumn: Font Reverse

		annotation SummarizationSetBy = Automatic

	partition ThemeFilter = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zZBtb5swFIX/C/taCjElg0jTlBTywmKnYZDGRNGUEgh4vKTgYvCvr0GqqkzTPu9aV9fn3CNd6TkcpJF0J63TS0LFNL8ahhgJpdd6oijhuZBPdR3RWo7e7uOqLGgad/dhmSu1pnxoOSpoVF2rtI7kOM2iPqxEncPw3i1XpExxbnIMknAN5gQDc/RSuHz/aCZoxxpkTRm0pvpmzppw6TSnfEfOSxSuua2jEWvwHvFg3+eNByjykNgaJFgTGmDuM/TsJIhnBHtOhohoEORwgTl6tltMLgAtVg+bn2qLCNQR2YpbsF0XItU55uSlrMNk4rTLE27rrrMssEgXJKEx8dY0qMPXsGkL97W5PlEjUquZ/52lZ5p8M1RVUPoyH6r/qUPdelEcj2Jw6+mmbo8Hzx73TzreHaReW6fq98DfVP9j/tkH/5D1GpGpDvlW9CxD+Yoh4GaI+/rGmyWB52tI3IO5z4P0n/zdH9Mu2+6yzC26kNkpb5D3i9qPlFyQJRtv5vw6wzncrJ7+4P836sDWVE273X56n/zHQ0nH4zs=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ThemeID = _t, Theme = _t, #"Theme Number" = _t, #"Bosch Logo" = _t, #"Font Reverse" = _t, Font = _t, #"Banner Color" = _t, #"Background Color" = _t, #"Visual Background Color" = _t, #"Visual Border Color" = _t, #"Shadow Color" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Theme", type text}, {"Bosch Logo", type text}, {"Theme Number", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Theme Icon", each Character.FromNumber([Theme Number]) & " " & [Theme])
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

