table 'Export Worksheet'
	lineageTag: 6f24610e-044c-48b9-a039-9aa60cc09d8f

	column ITEM_ID
		dataType: string
		lineageTag: 8b64eaeb-770f-4efe-8e00-7db99bbf941c
		summarizeBy: none
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TYPE_ID
		dataType: string
		lineageTag: 9fd4d451-f53c-470c-8258-5c6d97bcf138
		summarizeBy: none
		sourceColumn: ITEM_TYPE_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_GROUP
		dataType: string
		lineageTag: 2ccd2cf3-1a85-4123-af1d-530646063fb4
		summarizeBy: none
		sourceColumn: ITEM_GROUP

		annotation SummarizationSetBy = Automatic

	column PREFIX_ID
		dataType: string
		lineageTag: 290368a4-b080-49db-94fd-956150b2b8d6
		summarizeBy: none
		sourceColumn: PREFIX_ID

		annotation SummarizationSetBy = Automatic

	column PREFIX_TITLE
		dataType: string
		lineageTag: 70fb49db-6123-4ec2-8520-3240357b9504
		summarizeBy: none
		sourceColumn: PREFIX_TITLE

		annotation SummarizationSetBy = Automatic

	column ITEM_TITLE
		dataType: string
		lineageTag: 869a278a-f6bf-4fb9-92f8-5e22211f1a62
		summarizeBy: none
		sourceColumn: ITEM_TITLE

		annotation SummarizationSetBy = Automatic

	column SURVEY_ID
		dataType: string
		lineageTag: 8c7da340-9f1e-4707-9349-71821887292c
		summarizeBy: none
		sourceColumn: SURVEY_ID

		annotation SummarizationSetBy = Automatic

	column SURVEY_NAME
		dataType: string
		lineageTag: ab5a89a2-3b44-43fa-8799-e5c1080e86de
		summarizeBy: none
		sourceColumn: SURVEY_NAME

		annotation SummarizationSetBy = Automatic

	column ACTIVE_SURVEY
		dataType: string
		lineageTag: 228c68ca-d506-4907-841d-ca04cf589005
		summarizeBy: none
		sourceColumn: ACTIVE_SURVEY

		annotation SummarizationSetBy = Automatic

	column MEAN_SCORE
		dataType: double
		lineageTag: e2d1197c-6496-451f-b84a-7dbd2dffa211
		summarizeBy: sum
		sourceColumn: MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMPLETED_SURVEYS
		dataType: int64
		formatString: 0
		lineageTag: 5150f0ac-e0e2-4ce4-840d-245c311d52d1
		summarizeBy: sum
		sourceColumn: COMPLETED_SURVEYS

		annotation SummarizationSetBy = Automatic

	column TOTAL_SURVEYS
		dataType: int64
		formatString: 0
		lineageTag: 3ecb0251-e977-4fd7-a1d9-88ff7239bcb1
		summarizeBy: sum
		sourceColumn: TOTAL_SURVEYS

		annotation SummarizationSetBy = Automatic

	column FROM_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8f2146b-d393-4150-ab03-ab2de2ac356c
		summarizeBy: none
		sourceColumn: FROM_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TO_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a0d04fc-60c8-4e9a-ac83-6d2b1eb8ba51
		summarizeBy: none
		sourceColumn: TO_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ITEM_REVISION_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc5c72fd-823e-4aa3-9651-47c091a2b442
		summarizeBy: none
		sourceColumn: ITEM_REVISION_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLASSES
		dataType: int64
		formatString: 0
		lineageTag: b1ad77be-5436-4cbe-9260-3134b4ebea3b
		summarizeBy: sum
		sourceColumn: CLASSES

		annotation SummarizationSetBy = Automatic

	column ITEM_MEAN_SCORE
		dataType: double
		lineageTag: bc237023-60e3-4240-8e7d-d201c7d048dd
		summarizeBy: sum
		sourceColumn: ITEM_MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMPLETED_ITEMS
		dataType: int64
		formatString: 0
		lineageTag: 19bf6f77-6757-44ed-93f7-f7b35a67c98d
		summarizeBy: sum
		sourceColumn: COMPLETED_ITEMS

		annotation SummarizationSetBy = Automatic

	column TOTAL_ITEMS
		dataType: int64
		formatString: 0
		lineageTag: aedf6c35-c484-4680-8e01-16e1ac00f039
		summarizeBy: sum
		sourceColumn: TOTAL_ITEMS

		annotation SummarizationSetBy = Automatic

	column PAGE
		dataType: int64
		formatString: 0
		lineageTag: 249c6c93-0f52-4e34-86ee-6d13214902d2
		summarizeBy: sum
		sourceColumn: PAGE

		annotation SummarizationSetBy = Automatic

	column PAGE_TITLE
		dataType: string
		lineageTag: 7a7dcd5d-f6f3-4590-9db3-85493bddb0ed
		summarizeBy: none
		sourceColumn: PAGE_TITLE

		annotation SummarizationSetBy = Automatic

	column PAGE_MEAN_SCORE
		dataType: double
		lineageTag: 17a782b0-8e83-408c-9c9d-fde6abe676ae
		summarizeBy: sum
		sourceColumn: PAGE_MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUESTION
		dataType: int64
		formatString: 0
		lineageTag: 76dcafad-7e7e-4302-a9af-151d62f0077b
		summarizeBy: sum
		sourceColumn: QUESTION

		annotation SummarizationSetBy = Automatic

	column QUESTION_TYPE
		dataType: string
		lineageTag: 1a20f7a0-4009-4129-ab9f-9e06e4bee0f2
		summarizeBy: none
		sourceColumn: QUESTION_TYPE

		annotation SummarizationSetBy = Automatic

	column QUESTION_TEXT
		dataType: string
		lineageTag: 12247e62-db03-4d25-8320-1c734d7423f5
		summarizeBy: none
		sourceColumn: QUESTION_TEXT

		annotation SummarizationSetBy = Automatic

	column ANSWER
		dataType: string
		lineageTag: 5e7a673e-dbba-476d-9fd4-7cfa084a1356
		summarizeBy: none
		sourceColumn: ANSWER

		annotation SummarizationSetBy = Automatic

	column GENAI_ANSWER_ORIG_LANG
		dataType: string
		lineageTag: 81f9c1cd-262f-4193-8dbd-6b31f7acd029
		summarizeBy: none
		sourceColumn: GENAI_ANSWER_ORIG_LANG

		annotation SummarizationSetBy = Automatic

	column GENAI_ANSWER_TRANSLATION_ENG
		dataType: string
		lineageTag: 05640732-cae9-4e82-b885-6cb415bf902f
		summarizeBy: none
		sourceColumn: GENAI_ANSWER_TRANSLATION_ENG

		annotation SummarizationSetBy = Automatic

	column GENAI_IS_RUBBISH
		dataType: int64
		formatString: 0
		lineageTag: 4565361e-ae55-4cdb-a826-a31656eb3d71
		summarizeBy: sum
		sourceColumn: GENAI_IS_RUBBISH

		annotation SummarizationSetBy = Automatic

	column TOTAL_RESPONDENTS
		dataType: int64
		formatString: 0
		lineageTag: 24044249-2067-46dc-958a-362d9af2a603
		summarizeBy: sum
		sourceColumn: TOTAL_RESPONDENTS

		annotation SummarizationSetBy = Automatic

	column RESPONDENTS
		dataType: int64
		formatString: 0
		lineageTag: 2af9d7bc-c219-4711-ab6e-90bf46a73a91
		summarizeBy: sum
		sourceColumn: RESPONDENTS

		annotation SummarizationSetBy = Automatic

	column DISCOUNT_PERCENTAGE
		dataType: double
		lineageTag: 56ad21ef-5ec6-402b-b390-eee7ec30a33f
		summarizeBy: sum
		sourceColumn: DISCOUNT_PERCENTAGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMMENTS
		dataType: string
		lineageTag: fdb5c6f1-9bda-4158-89c6-eb4f6c40322e
		summarizeBy: none
		sourceColumn: COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_UNIQUE_ID
		dataType: string
		lineageTag: a17d1bfa-ce3c-41df-b556-e484c39c7940
		summarizeBy: none
		sourceColumn: GENAI_UNIQUE_ID

		annotation SummarizationSetBy = Automatic

	column BATCH_ID
		dataType: string
		lineageTag: 1405dbb4-bc66-4c83-ab3b-a76bfb82882f
		summarizeBy: none
		sourceColumn: BATCH_ID

		annotation SummarizationSetBy = Automatic

	column BATCH_MONTH
		dataType: int64
		formatString: 0
		lineageTag: c458db78-2879-4b28-a79c-d911459c42a8
		summarizeBy: sum
		sourceColumn: BATCH_MONTH

		annotation SummarizationSetBy = Automatic

	column BATCH_YEAR
		dataType: int64
		formatString: 0
		lineageTag: dca5a5e8-8972-420d-ad37-b47404d44463
		summarizeBy: sum
		sourceColumn: BATCH_YEAR

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ca690c5-4263-4f93-a947-144e78a06906
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CognitiveServices.ScoreSentiment'
		dataType: string
		lineageTag: 36c2e62c-9126-413a-a8dc-2c787ac163db
		summarizeBy: none
		sourceColumn: CognitiveServices.ScoreSentiment

		annotation SummarizationSetBy = Automatic

	column 'Detect language.Detected Language Name'
		dataType: string
		lineageTag: 7fd9060d-57aa-49de-acb0-438239773410
		summarizeBy: none
		sourceColumn: Detect language.Detected Language Name

		annotation SummarizationSetBy = Automatic

	column 'Detect language.Detected Language ISO Code'
		dataType: string
		lineageTag: d06a91be-405c-4412-8db4-b0ed87168394
		summarizeBy: none
		sourceColumn: Detect language.Detected Language ISO Code

		annotation SummarizationSetBy = Automatic

	partition 'Export Worksheet' = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"a0e5d209-46ca-4ad9-bbf1-85ade94b6614" = Workspaces{[workspaceId="a0e5d209-46ca-4ad9-bbf1-85ade94b6614"]}[Data],
				    #"4a9235e5-0709-4e13-ad52-5b578f35d18b" = #"a0e5d209-46ca-4ad9-bbf1-85ade94b6614"{[dataflowId="4a9235e5-0709-4e13-ad52-5b578f35d18b"]}[Data],
				    #"Export Worksheet_" = #"4a9235e5-0709-4e13-ad52-5b578f35d18b"{[entity="Export Worksheet",version=""]}[Data],
				    #"Applied Detect language" = AIFunctions.PostProcess(Table.AddColumn(#"Export Worksheet_", "Detect language", each #"Detect language"([GENAI_ANSWER_ORIG_LANG])), "Detect language", "CognitiveServices.DetectLanguagetext") meta [FunctionBrowser="TextAnalytics"]
				in
				    #"Applied Detect language"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

