table 'Export Worksheet'
	lineageTag: 8ba18c03-add2-47b5-8017-3e0b7a3eed0e

	column ITEM_ID
		dataType: string
		lineageTag: d370134a-cf3b-441b-a3ba-7598d0166d58
		summarizeBy: none
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TYPE_ID
		dataType: string
		lineageTag: 940d8e6f-6e45-44ca-9314-d9caf98ea23c
		summarizeBy: none
		sourceColumn: ITEM_TYPE_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_GROUP
		dataType: string
		lineageTag: 0d1c02ae-1606-4396-bf61-7121c75c91e9
		summarizeBy: none
		sourceColumn: ITEM_GROUP

		annotation SummarizationSetBy = Automatic

	column PREFIX_ID
		dataType: string
		lineageTag: fbc4726d-2aa0-42fb-9547-4f1791aec174
		summarizeBy: none
		sourceColumn: PREFIX_ID

		annotation SummarizationSetBy = Automatic

	column PREFIX_TITLE
		dataType: string
		lineageTag: 3b92f974-5c6e-4d3d-88d4-56669dd37a38
		summarizeBy: none
		sourceColumn: PREFIX_TITLE

		annotation SummarizationSetBy = Automatic

	column ITEM_TITLE
		dataType: string
		lineageTag: c6932e12-a71d-443d-8326-c57942bc0103
		summarizeBy: none
		sourceColumn: ITEM_TITLE

		annotation SummarizationSetBy = Automatic

	column SURVEY_ID
		dataType: string
		lineageTag: b69f7474-1b4a-405c-a859-dee8c1baa339
		summarizeBy: none
		sourceColumn: SURVEY_ID

		annotation SummarizationSetBy = Automatic

	column SURVEY_NAME
		dataType: string
		lineageTag: 8ead8d6c-9357-4a74-adde-fb942fee61cc
		summarizeBy: none
		sourceColumn: SURVEY_NAME

		annotation SummarizationSetBy = Automatic

	column ACTIVE_SURVEY
		dataType: string
		lineageTag: 69f23e37-f411-4ae7-a747-23be544af5fa
		summarizeBy: none
		sourceColumn: ACTIVE_SURVEY

		annotation SummarizationSetBy = Automatic

	column MEAN_SCORE
		dataType: double
		lineageTag: 0da8b420-44db-4dea-ad10-b7dbd501aecd
		summarizeBy: sum
		sourceColumn: MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMPLETED_SURVEYS
		dataType: int64
		formatString: 0
		lineageTag: 36a92e76-5a12-4e3f-88c9-a7228ebf387e
		summarizeBy: sum
		sourceColumn: COMPLETED_SURVEYS

		annotation SummarizationSetBy = Automatic

	column TOTAL_SURVEYS
		dataType: int64
		formatString: 0
		lineageTag: 77752558-23ad-4919-9b01-2eafe7c4e142
		summarizeBy: sum
		sourceColumn: TOTAL_SURVEYS

		annotation SummarizationSetBy = Automatic

	column FROM_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: b33512f6-213c-428d-8448-c44fa4a9af16
		summarizeBy: none
		sourceColumn: FROM_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TO_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8cb23df6-003b-4ab5-9586-c4cfae2cda93
		summarizeBy: none
		sourceColumn: TO_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ITEM_REVISION_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1142f1b1-c888-452c-b3aa-baab439019eb
		summarizeBy: none
		sourceColumn: ITEM_REVISION_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLASSES
		dataType: int64
		formatString: 0
		lineageTag: b5f1c446-74fc-4d4d-b37b-1f128c55031a
		summarizeBy: sum
		sourceColumn: CLASSES

		annotation SummarizationSetBy = Automatic

	column ITEM_MEAN_SCORE
		dataType: double
		lineageTag: 91e33a3d-8473-4835-88b8-c4e94e856e90
		summarizeBy: sum
		sourceColumn: ITEM_MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMPLETED_ITEMS
		dataType: int64
		formatString: 0
		lineageTag: 56e49297-5d42-49d3-9ec2-fde722a43804
		summarizeBy: sum
		sourceColumn: COMPLETED_ITEMS

		annotation SummarizationSetBy = Automatic

	column TOTAL_ITEMS
		dataType: int64
		formatString: 0
		lineageTag: 55f263d4-7a4b-476b-bdf7-521768fe9407
		summarizeBy: sum
		sourceColumn: TOTAL_ITEMS

		annotation SummarizationSetBy = Automatic

	column PAGE
		dataType: int64
		formatString: 0
		lineageTag: c74a4188-0c55-4354-968e-f1ed10de3e86
		summarizeBy: sum
		sourceColumn: PAGE

		annotation SummarizationSetBy = Automatic

	column PAGE_TITLE
		dataType: string
		lineageTag: ae1ac37c-3677-4721-bc84-4f07a3b6b591
		summarizeBy: none
		sourceColumn: PAGE_TITLE

		annotation SummarizationSetBy = Automatic

	column PAGE_MEAN_SCORE
		dataType: double
		lineageTag: 7deeed1f-e59d-4d27-b89d-efcd03d9018f
		summarizeBy: sum
		sourceColumn: PAGE_MEAN_SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUESTION
		dataType: int64
		formatString: 0
		lineageTag: ea6a75b5-ac60-48f9-ac6e-e900d9f0a02a
		summarizeBy: sum
		sourceColumn: QUESTION

		annotation SummarizationSetBy = Automatic

	column QUESTION_TYPE
		dataType: string
		lineageTag: 05e2e424-45f3-40e2-b2a7-7d2ce3f2e294
		summarizeBy: none
		sourceColumn: QUESTION_TYPE

		annotation SummarizationSetBy = Automatic

	column QUESTION_TEXT
		dataType: string
		lineageTag: 28b3331c-1008-4818-ad9d-b737b1b210c8
		summarizeBy: none
		sourceColumn: QUESTION_TEXT

		annotation SummarizationSetBy = Automatic

	column ANSWER
		dataType: string
		lineageTag: d351c07b-3f5c-424a-b0a2-f8c6f3188539
		summarizeBy: none
		sourceColumn: ANSWER

		annotation SummarizationSetBy = Automatic

	column GENAI_ANSWER_ORIG_LANG
		dataType: string
		lineageTag: 932d7aad-f297-4a79-aa5a-355b6e5c3daf
		summarizeBy: none
		sourceColumn: GENAI_ANSWER_ORIG_LANG

		annotation SummarizationSetBy = Automatic

	column GENAI_ANSWER_TRANSLATION_ENG
		dataType: string
		lineageTag: 06518e8c-9b6f-4eeb-ab18-5085f9d04808
		summarizeBy: none
		sourceColumn: GENAI_ANSWER_TRANSLATION_ENG

		annotation SummarizationSetBy = Automatic

	column GENAI_IS_RUBBISH
		dataType: int64
		formatString: 0
		lineageTag: 6d7147f9-80e2-466b-aacb-79375281e5ce
		summarizeBy: sum
		sourceColumn: GENAI_IS_RUBBISH

		annotation SummarizationSetBy = Automatic

	column TOTAL_RESPONDENTS
		dataType: int64
		formatString: 0
		lineageTag: 42d3c83e-da7b-46db-9daf-bcd6d55f57bc
		summarizeBy: sum
		sourceColumn: TOTAL_RESPONDENTS

		annotation SummarizationSetBy = Automatic

	column RESPONDENTS
		dataType: int64
		formatString: 0
		lineageTag: 229ad749-001a-4573-a995-b6b23fb1e033
		summarizeBy: sum
		sourceColumn: RESPONDENTS

		annotation SummarizationSetBy = Automatic

	column DISCOUNT_PERCENTAGE
		dataType: double
		lineageTag: 27c8c1f0-31a8-455b-9e9a-b11bf23e6cfd
		summarizeBy: sum
		sourceColumn: DISCOUNT_PERCENTAGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMMENTS
		dataType: string
		lineageTag: 14e33ae9-89c1-4bd4-9a4a-4d7ebbf01418
		summarizeBy: none
		sourceColumn: COMMENTS

		annotation SummarizationSetBy = Automatic

	column GENAI_UNIQUE_ID
		dataType: string
		lineageTag: 8bbeec0e-45ac-4715-8079-96916a7ef400
		summarizeBy: none
		sourceColumn: GENAI_UNIQUE_ID

		annotation SummarizationSetBy = Automatic

	column BATCH_ID
		dataType: string
		lineageTag: 8e2de84a-bdae-446a-9366-e33d5e03a916
		summarizeBy: none
		sourceColumn: BATCH_ID

		annotation SummarizationSetBy = Automatic

	column BATCH_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 2ab61549-c9e3-48d4-8103-966e6984580a
		summarizeBy: sum
		sourceColumn: BATCH_MONTH

		annotation SummarizationSetBy = Automatic

	column BATCH_YEAR
		dataType: int64
		formatString: 0
		lineageTag: d29b472b-4545-4172-bd62-384de5cb3aa5
		summarizeBy: sum
		sourceColumn: BATCH_YEAR

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 745e4915-93bc-4fb4-82a8-a9a517eeb39e
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Export Worksheet' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bosch-my.sharepoint.com/personal/dmo5hc_bosch_com/Documents/XAB3_TEAM/OTHERS/TRAINING_SURVEY_TRANSLATED.xlsx"), null, true),
				    #"Export Worksheet_Sheet" = Source{[Item="Export Worksheet",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Export Worksheet_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ITEM_ID", type text}, {"ITEM_TYPE_ID", type text}, {"ITEM_GROUP", type text}, {"PREFIX_ID", type text}, {"PREFIX_TITLE", type text}, {"ITEM_TITLE", type text}, {"SURVEY_ID", type text}, {"SURVEY_NAME", type text}, {"ACTIVE_SURVEY", type text}, {"MEAN_SCORE", type number}, {"COMPLETED_SURVEYS", Int64.Type}, {"TOTAL_SURVEYS", Int64.Type}, {"FROM_DATE", type date}, {"TO_DATE", type date}, {"ITEM_REVISION_DATE", type date}, {"CLASSES", Int64.Type}, {"ITEM_MEAN_SCORE", type number}, {"COMPLETED_ITEMS", Int64.Type}, {"TOTAL_ITEMS", Int64.Type}, {"PAGE", Int64.Type}, {"PAGE_TITLE", type text}, {"PAGE_MEAN_SCORE", type number}, {"QUESTION", Int64.Type}, {"QUESTION_TYPE", type text}, {"QUESTION_TEXT", type text}, {"ANSWER", type text}, {"GENAI_ANSWER_ORIG_LANG", type text}, {"GENAI_ANSWER_TRANSLATION_ENG", type text}, {"GENAI_IS_RUBBISH", Int64.Type}, {"TOTAL_RESPONDENTS", Int64.Type}, {"RESPONDENTS", Int64.Type}, {"DISCOUNT_PERCENTAGE", type number}, {"COMMENTS", type any}, {"GENAI_UNIQUE_ID", type any}, {"BATCH_ID", type text}, {"BATCH_MONTH", Int64.Type}, {"BATCH_YEAR", Int64.Type}, {"EXPORT_DATE", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

