table E9_DIM_RISK_CATEGORIES
	lineageTag: 1422ff76-9331-4b1c-87b8-79a9555d44c3

	column L0_ID
		dataType: double
		lineageTag: deb80005-217f-4dcf-98a4-7fc9cf58c303
		summarizeBy: none
		sourceColumn: L0_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L0_VALUE
		dataType: string
		lineageTag: be3d6ace-7981-49cf-a5f7-93370eff591b
		summarizeBy: none
		sourceColumn: L0_VALUE

		annotation SummarizationSetBy = Automatic

	column L1_ID
		dataType: int64
		formatString: 0
		lineageTag: 19096dab-697b-4cbb-bad1-c87aebf31ba6
		summarizeBy: none
		sourceColumn: L1_ID

		annotation SummarizationSetBy = Automatic

	column L1_VALUE
		dataType: string
		lineageTag: 6ef468c6-a936-4fd8-b2de-2d2b5c065c27
		summarizeBy: none
		sourceColumn: L1_VALUE

		annotation SummarizationSetBy = Automatic

	column L1_COLOR
		dataType: string
		lineageTag: eb6c38c1-52bb-4c0f-9f53-06b7f3ddc6f3
		summarizeBy: none
		sourceColumn: L1_COLOR

		annotation SummarizationSetBy = Automatic

	column L2_ID
		dataType: double
		lineageTag: b316b9ac-7b5c-43d1-bdc8-6b3cda775a10
		summarizeBy: none
		sourceColumn: L2_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L2_VALUE
		dataType: string
		lineageTag: 3a932466-f85f-4c46-bebc-99e6e2eb6ce9
		summarizeBy: none
		sourceColumn: L2_VALUE

		annotation SummarizationSetBy = Automatic

	column VALID_YEAR
		dataType: int64
		formatString: 0
		lineageTag: c1c771c0-b7c0-41d7-8957-b2ae021c3774
		summarizeBy: none
		sourceColumn: VALID_YEAR

		annotation SummarizationSetBy = Automatic

	column L2_NUMBER
		dataType: string
		lineageTag: 60c832b6-cf1e-4df3-ae0b-94f6a4b5e6df
		summarizeBy: none
		sourceColumn: L2_NUMBER

		annotation SummarizationSetBy = Automatic

	column L1
		dataType: string
		lineageTag: 600d1dca-2e8d-4a88-a548-ce2afde86b75
		summarizeBy: none
		sourceColumn: L1
		sortByColumn: L1_VALUE

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition E9_DIM_RISK_CATEGORIES = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="
				    SELECT 
				        DECODE(L2_VALUE, 'Other', 999 , L0_ID) AS ""L0_ID"", 
				        DECODE(L2_VALUE, 'Other', 'Other' , L0_VALUE) AS ""L0_VALUE"",
				        DECODE(L2_VALUE, 'Other', 999 , L1_ID) AS ""L1_ID"", 
				        DECODE(L2_VALUE, 'Other', 'Other' , L1_VALUE) AS ""L1_VALUE"", 
				        DECODE(L2_VALUE, 'Other', '#808080' , L1_COLOR) AS ""L1_COLOR"",
				        L2_ID, 
				        L2_VALUE, 
				        VALID_YEAR
				    FROM MARD_PCMS.X_IFR_PCMS_LEVEL2_RISK_CATEGORIES"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"L1_ID", Int64.Type}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "L2_NUMBER", each Text.BeforeDelimiter([L2_VALUE], " "), type text),
				    #"Trimmed Text" = Table.TransformColumns(#"Inserted Text Before Delimiter",{{"L2_NUMBER", Text.Trim, type text}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Trimmed Text", "L1", each Text.AfterDelimiter([L1_VALUE], " "), type text),
				    #"Trimmed Text1" = Table.TransformColumns(#"Inserted Text After Delimiter",{{"L1", Text.Trim, type text}})
				in
				    #"Trimmed Text1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

