table E9_MEASURES
	lineageTag: afdf23fe-134d-4f34-a930-531fc4d39278

	measure TEXT_OVERVIEW = "Overview"
		lineageTag: 0a720482-e79f-4103-ac58-4ae7eed0359a

	measure TEXT_PCM_CHECK_RATING = "PCM Check Rating"
		lineageTag: debbb25c-061d-45a9-adb2-3a3c36ac8662

	measure TEXT_RISK_CATEGORIES = "Risk Categories"
		lineageTag: a6064bca-aa76-46f0-9bbc-169a97a1836c

	measure TEXT_MEASURE = "Measures"
		lineageTag: bf088add-c3b1-475e-99e1-51fa07781963

	measure TEXT_OE&PROJECT = "OE & Legal Entity"
		lineageTag: 784bb571-6035-4d18-ba19-cee37f36374a

	measure COUNT_PCM_CHECK = DISTINCTCOUNT(E9_PCM_CHECK[RID])
		formatString: 0
		lineageTag: 17ec5bde-6e75-4dd4-b45c-94f15ce0cd32

	measure LABEL_PREFILL = "Pre-fill (" & [COUNT_STS_PREFILL] + 0 & ")"
		lineageTag: a7c64aec-65cd-4608-a72e-c59040045dff

	measure LABEL_INPROGESS = "In Progress (" & [COUNT_STS_INPROGRESS]+ 0 & ")"
		lineageTag: 7f213631-910c-4ed7-b353-f65ac9df253a

	measure LABEL_INREVIEW = "In Review (" & [COUNT_STS_INREVIEW] + 0 & ")"
		lineageTag: 740f9e10-2fe7-45ef-888c-b49a8c8f0a0c

	measure LABEL_INAPPROVAL = "In Approval (" & [COUNT_STS_INAPPROVAL] + 0 & ")"
		lineageTag: c88bc9f4-f227-46a4-875d-f019d26e1996

	measure LABEL_APPROVED = "Approved (" & [COUNT_STS_APPROVED] + 0 & ")"
		lineageTag: 6bbaed1c-7063-435b-bbb0-bd43f15e6314

	measure COUNT_STS_PREFILL = ```
			CALCULATE([COUNT_PCM_CHECK], E9_PCM_CHECK[PCM_CHECK_STATUS] = "Pre-fill") 
			```
		formatString: 0
		lineageTag: c365693d-a12d-493a-a927-11b42c06026b

	measure COUNT_STS_INPROGRESS = CALCULATE([COUNT_PCM_CHECK], E9_PCM_CHECK[PCM_CHECK_STATUS] = "In Progress")
		formatString: 0
		lineageTag: 01dd6844-d94b-44d2-a5e1-9d06419d4a7f

	measure COUNT_STS_INREVIEW = CALCULATE([COUNT_PCM_CHECK], E9_PCM_CHECK[PCM_CHECK_STATUS] = "In Review")
		formatString: 0
		lineageTag: b186e5f4-738f-453b-8070-9739f1276754

	measure COUNT_STS_INAPPROVAL = CALCULATE([COUNT_PCM_CHECK], E9_PCM_CHECK[PCM_CHECK_STATUS] = "In Approval")
		formatString: 0
		lineageTag: da178aaa-845e-453c-b9f9-a91b86cf0d97

	measure COUNT_STS_APPROVED = CALCULATE([COUNT_PCM_CHECK], E9_PCM_CHECK[PCM_CHECK_STATUS] = "Approved")
		formatString: 0
		lineageTag: 1c84bba1-e954-422c-ae9e-bd2b0e9fc8f7

	measure SELECTED_OE =
			IF (
			    ISFILTERED ( E9_DIM_OE[OE_ABBR]),
			    CONCATENATEX (
			        VALUES ( E9_DIM_OE[OE_ABBR] ),
			        E9_DIM_OE[OE_ABBR],
			        ", ",
			        E9_DIM_OE[OE_ABBR]
			    ),
			    "All"
			)
		lineageTag: 0ab2ab65-3bc5-4e6f-8166-d39e558b5161

	measure SELECTED_BU = ```
			
			VAR BU =
			    FILTER(
			        VALUES ( E9_DIM_BU[BU]),
			        CALCULATE ( [COUNT_PCM_CHECK] ) > 0 
			    )
			RETURN 
			IF (
			    ISFILTERED ( E9_DIM_BU[BU]),
			    CONCATENATEX ( BU, E9_DIM_BU[BU], ", " )
			    ,
			    "All"
			)
			```
		lineageTag: 3a632a86-5f80-4f08-bb7e-f00a4a926c62

	measure SELECTED_REGION =
			IF (
			    ISFILTERED ( E9_DIM_REGION[CONTINENT] ),
			    CONCATENATEX (
			        VALUES ( E9_DIM_REGION[CONTINENT] ),
			        E9_DIM_REGION[CONTINENT],
			        ", ",
			        E9_DIM_REGION[CONTINENT]
			    ),
			    "All"
			)
		lineageTag: 71511946-460b-4302-bedb-f43f44f6119a

	measure SELECTED_COUNTRY =
			IF (
			    ISFILTERED ( E9_PCM_CHECK[COUNTRY] ),
			    CONCATENATEX (
			        VALUES ( E9_PCM_CHECK[COUNTRY] ),
			        E9_PCM_CHECK[COUNTRY],
			        ", ",
			        E9_PCM_CHECK[COUNTRY]
			    ),
			    "All"
			)
		lineageTag: 4f8c97de-7f19-40b5-9a46-9676fb5105ff

	measure COUNT_PCM_CHECK_PER_REGION =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    SUMMARIZECOLUMNS ( E9_DIM_REGION[CONTINENT] ),
			    ALLSELECTED ( E9_DIM_REGION[COUNTRY_DISPLAY_TEXT] )
			) + 0
		formatString: 0
		lineageTag: 636450be-7f8c-470c-a733-ad592712826d

	measure COLOR_PCM_CHECK_PER_REGION = IF ( [COUNT_PCM_CHECK_PER_REGION] > 0, "#007BC0", "#D64554" )
		lineageTag: 175a9a72-a30d-4f2c-969f-5de75cc5932e

	measure COUNT_PCM_CHECK_APPROVED_OVER_TIME_FUTURE =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR] )
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey]), 0 )
			            )
			            && AND (
			                E9_PCM_CHECK[END_DATE_PLUS35]
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey]), 0 ),
			                TRUE ()
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 3c3811aa-c06b-4cd9-a754-e7ca14acf50d

	measure COUNT_PCM_CHECK_APRROVED_OVER_TIME =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year])
			            && AND (
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[RESOLUTION_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[RESOLUTION_DATE]
			                )
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( TODAY (), 1 )
			                    > EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 7e486782-2e61-4a0d-9425-a72e38162139

	measure COUNT_PCM_CHECK_INAPPROVAL_OVER_TIME =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_APPROVAL_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_APPROVAL_DATE]
			                )
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[RESOLUTION_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[RESOLUTION_DATE]
			                )
			                    > EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 315db58e-e2a7-488b-81d1-260046d81e16

	measure COUNT_PCM_CHECK_INAPPROVAL_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && ISBLANK ( E9_PCM_CHECK[RESOLUTION_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E9_PCM_CHECK[END_DATE_PLUS35] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                E9_PCM_CHECK[END_DATE_PLUS7]
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ) < E9_PCM_CHECK[END_DATE_PLUS35]
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 0c72674e-5ba1-4a62-826c-3270f14d9f2e

	measure COUNT_PCM_CHECK_INPROGRESS_OVER_TIME =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR] )
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_PROGRESS_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_PROGRESS_DATE]
			                )
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_REVIEW_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_REVIEW_DATE]
			                )
			                    > EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 8704597f-3e21-4d3e-b0e3-0076a78147fc

	measure COUNT_PCM_CHECK_INPROGRESS_OVER_TIME_FUTURE =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED (E9_PCM_CHECK),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && ISBLANK ( E9_PCM_CHECK[IN_REVIEW_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E9_PCM_CHECK[END_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                E9_PCM_CHECK[START_DATE]
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ) < E9_PCM_CHECK[END_DATE]
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: e383377a-4e6b-458d-b825-018cdda513d7

	measure COUNT_PCM_CHECK_INREVIEW_OVER_TIME =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR] )
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_REVIEW_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_REVIEW_DATE]
			                )
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_APPROVAL_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_APPROVAL_DATE]
			                )
			                    > EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: e03ed0e4-2a99-4a8f-9df2-88c30a65b97c

	measure COUNT_PCM_CHECK_INREVIEW_OVER_TIME_FUTURE =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && ISBLANK ( E9_PCM_CHECK[IN_APPROVAL_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 ) < E9_PCM_CHECK[END_DATE_PLUS7]
			                    && (
			                        EOMONTH ( TODAY (), 0 )
			                            < EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			                    )
			                    && AND (
			                        E9_PCM_CHECK[END_DATE]
			                            <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                        EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ) < E9_PCM_CHECK[END_DATE_PLUS7]
			                    )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 985f8dd8-cf0a-4eba-92ab-149ff4ffb27b

	measure COUNT_PCM_CHECK_PREFILL_OVER_TIME =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && AND (
			                E9_PCM_CHECK[CREATED_DATE]
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E9_PCM_CHECK[IN_PROGRESS_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E9_PCM_CHECK[IN_PROGRESS_DATE]
			                )
			                    > EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 135d4d5c-d1ba-4f98-8c31-fe029e95715a

	measure COUNT_PCM_CHECK_PREFILL_OVER_TIME_FUTURE =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    FILTER (
			        ALLSELECTED (E9_PCM_CHECK),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			                - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			            && ISBLANK ( E9_PCM_CHECK[IN_PROGRESS_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E9_PCM_CHECK[START_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                EOMONTH ( TODAY (), 1 )
			                    <= EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E9_DIM_DATE[FullDateAlternateKey] ), 0 ) < E9_PCM_CHECK[START_DATE]
			            )
			    )
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 5d173d18-db1d-4e55-b737-ac31fd27e74d

	measure MAX_DATE_PCM_CHECK =
			MAXX (
			    {
			        MAX ( E9_PCM_CHECK[CREATED_DATE] ),
			        MAX ( E9_PCM_CHECK[IN_PROGRESS_DATE] ),
			        MAX ( E9_PCM_CHECK[IN_REVIEW_DATE] ),
			        MAX ( E9_PCM_CHECK[IN_APPROVAL_DATE] ),
			        MAX ( E9_PCM_CHECK[RESOLUTION_DATE] )
			    },
			    [Value]
			)
		formatString: General Date
		displayFolder: OVER_TIME
		lineageTag: 00d6821b-f2e7-490e-a829-0db7255912bc

	measure MIN_DATE_PCM_CHECK =
			
			MINX (
			    {
			        MIN ( E9_PCM_CHECK[CREATED_DATE] ),
			        MIN ( E9_PCM_CHECK[IN_PROGRESS_DATE] ),
			        MIN ( E9_PCM_CHECK[IN_REVIEW_DATE] ),
			        MIN ( E9_PCM_CHECK[IN_APPROVAL_DATE] ),
			        MIN ( E9_PCM_CHECK[RESOLUTION_DATE] )
			    },
			    [Value]
			)
		formatString: General Date
		displayFolder: OVER_TIME
		lineageTag: f1d9ed11-a2f9-49f4-8d19-8d80e6831b90

	measure PRESET_FILTER_PCM_CHECK_YEAR =
			
			VAR FILTER_PCM_YEAR_TABLE =
			    FILTER (
			        ALLSELECTED ( E9_PCM_CHECK ),
			        E9_PCM_CHECK[PCM_CHECK_YEAR]
			            = SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) - MAX ( 'E9_PARA_PREVIOUS_YEAR'[Para_Previous_Year] )
			    )
			VAR START_POINT =
			    DATE ( YEAR (
			        CALCULATE (
			            [MIN_DATE_PCM_CHECK],
			            ALLSELECTED ( E9_DIM_DATE ),
			            FILTER_PCM_YEAR_TABLE
			        )
			    ), 01, 01)
			VAR MAX_PCM_CHECK_YEAR =
			    YEAR (
			        CALCULATE (
			            [MAX_DATE_PCM_CHECK],
			            ALLSELECTED ( E9_DIM_DATE ),
			            FILTER_PCM_YEAR_TABLE
			        )
			    )
			VAR PCM_CHECK_YEAR =
			    CALCULATE (
			        MAX ( E9_PCM_CHECK[PCM_CHECK_YEAR] ),
			        ALLSELECTED ( E9_DIM_DATE ),
			        FILTER_PCM_YEAR_TABLE
			    )
			VAR END_POINT =
			    IF (
			        MAX_PCM_CHECK_YEAR > YEAR ( START_POINT ),
			        CALCULATE (
			            [MAX_DATE_PCM_CHECK],
			            ALLSELECTED ( E9_DIM_DATE ),
			            FILTER_PCM_YEAR_TABLE
			        ),
			            IF(
			                YEAR(TODAY()) <= YEAR ( START_POINT ) && MONTH(TODAY())>= 10,
			                EOMONTH(DATE ( YEAR ( START_POINT ), 12, 31 ),3),
			                DATE ( YEAR ( START_POINT ), 12, 31 )
			            )
			    )
			RETURN SWITCH (
			        TRUE (),
			        AND (
			            START_POINT <= MAX ( E9_DIM_DATE[FullDateAlternateKey] ),
			            MIN ( E9_DIM_DATE[FullDateAlternateKey] ) <= END_POINT
			        ), 1,
			        0
			    )
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: f44fde64-6075-4875-b019-b4ab83c12bbe

	measure REFERENCE_OVERLAY_FUTURE_TIME =
			
			IF (
			    EOMONTH ( TODAY (), 0 ) < MAX ( E9_DIM_DATE[FullDateAlternateKey] ),
			    9999,
			    BLANK ()
			)
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: 67149aa2-567f-43ca-b6ea-d24249dc5e44

	measure MAX_COUNT_PCM_CHECK = MAXX ( ALLSELECTED ( E9_PCM_CHECK[PCM_CHECK_YEAR] ), [COUNT_PCM_CHECK] ) + 1
		formatString: 0
		displayFolder: OVER_TIME
		lineageTag: f37fb413-8013-4265-9439-7d9de113db7a

	measure PCM_OVERTIME_YEARVIEW_TITLE =
			"PCM Check: "
			    & (
			        SELECTEDVALUE ( E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR])
			            - MAX ( E9_PARA_PREVIOUS_YEAR[Para_Previous_Year] )
			    )
		displayFolder: OVER_TIME
		lineageTag: a6e2d137-3c0c-462f-b168-0103fc5c99ca

	measure SELECTED_LEGAL_ENTITY = ```
			
			VAR LE =
			    FILTER(
			        VALUES ( E9_DIM_LE[LE_NAME]),
			        CALCULATE ( [COUNT_PCM_CHECK] ) > 0 
			    )
			RETURN 
			IF (
			    ISFILTERED ( E9_DIM_LE[LE_NAME]),
			    CONCATENATEX ( VALUES ( E9_DIM_LE[LE_NAME]), E9_DIM_LE[LE_NAME], ", " )
			    ,
			    "All"
			)
			```
		lineageTag: ca0e1b5a-af60-4f1c-ae45-cb910231a118

	measure REGION_COVERAGE = ```
			
			    DIVIDE (
			        CALCULATE (
			            COUNTROWS(
			                FILTER ( VALUES ( E9_DIM_REGION[CONTINENT] ), CALCULATE ( [COUNT_PCM_CHECK] ) > 0 && E9_DIM_REGION[CONTINENT]<>BLANK() )
			            )
			    ),
			        CALCULATE (
			            COUNTROWS(VALUES(E9_DIM_REGION[CONTINENT]) ),
			            ALLSELECTED ( E9_DIM_REGION ),
			            E9_DIM_REGION[CONTINENT]<>BLANK()
			        )
			    ) + 0
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9d2e3e47-702d-4d79-a3a2-7e51fa307584

	measure REGION_NOT_COVERED =
			
			VAR ZeroCheckRegions =
			    FILTER(
			        VALUES ( E9_DIM_REGION[CONTINENT] ),
			        CALCULATE ( [COUNT_PCM_CHECK] ) = 0 && E9_DIM_REGION[CONTINENT]<>BLANK()
			    )
			VAR RegionList =
			    CONCATENATEX ( ZeroCheckRegions, E9_DIM_REGION[CONTINENT], ", " )
			RETURN
			    IF ( ISBLANK ( RegionList ) || LEN ( RegionList ) = 0, "None", RegionList )
		lineageTag: fc1f5cf6-9852-4b16-b703-e8eb19bfe267

	measure COUNT_RATING = CALCULATE(DISTINCTCOUNT(E9_PCM_CHECK[RID_QUESTIONID]), NOT E9_PCM_CHECK[RATING] IN {"NA", BLANK()})
		formatString: 0
		displayFolder: RATING
		lineageTag: 8e61e944-14d9-450d-bb33-528bfcdfd1e4

	measure COUNT_F = CALCULATE([COUNT_RATING], FILTER(E9_PCM_CHECK, E9_PCM_CHECK[RATING] = "F"))
		formatString: 0
		displayFolder: RATING
		lineageTag: 27b77b8b-eb88-43c4-b1b7-be85817a7b51

	measure COUNT_L = CALCULATE([COUNT_RATING], FILTER(E9_PCM_CHECK, E9_PCM_CHECK[RATING] = "L"))
		formatString: 0
		displayFolder: RATING
		lineageTag: cc96037e-3706-4960-ab5f-46e0106a33f3

	measure COUNT_P = CALCULATE([COUNT_RATING], FILTER(E9_PCM_CHECK, E9_PCM_CHECK[RATING] = "P"))
		formatString: 0
		displayFolder: RATING
		lineageTag: 242fb977-0e81-4488-88ce-8d4955fd010f

	measure COUNT_N = CALCULATE([COUNT_RATING], FILTER(E9_PCM_CHECK, E9_PCM_CHECK[RATING] = "N"))
		formatString: 0
		displayFolder: RATING
		lineageTag: a897d260-565e-4260-a9a9-108eecf15ae5

	measure COUNT_ALL_RATING = ```
			IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]) || ISFILTERED(E9_PCM_CHECK[OE_CODE]),
			    CALCULATE([COUNT_RATING],
			    ALL (E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[BU_CODE], 
			    E9_PCM_CHECK[NUMBER_OF_CHECKS]), ALL(E9_PCM_CHECK_UNPIVOT_BU), ALL(E9_DIM_OE[OE_ABBR])
			    ),
			    CALCULATE([COUNT_RATING],
			    ALL (E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[BU_CODE]
			    , E9_PCM_CHECK[NUMBER_OF_CHECKS], E9_PCM_CHECK[NUMBER_OF_QUESTION]
			    , E9_PCM_CHECK[TOPIC_ID], E9_PCM_CHECK[TOPIC_NAME], E9_PCM_CHECK[QUESTION]
			    ), ALL(E9_PCM_CHECK_UNPIVOT_BU), ALL(E9_DIM_OE[OE_ABBR])
			    ))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: a26396a1-1be4-46c3-a7ac-508ea36d94d5

	measure %_F = [COUNT_F]/[COUNT_RATING]
		displayFolder: RATING
		lineageTag: 32bef906-86e6-4f85-976d-41e278f64d6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_L = [COUNT_L]/[COUNT_RATING]
		displayFolder: RATING
		lineageTag: 0e9a09d3-b98c-4b08-9a83-dcab911ad6ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_N = [COUNT_N]/[COUNT_RATING]
		displayFolder: RATING
		lineageTag: d5bb8c28-b180-4830-a803-430c91a4b6a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_P = [COUNT_P]/[COUNT_RATING]
		displayFolder: RATING
		lineageTag: 9b4dcc17-b19d-48dc-981d-6be23fb65431

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_F =
			
			VAR countrating =
			    IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			    CALCULATE ([COUNT_F],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE]
			    , E9_PCM_CHECK[NUMBER_OF_CHECKS]), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR])),
			    CALCULATE ([COUNT_F],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[BU_CODE], E9_PCM_CHECK[OE_CODE]
			    , E9_PCM_CHECK[TOPIC_ID], E9_PCM_CHECK[TOPIC_NAME]
			    , E9_PCM_CHECK[NUMBER_OF_CHECKS], E9_PCM_CHECK[NUMBER_OF_QUESTION], E9_PCM_CHECK[QUESTION], E9_PCM_CHECK[QUESTION_ID]), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR]))
			    )
			VAR percentage = countrating / [COUNT_ALL_RATING]
			VAR delta = [%_F] - percentage
			RETURN
			    delta
		displayFolder: RATING
		lineageTag: 01f19a5c-418b-4d00-a50b-22b43f8b533d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_L =
			
			VAR countrating =
			    IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			    CALCULATE ([COUNT_L],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE]), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR])),
			    CALCULATE ([COUNT_L],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[BU_CODE], E9_PCM_CHECK[TOPIC_ID], E9_PCM_CHECK[TOPIC_NAME], E9_PCM_CHECK[OE_CODE] ), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR]))
			    )
			VAR percentage = countrating / [COUNT_ALL_RATING]
			VAR delta = [%_L] - percentage
			RETURN
			    delta
		displayFolder: RATING
		lineageTag: 1ee16381-3791-4a21-b19f-80a6f1cfb369

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_P =
			
			VAR countrating =
			    IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			    CALCULATE ([COUNT_P],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE]), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR])),
			    CALCULATE ([COUNT_P],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[TOPIC_ID], E9_PCM_CHECK[TOPIC_NAME], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE] ), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR]))
			    )
			VAR percentage = countrating / [COUNT_ALL_RATING]
			VAR delta = [%_P] - percentage
			RETURN
			    delta
		displayFolder: RATING
		lineageTag: b180d030-9212-4412-94c1-f9535463c2f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_N = ```
			
			VAR countrating =
			    IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]) || ISFILTERED(E9_PCM_CHECK[OE_CODE]),
			    CALCULATE ([COUNT_N],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[NUMBER_OF_CHECKS], E9_PCM_CHECK[BU_CODE])
			    , ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR])),
			    CALCULATE ([COUNT_N],
			    ALL ( E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[TOPIC_ID], E9_PCM_CHECK[TOPIC_NAME], E9_PCM_CHECK[BU_CODE]
			    , E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[NUMBER_OF_CHECKS], E9_PCM_CHECK[NUMBER_OF_QUESTION]), ALL(E9_DIM_BU[BU]), ALL(E9_DIM_OE[OE_ABBR]))
			    )
			VAR percentage = 
			                countrating / [COUNT_ALL_RATING]
			VAR delta = [%_N] - percentage
			RETURN
			    delta
			```
		displayFolder: RATING
		lineageTag: 147ad058-b54e-40c9-b8bb-96438d9a1a22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RATING_NUMBER =
			
			VAR DeltaF = [DELTA_F]
			VAR DeltaN = [DELTA_N]
			VAR DeltaP = [DELTA_P]
			VAR DeltaL = [DELTA_L]
			
			VAR WeightedSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP * 2 )
			        + IF ( DeltaL < 0, 0, DeltaL * 3 )
			        + IF ( DeltaF < 0, 0, DeltaF * 4 )
			VAR TotalSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP )
			        + IF ( DeltaL < 0, 0, DeltaL )
			        + IF ( DeltaF < 0, 0, DeltaF )
			VAR result =
			    IF ([COUNT_RATING]=0,
			        BLANK(),
			        ROUND ( IFERROR ( WeightedSum / TotalSum, 4 ), 0 )
			    )
			RETURN
			    result
		displayFolder: RATING
		lineageTag: 8c2d1c7a-3edb-4d22-a7f5-ffbe596e6964

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RATING_TEXT = ```
			
			VAR RatingNumber = [RATING_NUMBER]
			VAR Rating =
			    SWITCH (
			        TRUE (),
			        RatingNumber = 0, "NA",
			        RatingNumber = 1, "N",
			        RatingNumber = 2, "P",
			        RatingNumber = 3, "L",
			        RatingNumber = 4, "F"
			        
			    )
			RETURN
			    Rating
			```
		displayFolder: RATING
		lineageTag: c1495de6-e63f-4573-a36b-92b05de18e0c

	measure COLOR_RATING = ```
			
			VAR SelectedValue = [RATING_TEXT]
			RETURN
			    SWITCH (
			        TRUE (),
			        SelectedValue = "NA", "#c1c7cc",
			        SelectedValue = "N", "#FF5152",
			        SelectedValue = "P", "#FFAB40",
			        SelectedValue = "L", "#FFEA00",
			        SelectedValue = "F", "#67D884" 
			    )
			```
		displayFolder: RATING
		lineageTag: 0796a6b6-f292-4b15-bad2-8010301b5b5c

	measure COUNT_PCM_CHECKPLUS0 = DISTINCTCOUNT(E9_PCM_CHECK[RID]) + 0
		formatString: 0
		lineageTag: 276d6c3d-27b2-4720-bc0d-3978aaf4b56e

	measure PY_COUNT_ALL = ```
			IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			            CALCULATE([COUNT_ALL_RATING]
			            , FILTER(ALLEXCEPT(E9_PCM_CHECK, E9_PCM_CHECK[TOPIC_ID]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME])
			            )),
			            CALCULATE([COUNT_ALL_RATING]
			            , FILTER(ALLEXCEPT(E9_PCM_CHECK, E9_PCM_CHECK[TOPIC_ID]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            )))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 3c164fdc-5030-4d8d-b5be-923cbf11f17c

	measure PY_%F = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]), CALCULATE([%_F], prevtopic),
			    IF(ISINSCOPE(E9_PCM_CHECK[TOPIC_NAME]), CALCULATE([%_F], totalpre),
			    CALCULATE([%_F], 
			    FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]), E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])))))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: bbf919ef-c749-42b2-b57f-d29c53de9ede

	measure PY_%L = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]), CALCULATE([%_L], prevtopic),
			    IF(ISINSCOPE(E9_PCM_CHECK[TOPIC_NAME]), CALCULATE([%_L], totalpre),
			    CALCULATE([%_L], 
			    FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]), E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])))))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: eab98d48-03d2-4f1d-a6ee-0ff6ee020282

	measure PY_%P = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]), CALCULATE([%_P], prevtopic),
			    IF(ISINSCOPE(E9_PCM_CHECK[TOPIC_NAME]), CALCULATE([%_P], totalpre),
			    CALCULATE([%_P], 
			    FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]), E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])))))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 17139e54-35b7-4fa9-a1bd-5ccc5c0a1411

	measure PY_%N = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]), CALCULATE([%_N], prevtopic),
			    IF(ISINSCOPE(E9_PCM_CHECK[TOPIC_NAME]), CALCULATE([%_N], totalpre),
			    CALCULATE([%_N], 
			    FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING], E9_PCM_CHECK[OE_FIXED_LEN]), E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR])))))
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 17714ec0-5204-44a8-bda6-3a92922387e9

	measure PY_DELTA_F = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			            CALCULATE([COUNT_F], prevtopic)/ [PY_COUNT_ALL],
			            CALCULATE([COUNT_F], totalpre)/ [PY_COUNT_ALL])
			
			VAR delta = [PY_%F] - percentage
			
			RETURN delta
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: c4b51e76-1925-4467-aa72-3eb1c4d40843

	measure PY_DELTA_L = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			            CALCULATE([COUNT_L], prevtopic)/ [PY_COUNT_ALL],
			            CALCULATE([COUNT_L], totalpre)/ [PY_COUNT_ALL])
			
			VAR delta = [PY_%L] - percentage
			
			RETURN delta
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 10334a80-b688-4d93-8c27-95215c5fa3b2

	measure PY_DELTA_P = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			            CALCULATE([COUNT_P], prevtopic)/ [PY_COUNT_ALL],
			            CALCULATE([COUNT_P], totalpre)/ [PY_COUNT_ALL])
			
			VAR delta = [PY_%P] - percentage
			
			RETURN delta
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 2b002450-ba15-4f7b-a19d-3d1c6595440b

	measure PY_DELTA_N = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            && E9_PCM_CHECK[TOPIC_NAME] = MAX(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK,E9_PCM_CHECK[RATING]),
			            E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E9_PCM_CHECK[OE_FIXED_LEN]),
			            CALCULATE([COUNT_N], prevtopic)/ [PY_COUNT_ALL],
			            CALCULATE([COUNT_N], totalpre)/ [PY_COUNT_ALL])
			
			VAR delta = [PY_%N] - percentage
			
			RETURN delta
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 8db1cfff-5070-48f5-a8c3-79aa96af3c43

	measure PY_RATING_NUMBER = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E9_PCM_CHECK, E9_PCM_CHECK[RATING]
			            , E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE], E9_PCM_CHECK[CONTINENT], E9_PCM_CHECK[COUNTRY])
			            , E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]) && 
			            E9_PCM_CHECK[TOPIC_NAME] = SELECTEDVALUE(E9_PCM_CHECK[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E9_PCM_CHECK, E9_PCM_CHECK[RATING]
			            , E9_PCM_CHECK[OE_FIXED_LEN], E9_PCM_CHECK[OE_CODE], E9_PCM_CHECK[BU_CODE], E9_PCM_CHECK[CONTINENT], E9_PCM_CHECK[COUNTRY])
			            , E9_PCM_CHECK[PCM_CHECK_YEAR] = MAX(E9_PCM_CHECK[PREVIOUS_YEAR]))
			            
			var checknull = IF(ISINSCOPE(E9_PCM_CHECK[TOPIC_NAME]), CALCULATE ([COUNT_RATING] ,prevtopic), CALCULATE([COUNT_RATING], totalpre))
			
			VAR DeltaF = [PY_DELTA_F]
			VAR DeltaN = [PY_DELTA_N]
			VAR DeltaP = [PY_DELTA_P]
			VAR DeltaL = [PY_DELTA_L]
			
			VAR WeightedSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP * 2 )
			        + IF ( DeltaL < 0, 0, DeltaL * 3 )
			        + IF ( DeltaF < 0, 0, DeltaF * 4 )
			VAR TotalSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP )
			        + IF ( DeltaL < 0, 0, DeltaL )
			        + IF ( DeltaF < 0, 0, DeltaF )
			VAR result =
			    IF (checknull = 0, 0
			            , ROUND ( IFERROR ( WeightedSum / TotalSum, 4 ), 0 )
			    )
			
			RETURN
			   result
			```
		formatString: 0
		displayFolder: RATING
		lineageTag: 89ae316e-5ee0-46bf-b147-95efdf664df5

	measure RATING_COMPARISON =
			
			VAR selectedyear =
			    SELECTEDVALUE ( E9_PCM_CHECK[PCM_CHECK_YEAR] )
			VAR CurrentYearRatingValue = [RATING_NUMBER]
			VAR CurrentYearRating = [RATING_TEXT]
			VAR PreviousYearRatingValue = [PY_RATING_NUMBER]
			VAR RankDifference = CurrentYearRatingValue - PreviousYearRatingValue
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( selectedyear ) || ISBLANK ( CurrentYearRatingValue ), "∅",
			        PreviousYearRatingValue=0 || CurrentYearRatingValue = 0, "∅",
			        RankDifference = 1, "↗",
			        RankDifference = 2, "↗↗",
			        RankDifference = 3, "↗↗↗",
			        RankDifference = 4, "↗↗↗↗",
			        RankDifference = 0, "(=)",
			        RankDifference = -1, "↘",
			        RankDifference = -2, "↘↘",
			        RankDifference = -3, "↘↘↘",
			        RankDifference = -4, "↘↘↘↘"
			    )
			RETURN
			    Result
		displayFolder: RATING
		lineageTag: 9bc94a45-dcf8-4b59-99e7-d8215e1436ed

	measure COLOR_TEXT_RATING =
			
			VAR CurrentYearRatingValue = [RATING_NUMBER]
			VAR CurrentYearRating = [RATING_TEXT]
			VAR PreviousYearRatingValue = [PY_RATING_NUMBER]
			VAR RankDifference = CurrentYearRatingValue - PreviousYearRatingValue
			VAR Color =
			    IF (
			        ISINSCOPE ( E9_PCM_CHECK[TOPIC_ID] ) && ISINSCOPE ( E9_PCM_CHECK[OE_FIXED_LEN] )
			            || ISINSCOPE ( E9_PCM_CHECK[OE_FIXED_LEN] ),
			        [COLOR_RATING],
			        IF (CurrentYearRatingValue = 0 || PreviousYearRatingValue = 0
			            ,"black"
			            , IF ( RankDifference >= 0, "green", "red" )
			        )
			    )
			RETURN
			    Color
		displayFolder: RATING
		lineageTag: 703b7774-2225-4539-a150-25ead9005313

	measure COLOR_BACKGROUND_RATING =
			
			VAR cf =
			    IF (
			        ISINSCOPE ( E9_PCM_CHECK[TOPIC_ID] ) && ISINSCOPE ( E9_PCM_CHECK[OE_FIXED_LEN] )
			            || ISINSCOPE ( E9_PCM_CHECK[OE_FIXED_LEN] ),
			        [COLOR_RATING],
			        "white"
			    )
			RETURN
			    cf
		displayFolder: RATING
		lineageTag: e9fe4eaa-1e22-4fdb-8e2c-c449b74b7d74

	measure L2R_COUNT_RATING = COUNT(E9_PCM_CHECKS_L2_CATEGORIES[RID_QUESTIONID])
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 3c7163bf-ddd9-4474-b4ee-85dd96f90d89

	measure L2R_COUNT_TOTAL_RATING =
			CALCULATE (
			    [L2R_COUNT_RATING],
			    ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 1cae3b11-6dea-4f93-b1f8-84f189ac14c4

	measure L2R_PERCENTAGE_RATING = DIVIDE ( [L2R_COUNT_RATING], [L2R_COUNT_TOTAL_RATING], 0 )
		displayFolder: RISK_CATEGORIES
		lineageTag: 804e4e0d-18cb-4f64-a88f-7aea7a84bfd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure L2R_COUNT_ALL_RATING =
			
			CALCULATE (
			    [COUNT_RATING],
			    FILTER (
			        ALL ( E9_PCM_CHECKS_L2_CATEGORIES ),
			        NOT E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: d8fc6c54-256a-412a-a746-f4f1a0196cef

	measure L2R_DELTA_F =
			
			VAR COUNT_ALL_RATING_F =
			    CALCULATE (
			        [L2R_COUNT_RATING],
			        FILTER (
			            ALL ( E9_PCM_CHECKS_L2_CATEGORIES ),
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "F"
			        )
			    )
			VAR PCT_ALL_RATING_F = COUNT_ALL_RATING_F / [L2R_COUNT_ALL_RATING]
			VAR PCT_F =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [L2R_COUNT_RATING], E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "F" ) + 0,
			            CALCULATE (
			                [L2R_COUNT_TOTAL_RATING],
			                NOT E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_F =
			    IF ( ISBLANK ( PCT_F ), BLANK (), PCT_F - PCT_ALL_RATING_F )
			RETURN DELTA_F
		displayFolder: RISK_CATEGORIES
		lineageTag: 677dac18-8101-4498-8c72-0067a425bd28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure L2R_DELTA_L =
			
			VAR COUNT_ALL_RATING_L =
			    CALCULATE (
			        [L2R_COUNT_RATING],
			        FILTER (
			            ALL ( E9_PCM_CHECKS_L2_CATEGORIES ),
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "L"
			        )
			    )
			VAR PCT_ALL_RATING_L = COUNT_ALL_RATING_L / [L2R_COUNT_ALL_RATING]
			VAR PCT_L =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [L2R_COUNT_RATING], E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "L" ) + 0,
			            CALCULATE (
			                [L2R_COUNT_TOTAL_RATING],
			                NOT E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_L =
			    IF ( ISBLANK ( PCT_L ), BLANK (), PCT_L - PCT_ALL_RATING_L )
			RETURN
			    DELTA_L
		displayFolder: RISK_CATEGORIES
		lineageTag: 41687b86-a638-4863-8d86-05430145fed8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure L2R_DELTA_P =
			
			VAR COUNT_ALL_RATING_P =
			    CALCULATE (
			        [L2R_COUNT_RATING],
			        FILTER (
			            ALL ( E9_PCM_CHECKS_L2_CATEGORIES ),
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "P"
			        )
			    )
			VAR PCT_ALL_RATING_P = COUNT_ALL_RATING_P / [L2R_COUNT_ALL_RATING]
			VAR PCT_P =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [L2R_COUNT_RATING], E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "P" ) + 0,
			            CALCULATE (
			                [L2R_COUNT_TOTAL_RATING],
			                NOT E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_P =
			    IF ( ISBLANK ( PCT_P ), BLANK (), PCT_P - PCT_ALL_RATING_P )
			RETURN
			    DELTA_P
		displayFolder: RISK_CATEGORIES
		lineageTag: e95bd2f8-b269-4aff-80ad-fbb23a2b0f54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure L2R_DELTA_N =
			
			VAR COUNT_ALL_RATING_N =
			    CALCULATE (
			        [L2R_COUNT_RATING],
			        FILTER (
			            ALL ( E9_PCM_CHECKS_L2_CATEGORIES ),
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "N"
			        )
			    )
			VAR PCT_ALL_RATING_N = COUNT_ALL_RATING_N / [L2R_COUNT_ALL_RATING]
			VAR PCT_N =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [L2R_COUNT_RATING], E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "N" ) + 0,
			            CALCULATE (
			                [L2R_COUNT_TOTAL_RATING],
			                NOT E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_N =
			    IF ( ISBLANK ( PCT_N ), BLANK (), PCT_N - PCT_ALL_RATING_N )
			RETURN
			    DELTA_N
		displayFolder: RISK_CATEGORIES
		lineageTag: 5443113a-b7e5-40f7-aa1a-dc7dbcf17bdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW_NO_ROUND =
			
			VAR ISNA =
			    IF ( MAX ( E9_PCM_CHECKS_L2_CATEGORIES[RATING] ) IN { "NA" }, 0, BLANK () )
			VAR RESULT =
			    IF (
			        ISBLANK ( [L2R_DELTA_F] ) || ISBLANK ( [L2R_DELTA_L] )
			            || ISBLANK ( [L2R_DELTA_P] )
			            || ISBLANK ( [L2R_DELTA_N] ),
			        ISNA,
			        IFERROR (
			            (
			                IF ( [L2R_DELTA_N] < 0, 0, [L2R_DELTA_N] )
			                    + IF ( [L2R_DELTA_P] < 0, 0, [L2R_DELTA_P] * 2 )
			                    + IF ( [L2R_DELTA_L] < 0, 0, [L2R_DELTA_L] * 3 )
			                    + IF ( [L2R_DELTA_F] < 0, 0, [L2R_DELTA_F] * 4 )
			            )
			                / (
			                    IF ( [L2R_DELTA_N] < 0, 0, [L2R_DELTA_N] )
			                        + IF ( [L2R_DELTA_P] < 0, 0, [L2R_DELTA_P] )
			                        + IF ( [L2R_DELTA_L] < 0, 0, [L2R_DELTA_L] )
			                        + IF ( [L2R_DELTA_F] < 0, 0, [L2R_DELTA_F] )
			                ),
			            4
			        )
			    )
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES
		lineageTag: a1f0aad9-e494-447e-8bf4-de3f7ed03be3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MOST_PREVIOUS_YEAR =
			
			CALCULATE (
			    MAX ( E9_PCM_CHECK[PCM_CHECK_YEAR] ),
			    FILTER (
			        ALLEXCEPT (
			            E9_PCM_CHECK,
			            E9_PCM_CHECK[OE_CODE],
			            E9_PCM_CHECK[BU_CODE],
			            E9_DIM_REGION[CONTINENT],
			            E9_DIM_REGION[COUNTRY_GROUP_CODE],
			            E9_DIM_REGION[COUNTRY_DISPLAY_TEXT]
			        ),
			        AND (
			            E9_PCM_CHECK[PCM_CHECK_YEAR] < SELECTEDVALUE ( E9_PCM_CHECK[PCM_CHECK_YEAR] ),
			            NOT E9_PCM_CHECK[RATING] IN { "NA", BLANK () }
			        )
			    ),
			    ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 377a0c2a-43db-4149-b460-d2f789d77f89

	measure XS_RAW_PREVIOUS_YEAR =
			
			VAR PC_YEAR = [MOST_PREVIOUS_YEAR]
			VAR DELTA_F_PY =
			    CALCULATE ( [L2R_DELTA_F], E9_PCM_CHECK[PCM_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_L_PY =
			    CALCULATE ( [L2R_DELTA_L], E9_PCM_CHECK[PCM_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_P_PY =
			    CALCULATE ( [L2R_DELTA_P], E9_PCM_CHECK[PCM_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_N_PY =
			    CALCULATE ( [L2R_DELTA_N], E9_PCM_CHECK[PCM_CHECK_YEAR] = PC_YEAR )
			VAR RESULT =
			    IF (
			        ISBLANK ( DELTA_F_PY ) || ISBLANK ( DELTA_L_PY )
			            || ISBLANK ( DELTA_P_PY )
			            || ISBLANK ( DELTA_N_PY ),
			        BLANK (),
			        ROUND (
			            IFERROR (
			                (
			                    IF ( DELTA_N_PY < 0, 0, DELTA_N_PY )
			                        + IF ( DELTA_P_PY < 0, 0, DELTA_P_PY * 2 )
			                        + IF ( DELTA_L_PY < 0, 0, DELTA_L_PY * 3 )
			                        + IF ( DELTA_F_PY < 0, 0, DELTA_F_PY * 4 )
			                )
			                    / (
			                        IF ( DELTA_N_PY < 0, 0, DELTA_N_PY )
			                            + IF ( DELTA_P_PY < 0, 0, DELTA_P_PY )
			                            + IF ( DELTA_L_PY < 0, 0, DELTA_L_PY )
			                            + IF ( DELTA_F_PY < 0, 0, DELTA_F_PY )
			                    ),
			                4
			            ),
			            0
			        )
			    )
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES
		lineageTag: b2ef231b-9ca8-4af2-9b02-3f52f6c608a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW_COMPARE =
			
			VAR selectedyear =
			    SELECTEDVALUE ( E9_PCM_CHECK[PCM_CHECK_YEAR] )
			VAR CurrentYear_XS_RAW = [XS_RAW]
			VAR PreviousYear_XS_RAW = [XS_RAW_PREVIOUS_YEAR]
			VAR RankDifference = CurrentYear_XS_RAW - PreviousYear_XS_RAW
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( SelectedYear ), BLANK (),
			        ISBLANK ( CurrentYear_XS_RAW ), BLANK (),
			        ISBLANK ( PreviousYear_XS_RAW ), "∅",
			        SWITCH (
			            TRUE (),
			            RankDifference = 1, "↗",
			            RankDifference = 2, "↗↗",
			            RankDifference = 3, "↗↗↗",
			            RankDifference = 4, "↗↗↗↗",
			            RankDifference = 0, "(=)",
			            RankDifference = -1, "↘",
			            RankDifference = -2, "↘↘",
			            RankDifference = -3, "↘↘↘",
			            RankDifference = -4, "↘↘↘↘",
			            BLANK ()
			        )
			    )
			RETURN
			    Result
		displayFolder: RISK_CATEGORIES
		lineageTag: 8842e076-65e7-46f8-a03b-ed883a1d4c92

	measure XS_RAW = ROUND ( [XS_RAW_NO_ROUND], 0 )
		displayFolder: RISK_CATEGORIES
		lineageTag: 7e8bcb87-4221-43c8-b6a7-b094c2579d31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW_COMPARE_COLOR =
			
			VAR selectedyear =
			    SELECTEDVALUE ( E9_PCM_CHECK[PCM_CHECK_YEAR] )
			VAR CurrentYear_XS_RAW = [XS_RAW]
			VAR PreviousYear_XS_RAW = [XS_RAW_PREVIOUS_YEAR]
			VAR RankDifference = CurrentYear_XS_RAW - PreviousYear_XS_RAW
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( SelectedYear ), BLANK (),
			        ISBLANK ( CurrentYear_XS_RAW ), BLANK (),
			        ISBLANK ( PreviousYear_XS_RAW ), MAX ( ThemeFilter[Font] ),
			        SWITCH (
			            TRUE (),
			            RankDifference >= 0, "green",
			            RankDifference < 0, "red",
			            MAX ( ThemeFilter[Font] )
			        )
			    )
			RETURN
			    Result
		displayFolder: RISK_CATEGORIES
		lineageTag: 8869fdc9-b872-450d-9ea0-ea752b8d9ef6

	measure SORT_NUM_CASES_BY_RISKSTATEMENT =
			
			IF (
			    SELECTEDVALUE ( E9_SORT[SORT_NAME] ) = "ASC",
			    SWITCH (
			        SELECTEDVALUE ( E9_SORT_BY[MEASURE] ),
			        "Rating", [XS_RAW_NO_ROUND],
			        [MAX_RISK_STATEMENT_ID]
			    ),
			    SWITCH (
			        SELECTEDVALUE ( E9_SORT_BY[MEASURE] ),
			        "Rating", - [XS_RAW_NO_ROUND],
			        - [MAX_RISK_STATEMENT_ID]
			    )
			)
		displayFolder: RISK_CATEGORIES
		lineageTag: fb2cc919-b447-4c24-a1e7-95918a9e0d0e

	measure MAX_RISK_STATEMENT_ID =
			MAXX (
			    E9_PCM_CHECKS_L2_CATEGORIES,
			    RELATED (E9_DIM_RISK_CATEGORIES[L2_ID])
			)
		displayFolder: RISK_CATEGORIES
		lineageTag: ebcee8d9-b72e-40b7-8714-c1e2d6004f81

	measure COUNT_QUESTION_L2_CATEGORIES_TBL = COUNT ( E9_PCM_CHECKS_L2_CATEGORIES[RID_QUESTIONID] )
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: aed40d16-c420-4f72-b915-45450c8c28ef

	measure COUNT_QUESTION_N =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "N"
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: e56121b0-46c7-470a-addc-2e7eb5392c96

	measure COUNT_QUESTION_F =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "F"
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: b01244df-f56e-427a-a31a-e00849ab1831

	measure COUNT_QUESTION_L =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "L"
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 60fd2b4b-c88a-4ddc-8f70-9f3d7e5bd3a1

	measure COUNT_QUESTION_P =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "P"
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 143a5782-b275-46c0-8110-c90624a635f6

	measure COUNT_QUESTION_L&P =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] IN { "L", "P" }
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: cd3a3fe2-4b86-4097-9ebe-091fd45f746e

	measure COUNT_QUESTION_L_PLUS0 =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "L"
			) + 0
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 9d938f6f-da50-4111-a709-97940a0c3c93

	measure COUNT_QUESTION_P_PLUS0 =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "P"
			)
			    + IF ( [COUNT_QUESTION_L_PLUS0] > 0, 0, BLANK () )
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 0f8bbfa3-f968-41d2-a2ed-9a66d09a771d

	measure COUNT_TOTAL_QUESTION =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    ALLEXCEPT (
			        E9_PCM_CHECKS_L2_CATEGORIES,
			        E9_PCM_CHECKS_L2_CATEGORIES[L2_VALUE],
			        E9_DIM_RISK_CATEGORIES[L2_ID]
			    )
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 4af43884-3ba1-40f6-86eb-6d35cb30e286

	measure MAX_L_PER_L2R =
			
			VAR COUNT_QUESTION_L_PER_L2R_TABLE =
			    SUMMARIZE (
			        E9_PCM_CHECKS_L2_CATEGORIES,
			        E9_PCM_CHECKS_L2_CATEGORIES[L2_VALUE],
			        "Count_Question", [COUNT_QUESTION_L_PLUS0]
			    )
			VAR RESULT =
			    MAXX ( COUNT_QUESTION_L_PER_L2R_TABLE, [Count_Question] ) + 1
			RETURN
			    RESULT
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 9f0ac4e8-a95f-422f-9b99-35e7f943721b

	measure MAX_P_PER_L2R =
			
			VAR COUNT_QUESTION_P_PER_L2R_TABLE =
			    SUMMARIZE (
			        E9_PCM_CHECKS_L2_CATEGORIES,
			        E9_PCM_CHECKS_L2_CATEGORIES[L2_VALUE],
			        "Count_Question", [COUNT_QUESTION_P_PLUS0]
			    )
			VAR RESULT =
			    MAXX ( COUNT_QUESTION_P_PER_L2R_TABLE, [Count_Question] ) + 1
			RETURN
			    RESULT
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: 4cd98636-74f5-4570-9076-a33d5329f81d

	measure BUBBLE_COLOR =
			SWITCH (
			    TRUE (),
			    [COUNT_QUESTION_N] > 0, "#ED0007",
			    MAX (E9_DIM_RISK_CATEGORIES[L1_COLOR])
			)
		displayFolder: PRIORITIZED_L2R
		lineageTag: 57e82f93-e8ab-4aae-b932-8c02eeb837d5

	measure PCT_SCALE_L = [COUNT_QUESTION_L_PLUS0] / [COUNT_ALL_QUESTION] / [COUNT_TOTAL_QUESTION] * 100/100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PRIORITIZED_L2R
		lineageTag: c8d5355b-24c2-4cc9-896c-b199dbc3eb2e

	measure COUNT_ALL_QUESTION =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    ALL ( E9_PCM_CHECKS_L2_CATEGORIES )
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: caf4722a-8a9b-4c18-a435-f80a3b7f6754

	measure PCT_SCALE_P = [COUNT_QUESTION_P_PLUS0] / [COUNT_ALL_QUESTION] / [COUNT_TOTAL_QUESTION] * 100/100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PRIORITIZED_L2R
		lineageTag: d55cf974-354a-48fe-ad2f-0217f9e0fde5

	measure PCT_SCALE_L&P = [PCT_SCALE_L] + [PCT_SCALE_P]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PRIORITIZED_L2R
		lineageTag: 12adf271-c4ce-45bb-85be-9b5792a1a8c0

	measure MAX_%L_PER_L2R =
			
			VAR PCT_QUESTION_L_PER_L2R_TABLE =
			    SUMMARIZE (
			        E9_PCM_CHECKS_L2_CATEGORIES,
			        E9_PCM_CHECKS_L2_CATEGORIES[L2_VALUE],
			        "Pct_Question", [PCT_SCALE_L]
			    )
			VAR RESULT =
			    MAXX ( PCT_QUESTION_L_PER_L2R_TABLE, [Pct_Question] ) + 0.001
			RETURN
			    RESULT
		displayFolder: PRIORITIZED_L2R
		lineageTag: ccb7829b-9499-4bdd-a882-ffab0fe5572e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MAX_%P_PER_L2R =
			
			VAR PCT_QUESTION_P_PER_L2R_TABLE =
			    SUMMARIZE (
			        E9_PCM_CHECKS_L2_CATEGORIES,
			        E9_PCM_CHECKS_L2_CATEGORIES[L2_VALUE],
			        "Pct_Question", [PCT_SCALE_P]
			    )
			VAR RESULT =
			    MAXX ( PCT_QUESTION_P_PER_L2R_TABLE, [Pct_Question] ) + 0.001
			RETURN
			    RESULT
		displayFolder: PRIORITIZED_L2R
		lineageTag: 6ce6b870-881d-4cf7-808e-eeedd037cb72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BUBLE_TEXT = "⬤"
		displayFolder: PRIORITIZED_L2R
		lineageTag: c79ee8b2-4703-4043-a2ea-f9b56f178e7e

	measure L2R_4RATING = ```
			IF([L2R_COUNT_RATING]> 0,
			"Fully achieved: " & [L2R_COUNT_F] & UNICHAR(10) & 
			"Largely achieved: " & [L2R_COUNT_L] & UNICHAR(10) &
			"Partially achieved: " & [L2R_COUNT_P] & UNICHAR(10) &
			"Not achieved: " & [L2R_COUNT_N] & UNICHAR(10) & 
			"N/A: " & [L2R_COUNT_NA] & UNICHAR(10), BLANK())
			```
		displayFolder: RISK_CATEGORIES
		lineageTag: 36876e0b-706d-48c2-89d7-0bbaf54e6d83

	measure COUNT_QUESTION_NA =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "NA"
			)
		formatString: 0
		displayFolder: PRIORITIZED_L2R
		lineageTag: d0d98ee4-4ec1-4fa7-9920-cd9ee0125213

	measure L2R_COUNT_F =
			CALCULATE (
			        [L2R_COUNT_RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "F",
			        ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			    )+0
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: bd95b8af-8d93-421a-8c3e-df0fa127fe6d

	measure L2R_COUNT_L =
			CALCULATE (
			        [L2R_COUNT_RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "L",
			        ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			    )+0
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 1a4ee1e2-0815-47f3-8df3-6bc77c2dbc08

	measure L2R_COUNT_P =
			CALCULATE (
			        [L2R_COUNT_RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "P",
			        ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			    ) + 0
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 9e7fb726-2d11-46af-ac55-f1d671abbc6b

	measure L2R_COUNT_N =
			CALCULATE (
			        [L2R_COUNT_RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "N",
			        ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			    )+0
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 90cc9fba-2e9b-42f7-99f4-fd0f8c99ecbe

	measure L2R_COUNT_NA =
			CALCULATE (
			        [L2R_COUNT_RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING] = "NA",
			        ALLSELECTED (
			        E9_PCM_CHECKS_L2_CATEGORIES[RATING],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E9_PCM_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			    )+0
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: be85eb58-4a8b-47db-ae63-4b95fd100f81

	measure AVG_RATING_RAW =
			
			VAR DeltaF = [DELTA_F]
			VAR DeltaN = [DELTA_N]
			VAR DeltaP = [DELTA_P]
			VAR DeltaL = [DELTA_L]
			
			VAR WeightedSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP * 2 )
			        + IF ( DeltaL < 0, 0, DeltaL * 3 )
			        + IF ( DeltaF < 0, 0, DeltaF * 4 )
			VAR TotalSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP )
			        + IF ( DeltaL < 0, 0, DeltaL )
			        + IF ( DeltaF < 0, 0, DeltaF )
			VAR result =
			    IF ([COUNT_RATING]=0,
			        "NA",
			        IFERROR ( WeightedSum / TotalSum, 4 )
			    )
			RETURN
			    result
		lineageTag: 3064f30c-7216-4ee9-9d79-28f77d34df68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure L1_TAXONOMY =
			IF(
			    MIN(E9_DIM_RISK_CATEGORIES[L2_ID]) = CALCULATE(MIN(E9_DIM_RISK_CATEGORIES[L2_ID]), ALLSELECTED(E9_DIM_RISK_CATEGORIES[L2_VALUE])),
			    MAX(E9_DIM_RISK_CATEGORIES[L1_VALUE]),
			    ""
			)
		lineageTag: 36f9eead-8df6-4fce-96bc-55a98d9219ae

	measure COUNT_MEASURE = ```
			
			                CALCULATE(COUNTROWS(E9_PCM_CHECK)
			                ,'E9_PCM_CHECK'[TYPE_OF_GUIDANCE]="Measure"
			              )+0
			```
		formatString: 0
		displayFolder: MEASURES
		lineageTag: 1917544f-e7f3-4e4b-888c-0ad71e58a08e

	measure COUNT_OPEN_MEASURE =
			
			CALCULATE(
				[COUNT_MEASURE],
				'E9_PCM_CHECK'[GUIDANCE_STATUS_DESC]="Open"
			)
		formatString: 0
		displayFolder: MEASURES
		lineageTag: 7ab471a0-af4b-4590-bbbd-ac6649ccfb1c

	measure PERCENTAGE_OPEN_MEASURE =
			[COUNT_OPEN_MEASURE]/
			                        CALCULATE([COUNT_MEASURE]
			                        ,ALL(E9_PCM_CHECK[GUIDANCE_STATUS_DESC])
			                        ,E9_PCM_CHECK[GUIDANCE_STATUS_DESC]<>BLANK()
			                        )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEASURES
		lineageTag: 784b4aed-3f5f-4418-a417-097de16c0764

	measure COUNT_SOONDUE_MEASURE =
			
			CALCULATE(
				[COUNT_MEASURE],
				'E9_PCM_CHECK'[GUIDANCE_STATUS_DESC]="Soon Due"
			)
		formatString: 0
		displayFolder: MEASURES
		lineageTag: 3b0f38cb-bacb-40f0-8bfb-2c6f360fee04

	measure COUNT_OVERDUE_MEASURE =
			
			CALCULATE(
				[COUNT_MEASURE],
				'E9_PCM_CHECK'[GUIDANCE_STATUS_DESC]="Overdue"
			) + 0
		formatString: 0
		displayFolder: MEASURES
		lineageTag: 73a71699-72b6-4f3b-ab1d-f8011d44a756

	measure PERCENTAGE_SOONDUE_MEASURE =
			[COUNT_SOONDUE_MEASURE]/
			                        CALCULATE([COUNT_MEASURE]
			                        ,ALL(E9_PCM_CHECK[GUIDANCE_STATUS_DESC])
			                        ,E9_PCM_CHECK[GUIDANCE_STATUS_DESC]<>BLANK()
			                        )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEASURES
		lineageTag: 5e8bc509-5894-4068-a5a9-f36e6343871f

	measure PERCENTAGE_OVERDUE_MEASURE = ```
			[COUNT_OVERDUE_MEASURE]/
			                        CALCULATE([COUNT_MEASURE]
			                        ,ALLSELECTED(E9_PCM_CHECK[GUIDANCE_STATUS_DESC])
			                        ,E9_PCM_CHECK[GUIDANCE_STATUS_DESC]<>BLANK()
			                        
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEASURES
		lineageTag: dc33a10f-b108-4040-a6e8-b0da0b6a3906

	measure MEASURE_OVERDUE_DAYS = ```
			
			VAR sts = MAXX(E9_PCM_CHECK, E9_PCM_CHECK[GUIDANCE_STATUS_DESC])
			VAR duedate = MAXX(E9_PCM_CHECK, E9_PCM_CHECK[GUIDANCE_DUE_DATE])
			VAR resolutiondate = MAXX(E9_PCM_CHECK, E9_PCM_CHECK[GUIDANCE_RESOLUTION_DATE])
			VAR currentdate = TODAY()
			VAR result =    IF(ISBLANK(resolutiondate)
			                ,IF(DATEDIFF(duedate, currentdate, DAY) > 0
			                    , DATEDIFF(duedate, currentdate, DAY), 0)
			                ,IF(DATEDIFF(duedate, resolutiondate, DAY) > 0
			                    , DATEDIFF(duedate, resolutiondate, DAY) , 0)
			                )
			RETURN IF(
			        ISBLANK(DueDate), 
			        BLANK(),  // If no due date, return blank
			        IF(
			            ISBLANK(ResolutionDate), 
			            MAX(0, DATEDIFF(DueDate, CurrentDate, DAY)),  
			            MAX(0, DATEDIFF(DueDate, ResolutionDate, DAY)) 
			        )
			    )
			```
		formatString: 0
		displayFolder: MEASURES
		lineageTag: 7ff98a93-ec86-440c-8327-f6a4fe6c9a4f

	measure MEASURE_STATUS_COLOR =
			
			VAR meausre_status = SELECTEDVALUE(E9_PCM_CHECK[GUIDANCE_STATUS_DESC])
			VAR theme = SELECTEDVALUE(E9_THEME[Theme])
			RETURN
			                    SWITCH(
			                        TRUE(),
			                        meausre_status="Open" && theme = "Light", "#000000",
			                        meausre_status="Completed" && theme = "Light", "#000000",
			                        meausre_status="Soon Due" && theme = "Light", "#FFAB40",
			                        meausre_status="Overdue" && theme = "Light", "#ED0007",
			                        meausre_status="Open" && theme = "Dark", "#FFFFFF",
			                        meausre_status="Completed" && theme = "Dark", "#FFFFFF",
			                        meausre_status="Soon Due" && theme = "Dark", "#FD9000",
			                        meausre_status="Overdue" && theme = "Dark", "#F13339"
			
			                        )
		displayFolder: MEASURES
		lineageTag: dc2eab71-ef98-4ef0-8a1a-c4864a7d71d4

	measure COLOR_FINDINGS = IF(SELECTEDVALUE(E9_PCM_CHECK[TYPE_OF_GUIDANCE]) <> "Measure", "blacks", MAX(ThemeFilter[Font]))
		lineageTag: c2b1c468-2322-42b9-9869-9b8ac7921c9a

	measure _DUMMY =
			
			CALCULATE (
			    [COUNT_PCM_CHECK],
			    ALL(E9_PCM_CHECK[OE_CODE]),
			    VALUES(E9_PCM_CHECK[CONTINENT])
			) + 0
		formatString: 0
		lineageTag: 828fa86d-5514-496b-bdf2-30112b7a08b5

	measure COUNT_LEGAL_ENTITY = ```
			
			CALCULATE(DISTINCTCOUNTNOBLANK(E9_PCM_LE_OE[LE_NUMBER])
			    , SELECTEDVALUE(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= YEAR(E9_PCM_LE_OE[LE_STATUS_VALID_FROM])
			    && SELECTEDVALUE(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= YEAR(E9_PCM_LE_OE[OE_VALID_FROM])
			) 
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: fc20ebf7-aa35-489a-84eb-732196e811b7

	measure COLOR_AVERAGE_RATING =
			
			VAR rating = [AVG_RATING_TEXT]
			RETURN
			SWITCH(TRUE(),
			        rating = "NA", "#C1C7CC",
			        rating = "N", "#FF5152",
			        rating = "P", "#FFAB40",
			        rating = "L", "#FFEA00",
			        rating = "F", "#67D884"
			)
		lineageTag: 77b6951c-c67f-450d-9258-6e11083a6943

	measure PRESET_VALID_OE = ```
			
			var minyear = year(MIN(E9_PCM_LE_OE[OE_VALID_FROM]))
			var leisvalid = year(MIN(E9_PCM_LE_OE[LE_STATUS_VALID_FROM]))
			VAR result = IF(ISBLANK(minyear), BLANK(),
			    IF(SELECTEDVALUE(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= minyear 
			    && SELECTEDVALUE(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= leisvalid
			        , 1 , 0))
			RETURN result
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: d645129e-f71a-4627-9546-ef74c75d14f6

	measure COUNT_PCM_CHECK_PER_OE_TOOLTIP = ```
			
			VAR result = 
			    CALCULATE(DISTINCTCOUNT(E9_PCM_CHECK[RID]),
			    ALL(E9_PCM_LE_OE),
			    ALL(E9_DIM_OE),
			    TREATAS(
			        VALUES(TOOLTIP[OE_ABBR]), 
			        E9_PCM_CHECK[OE_CODE]
			    ),
			    TREATAS(
			        VALUES(TOOLTIP[LE_CONTINENT]), 
			        E9_PCM_CHECK[CONTINENT]
			    ))+ 0
			RETURN result
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: 99aaebcf-0f03-428f-9dca-ba5ef7dec067

	measure PRESET_VALID_OE_TOOLTIP = ```
			
			var minyear = year(MIN(TOOLTIP[OE_VALID_FROM]))
			var leisvalid = year(MIN(E9_PCM_LE_OE[LE_STATUS_VALID_FROM]))
			VAR result = IF(ISBLANK(minyear), BLANK(),
			    IF(MAX(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= minyear 
			    && MAX(E9_DISTINCT_PCM_CHECK_YEAR[PCM_CHECK_YEAR]) >= leisvalid
			        , 1 , 0))
			RETURN result
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: c232b57b-73db-4be4-ac87-28dee980b3f5

	measure COUNT_LEGAL_ENTITY_TOOLTIP = ```
			
			CALCULATE(DISTINCTCOUNTNOBLANK(E9_PCM_LE_OE[LE_NUMBER]),
			    ALL(E9_PCM_LE_OE),
			    ALL(E9_DIM_OE),
			    TREATAS(
			        VALUES(TOOLTIP[OE_ABBR]), 
			        E9_PCM_LE_OE[OE_ABBR]
			    ),
			    TREATAS(
			        VALUES(TOOLTIP[LE_CONTINENT]), 
			        E9_PCM_LE_OE[LE_CONTINENT]
			    )
			)
			+ 0
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: e00b8da7-e612-4d58-9b03-5a640cdafe38

	measure 'Data Updated Text' =
			
			VAR GRC_PCMC = FILTER('Last Refreshed Date', 'Last Refreshed Date'[INTERFACE_VIEW] = "X_IFR_GRC_EPIC9_PCMC")
			RETURN SWITCH(TRUE(),
			    CALCULATE(MAX('Last Refreshed Date'[IS_OLD_DATA]),GRC_PCMC) = 1, "⚠ " & CALCULATE(MAX('Last Refreshed Date'[Data Updated Text]),GRC_PCMC),
			    CALCULATE(MAX('Last Refreshed Date'[Data Updated Text]),GRC_PCMC))
		lineageTag: 3059b752-bb31-433d-a1c6-bff4ae16b8e0

	measure 'Data Updated Font Color' =
			
			VAR GRC_PCMC = FILTER('Last Refreshed Date', 'Last Refreshed Date'[INTERFACE_VIEW] = "X_IFR_GRC_EPIC9_PCMC")
			RETURN
			SWITCH(TRUE(),
			    CALCULATE(MAX('Last Refreshed Date'[IS_OLD_DATA]), GRC_PCMC) = 1, "#ED0007",
			    MAX(ThemeFilter[Font]))
		lineageTag: 15da07de-bb3d-4cf1-a495-901cacc1fb55

	measure 'Data Updated Tooltips' =
			
			VAR GRC_PCMC = FILTER('Last Refreshed Date', 'Last Refreshed Date'[INTERFACE_VIEW] = "X_IFR_GRC_EPIC9_PCMC")
			RETURN
			SWITCH(TRUE(),
			    CALCULATE(MAX('Last Refreshed Date'[IS_OLD_DATA]), GRC_PCMC) = 1, "Product Compliance Maturity Checks (PCM Checks) data is older than 1 day and may not be up to date.",
			    "Data is up to date.")
		lineageTag: 76f5c0ca-57a3-428c-bd4a-3920b6b86815

	measure AVG_RATING_TEXT =
			
			VAR rating = [AVG_RATING_RAW]
			RETURN
			SWITCH(TRUE(),
			        rating = "NA", "NA",
			        rating > 0 && rating <= 1, "N",
			        rating > 1 && rating <= 2, "P",
			        rating > 2 && rating <= 3, "L",
			        rating > 3 && rating <= 4, "F"
			)
		displayFolder: ACTIVE_OE
		lineageTag: f57404d9-ea9e-467a-8f92-be78815d7afb

	measure COUNT_PCM_CHECK_PER_OE = ```
			
			VAR result = 
			    CALCULATE(DISTINCTCOUNT(E9_PCM_CHECK[RID]),
			    ALL(E9_PCM_LE_OE),
			    ALL(E9_DIM_OE),
			    TREATAS(
			        VALUES(E9_PCM_LE_OE[OE_ABBR]), 
			        E9_PCM_CHECK[OE_CODE]
			    ),
			    TREATAS(
			        VALUES(E9_PCM_LE_OE[LE_CONTINENT]), 
			        E9_PCM_CHECK[CONTINENT]
			    ))+ 0
			RETURN result
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: f42bfd04-29df-482b-913a-32e0a7107b14

	measure BUBBLE_SIZE = ```
			IF(ISINSCOPE(E9_DIM_OE[OE_ABBR]) || ISINSCOPE(E9_PCM_LE_OE[OE_ABBR]),
			10, [COUNT_LEGAL_ENTITY]+0)
			
			```
		formatString: 0
		displayFolder: ACTIVE_OE
		lineageTag: 8a304c26-0b7d-4b39-87cd-e142dfa064eb

	column _MEASURE
		formatString: 0
		lineageTag: beda2ac4-8d3b-4998-94d9-2fb2824ba265
		summarizeBy: sum
		isNameInferred
		sourceColumn: [_MEASURE]

		annotation SummarizationSetBy = Automatic

	partition E9_MEASURES = calculated
		mode: import
		source = Row("_MEASURE", BLANK())

	annotation PBI_Id = c9076b0daab84db4a6c6fcb330d204da

