table E9_PCM_CHECK_UNPIVOT_BU
	lineageTag: 8c62292e-15db-477e-ad97-74fcc2d4a945

	column RID
		dataType: string
		lineageTag: 50873c6e-7e05-41f2-b81b-8b7648820c3a
		summarizeBy: none
		sourceColumn: RID

		annotation SummarizationSetBy = Automatic

	column BU
		dataType: string
		lineageTag: 6f8a24f1-d022-47c8-b384-383d45c91faf
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	partition E9_PCM_CHECK_UNPIVOT_BU = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT RID, BU_CODE#(lf)FROM MARD_PCMS.X_IFR_GRC_EPIC9_PCMC"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,null,"Not mapped to BU",Replacer.ReplaceValue,{"BU_CODE"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value", "BU_CODE", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"BU_CODE.1", "BU_CODE.2", "BU_CODE.3", "BU_CODE.4"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Split Column by Delimiter", {"RID"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Value", "BU"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns"),
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Duplicates",{{"BU", Text.Trim, type text}})
				in
				    #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

