table E9_PCM_LE_UNPIVOT
	lineageTag: 621cffa1-7c95-4520-8de5-8449b124332f

	column RID
		dataType: string
		lineageTag: 908f95d0-bc9f-4e6d-a910-256f9e5eca1b
		summarizeBy: none
		sourceColumn: RID

		annotation SummarizationSetBy = Automatic

	column LEGAL_ENTITY_ID
		dataType: string
		lineageTag: 7d3bfd00-3c7a-4191-85f9-2c162d2dc72c
		summarizeBy: none
		sourceColumn: LEGAL_ENTITY_ID

		annotation SummarizationSetBy = Automatic

	partition E9_PCM_LE_UNPIVOT = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT DISTINCT RID, LEGAL_ENTITY_NUMBER#(lf)FROM MARD_PCMS.X_IFR_GRC_EPIC9_PCMC"]),
				    #"Split Column by Delimiter" = Table.SplitColumn(Source, "LEGAL_ENTITY_NUMBER", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"LEGAL_ENTITY_NUMBER.1", "LEGAL_ENTITY_NUMBER.2", "LEGAL_ENTITY_NUMBER.3", "LEGAL_ENTITY_NUMBER.4", "LEGAL_ENTITY_NUMBER.5", "LEGAL_ENTITY_NUMBER.6", "LEGAL_ENTITY_NUMBER.7"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Split Column by Delimiter", {"RID"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Value", "LEGAL_ENTITY_ID"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns",{{"LEGAL_ENTITY_ID", Text.Trim, type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Trimmed Text")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

