table E9_PCM_LE_OE
	lineageTag: bb538f48-1911-4f4d-959e-d05ef330e26d

	column LE_NAME
		dataType: string
		lineageTag: b74f172d-690a-4a80-81d3-8ce53d84a4dd
		summarizeBy: none
		sourceColumn: LE_NAME

		annotation SummarizationSetBy = Automatic

	column LE_STATUS
		dataType: string
		lineageTag: c93d0c85-6d71-4aa5-ab7d-a6748a4de600
		summarizeBy: none
		sourceColumn: LE_STATUS

		annotation SummarizationSetBy = Automatic

	column OE_NAME
		dataType: string
		lineageTag: 271c41b5-9018-4549-9791-983be4efa831
		summarizeBy: none
		sourceColumn: OE_NAME

		annotation SummarizationSetBy = Automatic

	column OE_LOCATION
		dataType: string
		lineageTag: 6dbb61a9-1779-4f72-8f7b-7129e2893e4a
		summarizeBy: none
		sourceColumn: OE_LOCATION

		annotation SummarizationSetBy = Automatic

	column LE_COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 786a2352-c236-4d74-b0df-e0c1c1c71a99
		summarizeBy: none
		sourceColumn: LE_COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column LE_COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: b0287531-aaa9-43af-acdf-16932cbdd88e
		summarizeBy: none
		sourceColumn: LE_COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column LE_COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 6b75a477-06f6-4331-b0db-b34c43f5b3fc
		summarizeBy: none
		sourceColumn: LE_COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column LE_COUNTRY_GROUP
		dataType: string
		lineageTag: 2ab0109c-cef5-446a-979a-982ea25b1a68
		summarizeBy: none
		sourceColumn: LE_COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column LE_CONTINENT_CODE
		dataType: string
		lineageTag: 39bc609a-1236-4f38-9260-77a79c79df23
		summarizeBy: none
		sourceColumn: LE_CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column LE_CONTINENT
		dataType: string
		lineageTag: a0d94e7c-b20e-404d-b108-a67c8a5fe0fe
		summarizeBy: none
		sourceColumn: LE_CONTINENT

		annotation SummarizationSetBy = Automatic

	column OE_COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 48de393c-c05c-4ace-bfb6-16058fdb605f
		summarizeBy: none
		sourceColumn: OE_COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column OE_COUNTRY
		dataType: string
		lineageTag: 25513d56-9738-4874-8012-96d52b8b4967
		summarizeBy: none
		sourceColumn: OE_COUNTRY

		annotation SummarizationSetBy = Automatic

	column OE_COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: d5d5e3f5-d419-4ab1-b547-b0c752dda158
		summarizeBy: none
		sourceColumn: OE_COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column OE_COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 574b0966-b840-4c51-8c9a-c50f6d1a7315
		summarizeBy: none
		sourceColumn: OE_COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column OE_COUNTRY_GROUP
		dataType: string
		lineageTag: 7c00f191-103c-481c-bef6-8f4021b742ca
		summarizeBy: none
		sourceColumn: OE_COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column OE_CONTINENT_CODE
		dataType: string
		lineageTag: 0a27c8e2-c29c-40e5-b66a-eca571764554
		summarizeBy: none
		sourceColumn: OE_CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column OE_CONTINENT
		dataType: string
		lineageTag: fde648ae-9d6b-4f51-b309-d8e37a8424d3
		summarizeBy: none
		sourceColumn: OE_CONTINENT

		annotation SummarizationSetBy = Automatic

	column OE_ID
		dataType: string
		lineageTag: 2f12e792-e8df-4272-b728-981f46b077b0
		summarizeBy: none
		sourceColumn: OE_ID

		annotation SummarizationSetBy = Automatic

	column OE_VALID_FROM
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1801a316-4616-40c8-8b8c-755b34b8806d
		summarizeBy: none
		sourceColumn: OE_VALID_FROM

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OE_REGION_ID
		dataType: string
		lineageTag: beb326aa-3e96-4018-8d1a-fb8ffd6a9f65
		summarizeBy: none
		sourceColumn: OE_REGION_ID

		annotation SummarizationSetBy = Automatic

	column LE_NUMBER
		dataType: string
		lineageTag: 5ce7e5d7-2123-4569-a4ac-c88b41245357
		summarizeBy: none
		sourceColumn: LE_NUMBER

		annotation SummarizationSetBy = Automatic

	column LE_ABBR
		dataType: string
		lineageTag: de3bda18-3dc9-44f7-8fd2-957ac9375a98
		summarizeBy: none
		sourceColumn: LE_ABBR

		annotation SummarizationSetBy = Automatic

	column LE_COUNTRY_NAME
		dataType: string
		lineageTag: 0a0c9079-0105-4773-a72f-642274ae3ac8
		summarizeBy: none
		sourceColumn: LE_COUNTRY_NAME

		annotation SummarizationSetBy = Automatic

	column LE_TYPE_LINKED_OE
		dataType: string
		lineageTag: 0cb1e2b2-98c4-4cde-8ab6-b3ecc60a626c
		summarizeBy: none
		sourceColumn: LE_TYPE_LINKED_OE

		annotation SummarizationSetBy = Automatic

	column LE_LINKED_OE
		dataType: string
		lineageTag: d148cd57-33aa-4bc5-8179-ba09acbbe45f
		summarizeBy: none
		sourceColumn: LE_LINKED_OE

		annotation SummarizationSetBy = Automatic

	column OE_ABBR
		dataType: string
		lineageTag: 0d95009e-c00a-48fd-a97b-d3fc2589493e
		summarizeBy: none
		sourceColumn: OE_ABBR

		annotation SummarizationSetBy = Automatic

	column OE_DESCRIPTION
		dataType: string
		lineageTag: c8813d02-b5db-4563-ab4e-fee2abe9bbab
		summarizeBy: none
		sourceColumn: OE_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column OE_TYPE
		dataType: string
		lineageTag: c0fb835b-4323-4a4c-b086-5a15106adfb1
		summarizeBy: none
		sourceColumn: OE_TYPE

		annotation SummarizationSetBy = Automatic

	column OE_STATUS_GRC
		dataType: string
		lineageTag: a12a94ac-8111-4eb9-b571-7face6600cbf
		summarizeBy: none
		sourceColumn: OE_STATUS_GRC

		annotation SummarizationSetBy = Automatic

	column OE_RESPONSIBLE
		dataType: string
		lineageTag: ed61e72a-79d0-4f8c-a7b2-5c5cf8d32ce2
		summarizeBy: none
		sourceColumn: OE_RESPONSIBLE

		annotation SummarizationSetBy = Automatic

	column OE_ADMINISTRATOR
		dataType: string
		lineageTag: 84e36d7a-12f2-4542-ba36-c14b158734f0
		summarizeBy: none
		sourceColumn: OE_ADMINISTRATOR

		annotation SummarizationSetBy = Automatic

	column OE_INTERNAL_CONTROL_MANAGER
		dataType: string
		lineageTag: 35f7c891-50f4-42dc-bf3a-19869f8fe4f2
		summarizeBy: none
		sourceColumn: OE_INTERNAL_CONTROL_MANAGER

		annotation SummarizationSetBy = Automatic

	column OE_RISK_MANAGEMENT_OFFICER_OP
		dataType: string
		lineageTag: 74e51c10-948f-4525-adce-679d72773ad0
		summarizeBy: none
		sourceColumn: OE_RISK_MANAGEMENT_OFFICER_OP

		annotation SummarizationSetBy = Automatic

	column OE_DATE_OF_CHANGE_IN_GRC
		dataType: dateTime
		formatString: General Date
		lineageTag: 2531ecbd-4b9c-4d35-a4e3-7e8debc7a468
		summarizeBy: none
		sourceColumn: OE_DATE_OF_CHANGE_IN_GRC

		annotation SummarizationSetBy = Automatic

	column OE_VALID_TO
		dataType: dateTime
		formatString: General Date
		lineageTag: 8dbb4406-9f24-4f3e-b388-7696bbe28042
		summarizeBy: none
		sourceColumn: OE_VALID_TO

		annotation SummarizationSetBy = Automatic

	column OE_DATE_CHANGED
		dataType: dateTime
		formatString: General Date
		lineageTag: e12241b8-0a74-4f2b-b2af-c1a681c181cf
		summarizeBy: none
		sourceColumn: OE_DATE_CHANGED

		annotation SummarizationSetBy = Automatic

	column OE_PARENT_ID
		dataType: string
		lineageTag: e0c3f58a-05a7-469d-bbc8-cebcbace4765
		summarizeBy: none
		sourceColumn: OE_PARENT_ID

		annotation SummarizationSetBy = Automatic

	column OE_PARENT_NAME
		dataType: string
		lineageTag: 68685d93-b0bf-4432-b7a0-10ef6614e470
		summarizeBy: none
		sourceColumn: OE_PARENT_NAME

		annotation SummarizationSetBy = Automatic

	column OE_PARENT_STATUS_GRC
		dataType: string
		lineageTag: ceecd594-12a9-4634-ba68-d0b12622a652
		summarizeBy: none
		sourceColumn: OE_PARENT_STATUS_GRC

		annotation SummarizationSetBy = Automatic

	column OE_PARENT_DESCRIPTION
		dataType: string
		lineageTag: 22d96e41-50d6-4937-947f-8ead3a757ca8
		summarizeBy: none
		sourceColumn: OE_PARENT_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column LE_TYPE_OF_PERSON
		dataType: string
		lineageTag: 46beea7f-c4ce-41b8-a51b-35db4ca8d1c7
		summarizeBy: none
		sourceColumn: LE_TYPE_OF_PERSON

		annotation SummarizationSetBy = Automatic

	column LE_DATE_OF_STATUS_CHANGE
		dataType: dateTime
		formatString: General Date
		lineageTag: 8aaf8ab8-c221-4173-941e-7e2c87b411d1
		summarizeBy: none
		sourceColumn: LE_DATE_OF_STATUS_CHANGE

		annotation SummarizationSetBy = Automatic

	column LE_STATUS_VALID_FROM
		dataType: dateTime
		formatString: General Date
		lineageTag: 0c4e3605-bece-41bd-92e0-31d77d8e61f1
		summarizeBy: none
		sourceColumn: LE_STATUS_VALID_FROM

		annotation SummarizationSetBy = Automatic

	column LE_CITY
		dataType: string
		lineageTag: 8208c832-0267-47fd-b750-12e7da65ffdc
		summarizeBy: none
		sourceColumn: LE_CITY

		annotation SummarizationSetBy = Automatic

	column LE_STREET
		dataType: string
		lineageTag: b62ce064-e3ac-4fce-bd6f-aec02b82d4dd
		summarizeBy: none
		sourceColumn: LE_STREET

		annotation SummarizationSetBy = Automatic

	column LE_HOUSE_NUMBER
		dataType: string
		lineageTag: d638ee50-4fce-4878-93e1-21e7ea7f2de7
		summarizeBy: none
		sourceColumn: LE_HOUSE_NUMBER

		annotation SummarizationSetBy = Automatic

	column LE_TYPE
		dataType: string
		lineageTag: 1d6d4900-a682-4071-a45b-8e699185bc2e
		summarizeBy: none
		sourceColumn: LE_TYPE

		annotation SummarizationSetBy = Automatic

	column LE_POSTAL_CODE
		dataType: string
		lineageTag: df5571e1-5b76-494e-a892-e4c643461117
		summarizeBy: none
		sourceColumn: LE_POSTAL_CODE

		annotation SummarizationSetBy = Automatic

	column LE_CITYPOSTELCODE
		dataType: string
		lineageTag: a1774f04-0774-4f84-a13b-0f658ec3a5e0
		summarizeBy: none
		sourceColumn: LE_CITYPOSTELCODE

		annotation SummarizationSetBy = Automatic

	column LE_SAP_TRADING_PARTNER_NUMBER
		dataType: string
		lineageTag: 9d7f731c-66e9-4c35-9597-e8d024c728b4
		summarizeBy: none
		sourceColumn: LE_SAP_TRADING_PARTNER_NUMBER

		annotation SummarizationSetBy = Automatic

	column LE_COMPANY_CODE
		dataType: string
		lineageTag: 07647d5a-a38c-4de5-97e4-5f23fe23a800
		summarizeBy: none
		sourceColumn: LE_COMPANY_CODE

		annotation SummarizationSetBy = Automatic

	column LE_IFRS_STATUS
		dataType: string
		lineageTag: 294826b2-7966-4955-8951-d05a8b1bb260
		summarizeBy: none
		sourceColumn: LE_IFRS_STATUS

		annotation SummarizationSetBy = Automatic

	column LE_ASSIGNMENT_G
		dataType: string
		lineageTag: 3f2d6e10-146b-41a0-ba0b-12bf4f5554a2
		summarizeBy: none
		sourceColumn: LE_ASSIGNMENT_G

		annotation SummarizationSetBy = Automatic

	column LE_ASSIGNMENT_GBRG
		dataType: string
		lineageTag: d380841f-6093-4d1f-b29f-c09d40738041
		summarizeBy: none
		sourceColumn: LE_ASSIGNMENT_GBRG

		annotation SummarizationSetBy = Automatic

	column LE_ASSIGNMENT_DIRECT
		dataType: string
		lineageTag: 32f23265-1f7b-4f2a-b0de-4adffc714768
		summarizeBy: none
		sourceColumn: LE_ASSIGNMENT_DIRECT

		annotation SummarizationSetBy = Automatic

	column LE_MANDATE_NAME
		dataType: string
		lineageTag: de616bc2-b949-4531-8064-e639afa55d99
		summarizeBy: none
		sourceColumn: LE_MANDATE_NAME

		annotation SummarizationSetBy = Automatic

	column LE_MANDATE_PRIMARY_COMMITTEE
		dataType: string
		lineageTag: 4683eb62-9aa3-495f-83da-b25946062f49
		summarizeBy: none
		sourceColumn: LE_MANDATE_PRIMARY_COMMITTEE

		annotation SummarizationSetBy = Automatic

	column LE_BRC
		dataType: string
		lineageTag: 70b47e1d-856b-43c7-a158-640e5e094389
		summarizeBy: none
		sourceColumn: LE_BRC

		annotation SummarizationSetBy = Automatic

	column LE_LOCKED_FOR_GDPR
		dataType: string
		lineageTag: c8fab2fe-50a6-4178-8a81-f1289f92a57f
		summarizeBy: none
		sourceColumn: LE_LOCKED_FOR_GDPR

		annotation SummarizationSetBy = Automatic

	column LE_PARENT_ID
		dataType: string
		lineageTag: e5e30682-d88e-4811-aca7-935f7c313c51
		summarizeBy: none
		sourceColumn: LE_PARENT_ID

		annotation SummarizationSetBy = Automatic

	column LE_PARENT_NAME
		dataType: string
		lineageTag: 7b170510-3301-4db1-a1e8-4064c8a654eb
		summarizeBy: none
		sourceColumn: LE_PARENT_NAME

		annotation SummarizationSetBy = Automatic

	column LE_PERIOD
		dataType: string
		lineageTag: be8a7e98-3b55-4827-921d-04060a3954a4
		summarizeBy: none
		sourceColumn: LE_PERIOD

		annotation SummarizationSetBy = Automatic

	column LE_RECORD_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 17497e29-34fc-4764-8a5c-f6bf5edf29e9
		summarizeBy: none
		sourceColumn: LE_RECORD_DATE

		annotation SummarizationSetBy = Automatic

	column LE_REPORT_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 3bd06a27-5187-4693-855e-0735a64bc5c2
		summarizeBy: none
		sourceColumn: LE_REPORT_DATE

		annotation SummarizationSetBy = Automatic

	partition E9_PCM_LE_OE = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT * FROM MARD_PCMS.X_IFR_GRC_MD_LE_OE#(lf)WHERE OE_ABBR IS NOT NULL"]),
				    #"Added Custom" = Table.AddColumn(Source, "OE_REGION_ID", each [OE_ABBR]&[LE_CONTINENT_CODE])
				
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

