table E9_PCM_CHECK
	lineageTag: 0d4ad35d-d6e7-40ed-9023-8ba03ff9d8a1

	column RID
		dataType: string
		lineageTag: f5e14bcc-e37e-464b-8f63-860adcdd50ca
		summarizeBy: none
		sourceColumn: RID

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 1053c186-7a7a-4600-a911-20eae02a2f51
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column PCM_CHECK_NAME
		dataType: string
		lineageTag: a901fabd-fe6a-42de-a49b-be4d76b664ed
		summarizeBy: none
		sourceColumn: PCM_CHECK_NAME

		annotation SummarizationSetBy = Automatic

	column PCM_CHECK_STATUS
		dataType: string
		lineageTag: 60a82c7d-fb34-4ade-a3b7-bf217ea8eca2
		summarizeBy: none
		sourceColumn: PCM_CHECK_STATUS

		annotation SummarizationSetBy = Automatic

	column OE_CODE
		dataType: string
		lineageTag: 0fc5a173-d26b-469a-bc0c-822850c7384d
		summarizeBy: none
		sourceColumn: OE_CODE

		annotation SummarizationSetBy = Automatic

	column BU_CODE
		dataType: string
		lineageTag: f67c6c68-03b5-4a9d-baba-cc6e92678cb0
		summarizeBy: none
		sourceColumn: BU_CODE

		annotation SummarizationSetBy = Automatic

	column LOCATION
		dataType: string
		lineageTag: 4d7692e9-4e5f-42d4-8bd5-c6145b18b4c8
		summarizeBy: none
		sourceColumn: LOCATION

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 29e13d9c-8e5b-489c-9405-6873bd30c5a1
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT
		dataType: string
		lineageTag: 471390c7-302c-4edb-a7a5-a8b039be5440
		summarizeBy: none
		sourceColumn: CONTINENT

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: d20c1de8-a95d-4b17-8202-526b73aa03a0
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: a3c80e22-246c-4e98-9fb6-c5a5210a62f0
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: 32e1c7ec-26c2-442b-9817-1e67537b7ceb
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 6c181672-e4be-4af3-ba80-e10f9804ba3f
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: 2b6bba38-37df-483a-a5b0-c7f9c1432764
		summarizeBy: none
		sourceColumn: COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column START_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 63ddd361-56d8-4340-bced-9808af1afd58
		summarizeBy: none
		sourceColumn: START_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column END_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 418fccfe-60af-48a9-afa5-e17005a71760
		summarizeBy: none
		sourceColumn: END_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column QUESTION_TEMPLATE
		dataType: string
		lineageTag: cd014555-fc1d-4321-adf7-f25f015a81b4
		summarizeBy: none
		sourceColumn: QUESTION_TEMPLATE

		annotation SummarizationSetBy = Automatic

	column CREATED_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: b6a50fcb-78ce-429f-b6b7-7bf896643b8f
		summarizeBy: none
		sourceColumn: CREATED_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column RESOLUTION_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 0b64d463-0cef-4b15-b166-ed2b18513b15
		summarizeBy: none
		sourceColumn: RESOLUTION_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column PCM_CHECK_YEAR
		dataType: int64
		formatString: 0
		lineageTag: 002551c3-6583-4915-83d9-cb094fef6d2c
		summarizeBy: none
		sourceColumn: PCM_CHECK_YEAR

		annotation SummarizationSetBy = User

	column TOPIC_ID
		dataType: string
		lineageTag: c4408d94-a8e7-4e62-ac24-50ad5f68ba4e
		summarizeBy: none
		sourceColumn: TOPIC_ID

		annotation SummarizationSetBy = Automatic

	column TOPIC_NAME
		dataType: string
		lineageTag: 80873272-af3d-4e92-9798-1d6b97f73412
		summarizeBy: none
		sourceColumn: TOPIC_NAME

		annotation SummarizationSetBy = Automatic

	column QUESTION_ID
		dataType: string
		lineageTag: 92de00c8-4585-478c-bad3-3e63f26fe7a1
		summarizeBy: none
		sourceColumn: QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column QUESTION
		dataType: string
		lineageTag: 4129c03f-ff62-41bb-949d-c665f6126130
		summarizeBy: none
		sourceColumn: QUESTION

		annotation SummarizationSetBy = Automatic

	column QUESTION_DETAILS
		dataType: string
		lineageTag: 5720e983-d16d-4fc0-b622-d4d201d99dbc
		summarizeBy: none
		sourceColumn: QUESTION_DETAILS

		annotation SummarizationSetBy = Automatic

	column OE_DESCRIPTION_OF_EVIDENCE
		dataType: string
		lineageTag: 04637a92-4e5d-43b3-9e2a-88544c505a21
		summarizeBy: none
		sourceColumn: OE_DESCRIPTION_OF_EVIDENCE

		annotation SummarizationSetBy = Automatic

	column EQUIVALENT_FROM_PREVIOUS_YEAR
		dataType: string
		lineageTag: 411930db-590e-44c2-a788-4c03285e9c6f
		summarizeBy: none
		sourceColumn: EQUIVALENT_FROM_PREVIOUS_YEAR

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_YEAR
		dataType: int64
		formatString: 0
		lineageTag: 2836bd92-84ff-476c-b324-14a7ff2e429a
		summarizeBy: sum
		sourceColumn: PREVIOUS_YEAR

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_TOPIC_ID
		dataType: string
		lineageTag: 07433bc1-d8b0-42bc-8155-5ba8fb0e281a
		summarizeBy: none
		sourceColumn: PREVIOUS_TOPIC_ID

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_TOPIC_NAME
		dataType: string
		lineageTag: 7f02c5b3-42a8-4adf-a510-25dc0a2b9c73
		summarizeBy: none
		sourceColumn: PREVIOUS_TOPIC_NAME

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_QUESTION_ID
		dataType: string
		lineageTag: 2a8c27a2-8997-4514-adfa-37650d73af83
		summarizeBy: none
		sourceColumn: PREVIOUS_QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_QUESTION
		dataType: string
		lineageTag: b739ff69-6f2f-4099-a34b-97e190ade00c
		summarizeBy: none
		sourceColumn: PREVIOUS_QUESTION

		annotation SummarizationSetBy = Automatic

	column RATING
		dataType: string
		lineageTag: b73ece1b-c214-4dea-b58c-83ecdd438fb0
		summarizeBy: none
		sourceColumn: RATING

		annotation SummarizationSetBy = Automatic

	column RATING_DESC
		dataType: string
		lineageTag: fba1b715-9728-47d5-8204-9c8122cdce03
		summarizeBy: none
		sourceColumn: RATING_DESC

		annotation SummarizationSetBy = Automatic

	column RATING_COLOR
		dataType: string
		lineageTag: 5d08a527-b6a4-4713-8800-067875b6a8a3
		summarizeBy: none
		sourceColumn: RATING_COLOR

		annotation SummarizationSetBy = Automatic

	column RATING_COLOR_HEX
		dataType: string
		lineageTag: 6a6fe733-0c28-4bea-af10-bd9e6a24e970
		summarizeBy: none
		sourceColumn: RATING_COLOR_HEX

		annotation SummarizationSetBy = Automatic

	column EVIDENCE_DESC
		dataType: string
		lineageTag: b73942ef-2182-4a7c-bbb1-cee76b6571dd
		summarizeBy: none
		sourceColumn: EVIDENCE_DESC

		annotation SummarizationSetBy = Automatic

	column TYPE_OF_GUIDANCE
		dataType: string
		lineageTag: 4b267c3d-b446-48fb-8990-d491705a9d53
		summarizeBy: none
		sourceColumn: TYPE_OF_GUIDANCE

		annotation SummarizationSetBy = Automatic

	column GUIDANCE
		dataType: string
		lineageTag: 7dd716b0-a9f0-4588-96a6-0e48ec41ea17
		summarizeBy: none
		sourceColumn: GUIDANCE

		annotation SummarizationSetBy = Automatic

	column GUIDANCE_STATUS_CODE
		dataType: double
		lineageTag: 40710588-ab01-41fd-8505-5896da3f9884
		summarizeBy: sum
		sourceColumn: GUIDANCE_STATUS_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GUIDANCE_STATUS_DESC
		dataType: string
		lineageTag: 29d79b4d-2fc7-4154-a93e-db58c0ea0073
		summarizeBy: none
		sourceColumn: GUIDANCE_STATUS_DESC

		annotation SummarizationSetBy = Automatic

	column GUIDANCE_DESC
		dataType: string
		lineageTag: a47b9975-a3bf-4c4e-9c20-6da6f1564761
		summarizeBy: none
		sourceColumn: GUIDANCE_DESC

		annotation SummarizationSetBy = Automatic

	column GUIDANCE_CREATED_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 51124e55-46ba-45b7-975f-52ead80a4d86
		summarizeBy: none
		sourceColumn: GUIDANCE_CREATED_DATE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column GUIDANCE_DUE_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 57c57961-4a22-4815-9e9f-c06eb609f8b2
		summarizeBy: none
		sourceColumn: GUIDANCE_DUE_DATE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column GUIDANCE_RESOLUTION_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: c21758d1-bd1c-41cb-af29-4ed321b21a5a
		summarizeBy: none
		sourceColumn: GUIDANCE_RESOLUTION_DATE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column RC_YEAR
		dataType: int64
		formatString: 0
		lineageTag: 1fa85431-0a24-4f23-b364-9449b4d3d316
		summarizeBy: sum
		sourceColumn: RC_YEAR

		annotation SummarizationSetBy = Automatic

	column L2_ID
		dataType: string
		lineageTag: 1e40f184-c8fb-4837-af38-a0337d015bc8
		summarizeBy: none
		sourceColumn: L2_ID

		annotation SummarizationSetBy = Automatic

	column L2_VALUE
		dataType: string
		lineageTag: 7a76116e-d88d-476b-9ce4-22659c012f7f
		summarizeBy: none
		sourceColumn: L2_VALUE

		annotation SummarizationSetBy = Automatic

	column END_DATE_PLUS7
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7ac35377-218d-4f43-a0c0-7a53c47e9a58
		summarizeBy: none
		sourceColumn: END_DATE_PLUS7

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column END_DATE_PLUS35
		dataType: dateTime
		formatString: Long Date
		lineageTag: cce89103-1aab-477e-a192-15cb2d93fe63
		summarizeBy: none
		sourceColumn: END_DATE_PLUS35

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RID_QUESTIONID
		dataType: string
		lineageTag: 51571e05-8a25-4fa6-b698-6d75e4e40ea8
		summarizeBy: none
		sourceColumn: RID_QUESTIONID

		annotation SummarizationSetBy = Automatic

	column PCM_CHECK_YEAR2
		dataType: string
		lineageTag: 8fda0462-2c3f-4a54-9c80-7f2be1456391
		summarizeBy: none
		sourceColumn: PCM_CHECK_YEAR2

		annotation SummarizationSetBy = Automatic

	column OE_FIXED_LEN
		dataType: string
		lineageTag: 991f6c34-67b3-489f-971c-40107b846b9e
		summarizeBy: none
		sourceColumn: OE_FIXED_LEN

		annotation SummarizationSetBy = Automatic

	column NUMBER_OF_CHECKS
		dataType: int64
		lineageTag: a8fbc069-9836-4258-836a-9fb01105c438
		summarizeBy: sum
		sourceColumn: NUMBER_OF_CHECKS

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NUMBER_OF_QUESTION
		dataType: int64
		lineageTag: 9b0a60f7-d6dd-49f0-8a93-e4040c8bf70f
		summarizeBy: sum
		sourceColumn: NUMBER_OF_QUESTION

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LEGAL_ENTITY_NAME
		dataType: string
		lineageTag: 42103a0d-ee40-4d39-a25e-e01b19ccef75
		summarizeBy: none
		sourceColumn: LEGAL_ENTITY_NAME

		annotation SummarizationSetBy = Automatic

	column IN_PROGRESS_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5056d51-72df-4bea-a1fb-75d186011595
		summarizeBy: none
		sourceColumn: IN_PROGRESS_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IN_REVIEW_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 446fd686-c434-4c59-b489-5c049300db78
		summarizeBy: none
		sourceColumn: IN_REVIEW_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IN_APPROVAL_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3142b3b-7070-48e2-a7a3-7efab3cc50c4
		summarizeBy: none
		sourceColumn: IN_APPROVAL_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOOLTIP_ID
		dataType: string
		lineageTag: a68b911c-5eea-4a1b-b493-b1d12f8e0a53
		summarizeBy: none
		sourceColumn: TOOLTIP_ID

		annotation SummarizationSetBy = Automatic

	column LEGAL_ENTITY_NUMBER
		dataType: string
		lineageTag: 400cea36-54a9-4142-86e3-37c2ea631904
		summarizeBy: none
		sourceColumn: LEGAL_ENTITY_NUMBER

		annotation SummarizationSetBy = Automatic

	column LEGAL_ENTITY_LOCATION
		dataType: string
		lineageTag: a88f2541-4d70-4739-b486-ad5e3af81492
		summarizeBy: none
		sourceColumn: LEGAL_ENTITY_LOCATION

		annotation SummarizationSetBy = Automatic

	column LEGAL_ENTITY_COUNTRY
		dataType: string
		lineageTag: 6eb6e5cf-b353-424a-b7a5-30499a8e55e7
		summarizeBy: none
		sourceColumn: LEGAL_ENTITY_COUNTRY

		annotation SummarizationSetBy = Automatic

	partition E9_PCM_CHECK = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, 
				    Query="SELECT * FROM MARD_PCMS.X_IFR_GRC_EPIC9_PCMC"]),
				    EmptyCheck = if Table.IsEmpty(Source) = true then error "Table is empty. Update aborted" else Source,
				    #"Replaced Value" = Table.ReplaceValue(Source,"Pending Approval","In Approval",Replacer.ReplaceText,{"PCM_CHECK_STATUS"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"START_DATE", type date}, {"END_DATE", type date}, {"CREATED_DATE", type date}, {"IN_PROGRESS_DATE", type date}, {"IN_REVIEW_DATE", type date}, {"IN_APPROVAL_DATE", type date}, {"RESOLUTION_DATE", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "END_DATE_PLUS7", each Date.AddDays([END_DATE], 7)),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "END_DATE_PLUS35", each Date.AddDays([END_DATE], 35)),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "RID_QUESTIONID", each Text.Trim([RID]) & Text.Trim([QUESTION_ID])),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "PCM_CHECK_YEAR2", each "PCM Check Year: " & Number.ToText([PCM_CHECK_YEAR])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom3",{{"END_DATE_PLUS7", type date}, {"END_DATE_PLUS35", type date}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type1", "OE_FIXED_LEN", each Text.PadEnd([OE_CODE], 6, "⠀")),
				    #"Replaced Value1" = Table.ReplaceValue(#"Added Custom4",null,"Not mapped to LE",Replacer.ReplaceValue,{"LEGAL_ENTITY_NAME"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"Not mapped to BU",Replacer.ReplaceValue,{"BU_CODE"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value2", {"OE_CODE", "PCM_CHECK_YEAR"}, NUMBER_OF_CHECKS, {"OE_CODE", "PCM_CHECK_YEAR"}, "NUMBER_OF_CHECKS", JoinKind.LeftOuter),
				    #"Expanded NUMBER_OF_CHECKS" = Table.ExpandTableColumn(#"Merged Queries", "NUMBER_OF_CHECKS", {"NUMBER_OF_CHECKS"}, {"NUMBER_OF_CHECKS"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded NUMBER_OF_CHECKS", {"PCM_CHECK_YEAR", "TOPIC_ID"}, NUMBER_OF_QUESTION, {"PCM_CHECK_YEAR", "TOPIC_ID"}, "NUMBER_OF_QUESTION", JoinKind.LeftOuter),
				    #"Expanded NUMBER_OF_QUESTION" = Table.ExpandTableColumn(#"Merged Queries1", "NUMBER_OF_QUESTION", {"NUMBER_OF_QUESTION"}, {"NUMBER_OF_QUESTION"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Expanded NUMBER_OF_QUESTION",null,"Not mapped to Region",Replacer.ReplaceValue,{"CONTINENT"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",null,"Not mapped to Region",Replacer.ReplaceValue,{"COUNTRY_GROUP_CODE"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",null,"Not mapped to Country",Replacer.ReplaceValue,{"COUNTRY"}),
				    #"Added Custom5" = Table.AddColumn(#"Replaced Value5", "TOOLTIP_ID", each Number.ToText([PCM_CHECK_YEAR]) & [CONTINENT])
				in
				    #"Added Custom5"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

