table E9_THEME
	lineageTag: 24add7dd-6222-4852-9fdf-35d964f72225

	column ThemeID
		dataType: double
		lineageTag: 846e7625-26dc-4733-8f01-24729bceea25
		summarizeBy: count
		sourceColumn: ThemeID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Theme
		dataType: string
		lineageTag: c1b6c26c-06d5-4940-ac51-d3fe37784c39
		summarizeBy: none
		sourceColumn: Theme

		annotation SummarizationSetBy = Automatic

	column home
		dataType: string
		lineageTag: a3299dd2-d233-45dd-b992-571cde540302
		summarizeBy: none
		sourceColumn: home

		annotation SummarizationSetBy = Automatic

	column document-view
		dataType: string
		lineageTag: 990ea155-5816-4229-bf65-8b7638c0bf35
		summarizeBy: none
		sourceColumn: document-view

		annotation SummarizationSetBy = Automatic

	column document-search
		dataType: string
		lineageTag: 2198bb12-a468-4938-977b-a25db5220828
		summarizeBy: none
		sourceColumn: document-search

		annotation SummarizationSetBy = Automatic

	column document-test
		dataType: string
		lineageTag: 1158403a-c666-473d-930a-e5b33def93ea
		summarizeBy: none
		sourceColumn: document-test

		annotation SummarizationSetBy = Automatic

	column document
		dataType: string
		lineageTag: 661bb032-2876-4656-960a-b54a80966999
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	partition E9_THEME = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("3ZTbbuIwEIbfhWtScuySStUqNDQQYmdDE4LdrRDYIWegSSDET7+hLVJVaa9Wq9LKGlljzVzM94//x8eO0Ol2rDiMqvaOqmpX3vR6hG64ZVkGVckF+6t1sd1U8bq5Itu8V0q9c84FmyoodkVcBtw6zoJTcS9ozBrNp9txso1RrjIkRsQS7xMkqsJqM2XzOzWCs/oAda0GuqbY9/WBjMzDMp8ldASJxYh8qiESzF5zmM/v+gzoaQOy+mD7YwX7SIZ6lEE9VFDi1Ih5DDDC277DI0Yk5A55wEAFXE+BrtNAPeXhncJoTuK1c7PaliS6ua9rKljwkC5s6qGVjX65kmGShaBjp2DzaorCwXIq7WN5/LOOaRXdijLP/97zvHhNttm2uOW7pyP8T254tzJmxOIVhFy8m7qZNxvuhsRTCtulie3DyNpAETem+jYVMF2yXw4iyu2mi+exhydTsLbKPbNKWWt8Wy2OASvIKPTKd1NdqvRR/Co9kV/62FhCPpIACxXwIr2ZYgMISHQkmJgZMDwJu1EKfecs/dHWyRE0H6SHvI/VFQxjOpjYB+Ga5jgZ2UHfFzQ6h3RtbMAP4Tml61r7POn/hdssO3M71SIRSVDPIsg8Gbowb9cmsXVPBr6nYH3YIN85Yj2UYTJ+z423Hz5wS/Zjc2hNjoFmQhQ5i0ZdEUcbUj5dhMaDaAiau4wxN8DUe+PWv9jdEr2mZcRD3TnC7NSXnqyDx7pTQ2PI43woQsOTW0sR2zcZu2lrRGaEmHZiJMLEaQMd4UdGAj1m3GwV2j98ybbUQ5CX5hxs6IRTnbTSaF/THurGt3bEef8Bn7qPHbFFpS+L9EKJXa4Ri4rSPcd3sONPme1b+vSXoHcxbv0V6V2Wj/+d3tPTHw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ThemeID = _t, Theme = _t, home = _t, #"document-view" = _t, #"document-search" = _t, #"document-test" = _t, document = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ThemeID", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

