table 'Last Refreshed Date'
	lineageTag: fea80dd0-5812-4883-a247-c7a4428f4845

	column DATA_UPDATED_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 46b710a9-dd3f-402c-9b25-af9de3f5cb27
		summarizeBy: none
		sourceColumn: DATA_UPDATED_TIME

		annotation SummarizationSetBy = Automatic

	column 'Data Updated Text'
		dataType: string
		lineageTag: 3ec5d173-1755-4fd0-bd63-56cfdb6db9f2
		summarizeBy: none
		sourceColumn: Data Updated Text

		annotation SummarizationSetBy = Automatic

	column 'Power BI Refresh Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9b56fd8c-1c52-46b5-8716-43991520b71b
		summarizeBy: none
		sourceColumn: Power BI Refresh Time

		annotation SummarizationSetBy = Automatic

	column INTERFACE_VIEW
		dataType: string
		lineageTag: a44e53ed-f84b-4794-ad13-72f2be20a780
		summarizeBy: none
		sourceColumn: INTERFACE_VIEW

		annotation SummarizationSetBy = Automatic

	column IS_OLD_DATA
		dataType: double
		lineageTag: d90d4896-07cb-4f4a-9a49-9bea0b867381
		summarizeBy: sum
		sourceColumn: IS_OLD_DATA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Last Refreshed Date' = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="
				    SELECT 
				    INTERFACE_VIEW,
				    DATA_UPDATED_TIME,
				    IS_OLD_DATA
				    FROM MARD_PCMS.X_IFR_PCMS_EPIC_REPORT_DETAILS
				    WHERE EPIC_ID = 9"]),
				    #"Added Custom" = Table.AddColumn(Source, "Data Updated Text", each "Data updated: " & DateTime.ToText([DATA_UPDATED_TIME], [Format="dd MMM yyyy HH:mm tt"]) & Character.FromNumber(160)),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom", "Power BI Refresh Time", each DateTime.LocalNow()),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom2",{{"Power BI Refresh Time", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

