table _MEASURES
	lineageTag: 27410f2f-24ec-4dba-8178-701c4f8592df

	measure TOTAL_ASGMTS = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_OVERALL])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: 9cdf5f70-d10e-473d-86ec-58f11863b208

	measure TOTAL_ASGMTS_COMPLETED = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_COMPLETED])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: eca4bf23-3c27-407d-9b32-414eb482d35e

	measure TOTAL_ASGMTS_STILL_DUE = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_STILL_DUE])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: 9ff58dd7-2c43-4cb4-8c2f-cbc5b35f7ed6

	measure TOTAL_ASGMTS_OVERDUE = SUM(X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE])
		formatString: #,0
		displayFolder: NO_PIVOT
		lineageTag: cb58f064-5709-44ae-a228-8ef56524e6d8

	measure WhiteSpace = UNICHAR(8192)
		lineageTag: a6ba6b56-4035-49ce-8171-5d5da39b366a

	measure %_COMPLETED = DIVIDE([TOTAL_ASGMTS_COMPLETED],[TOTAL_ASGMTS],0)
		formatString: 0%;-0%;0%
		displayFolder: NO_PIVOT
		lineageTag: 6e247c78-50ff-48fd-9ebc-6afd142115cc

	measure %_STILL_DUE = DIVIDE([TOTAL_ASGMTS_STILL_DUE],[TOTAL_ASGMTS],0)
		formatString: 0%;-0%;0%
		displayFolder: NO_PIVOT
		lineageTag: c46bb2c5-1f7b-4303-953b-bfd39b436de5

	measure %_OVERDUE = DIVIDE([TOTAL_ASGMTS_OVERDUE],[TOTAL_ASGMTS],0)
		formatString: 0%;-0%;0%
		displayFolder: NO_PIVOT
		lineageTag: a69b7479-c130-413a-96b3-58673a29eccb

	measure ORG_AREA_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_ORG_AREA[ORG_AREA] ),
			    CONCATENATEX (
			        VALUES ( DIM_ORG_AREA[ORG_AREA] ),
			        DIM_ORG_AREA[ORG_AREA],
			        ", ",
			        DIM_ORG_AREA[ORG_AREA]
			    ),
			    "All"
			)
		lineageTag: 2092df0e-396b-4b32-8344-4c0dd932bfc2

	measure REGION_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_REGION[REGION] ),
			    CONCATENATEX (
			        VALUES ( DIM_REGION[REGION] ),
			        DIM_REGION[REGION],
			        ", ",
			        DIM_REGION[REGION]
			    ),
			    "All"
			)
		lineageTag: 9ea87ac1-71af-4f65-9b70-1510ac869e7f

	measure COUNTRY_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_COUNTRY[COUNTRY] ),
			    CONCATENATEX (
			        VALUES ( DIM_COUNTRY[COUNTRY] ),
			        DIM_COUNTRY[COUNTRY],
			        ", ",
			        DIM_COUNTRY[COUNTRY]
			    ),
			    "All"
			)
		lineageTag: b01c6cee-77c7-4c54-9934-7a7db11d3305

	measure TITLE_SELECTED_FILTER =
			
			IF (
			    ISFILTERED ( DIM_ITEM[TITLE] ),
			    CONCATENATEX (
			        VALUES ( DIM_ITEM[TITLE] ),
			        DIM_ITEM[TITLE],
			        ", ",
			        DIM_ITEM[TITLE]
			    ),
			    "All"
			)
		lineageTag: 52a4008f-1006-41ef-b1ec-bf70c987c97a

	measure TOTAL_ASGMTS_UPVT = SUM(X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[NUM_OF_ASS])
		formatString: #,0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 99684a1c-02ca-40d6-ae0e-243f00dd8428

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TOTAL_ASGMTS_UPVT_ALL =
			CALCULATE (
			    [TOTAL_ASGMTS_UPVT],
			    ALLEXCEPT (
			        X_IFR_EPIC6_TRAINING_RATE_UNPIVOT,
			        DIM_ORG_AREA[ORG_AREA],
			        DIM_REGION[REGION],
			        DIM_COUNTRY[COUNTRY],
			        DIM_ITEM[TITLE],
			        X_IFR_EPIC6_TRAINING_RATE[Year Month 2]
			    )
			)
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: e03c510b-6d5c-4b28-8a14-b885e5510890

	measure %_ASGMTS_TO_ALLSTATUS = DIVIDE ( [TOTAL_ASGMTS_UPVT], [TOTAL_ASGMTS_ALLSTATUS], 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: UNPIVOT_TABLE
		lineageTag: 50dfa4d6-ad1c-495a-9b96-7bc980e6d332

	measure 'Preset Value' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) >= 0, 1, 0 ),
			        "Overdue >=2%", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) >= 0.02, 1, 0 ),
			        "Overdue <2%", IF ( SUM ( X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] ) < 0.02, 1, 0 )
			    )
			RETURN
			    result
		formatString: 0
		lineageTag: 8924938f-ced9-45cc-bc2f-0b94a563c2db

	measure %_ASGMTS = DIVIDE([TOTAL_ASGMTS_UPVT],[TOTAL_ASGMTS_UPVT_ALL],0)
		formatString: 0%;-0%;0%
		displayFolder: UNPIVOT_TABLE
		lineageTag: bd98ca8b-3eb5-4878-a264-f3902359e7b9

	measure TOTAL_ASGMTS_ALLSTATUS =
			CALCULATE (
			    [TOTAL_ASGMTS_UPVT],
			    ALLSELECTED ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] )
			)
		formatString: #,0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 9611adac-95ab-4f4c-8f26-194b490723c6

	measure 'Preset Value UNPVT' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All", IF ( _MEASURES[%_ASGMTS] >= 0, 1, 0 ),
			        "Overdue >=2%", IF ( _MEASURES[%_ASGMTS] >= 0.02, 1, 0 ),
			        "Overdue <2%", IF ( _MEASURES[%_ASGMTS] < 0.02, 1, 0 )
			    )
			RETURN
			    result
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 9625dae4-938b-4e8e-9eb6-8f4bac4e158f

	measure 'Preset Value UNPVT Pie-expand' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) >= 0.00,
			                1,
			                0
			            ),
			        "Overdue >=2%",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) >= 0.02,
			                1,
			                0
			            ),
			        "Overdue <2%",
			            IF (
			                CALCULATE (
			                    _MEASURES[%_ASGMTS],
			                    X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			                ) < 0.02,
			                1,
			                0
			            )
			    )
			RETURN
			    result
		formatString: 0
		displayFolder: UNPIVOT_TABLE
		lineageTag: 1e957410-1957-47d7-9810-6e89ef72f576

	measure 'Preset Value 2' =
			
			VAR presetValue =
			    SELECTEDVALUE ( 'OVERDUE_RANGE'[Overdue Range] )
			VAR result =
			    SWITCH (
			        presetValue,
			        "All",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] >= 0
			            ),
			        "Overdue >=2%",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] >= 0.02
			            ),
			        "Overdue <2%",
			            CALCULATE (
			                [TOTAL_ASGMTS_OVERDUE],
			                X_IFR_EPIC6_TRAINING_RATE[ASS_OVERDUE_PCT] < 0.02
			            )
			    )
			RETURN
			    result
		formatString: 0
		lineageTag: bbc751df-02b9-4966-b62e-e801b57764a5

	measure TT_ASGMTS_CPLT =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Completed"
			        )
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: fcb5d15c-fc3e-4345-aea7-23d5a0e77277

	measure TT_ASGMTS_STDL =
			
			VAR FILTER_TB = FILTER (
			            ALL ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Still Due"
			        )
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 7fab11d0-bd0c-4b11-919b-aa9241a7a8df

	measure TT_ASGMTS_OVRD =
			
			VAR FILTER_TB = FILTER (
			            ALL ( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			        )
			
			VAR ASGMTS_ =
			    CALCULATE (
			        _MEASURES[TOTAL_ASGMTS_UPVT],
			        FILTER_TB
			    )
			RETURN
			    FORMAT (ASGMTS_, "#,##0" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 1ce01f35-07b1-4824-b793-2a61c640f56c

	measure TT_ASGMTS_3_STS = ```
			
			"Completed: " & [TT_ASGMTS_CPLT] & " (" & [TT_ASGMTS_CPLT%] & ")" & UNICHAR(10) & 
			"Still Due: " & [TT_ASGMTS_STDL] & " (" & [TT_ASGMTS_STDL%] & ")" & UNICHAR(10) &
			"Overdue: " & [TT_ASGMTS_OVRD] & " (" & [TT_ASGMTS_OVRD%] & ")"
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: 3aa5aed7-ec75-4064-9e9f-9e394f26504a

	measure TT_ASGMTS_CPLT% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS]),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Completed"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: c4414e26-2a38-4b66-8ed9-ddfd9ecd2a3f

	measure TT_ASGMTS_STDL% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Still Due"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: 0eed4453-51be-4c7c-8378-daad0aaa2adb

	measure TT_ASGMTS_OVRD% =
			
			VAR FILTER_TB = FILTER (
			            ALL( X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] ),
			            X_IFR_EPIC6_TRAINING_RATE_UNPIVOT[ASS_STATUS] = "Overdue"
			        )
			VAR PCT_ASGMTS_ =
			    CALCULATE (
			        _MEASURES[%_ASGMTS],
			        FILTER_TB
			    )
			RETURN
			    FORMAT ( PCT_ASGMTS_, "Percent" )
		displayFolder: UNPIVOT_TABLE
		lineageTag: d0b8b9b1-d081-40a6-b55d-53fff85cc6ef

	measure TT_ASGMTS_%_3STS = ```
			
			"Completed: " & [TT_ASGMTS_CPLT%] & UNICHAR(10) & 
			"Still Due: " & [TT_ASGMTS_STDL%] & UNICHAR(10) &
			"Overdue: " & [TT_ASGMTS_OVRD%]
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: a48a8ff0-857a-4f47-9f82-bbbf2f2d5fa6

	measure TT_ASGMTS_%_3STS_NO_PIVOT = ```
			
			"Completed: " & FORMAT ( [%_COMPLETED], "Percent" ) & UNICHAR(10) & 
			"Still Due: " & FORMAT ( [%_STILL_DUE], "Percent" ) & UNICHAR(10) &
			"Overdue: " & FORMAT ( [%_OVERDUE], "Percent" )
			```
		displayFolder: UNPIVOT_TABLE
		lineageTag: c0445c48-d118-44ab-a89e-95716ee813f1

	column MEASURES
		dataType: int64
		formatString: 0
		lineageTag: 940ddc61-1c79-4592-8516-8a24caed442e
		summarizeBy: sum
		sourceColumn: MEASURES

		annotation SummarizationSetBy = Automatic

	partition _MEASURES = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MEASURES = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MEASURES", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

