table DIM_COUNTRY
	excludeFromModelRefresh
	lineageTag: 2482af0f-8a3a-4fb9-81d0-7a60bb7e1c7c

	column COUNTRY
		dataType: string
		lineageTag: 84be4bce-2220-4545-8882-430e0116b383
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_FIX_LEN
		dataType: string
		lineageTag: 0aaedde2-bdec-43dc-9dea-68f5af1b2fe6
		summarizeBy: none
		sourceColumn: COUNTRY_FIX_LEN

		annotation SummarizationSetBy = Automatic

	partition DIM_COUNTRY = m
		mode: import
		source =
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT DISTINCT COUNTRY FROM MARD_PCMS.X_IFR_TRAINM_EPIC6_TRAINING_RATE"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,null,"",Replacer.ReplaceValue,{"COUNTRY"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "COUNTRY_FIX_LEN", each if Text.Length([COUNTRY])> 18 then Text.Start([COUNTRY],18) else Text.End(Text.Repeat(Character.FromNumber (8192), 18) & [COUNTRY],18))
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

