table DIM_REGION
	excludeFromModelRefresh
	lineageTag: 829ab9fb-cc22-4e03-9adb-e8e3ef560f05

	column REGION
		dataType: string
		lineageTag: 31f92850-e0ab-4b06-aff7-176ea28fa655
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column REGION_FIX_LEN
		dataType: string
		lineageTag: 3b7d9ff0-cb59-4c33-b3d4-115c3af8621a
		summarizeBy: none
		sourceColumn: REGION_FIX_LEN

		annotation SummarizationSetBy = Automatic

	partition DIM_REGION = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="SELECT DISTINCT REGION FROM MARD_PCMS.X_IFR_TRAINM_EPIC6_TRAINING_RATE"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,null,"",Replacer.ReplaceValue,{"REGION"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "REGION_FIX_LEN", 
				        each if Text.Length([REGION])> 18 then 
				                Text.Start([REGION],18) 
				            else Text.End(Text.Repeat(Character.FromNumber (8192), 18) & [REGION],18))
				in
				    #"Added Custom"
				```

	annotation PBI_ResultType = Table

