table 'Epic 7 - Internal Audit'
	excludeFromModelRefresh
	lineageTag: 0a56edae-3f52-4d1e-a69a-0e3b3e2f1b7e

	column AUDIT_ID
		dataType: string
		lineageTag: 310b8889-fc47-44ee-a9e2-2bdd09617db1
		summarizeBy: none
		sourceColumn: AUDIT_ID

		annotation SummarizationSetBy = Automatic

	column F_AUDIT_TOPIC
		dataType: string
		lineageTag: 2af9ebf1-788c-4cf1-8afb-53898b70bc99
		summarizeBy: none
		sourceColumn: F_AUDIT_TOPIC

		annotation SummarizationSetBy = Automatic

	column AUDIT_SUB_TOPIC
		dataType: string
		lineageTag: 371c5515-cccb-4c65-b384-41d5e4b81758
		summarizeBy: none
		sourceColumn: AUDIT_SUB_TOPIC

		annotation SummarizationSetBy = Automatic

	column OE_CODE
		dataType: string
		lineageTag: 0ce7796b-7830-467f-b20d-0378ac1afa6b
		summarizeBy: none
		sourceColumn: OE_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 2a3d5891-202e-4e3b-8213-f45ec28cf237
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT
		dataType: string
		lineageTag: 6f16785d-c30e-4911-80c6-d3191c9cd863
		summarizeBy: none
		sourceColumn: CONTINENT

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 3e1df91a-8df1-442e-8323-c45ac096105d
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: df2018f1-ffbb-4f92-af78-f8acc9e38bbe
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column AUDITED_COUNTRY
		dataType: string
		lineageTag: e79526ae-9fd3-4c39-b91d-7c932c2568eb
		summarizeBy: none
		sourceColumn: AUDITED_COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 46945211-e90a-4761-9c3f-c6aa14ffada6
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: 12987eea-97d0-426f-8591-c6411542d7b8
		summarizeBy: none
		sourceColumn: COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 9f6c6fd3-6ba4-4814-9cbc-a468fa531477
		summarizeBy: sum
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column AUDIT_TYPE
		dataType: string
		lineageTag: f7ddd80d-7691-4009-b88b-2b746b6b67ce
		summarizeBy: none
		sourceColumn: AUDIT_TYPE

		annotation SummarizationSetBy = Automatic

	column FINDING_DESCRIPTION
		dataType: string
		lineageTag: 681c9d64-97b9-4145-964a-8d4f956d5e29
		summarizeBy: none
		sourceColumn: FINDING_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column POTENTIAL_ROOT_CAUSE
		dataType: string
		lineageTag: 3d5e312e-5af8-401e-830a-b476a0b807a4
		summarizeBy: none
		sourceColumn: POTENTIAL_ROOT_CAUSE

		annotation SummarizationSetBy = Automatic

	column RISK
		dataType: string
		lineageTag: 47c23825-7632-41d4-91c9-f6eef9ba0369
		summarizeBy: none
		sourceColumn: RISK

		annotation SummarizationSetBy = Automatic

	column RISK_RATING
		dataType: string
		lineageTag: 8013ce55-e042-443b-ba20-fe7c2efe03b0
		summarizeBy: none
		sourceColumn: RISK_RATING

		annotation SummarizationSetBy = Automatic

	column RECOMMENDED_ACTION
		dataType: string
		lineageTag: e9002882-9ae8-422c-a220-d22aa332ecf9
		summarizeBy: none
		sourceColumn: RECOMMENDED_ACTION

		annotation SummarizationSetBy = Automatic

	column ACTION_STATUS
		dataType: string
		lineageTag: db2d974d-4649-4864-b8d5-747812bb9ee8
		summarizeBy: none
		sourceColumn: ACTION_STATUS

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd34ede5-93b8-4695-a93c-52ba4bb8a98d
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Extract key phrases'
		dataType: string
		lineageTag: d1faa94f-5973-4304-9ce5-3b70b02a49bb
		summarizeBy: none
		sourceColumn: Extract key phrases

		annotation SummarizationSetBy = Automatic

	partition 'Epic 7 - Internal Audit' = m
		mode: import
		source =
				let
				    Source = Oracle.Database("REDLake_ZeusQ_OpsDevSup_CI.world", [HierarchicalNavigation=true, Query="SELECT#(lf)    *#(lf)FROM MARD_PCMS.X_IFR_BRAIN_EPIC7_INTERNAL_AUDIT#(lf)WHERE EXPORT_DATE = (SELECT MAX(EXPORT_DATE) FROM MARD_PCMS.X_IFR_BRAIN_EPIC7_INTERNAL_AUDIT)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YEAR", Int64.Type}, {"EXPORT_DATE", type date}}),
				    #"Applied Extract key phrases" = AIFunctions.PostProcess(Table.AddColumn(#"Changed Type", "Extract key phrases", each #"Extract key phrases"([FINDING_DESCRIPTION], null)), "Extract key phrases", "CognitiveServices.ExtractKeyPhrasestexttext") meta [FunctionBrowser="TextAnalytics"],
				    #"Removed Columns" = Table.RemoveColumns(#"Applied Extract key phrases",{"Extract key phrases.KeyPhrase"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

