table 'Last Refreshed Date'
	excludeFromModelRefresh
	lineageTag: 4648edf7-51ee-452a-8877-48a62cf1078b

	column 'Last Refreshed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 97250b12-005a-4f16-a724-baaaa49ec592
		summarizeBy: none
		sourceColumn: Last Refreshed Date

		annotation SummarizationSetBy = Automatic

	column 'Data Updated Text'
		dataType: string
		lineageTag: b9bf03ba-fb1a-467c-aba4-77ccd717f9c7
		summarizeBy: none
		sourceColumn: Data Updated Text

		annotation SummarizationSetBy = Automatic

	partition 'Last Refreshed Date' = m
		mode: import
		source =
				let
				    Source = DateTime.LocalNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Last Refreshed Date"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Custom", each "Data updated: " & DateTime.ToText([Last Refreshed Date], [Format="dd MMM yyyy HH:mm tt"]) & Character.FromNumber(160)),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Custom", "Data Updated Text"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

