table OVERDUE_RANGE
	excludeFromModelRefresh
	lineageTag: 8e19736e-5e05-4096-b5ff-6c4fe03ac458

	column 'Overdue Range'
		dataType: string
		lineageTag: 0de58303-f688-478b-b3a1-d6a7c5313cd3
		summarizeBy: none
		sourceColumn: Overdue Range
		sortByColumn: RangeID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column RangeID
		dataType: string
		lineageTag: 93dc3da3-a15c-4940-ae63-dd1255764d7b
		summarizeBy: none
		sourceColumn: RangeID

		annotation SummarizationSetBy = Automatic

	partition OVERDUE_RANGE = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcszJUdJRMlSK1YlW8i9LLUopTVWIKTUwME61NVIFyhhhyiSDJYyVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Overdue Range" = _t, RangeID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Overdue Range", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

