table Table
	excludeFromModelRefresh
	lineageTag: 9b68aadd-fc09-4255-91f6-f6cf38f70e19

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c2ede3e4-a8e6-436d-954d-7192b5bd541a
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Item Title'
		dataType: string
		lineageTag: 05e4038f-14a0-4c2e-9221-14491d4fb77a
		summarizeBy: none
		sourceColumn: Item Title

		annotation SummarizationSetBy = Automatic

	column Answer
		dataType: string
		lineageTag: 201e7ff3-cb02-4a1e-92a0-c525f35dd572
		summarizeBy: none
		sourceColumn: Answer

		annotation SummarizationSetBy = Automatic

	column 'Score sentiment'
		dataType: double
		lineageTag: cf4e039a-f57e-4c76-bf02-f126699b66e8
		summarizeBy: sum
		sourceColumn: Score sentiment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Category
		dataType: string
		lineageTag: 321ff124-330b-45bd-a548-a8fc4a57aeac
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pVnfbxvHEf5XJnosKIE/jqT4KMGKIbhxK0iwgbp+WPKG5Jp7u+z+IC09mYLR1k2LPqRN0SSAK0RA0AROkYcaKBq0D5T/kius5r/o7O0xvSP8tBEEiDwuZ3Zn5/vmm9GjRzutncbOo5MPdk8OmeEjs3u4+/Dw7DGc7Ib3MFYa7BThARMO4dRqZNnuIX1phlzCPZWhtEzT++beoEd/7iqV7jxuPNppxxo+o4dWMy65nDSAnExQomaiAUtmwDDLzZiNrNLne8FtO6n67cT6vX1+la/+VJjsDPbp7yELFpNYiyeOCW7PIeMyNWhhYWCuaet8hGAsFwIEG83CKZqdVsVlN9bl06eFtVbVWC/WGIUdBS6YtHL9qrCb7Htj95XOmChs92NtG5xqmDgLTAg0dMczweZzW3jpN7t1L/uxXn5CT/WSGwRVxrnValdCM4g1fAxTtkCQCliacqskEzAqwGCCn25zK1KtZqyvpVo26BNugH41/sJxjSlYBWOfQsrZvb09MIjw8OD07Mhvw+8D2FAtsIRId78KkVY06CdkAjK0U7JUnHKwdcho1O++6ydkQ7+/5SQa4rIw2OslWwajEX6HwZP19VQLPqKPT0dTJ5xnLaOEsCgh5fT0AiXTXBlgbjQFckrZvr6WKWoLS9QpyvcC69RSsxXNAcfWJwoDez7noyIvnSYE2CmzkDljYUhv2Iy2d45MAxtb1MXLEiG9QXUb0ezxgCNBmwJDp1xfawSCObH5z9zMyTHtZP164sPWAAoA3HP6AtB6hr9wMFt/qylqZfL2+rXkjaacYxB85pFDHy7ZORg3fIIjW5QV4h6tGF1iyOtWu1oAWtH8MyV2U+EU9UNEE89PQwGha/25azbbPRgx46uJS6nOKIoyXf0SheeidBO/Vq0uR/PQgzdXxHgM3lzNlEAqCTA8F4p8a3fzO7n+K6Xc/M2f0dDLkgO7W0BrRxPPIXJ4nwkzmlI1WiqPHEfIAVnkV4qWERdyj6ghTvT6W0JXqCVJv721h2iKurt+TTiinNaw/kLNgEnB3ry8+UbcfKNpCzcvuQg4rqROO5qrJnxow/HMu1mrHc1ae8VPYXU/qeVlO5p0PnBUBWGoslKT1axGc8jti3/kq6/y1ZekzPJnlyEQne0bjWaEtx//6varv+Srr7/7+KPvVn/MV7/OV7/NV5f55Yf0MF99kT9b/effX7999bn3v3qZr/6Zr35Ja/774m/56nmxnXazShXtaKrYHJWc/yZf/StffZpffrQ5cz/ZUhPtH6BcAgviAvU5qQo5Cfqz268coxNNErXSPUjq0jwa/necJt2vpGc30j8WQSg5KVO43605icY31acl01SMpNNUnq6lDGX9fT5x9DjcdqEVvg9TNLqnbEiOxlTnSE5xiXCgh8i9HpB8Aoq0AfgGi9bcd/aidN7Zr8r6TjT+76s9OBAk4txkCrxQC1JZkpaC2aAss3N4ooYNGJJAHzEJgrqXDGFCXVlhcibVUmA6Qa8yaU0rOWkQH6YwVUtvkRh6o7dr8OhE8ws1UlYgOCp2fk3YYLiSXi1zo7lGMGeNJaUyw4C5olpVMNeJ5hlqE7gxDgOT91vbhqNJ4+1nz27/fnn7yXOiyNtXfygJ7PL3+erD/PJFwZuBpTrdWupEs8eRKcXckmosVWOUZumrLsvgiGpuyGivesc4pUI5JXFJFdkvQa+HSy1Mr0LSu7FYvzYkmb3qG+KsaF0a4DJImWauEINkRpYAaBVQ/74vjyYpiRuh0oALtlhfpTefPlm/GpVdbr+3xbZJNHEdSxLXaAypFoSzKdLx6GTGkoxwJfO2q4ySRLPXKWZlB7q+8t1GCFi32lIk0XR1RDsGessl8x4UyR3qfg2xVEYn46kC8k4Fxaw/V6CINyU2gBRhxnwnklLPymgNA4kjCgZP6VE4e7ualkk0o/049Bl+B9a3VgVxaziWJMAt3TEl1BlyARlx0yEXRK+UgXomKJWDTGwmtcyKpqmDMM0gSqyZT4rQVzMqmqbuULfyEId0E9qXKz8qk2bOCGDU8zuiYEltzIL6zwuO0yEtSJ2mttNj8ihsiRIP/VTNWAoO2sDTve15RRLNdt5VCHKwPNia5iTRdOdnRcBDQ9Xf3xoLJNGkNnQoFfXLmJ2WNasKyW40zdx1hJoH3PgxoKHmxPOcv6EZNbtYJqfxV1W/mtA7dbaKRDeag4gZMl5W40G1OelGk83En+z/ey7rcG2CGc019xUseIolgzVr1b0bzRCV6W6rXcV6Nxrrc2aMBSqCZYffqQ3ZutEIL6aibjzBISmSEISa8OtGI9Oquf+cRC5sJrtBtvnVYaxXDBn9mC/c6aDmOBq4PipUyJmWm36jU7vW+G5GBjSRtFhfe6FMwsEUhZb5akB8T6U2BHF/UJuD9KJh/aNAa+0tWutFA/TeQcjLpBqTXvw/UCp1Oivacp7NlbZegwQa6LSqI75eNFSLaw3jxXeTVi8ar4Xpzb+BfEuiccFxWSymbgOK7wenza3a2vshk1M/DPSdMSkckjapd36uHBhqlkQKXI6EI5lbEFSBHEOSS5GULXbIApIsPt1U1V61SD3+Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, #"Item Title" = _t, Answer = _t, #"Score sentiment" = _t, Category = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Item Title", type text}, {"Answer", type text}, {"Score sentiment", type number}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

