table VisionFunctionBrowser1
	lineageTag: 3244018b-41c8-4c99-bfce-0b3dd6996481

	column Name
		dataType: string
		lineageTag: fccb651b-17b8-44b6-8171-e5d769579967
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: e47b3121-8a10-45d5-8873-dab0cc52bff4
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column ItemKind
		dataType: string
		lineageTag: 21f90a54-1e9b-4d6c-918c-7ca7d3567a2b
		summarizeBy: none
		sourceColumn: ItemKind

		annotation SummarizationSetBy = Automatic

	column ItemName
		dataType: string
		lineageTag: bfc3fc65-e1de-4fd2-a2e2-8a39bab49b70
		summarizeBy: none
		sourceColumn: ItemName

		annotation SummarizationSetBy = Automatic

	column IsLeaf
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 92cbe73e-0f5f-4e0c-94ab-4e47f38458a4
		summarizeBy: none
		sourceColumn: IsLeaf

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.Category'
		dataType: string
		lineageTag: 6d9454f5-c72b-4dc6-9d17-0b9be042a49f
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.Category

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.Description'
		dataType: string
		lineageTag: 5ac6321a-ec70-460e-87af-5430d5213b3a
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.Description

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.ButtonText'
		dataType: string
		lineageTag: 046ee636-679d-4f38-9f16-9d5e7b712d3a
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.ButtonText

		annotation SummarizationSetBy = Automatic

	partition VisionFunctionBrowser1 = m
		mode: import
		source =
				let
				            Uncategorize = (functionTable as table) =>
				                let
				                    TableMetadata = Value.Metadata(Value.Type(functionTable)),
				                    TableKey = Table.Keys(functionTable){0},
				                    MetadataColumn = Table.AddColumn(functionTable, "MetadataColumn", each Value.Metadata([Data])),
				                    ExpandedMetadataColumn = Table.ExpandRecordColumn(MetadataColumn, "MetadataColumn", {"Publish"}, {"MetadataColumn.Publish"}),
				                    ExpandedMetadataColumn.Publish = Table.ExpandRecordColumn(
				                        ExpandedMetadataColumn,
				                        "MetadataColumn.Publish",
				                        {"Category", "Description", "ButtonText"},
				                        {"MetadataColumn.Publish.Category", "MetadataColumn.Publish.Description", "MetadataColumn.Publish.ButtonText"}),
				                    ReplacedName = Table.ReplaceValue(
				                        ExpandedMetadataColumn.Publish,
				                        each [Name],
				                        each if [MetadataColumn.Publish.ButtonText] <> null then [MetadataColumn.Publish.ButtonText] else [Name], Text.Replace, {"Name"}),
				                    FilteredRows = Table.SelectRows(ReplacedName, each ([MetadataColumn.Publish.Category] <> null)),
				                    NewTableType = Value.ReplaceMetadata(Value.Type(FilteredRows), TableMetadata),
				                    TableWithMetadata = Value.ReplaceType(FilteredRows, NewTableType),
				                    FunctionsNavigationTable = Table.AddKey(TableWithMetadata, TableKey[Columns], TableKey[Primary]),
				                    MetadataType = Value.Type(FunctionsNavigationTable)meta
				                    [
				                        NavigationTable.NameColumn = "Name",
				                        NavigationTable.DataColumn = "Data",
				                        NavigationTable.ItemKindColumn = "ItemKind",
				                        Preview.DelayColumn = "ItemName",
				                        NavigationTable.IsLeafColumn = "IsLeaf"
				                    ],
				                    NavigationTable = Value.ReplaceType(FunctionsNavigationTable, MetadataType)
				                in
				                    NavigationTable,
				            Source = Uncategorize(Table.SelectRows(AIFunctions.Contents(), each [Key] = "CognitiveServices.TagImagesanytext"))
				        in
				            Source

	annotation PBI_ResultType = Table

