table 'Key Measures'
	lineageTag: 3a560f03-f748-418d-89cb-914f6ebbdc5b

	measure 'Total Sales' = ```
			
			SUMX( Sales , 
			    Sales[Order Quantity] * Sales[Unit Price] )
			```
		formatString: #,0.00
		lineageTag: c2d4867d-a835-4c8b-a70b-7f80f5cd3b6f

		changedProperty = FormatString

	measure 'Total Costs' = ```
			
			SUMX( Sales , 
			    Sales[Order Quantity] * Sales[Total Unit Cost] )
			```
		lineageTag: f98a3ba9-c937-4856-9e3e-a9453296001d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profits' = [Total Sales] - [Total Costs]
		lineageTag: f8ac1860-ca41-469c-9189-30ed87027a80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Profit Margin' = DIVIDE( [Total Profits] , [Total Sales] , 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c974e152-1266-4131-b256-ae10b3b055c2

		changedProperty = FormatString

	measure 'City Selected' = SELECTEDVALUE( Regions[City] , "All Cities" )
		lineageTag: 1e029531-aec9-4509-aa38-bf6ba6d202be

	measure 'Dynamic Sales' = ```
			
			CALCULATE( [Total Sales] , 
			    FILTER( Regions , Regions[City] = [City Selected] ) ,  
			    FILTER( Products , Products[Product Name] = [Products Selected] ) )
			```
		lineageTag: 49c5c4c6-eb85-45e7-b896-c579a797c772

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Products Selected' = ```
			SELECTEDVALUE( Products[Product Name] , "All Products" ) 
			```
		lineageTag: 5298958f-37a3-4580-9d62-4f6453c4eb98

	measure 'Product by Ranking' = ```
			
			CALCULATE( SELECTEDVALUE( Products[Product Name] , BLANK() ) ,
			    FILTER( VALUES( Products[Product Name] ) , 
			        RANKX( ALL( Products ) , [Total Sales] , , DESC ) = [Ranking Index Value] ) )
			```
		lineageTag: 111aa667-945c-470b-844d-f5af3a04bb63

	measure 'Product Sales' = ```
			
			CALCULATE( [Total Sales] , 
			    FILTER( VALUES( Products[Product Name] ) , 
			        Products[Product Name] = [Product by Ranking] ) )
			```
		lineageTag: 51751088-71f6-47c9-b20a-ef2b8d5a0870

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative Product Sales' = ```
			
			VAR IndexRank = [Ranking Index Value]
			
			RETURN
			IF( ISBLANK( [Total Sales] ) , 
			    BLANK() , 
			        SUMX( FILTER(
			            SUMMARIZE( Products , Products[Product Name] ,
			                "Sales" , [Total Sales] , 
			                "Sales Ranking" , RANKX( ALL( Products ) , [Total Sales] , , DESC ) ) , 
			                    [Sales Ranking] <= IndexRank ) , 
			                        [Sales] ) )
			```
		lineageTag: da0962ea-378e-4edc-b910-a991a143158f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Sales of All Time' = ```
			
			CALCULATE( MAXX( Sales , [Total Sales] ) , 
			    ALL( Dates[Date] ) )
			```
		lineageTag: 2e16bed2-323c-4359-a2aa-f2e3f76688e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'First Product Ever Purchased' = ```
			
			MAXX(
			    TOPN( 1 , 
			        SUMMARIZE( Sales , Dates[Date] , Products[Product Name] ) ,
			        CALCULATE( MIN( Dates[Date] ) ) , ASC ) , 
			            Products[Product Name] )
			```
		lineageTag: 75f519d0-a8da-4d12-893c-6ce85c419044

	measure 'Customer Rank - 1' =
			
			RANKX( ALL ( Customers[Customer Names] ) , [Total Sales] , , DESC , Dense )
		formatString: 0
		lineageTag: 9bace9ae-7a30-4e0e-89bd-e3f413d3e711

	measure 'Customer Rank - 2' =
			
			RANKX( ALL ( Sales[Customer Name] ) , [Total Sales] , , DESC , Dense )
		formatString: 0
		lineageTag: 344d9db8-dcee-471c-abff-30aad62bae5c

	measure Color =
			
			IF( [Total Sales] <= 100000 , "RED" , "GREEN" )
		lineageTag: 0c2bc9a2-b055-4d56-a05b-fff5aec7f624

	measure 'HEX Code' =
			
			IF( [Total Sales] <= 100000 , "#FF0000" , "#00FF00" )
		lineageTag: 240086a6-a930-42a5-8742-38e30bee4f38

	measure 'Average Sales' =
			
			AVERAGEX(
			    VALUES( Regions[City] ) , [Total Sales] )
		lineageTag: e23fb733-c15a-4792-994f-3674879d7138

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Sales L3M' = ```
			
			VAR SelectedStates = SELECTEDVALUE( Regions[City] )
			
			RETURN
			CALCULATE( 
			    AVERAGEX( VALUES( Regions[City] ) , [Total Sales] ) , 
			    DATEADD( Dates[Date] , -3 , MONTH ) , 
			    FILTER( ALLSELECTED( Regions ) , 
			        Regions[City] = SelectedStates ) )
			```
		lineageTag: 2578a407-3cf9-45f5-89df-488054b160f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Revenue' = ```
			
			MAXX(
			    VALUES( Dates[Month & Year] ) , 
			        [Total Sales] )
			```
		lineageTag: 131db08c-2e4a-45d6-a39f-fe4426bf3f96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Revenue In Month' = ```
			
			TOPN( 
			    1 , 
			    VALUES( Dates[Month & Year] ) , 
			    [Highest Revenue] , 
			    DESC )
			```
		lineageTag: 9743f6c7-f984-4207-9620-82d0b245e912

	measure 'Highest Revenue Heading' = ```
			
			VAR _Highest_Revenue = 
			MAXX(
			    VALUES( Dates[Month & Year] ) , 
			        [Total Sales] )
			
			VAR _Highest_Revenue_In_Month = 
			TOPN( 
			    1 , 
			    VALUES( Dates[Month & Year] ) , 
			    [Highest Revenue] , 
			    DESC )
			
			VAR _Results = 
			"The Highest Sales Is " & FORMAT( _Highest_Revenue , "$#,##0.00/-" ) & " In The Month Of " & _Highest_Revenue_In_Month
			
			RETURN
			_Results
			```
		lineageTag: ae07df0c-42fd-4a58-9553-7c3e0a317f4b

	measure 'Dyanmic Results' = ```
			
			SWITCH( TRUE() , 
			    SELECTEDVALUE( 'Metric Selection'[Metric] ) = "Total Sales" , [Total Sales] , 
			    SELECTEDVALUE( 'Metric Selection'[Metric] ) = "Total Costs" , [Total Costs] , 
			    SELECTEDVALUE( 'Metric Selection'[Metric] ) = "Total Profits" , [Total Profits] , 
			    SELECTEDVALUE( 'Metric Selection'[Metric] ) = "% Profit Margin" , 
			        IF( ISBLANK( [Total Sales] ) , BLANK() , FORMAT( [% Profit Margin] , "#,##0.00%" ) ) , 
			[Total Sales] )
			```
		lineageTag: 742e208d-086b-40c9-b7a0-6c87f8c06a75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales FY 2018' = ```
			
			CALCULATE( [Total Sales] ,
			    REMOVEFILTERS( Dates ) , 
			    KEEPFILTERS( 'Secondary Dates' ) , 
			    USERELATIONSHIP( Dates[Date] , 'Secondary Dates'[Date] ) , 
			    'Secondary Dates'[Fiscal Year] = "FY18" )
			```
		lineageTag: 9be59407-7837-45a6-97a7-b2f555d3b792

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Font = "Times"
		lineageTag: d726016e-e004-4df4-a8ca-ca22a2ad0b26

	measure Rank =
			IF(
			    SELECTEDVALUE(Sort[Name]) = "ASC",
			    SWITCH(
			        SELECTEDVALUE('Sort By'[Measure]),
			        "Territory", [Territory Rank],
			        "Sale", RANKX(ALLSELECTED(Regions[Territory]),[Total Sales],,ASC),
			        RANKX(ALLSELECTED(Regions[Territory]),[Total Sales],,ASC)
			    ),
			    SWITCH(
			        SELECTEDVALUE('Sort By'[Measure]),
			        "Territory", [Territory Rank DESC],
			        "Sale", RANKX(ALLSELECTED(Regions[Territory]),[Total Sales],,DESC),
			        RANKX(ALLSELECTED(Regions[Territory]),[Total Sales],,DESC)
			    )
			)
		formatString: 0
		lineageTag: 9f2b7379-f0cc-4a4b-a3ca-c7989f3fbc64

	measure 'Territory Rank' = ```
			
			VAR CurrentTer = SELECTEDVALUE(Regions[Territory])
			VAR Result = 
			    COUNTROWS(
			        FILTER(
			            ALL(Regions[Territory]),
			            Regions[Territory] <= CurrentTer
			        )
			    )
			RETURN Result
			```
		formatString: 0
		lineageTag: aed15087-248e-496d-b4ea-5e955996cf40

	measure 'Territory Rank DESC' = ```
			
			VAR CurrentTer = SELECTEDVALUE(Regions[Territory])
			VAR Result = 
			    COUNTROWS(
			        FILTER(
			            ALL(Regions[Territory]),
			            Regions[Territory] > CurrentTer
			        )
			    )
			RETURN Result
			```
		formatString: 0
		lineageTag: 2e2c9bf8-18ba-4ce8-85a5-68cf8db790a0

	measure SelectFont = SELECTEDVALUE(FontTheme[Theme])
		lineageTag: 31b1e666-5552-4bf9-ad06-f05a775d0bfb

	measure SelectColumnTheme = SELECTCOLUMNS(FontTheme,"Theme",FontTheme[Theme])
		lineageTag: ca90787d-c8a7-4a93-b266-7f26fe753e53

	measure 'Rank 2' =
			IF(
			    SELECTEDVALUE(Sort[Name]) = "ASC",
			        SWITCH(
			        SELECTEDVALUE('Sort By'[Measure]),
			        "Sale", [Total Sales],
			        [Territory Rank]),
			        SWITCH(
			        SELECTEDVALUE('Sort By'[Measure]),
			        "Sale",-[Total Sales],
			        -[Territory Rank])
			)
		lineageTag: fce39124-dea4-4b64-a9ff-02684cd3a1de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Key Measures-ddd18929-a687-473a-af07-657a53b0a5bc' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_Id = e4f8f4b9-9887-42fe-9139-565fa167f6dc

	annotation LinkedQueryName = Key Measures

	annotation PBI_ResultType = Table

