table 'Metric Selection'
	lineageTag: a94cd5c3-3b10-4a28-9766-0ec5e9415d92

	column Index
		dataType: int64
		formatString: 0
		lineageTag: d38d5181-b895-4ab1-977b-0bdb03604eef
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 962772b4-bf22-481b-b108-c8a42d4e1e55
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Metric Selection-d665437b-715b-4774-9d44-af28a21c0f7c' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJL0nMUQhOzEktVorViVYygos55xeXQMSM4WIBRflpmVBRE6CoKlREwTexKD0zTyk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Index", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

