table Products
	lineageTag: cb54c0ba-d512-4ded-9cd9-498e27a1ea12

	measure 'Totals Sales Lookup' = ```
			
			VAR SelectedProducts = SELECTEDVALUE( Sales[Product Description Index] )
			
			VAR Results = 
			CALCULATE( [Total Sales] ,
			    FILTER( Sales , 
			        Sales[Product Description Index] = SelectedProducts ) )
			
			RETURN
			Results        
			```
		lineageTag: 16750614-8a53-4e38-b02c-2d3ee2bd1dfe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 110fcb82-a42a-4ecc-8e4a-b34e8a906fc2
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 91425e7b-7352-435a-b770-c2fc5bb64384
		summarizeBy: none
		sourceColumn: Product Name
		sortByColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Total Sales' =
			
			CALCULATE( [Total Sales] )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fd5a4fb0-2287-4a13-a71d-230274cf8fdf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Products-2e26384b-6374-4cc1-9c10-95c0e7a7f8cc = m
		mode: import
		queryGroup: 'Data Model'
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\DOCUMENTS\DNA Enterprise\Financial Reporting Resources\Financial Reporting resource pack\Financial Dataset - Harsh.xlsx"), null, true),
				    Products_Data_Table = Source{[Item="Products_Data",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Products_Data_Table,{{"Index", Int64.Type}, {"Product Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_Id = efeaa416-1a9b-469a-a15a-87af4bb26f34

	annotation LinkedQueryName = Products

	annotation PBI_ResultType = Table

