table 'Ranking Index'
	lineageTag: b8f49e19-0e5a-453e-96e5-7cdae49c123a

	measure 'Ranking Index Value' = SELECTEDVALUE('Ranking Index'[Ranking Index])
		formatString: 0
		lineageTag: daa4fda5-1bf5-42d2-9aa6-0f5c5a262042

	column 'Ranking Index'
		formatString: 0
		lineageTag: 4f2c7e19-d33d-493c-9f40-00c8cee5e885
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Ranking Index-802d4b0f-c8e6-49b8-8dc4-bceac866087f' = calculated
		mode: import
		source = GENERATESERIES(1, 30, 1)

	annotation PBI_Id = 9f492de498654faa9e9383aa23246332

