table Regions
	lineageTag: 90195775-7fdf-4c18-9ab4-0acc85941f73

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 4fef739d-0f2a-4adc-8f60-9e9a0400bbf8
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6108c10c-c11b-478b-877b-7482b9428277
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 69d6b35c-689d-4905-b363-6632c7b1915f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 2bf0df2c-4f6f-45bf-92e9-db2cbbed6d2d
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: eef8824f-151f-406e-847f-445a16bd4215
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	partition Regions-c85e852a-aed7-4f72-a330-1fd87bdc848e = m
		mode: import
		queryGroup: 'Data Model'
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\DOCUMENTS\DNA Enterprise\Financial Reporting Resources\Financial Reporting resource pack\Financial Dataset - Harsh.xlsx"), null, true),
				    Regions_Table_Table = Source{[Item="Regions_Table",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Regions_Table_Table,{{"Index", Int64.Type}, {"City", type text}, {"Country", type text}, {"Territory", type text}, {"Full Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_Id = bc2c21b8-fe7b-4f67-8028-bd0934177543

	annotation LinkedQueryName = Regions

	annotation PBI_ResultType = Table

