table Sort
	lineageTag: 227d4687-ef84-420f-9279-a06c67d2e768

	column Name
		dataType: string
		lineageTag: a5715048-07c6-4f6e-9db5-147a7a7e9809
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column SortFullName
		dataType: string
		lineageTag: 46012e48-da8b-42a3-844d-ec66c62500c3
		summarizeBy: none
		sourceColumn: SortFullName

		annotation SummarizationSetBy = Automatic

	partition Sort = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcgx2VtJRSixOTs1LycxLV4rViVZyAYulpCIEYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, SortFullName = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

