table 'Territory Color'
	lineageTag: e8eca073-f3ea-43e8-97ac-f73cf16ded5a

	column Territory
		dataType: string
		lineageTag: f1dd30e2-a300-4456-bde3-594b06f8d266
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: e370da0f-1c20-4b9b-9edd-d895e24a3909
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	partition 'Territory Color' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VY49C4MwFEX/iqSrQ/NUTMdodCyUSh3EIbQPDKQR8kHpv69Jpq7nXO69y0Ku+Cnue/BbMUuNjpTk1EFXtS1Zy8Pu1m9oTTGhtcrv9hsDAgRl5xS4BUTjtDSvKIZmqFmVRO7kwXkrtZLRjnRsOEt2ku4tTcaU1lBBwg/1PDYyZi2/QMYzOh9P/Lf1ogdO1vUH", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Territory = _t, Color = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Territory", type text}, {"Color", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

