table Images
	lineageTag: 0aa9a571-e5fe-437f-876a-1d22a247a6af

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 3d7bd89a-0484-4106-96c4-0bef0f0202d8
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: a291af79-c8e3-4d76-ba6f-cbf6bfc089cd
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column 'Tag images.Tags'
		dataType: string
		lineageTag: bb55510d-c2f6-46db-be46-ddb68ec9e235
		summarizeBy: none
		sourceColumn: Tag images.Tags

		annotation SummarizationSetBy = Automatic

	column 'Tag images.Json'
		dataType: string
		lineageTag: 2c42eeb0-2692-43fa-9f56-cf69526ff2c3
		summarizeBy: none
		sourceColumn: Tag images.Json

		annotation SummarizationSetBy = Automatic

	column 'Tag images.Tag'
		dataType: string
		lineageTag: 53c6f6f6-7555-43ab-987d-e612f9c1c0f0
		summarizeBy: none
		sourceColumn: Tag images.Tag

		annotation SummarizationSetBy = Automatic

	column 'Tag images.Confidence'
		dataType: double
		lineageTag: 4d8989ba-5364-4c32-ac50-f0191a61a3da
		summarizeBy: sum
		sourceColumn: Tag images.Confidence

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tag images.ErrorMessage'
		dataType: string
		lineageTag: e1151630-fa2b-4e32-8296-fb458d59f3f6
		summarizeBy: none
		sourceColumn: Tag images.ErrorMessage

		annotation SummarizationSetBy = Automatic

	partition Images = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("1ZJNS8NAEIb/S8Gbm85+zewKQSrF9tKrIrXIJtm1kcTEfJD4722tIu29UGEOM++cHp53vZ5su65ub6bTuujbqH9v68K12yitymnd+DLvy5d6W3UV42gQLChlBQDTJBBTRCEd3n7EBp57AIFDLIB+dtd3VRyqpnTdIQh5F6dNVR+ufCzyJG4SpiKI5G+WZ/FKDuPqbSbD/M6sluPgFhaSTz48PWZFWI4mLB76/e97n13J+W4mm+s/krx0r/6U5cBA3BhprRSSOCOXuaB9llp0RwzckrpgBsGFkGZPQiz1ilRwHrw0/4mB7ySQAOTasNRl2iOR3pXrbF26P4cHrqUQ2ipkKjEeEpFwF/DEA16wBzRgDSpBWhGDhLQIijDL+EV0afMF", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [URL = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"URL", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "URL"}),
				    #"Applied Tag images" = AIFunctions.PostProcess(Table.AddColumn(#"Reordered Columns", "Tag images", each #"Tag images"([URL], null)), "Tag images", "CognitiveServices.TagImagesanytext") meta [FunctionBrowser="Vision"]
				in
				    #"Applied Tag images"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

