table 'Internal Audit'
	lineageTag: 65eb4697-a892-451b-8d1a-bac1843e932c

	column AUDIT_ID
		dataType: string
		lineageTag: ccd3db7a-bcfe-4b15-b9ac-f27135fe5f05
		summarizeBy: none
		sourceColumn: AUDIT_ID

		annotation SummarizationSetBy = Automatic

	column AUDIT_TOPIC
		dataType: string
		lineageTag: ff132388-5c8f-41be-8fc7-ee9c9fcd4371
		summarizeBy: none
		sourceColumn: AUDIT_TOPIC

		annotation SummarizationSetBy = Automatic

	column AUDIT_SUB_TOPIC
		dataType: string
		lineageTag: d5e296c9-ff4a-426c-a656-16e8fe0554c7
		summarizeBy: none
		sourceColumn: AUDIT_SUB_TOPIC

		annotation SummarizationSetBy = Automatic

	column OE_CODE
		dataType: string
		lineageTag: ca414492-ca29-4bce-bd68-9259a68fe46b
		summarizeBy: none
		sourceColumn: OE_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 4ed42a47-69c9-4be1-a977-3f14c721a299
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT
		dataType: string
		lineageTag: b71b7e1c-3b5e-48ee-ad8a-4a11ebf63284
		summarizeBy: none
		sourceColumn: CONTINENT

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 3b9c3991-8ce6-4934-ab25-5f969f229850
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: dd957143-d68d-41e5-9c32-34552bdf10ff
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: 3fd21038-7f59-477f-a8e4-5c5fb95cfbb2
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 68bd101e-ce28-4d7d-94df-7e0273adbed1
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: bf2a071a-45a6-41a6-b19a-a3e7c969410e
		summarizeBy: none
		sourceColumn: COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 165f0568-c370-4d2a-8dfd-2b8ee8a36564
		summarizeBy: sum
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column AUDIT_TYPE
		dataType: string
		lineageTag: 9cfbaa6a-82c2-494a-9551-aeb49f6fc317
		summarizeBy: none
		sourceColumn: AUDIT_TYPE

		annotation SummarizationSetBy = Automatic

	column FINDING_DESCRIPTION
		dataType: string
		lineageTag: 0320c3a3-6f7f-4579-8f91-97975cc422e4
		summarizeBy: none
		sourceColumn: FINDING_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column POTENTIAL_ROOT_CAUSE
		dataType: string
		lineageTag: 52066ced-7566-4ad3-b6d0-6d2bea830a83
		summarizeBy: none
		sourceColumn: POTENTIAL_ROOT_CAUSE

		annotation SummarizationSetBy = Automatic

	column RISK
		dataType: string
		lineageTag: 3b0f4bb5-d172-497e-90ad-e18190894458
		summarizeBy: none
		sourceColumn: RISK

		annotation SummarizationSetBy = Automatic

	column RISK_RATING
		dataType: string
		lineageTag: d544a251-2ab3-4f48-94c6-3232972ebf15
		summarizeBy: none
		sourceColumn: RISK_RATING

		annotation SummarizationSetBy = Automatic

	column RECOMMENDED_ACTION
		dataType: string
		lineageTag: 5fe06795-d896-4a91-8591-07692fe95e16
		summarizeBy: none
		sourceColumn: RECOMMENDED_ACTION

		annotation SummarizationSetBy = Automatic

	column ACTION_STATUS
		dataType: string
		lineageTag: 6c6f7d41-e92f-48d1-8905-e4088a6a7633
		summarizeBy: none
		sourceColumn: ACTION_STATUS

		annotation SummarizationSetBy = Automatic

	column CPCO_SELECTED_TOPICS
		dataType: string
		lineageTag: 098359c1-adc7-4bd4-a945-757898b55134
		summarizeBy: none
		sourceColumn: CPCO_SELECTED_TOPICS

		annotation SummarizationSetBy = Automatic

	column 'Extract key phrases of Findings'
		dataType: string
		lineageTag: afdd9d1b-2ba3-41dd-84a4-285f4fd64e29
		summarizeBy: none
		sourceColumn: Extract key phrases of Findings

		annotation SummarizationSetBy = Automatic

	column 'Extract key phrases of Recommendeds'
		dataType: string
		lineageTag: af9f2892-c9a9-466d-972b-b1ee778e1fa9
		summarizeBy: none
		sourceColumn: Extract key phrases of Recommendeds

		annotation SummarizationSetBy = Automatic

	column EXPORT_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 14e695c1-a666-4ba3-8ce2-9cf3747007e0
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		variation Variation
			isDefault
			relationship: 0c48a05e-1943-4285-971d-fe1af575b02d
			defaultHierarchy: LocalDateTable_84b9d356-e08b-4520-be70-6e3bca4d9d00.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Internal Audit' = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database("REDLake_ZeusP_OpsDevSup_CI.world", [HierarchicalNavigation=true, Query="
				    SELECT
				    *
				    FROM MARD_PCMS.X_IFR_BRAIN_EPIC7_INTERNAL_AUDIT
				    "]),
				    #"Applied Extract key phrases" = Table.AddColumn(Source, "Extract key phrases of Findings", 
				    each #"Extract key phrases"([FINDING_DESCRIPTION], "EN"))
				    meta [FunctionBrowser="TextAnalytics"],
				    #"Applied Extract key phrases Recommended Action" = Table.AddColumn(#"Applied Extract key phrases", "Extract key phrases of Recommendeds", 
				    each #"Extract key phrases"([RECOMMENDED_ACTION], "EN"))
				    meta [FunctionBrowser="TextAnalytics"]
				in
				    #"Applied Extract key phrases Recommended Action"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

