table TextAnalyticsFunctionBrowser1
	lineageTag: 0b26cc6a-7721-46cd-bf7a-bb6827000b6f

	column Name
		dataType: string
		lineageTag: ce5d46bf-bd15-4574-aac7-b50af325ca2b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 09630b61-21c2-46a9-83e9-b145d3f6aad3
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column ItemKind
		dataType: string
		lineageTag: 1c3ae40f-0c50-444d-8ae4-0474e3eb6395
		summarizeBy: none
		sourceColumn: ItemKind

		annotation SummarizationSetBy = Automatic

	column ItemName
		dataType: string
		lineageTag: 74363938-4247-440f-a93f-b597f8fa02dc
		summarizeBy: none
		sourceColumn: ItemName

		annotation SummarizationSetBy = Automatic

	column IsLeaf
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 25e17800-611b-49c6-9ad0-689902892e52
		summarizeBy: none
		sourceColumn: IsLeaf

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.Category'
		dataType: string
		lineageTag: f205fb80-d48d-4ac5-b279-5adc3d5b04bd
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.Category

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.Description'
		dataType: string
		lineageTag: 91eeeb02-933b-4061-8b8a-c0d7210ee20c
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.Description

		annotation SummarizationSetBy = Automatic

	column 'MetadataColumn.Publish.ButtonText'
		dataType: string
		lineageTag: 23dc5b27-8d77-40aa-9257-ae9536f9d161
		summarizeBy: none
		sourceColumn: MetadataColumn.Publish.ButtonText

		annotation SummarizationSetBy = Automatic

	partition TextAnalyticsFunctionBrowser1 = m
		mode: import
		source =
				let
				            Uncategorize = (functionTable as table) =>
				                let
				                    TableMetadata = Value.Metadata(Value.Type(functionTable)),
				                    TableKey = Table.Keys(functionTable){0},
				                    MetadataColumn = Table.AddColumn(functionTable, "MetadataColumn", each Value.Metadata([Data])),
				                    ExpandedMetadataColumn = Table.ExpandRecordColumn(MetadataColumn, "MetadataColumn", {"Publish"}, {"MetadataColumn.Publish"}),
				                    ExpandedMetadataColumn.Publish = Table.ExpandRecordColumn(
				                        ExpandedMetadataColumn,
				                        "MetadataColumn.Publish",
				                        {"Category", "Description", "ButtonText"},
				                        {"MetadataColumn.Publish.Category", "MetadataColumn.Publish.Description", "MetadataColumn.Publish.ButtonText"}),
				                    ReplacedName = Table.ReplaceValue(
				                        ExpandedMetadataColumn.Publish,
				                        each [Name],
				                        each if [MetadataColumn.Publish.ButtonText] <> null then [MetadataColumn.Publish.ButtonText] else [Name], Text.Replace, {"Name"}),
				                    FilteredRows = Table.SelectRows(ReplacedName, each ([MetadataColumn.Publish.Category] <> null)),
				                    NewTableType = Value.ReplaceMetadata(Value.Type(FilteredRows), TableMetadata),
				                    TableWithMetadata = Value.ReplaceType(FilteredRows, NewTableType),
				                    FunctionsNavigationTable = Table.AddKey(TableWithMetadata, TableKey[Columns], TableKey[Primary]),
				                    MetadataType = Value.Type(FunctionsNavigationTable)meta
				                    [
				                        NavigationTable.NameColumn = "Name",
				                        NavigationTable.DataColumn = "Data",
				                        NavigationTable.ItemKindColumn = "ItemKind",
				                        Preview.DelayColumn = "ItemName",
				                        NavigationTable.IsLeafColumn = "IsLeaf"
				                    ],
				                    NavigationTable = Value.ReplaceType(FunctionsNavigationTable, MetadataType)
				                in
				                    NavigationTable,
				            Source = Uncategorize(Table.SelectRows(AIFunctions.Contents(), each [Key] = "CognitiveServices.DetectLanguagetext" or [Key] = "CognitiveServices.ExtractKeyPhrasestexttext" or [Key] = "CognitiveServices.ScoreSentimenttexttext"))
				        in
				            Source

	annotation PBI_ResultType = Table

