table 'Training Rate'
	lineageTag: 953d0b3d-40e2-499c-9854-58cd976136e1

	column EXPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9fc96106-9f8e-4636-a9ec-12c59beeeb3b
		summarizeBy: none
		sourceColumn: EXPORT_DATE

		variation Variation
			isDefault
			relationship: c027eb30-6d1c-48d4-a663-faf4b31182e0
			defaultHierarchy: LocalDateTable_950cd768-2ca7-4070-901b-d43916d90250.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ITEM_ID
		dataType: string
		lineageTag: 601790a1-8fe1-493f-88c4-0acab7e4ab11
		summarizeBy: none
		sourceColumn: ITEM_ID

		annotation SummarizationSetBy = Automatic

	column ITEM_TITLE
		dataType: string
		lineageTag: a1529d74-6ebb-4a50-94cb-7ab5db05bc6c
		summarizeBy: none
		sourceColumn: ITEM_TITLE

		annotation SummarizationSetBy = Automatic

	column ITEM_TYPE
		dataType: string
		lineageTag: 70fe017a-8d67-4671-9c9f-5c34b015dde6
		summarizeBy: none
		sourceColumn: ITEM_TYPE

		annotation SummarizationSetBy = Automatic

	column ITEM_GROUP
		dataType: string
		lineageTag: 132fefa9-da9f-4a16-910e-d26d76af681a
		summarizeBy: none
		sourceColumn: ITEM_GROUP

		annotation SummarizationSetBy = Automatic

	column PREFIX_ID
		dataType: string
		lineageTag: 618df0e1-e855-4954-828d-089226c95fbc
		summarizeBy: none
		sourceColumn: PREFIX_ID

		annotation SummarizationSetBy = Automatic

	column PREFIX_TITLE
		dataType: string
		lineageTag: bded794a-dad6-4ed9-8915-84485272966f
		summarizeBy: none
		sourceColumn: PREFIX_TITLE

		annotation SummarizationSetBy = Automatic

	column ORG_AREA
		dataType: string
		lineageTag: 00285e0e-30a0-4b8c-924e-23048b10c125
		summarizeBy: none
		sourceColumn: ORG_AREA

		annotation SummarizationSetBy = Automatic

	column BU_EXTENDED
		dataType: string
		lineageTag: c2ba7c24-29ad-4345-8bbe-58d5ea4fc219
		summarizeBy: none
		sourceColumn: BU_EXTENDED

		annotation SummarizationSetBy = Automatic

	column DEPARTMENT
		dataType: string
		lineageTag: 408c3fa1-2bca-412a-8f0f-324332aabf97
		summarizeBy: none
		sourceColumn: DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column ORGANIZATION
		dataType: string
		lineageTag: 38fd8cfa-fb12-4310-a202-df2189092574
		summarizeBy: none
		sourceColumn: ORGANIZATION

		annotation SummarizationSetBy = Automatic

	column CONTINENT_CODE
		dataType: string
		lineageTag: 6efdd18d-1ad2-454c-825a-4a5dc95c025e
		summarizeBy: none
		sourceColumn: CONTINENT_CODE

		annotation SummarizationSetBy = Automatic

	column CONTINENT
		dataType: string
		lineageTag: b3056b9b-173a-402f-b400-03bbd3fb8225
		summarizeBy: none
		sourceColumn: CONTINENT

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP_CODE
		dataType: string
		lineageTag: 970471d1-9da4-4127-9f11-837735aa7880
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_GROUP
		dataType: string
		lineageTag: 302f568b-af08-4865-a462-a5341401d6a9
		summarizeBy: none
		sourceColumn: COUNTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: a3a4fcd9-b3de-441b-a559-dc6f166fdd02
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 5cd0b48a-8d79-48a6-96c2-3fc9740b92e5
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_DISPLAY_TEXT
		dataType: string
		lineageTag: d42ba0b8-94b5-4429-ba9a-283e97c7d63d
		summarizeBy: none
		sourceColumn: COUNTRY_DISPLAY_TEXT

		annotation SummarizationSetBy = Automatic

	column ASS_OVERALL
		dataType: int64
		formatString: 0
		lineageTag: 1558e572-b90a-4ae5-ae91-7430cc5e083b
		summarizeBy: sum
		sourceColumn: ASS_OVERALL

		annotation SummarizationSetBy = Automatic

	column ASS_COMPLETED
		dataType: int64
		formatString: 0
		lineageTag: beea003e-985e-4f6a-8777-b9dfaea53a6e
		summarizeBy: sum
		sourceColumn: ASS_COMPLETED

		annotation SummarizationSetBy = Automatic

	column ASS_COMPLETED_PCT
		dataType: double
		lineageTag: 422e2695-7455-4c98-ac94-681f89c023db
		summarizeBy: sum
		sourceColumn: ASS_COMPLETED_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASS_COMPLETED_QUOTIENT
		dataType: double
		lineageTag: f8ed553e-aa61-46e4-aa43-d1ba4c73bf53
		summarizeBy: sum
		sourceColumn: ASS_COMPLETED_QUOTIENT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASS_STILL_DUE
		dataType: int64
		formatString: 0
		lineageTag: 4d2c7f0d-c1c6-478c-abaf-e49ac2138335
		summarizeBy: sum
		sourceColumn: ASS_STILL_DUE

		annotation SummarizationSetBy = Automatic

	column ASS_STILL_DUE_PCT
		dataType: double
		lineageTag: 950a478a-7592-4c63-a99c-cf2440af5788
		summarizeBy: sum
		sourceColumn: ASS_STILL_DUE_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASS_STILL_DUE_QUOTIENT
		dataType: double
		lineageTag: 635591a2-029f-46d9-844e-b11cca372212
		summarizeBy: sum
		sourceColumn: ASS_STILL_DUE_QUOTIENT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASS_OVERDUE
		dataType: int64
		formatString: 0
		lineageTag: a6c906e9-1e65-4481-8141-17aaf2737529
		summarizeBy: sum
		sourceColumn: ASS_OVERDUE

		annotation SummarizationSetBy = Automatic

	column ASS_OVERDUE_PCT
		dataType: double
		lineageTag: f8266df9-c728-43ed-b6e5-15edea86605f
		summarizeBy: sum
		sourceColumn: ASS_OVERDUE_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASS_OVERDUE_QUOTIENT
		dataType: double
		lineageTag: f52d269f-022d-459e-bf8b-7793e5edc882
		summarizeBy: sum
		sourceColumn: ASS_OVERDUE_QUOTIENT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_OVERDUE_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 67c8e784-11f3-46a9-88f7-a8aae3203bfc
		summarizeBy: sum
		sourceColumn: TOTAL_OVERDUE_DAYS

		annotation SummarizationSetBy = Automatic

	column EARLIEST_REQUIRED_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 5db0ca16-dbaf-4a31-87a3-e2d9ebeaae53
		summarizeBy: none
		sourceColumn: EARLIEST_REQUIRED_DATE

		variation Variation
			isDefault
			relationship: 2aff948f-798f-4ef6-99b5-4ff8eecd23d8
			defaultHierarchy: LocalDateTable_35f04e6c-7913-41ab-b059-11e258065d65.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LATEST_REQUIRED_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 1aa6d3e8-9686-44b9-a86c-ef0feb3c7499
		summarizeBy: none
		sourceColumn: LATEST_REQUIRED_DATE

		variation Variation
			isDefault
			relationship: 4d118f01-e96a-43ff-9121-ad29f4b79c11
			defaultHierarchy: LocalDateTable_05b0ae39-7edd-43c4-b3ef-c441e7b3afde.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SHORTEST_OVERDUE_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 3f528543-cd53-4740-91b2-9b343a78b99c
		summarizeBy: sum
		sourceColumn: SHORTEST_OVERDUE_DAYS

		annotation SummarizationSetBy = Automatic

	column LONGEST_OVERDUE_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 11700440-1321-4be9-ab05-704081133320
		summarizeBy: sum
		sourceColumn: LONGEST_OVERDUE_DAYS

		annotation SummarizationSetBy = Automatic

	column BE_MASKED
		dataType: int64
		formatString: 0
		lineageTag: 9651144c-ac03-409f-ba09-f22daeead783
		summarizeBy: sum
		sourceColumn: BE_MASKED

		annotation SummarizationSetBy = Automatic

	partition 'Training Rate' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bosch-my.sharepoint.com/personal/dmo5hc_bosch_com/Documents/XAB3_TEAM/OTHERS/TRAINING_RATE_17032025.xlsx"), null, true),
				    #"Export Worksheet1" = Source{[Name="Export Worksheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Export Worksheet1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EXPORT_DATE", type date}, {"ITEM_ID", type text}, {"ITEM_TITLE", type text}, {"ITEM_TYPE", type text}, {"ITEM_GROUP", type text}, {"PREFIX_ID", type text}, {"PREFIX_TITLE", type text}, {"ORG_AREA", type text}, {"BU_EXTENDED", type text}, {"DEPARTMENT", type text}, {"ORGANIZATION", type text}, {"CONTINENT_CODE", type text}, {"CONTINENT", type text}, {"COUNTRY_GROUP_CODE", type text}, {"COUNTRY_GROUP", type text}, {"COUNTRY", type text}, {"COUNTRY_ISO_CODE", type text}, {"COUNTRY_DISPLAY_TEXT", type text}, {"ASS_OVERALL", Int64.Type}, {"ASS_COMPLETED", Int64.Type}, {"ASS_COMPLETED_PCT", type number}, {"ASS_COMPLETED_QUOTIENT", type number}, {"ASS_STILL_DUE", Int64.Type}, {"ASS_STILL_DUE_PCT", type number}, {"ASS_STILL_DUE_QUOTIENT", type number}, {"ASS_OVERDUE", Int64.Type}, {"ASS_OVERDUE_PCT", type number}, {"ASS_OVERDUE_QUOTIENT", type number}, {"TOTAL_OVERDUE_DAYS", Int64.Type}, {"EARLIEST_REQUIRED_DATE", type datetime}, {"LATEST_REQUIRED_DATE", type datetime}, {"SHORTEST_OVERDUE_DAYS", Int64.Type}, {"LONGEST_OVERDUE_DAYS", Int64.Type}, {"BE_MASKED", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

