table _MEASURE
	lineageTag: 086aec73-9bb4-457f-b4e1-d4580a28d365

	measure 'Overview text' = "Overview"
		displayFolder: _TEXTS & LABELS
		lineageTag: cdfd52b4-8b30-41fc-a4c4-c387291f32b7

	measure COUNT_PC_CHECK = DISTINCTCOUNT ( E10_PC_CHECKS[RID] )
		formatString: 0
		lineageTag: bb82a94f-a939-4b0d-bf7f-19a6a4d2a73b

	measure 'Rating text' = "PC Checks Rating"
		displayFolder: _TEXTS & LABELS
		lineageTag: c271dd91-739f-4fd3-abe1-b410989fc324

	measure 'Risk text' = "Risk Categories"
		displayFolder: _TEXTS & LABELS
		lineageTag: dc98fcff-64cd-4580-8cee-4eddce5fd4ee

	measure 'Measurement text' = "Measures"
		displayFolder: _TEXTS & LABELS
		lineageTag: 1c315ade-f4a2-4b7c-8f35-760bd942fcec

	measure 'OE&project text' = "OE & Projects"
		displayFolder: _TEXTS & LABELS
		lineageTag: 5c5a0679-1811-481e-90ec-018c10a88946

	measure prefill-label = ```
			"Pre-fill (" & [Prefill] & ")" 
			```
		displayFolder: _TEXTS & LABELS
		lineageTag: 1b917cd8-002a-481d-ba02-1032e4e44d87

	measure Prefill = CALCULATE ( [COUNT_PC_CHECK], E10_PC_CHECKS[PC_CHECK_STATUS] = "pre-fill" ) + 0
		formatString: 0
		lineageTag: a15f3ff6-0899-4da8-86cc-378f0672fe95

	measure 'In Approval' = CALCULATE ( [COUNT_PC_CHECK], E10_PC_CHECKS[PC_CHECK_STATUS] = "in approval" ) + 0
		formatString: 0
		lineageTag: b313cbfe-3166-4eb6-9d27-1875960d6d68

	measure 'in approval-label' = "In Approval (" & [In Approval] & ")"
		displayFolder: _TEXTS & LABELS
		lineageTag: a30685aa-4233-4427-90cb-a40e21665d16

	measure 'In Progress' = CALCULATE ( [COUNT_PC_CHECK], E10_PC_CHECKS[PC_CHECK_STATUS] = "in progress" ) + 0
		formatString: 0
		lineageTag: ab8694b6-6fe8-4f4e-bde6-153ba296cee4

	measure 'in progress-label' = ```
			"In Progress (" & [In Progress] & ")" 
			```
		displayFolder: _TEXTS & LABELS
		lineageTag: 9694bf65-3c7b-418c-8b08-67445079c351

	measure 'In Review' = CALCULATE ( [COUNT_PC_CHECK], E10_PC_CHECKS[PC_CHECK_STATUS] = "in review" ) + 0
		formatString: 0
		lineageTag: 2941ce10-e353-4fbc-83dd-820ad800ef48

	measure 'in review-label' = ```
			"In Review (" & [In Review] & ")" 
			```
		displayFolder: _TEXTS & LABELS
		lineageTag: 99c363ab-9009-4941-84e0-fd041897d2c0

	measure Approved = CALCULATE ( [COUNT_PC_CHECK], E10_PC_CHECKS[PC_CHECK_STATUS] = "approved" ) + 0
		formatString: 0
		lineageTag: 6a448ae4-b6bb-4f58-8cb4-ca4feea07e07

	measure approved-label = ```
			"Approved (" & [Approved] & ")" 
			```
		displayFolder: _TEXTS & LABELS
		lineageTag: a3a89342-51ed-4ec7-96fe-92cfe6473453

	measure 'OE Selected filter' =
			IF (
			    ISFILTERED ( E10_PC_CHECKS[OE] ),
			    CONCATENATEX (
			        VALUES ( E10_PC_CHECKS[OE] ),
			        E10_PC_CHECKS[OE],
			        ", ",
			        E10_PC_CHECKS[OE]
			    ),
			    "All"
			)
		lineageTag: 2a728d49-a60d-4e49-9368-5cbb35950484

	measure 'BU Selected filter' =
			IF (
			    ISFILTERED ( E10_PC_CHECKS[BU_CODE] ),
			    CONCATENATEX (
			        VALUES ( E10_PC_CHECKS[BU_CODE] ),
			        E10_PC_CHECKS[BU_CODE],
			        ", ",
			        E10_PC_CHECKS[BU_CODE]
			    ),
			    "All"
			)
		lineageTag: 7d3e94f4-4b1a-4818-967b-e90df446702d

	measure 'Country Selected filter' =
			IF (
			    ISFILTERED ( E10_DIM_REGION[COUNTRY_DISPLAY_TEXT] ),
			    CONCATENATEX (
			        VALUES ( E10_DIM_REGION[COUNTRY_DISPLAY_TEXT] ),
			        E10_DIM_REGION[COUNTRY_DISPLAY_TEXT],
			        ", ",
			        E10_DIM_REGION[COUNTRY_DISPLAY_TEXT]
			    ),
			    "All"
			)
		lineageTag: 568fe372-d5d9-41aa-8b63-378a75c7a3aa

	measure 'Region Selected filter' =
			IF (
			    ISFILTERED ( E10_DIM_REGION[CONTINENT] ),
			    CONCATENATEX (
			        VALUES ( E10_DIM_REGION[CONTINENT] ),
			        E10_DIM_REGION[CONTINENT],
			        ", ",
			        E10_DIM_REGION[CONTINENT]
			    ),
			    "All"
			)
		lineageTag: a2da532f-5b5d-40b2-9a65-0202e370031a

	measure Coverage = ```
			
			    DIVIDE (
			        CALCULATE (
			            COUNTROWS(
			                FILTER ( VALUES ( E10_DIM_REGION[CONTINENT] ), CALCULATE ( [COUNT_PC_CHECK] ) > 0 && E10_DIM_REGION[CONTINENT]<>BLANK() )
			            )
			    ),
			        CALCULATE (
			            COUNTROWS(VALUES(E10_DIM_REGION[CONTINENT]) ),
			            ALLSELECTED ( E10_DIM_REGION ),
			            E10_DIM_REGION[CONTINENT]<>BLANK()
			        )
			    )
			```
		formatString: 0%;-0%;0%
		lineageTag: ad4f194b-a545-41c1-8668-ab6d8c156799

	measure NotCovered =
			
			VAR ZeroProjectRegions =
			    FILTER(
			        VALUES ( E10_DIM_REGION[CONTINENT] ),
			        CALCULATE ( [COUNT_PC_CHECK] ) = 0 && E10_DIM_REGION[CONTINENT]<>BLANK()
			    )
			VAR RegionList =
			    CONCATENATEX ( ZeroProjectRegions, E10_DIM_REGION[CONTINENT], ", " )
			RETURN
			    IF ( ISBLANK ( RegionList ) || LEN ( RegionList ) = 0, "None", RegionList )
		lineageTag: 5c22b255-8511-40c7-a8ed-2a3727551faa

	measure RegionsWithProjects =
			CALCULATE (
			    COUNTROWS (
			        FILTER (
			            VALUES ( E10_DIM_REGION[CONTINENT] ),
			            CALCULATE ( [COUNT_PC_CHECK] ) > 0
			        )
			    )
			)
		formatString: 0
		lineageTag: 8193619b-7a34-4996-815c-61bfc41f8aa1

	measure COUNT_PC_CHECK_APPROVED =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    E10_PC_CHECKS[PC_CHECK_STATUS] = "approved",
			    USERELATIONSHIP ( E10_DIM_DATE[FullDateAlternateKey], E10_PC_CHECKS[RESOLUTION_DATE] )
			)
		formatString: 0
		lineageTag: f5758ddd-a13e-4ff9-9af6-f2df57746724

	measure COUNT_PC_CHECK_INPROGRESS =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    E10_PC_CHECKS[PC_CHECK_STATUS] = "In Progress",
			    USERELATIONSHIP ( E10_DIM_DATE[FullDateAlternateKey], E10_PC_CHECKS[INPROGRESS_DATE] )
			)
		formatString: 0
		lineageTag: e43200ed-bd47-45c9-a587-c19dd0519fbd

	measure COUNT_PC_CHECK_PLUS0 = [COUNT_PC_CHECK] + 0
		formatString: 0
		lineageTag: 050c3f7c-7d0d-4050-a3db-28f61d9030e0

	measure COUNT_PC_CHECK_PER_REGION_COLOR = IF ( [COUNT_PC_CHECK_PER_REGION] > 0, "#007BC0", "#D64554" )
		lineageTag: 550d7883-91f8-445a-9cfe-6e840f0856da

	measure COUNT_PC_CHECK_PER_REGION =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    SUMMARIZECOLUMNS ( E10_DIM_REGION[CONTINENT] ),
			    ALLSELECTED ( E10_DIM_REGION[COUNTRY_DISPLAY_TEXT] )
			) + 0
		formatString: 0
		lineageTag: 4723dd6e-0f38-4f85-b9f3-ad5d4cb84d38

	measure PRESET_FILTER_PC_CHECK_YEAR =
			VAR FILTER_PC_YEAR_TABLE =
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			    )
			VAR START_POINT =
			    DATE ( YEAR (
			        CALCULATE (
			            [MIN_DATE_PC_CHECK],
			            ALLSELECTED ( E10_DIM_DATE ),
			            FILTER_PC_YEAR_TABLE
			        )
			    ), 01, 01 )
			VAR MAX_PC_CHECK_YEAR =
			    YEAR (
			        CALCULATE (
			            [MAX_DATE_PC_CHECK],
			            ALLSELECTED ( E10_DIM_DATE ),
			            FILTER_PC_YEAR_TABLE
			        )
			    )
			VAR PC_CHECK_YEAR =
			    CALCULATE (
			        MAX ( E10_PC_CHECKS[PC_CHECK_YEAR] ),
			        ALLSELECTED ( E10_DIM_DATE ),
			        FILTER_PC_YEAR_TABLE
			    )
			VAR END_POINT =
			    IF (
			        MAX_PC_CHECK_YEAR > YEAR ( START_POINT ),
			        CALCULATE (
			            [MAX_DATE_PC_CHECK],
			            ALLSELECTED ( E10_DIM_DATE ),
			            FILTER_PC_YEAR_TABLE
			        ),
			            IF(
			                YEAR(TODAY()) <= YEAR ( START_POINT ) && MONTH(TODAY())>= 10,
			                EOMONTH(DATE ( YEAR ( START_POINT ), 12, 31 ),3),
			                DATE ( YEAR ( START_POINT ), 12, 31 )
			            )
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        AND (
			            START_POINT <= MAX ( E10_DIM_DATE[FullDateAlternateKey] ),
			            MIN ( E10_DIM_DATE[FullDateAlternateKey] ) <= END_POINT
			        ), 1,
			        0
			    )
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 1ec6ab90-359f-44c5-a563-e8e3666e13ba

	measure REFERENCE_OVERLAY_FUTURE_TIME =
			IF (
			    EOMONTH ( TODAY (), 0 ) < MAX ( E10_DIM_DATE[FullDateAlternateKey] ),
			    9999,
			    BLANK ()
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: efae67b1-6c5f-403a-acb7-2ab99fa23aa5

	measure COUNT_PC_CHECK_PREFILL_OVER_TIME =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && AND (
			                E10_PC_CHECKS[CREATED_DATE]
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INPROGRESS_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INPROGRESS_DATE]
			                )
			                    > EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 029c0065-cbdc-4dba-b82f-5ca6928326a6

	measure COUNT_PC_CHECK_INPROGRESS_OVER_TIME =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INPROGRESS_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INPROGRESS_DATE]
			                )
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INREVIEW_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INREVIEW_DATE]
			                )
			                    > EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 6988fe89-ca37-4f26-a6c2-adc73908bfc5

	measure COUNT_PC_CHECK_INREVIEW_OVER_TIME =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INREVIEW_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INREVIEW_DATE]
			                )
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INAPPROVAL_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INAPPROVAL_DATE]
			                )
			                    > EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 6742f307-a04f-4273-9544-7f370301046f

	measure COUNT_PC_CHECK_INAPPROVAL_OVER_TIME =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[INAPPROVAL_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[INAPPROVAL_DATE]
			                )
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[RESOLUTION_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[RESOLUTION_DATE]
			                )
			                    > EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 577d2d80-5baa-45a8-99c0-4f9cf5dbc4d3

	measure COUNT_PC_CHECK_APRROVED_OVER_TIME =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && AND (
			                IF (
			                    ISBLANK ( E10_PC_CHECKS[RESOLUTION_DATE] ),
			                    EOMONTH ( TODAY (), 1 ),
			                    E10_PC_CHECKS[RESOLUTION_DATE]
			                )
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( TODAY (), 1 )
			                    > EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			    )
			)
		displayFolder: PC_OVERTIME
		lineageTag: 2786196d-80a5-45f7-b05c-62cd6ae21a5d

	measure MAX_DATE_PC_CHECK =
			MAXX (
			    {
			        MAX ( E10_PC_CHECKS[CREATED_DATE] ),
			        MAX ( E10_PC_CHECKS[INPROGRESS_DATE] ),
			        MAX ( E10_PC_CHECKS[INREVIEW_DATE] ),
			        MAX ( E10_PC_CHECKS[INAPPROVAL_DATE] ),
			        MAX ( E10_PC_CHECKS[RESOLUTION_DATE] )
			    },
			    [Value]
			)
		formatString: General Date
		displayFolder: PC_OVERTIME
		lineageTag: e5ee3cfb-dced-41c1-a296-e696010d9c48

	measure MIN_DATE_PC_CHECK =
			MINX (
			    {
			        MIN ( E10_PC_CHECKS[CREATED_DATE] ),
			        MIN ( E10_PC_CHECKS[INPROGRESS_DATE] ),
			        MIN ( E10_PC_CHECKS[INREVIEW_DATE] ),
			        MIN ( E10_PC_CHECKS[INAPPROVAL_DATE] ),
			        MIN ( E10_PC_CHECKS[RESOLUTION_DATE] )
			    },
			    [Value]
			)
		formatString: General Date
		displayFolder: PC_OVERTIME
		lineageTag: 90d75102-1149-4576-af07-82ffed55cd85

	measure MAX_COUNT_PC_CHECK = MAXX ( ALLSELECTED ( E10_PC_CHECKS[PC_CHECK_YEAR] ), [COUNT_PC_CHECK_PLUS0] ) + 1
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: c24b01f8-1d69-450f-a4d5-a449b9b0f4b1

	measure COUNT_PC_CHECK_APPROVED_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                E10_PC_CHECKS[END_DATE_PLUS35]
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                TRUE ()
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 43e2876c-0111-4b18-8543-eef23079d050

	measure COUNT_PC_CHECK_INAPPROVAL_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && ISBLANK ( E10_PC_CHECKS[RESOLUTION_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E10_PC_CHECKS[END_DATE_PLUS35] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                E10_PC_CHECKS[END_DATE_PLUS7]
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ) < E10_PC_CHECKS[END_DATE_PLUS35]
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: c44babf7-0483-405e-992e-2323f22e151e

	measure COUNT_PC_CHECK_INPROGRESS_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && ISBLANK ( E10_PC_CHECKS[INREVIEW_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E10_PC_CHECKS[END_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                E10_PC_CHECKS[START_DATE]
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ) < E10_PC_CHECKS[END_DATE]
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 249c341f-1e22-4141-af0e-0a8b86ba6f4a

	measure COUNT_PC_CHECK_INREVIEW_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && ISBLANK ( E10_PC_CHECKS[INAPPROVAL_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 ) < E10_PC_CHECKS[END_DATE_PLUS7]
			                    && (
			                        EOMONTH ( TODAY (), 0 )
			                            < EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			                    )
			                    && AND (
			                        E10_PC_CHECKS[END_DATE]
			                            <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                        EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ) < E10_PC_CHECKS[END_DATE_PLUS7]
			                    )
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 944fa4c6-6a66-47f3-a0d3-d2cb4fd76d92

	measure COUNT_PC_CHECK_PREFILL_OVER_TIME_FUTURE =
			CALCULATE (
			    [COUNT_PC_CHECK],
			    FILTER (
			        ALLSELECTED ( E10_PC_CHECKS ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            = SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			                - MAX ( 'E10_PARA_PREVIOUS_YEAR_TBL'[Para_Previous_Year] )
			            && ISBLANK ( E10_PC_CHECKS[INPROGRESS_DATE] )
			            && ( EOMONTH ( TODAY (), 0 ) < E10_PC_CHECKS[START_DATE] )
			            && (
			                EOMONTH ( TODAY (), 0 )
			                    < EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 )
			            )
			            && AND (
			                EOMONTH ( TODAY (), 1 )
			                    <= EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ),
			                EOMONTH ( MAX ( E10_DIM_DATE[FullDateAlternateKey] ), 0 ) < E10_PC_CHECKS[START_DATE]
			            )
			    )
			)
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: aadfe553-9172-4c7d-ae9e-bdd91d939a79

	measure PC_OVERTIME_YEARVIEW_TITLE =
			"PC Check: "
			    & (
			        SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] )
			            - MAX ( E10_PARA_PREVIOUS_YEAR_TBL[Para_Previous_Year] )
			    )
		displayFolder: PC_OVERTIME
		lineageTag: a8e9bb16-becd-48eb-ac53-955f7069f593

	measure MAX_COUNT_PC_CHECK_YEARVIEW =
			MAXX (
			    FILTER (
			        ALL ( E10_PC_CHECKS[PC_CHECK_YEAR] ),
			        E10_PC_CHECKS[PC_CHECK_YEAR]
			            IN {
			                SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] ) - 0,
			                SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] ) - 1,
			                SELECTEDVALUE ( E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR] ) - 2
			            }
			    ),
			    [COUNT_PC_CHECK_PLUS0]
			) + 1
		formatString: 0
		displayFolder: PC_OVERTIME
		lineageTag: 9d67ab23-aeb1-4326-b2b0-3396a0693c68

	measure 'COUNT F' =
			CALCULATE (
			    [COUNT RATING],
			    FILTER ( E10_PC_CHECKS, E10_PC_CHECKS[RATING] = "F" )
			)
		formatString: 0
		displayFolder: Ratings
		lineageTag: 9154d1f0-9700-440f-b416-5e274e4e0846

	measure 'COUNT P' =
			CALCULATE (
			    [COUNT RATING],
			    FILTER ( E10_PC_CHECKS, E10_PC_CHECKS[RATING] = "P" )
			)
		formatString: 0
		displayFolder: Ratings
		lineageTag: b9f33a84-02e4-4900-87c5-e4c0e035adc1

	measure 'COUNT L' =
			CALCULATE (
			    [COUNT RATING],
			    FILTER ( E10_PC_CHECKS, E10_PC_CHECKS[RATING] = "L" )
			)
		formatString: 0
		displayFolder: Ratings
		lineageTag: 8db786ae-7419-4809-aaa9-77ae7c9fa1b7

	measure 'COUNT N' =
			CALCULATE (
			    [COUNT RATING],
			    FILTER ( E10_PC_CHECKS, E10_PC_CHECKS[RATING] = "N" )
			)
		formatString: 0
		displayFolder: Ratings
		lineageTag: af40b8a2-fd02-4367-91e9-6d241ed17b07

	measure '% F rating' = [COUNT F]/[COUNT RATING]
		displayFolder: Ratings
		lineageTag: 74b76c13-0778-4bd4-bcdf-68215a38d087

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% L rating' = [COUNT L]/[COUNT RATING]
		displayFolder: Ratings
		lineageTag: b68325b8-1e50-4ac7-b9a4-77ebe0b2771b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% P rating' = [COUNT P]/[COUNT RATING]
		displayFolder: Ratings
		lineageTag: aa102ccb-d78c-4597-9807-3352f9bce075

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% N rating' = [COUNT N]/[COUNT RATING]
		displayFolder: Ratings
		lineageTag: 804bfe0d-382a-48f4-9727-d094e0374722

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COUNT ALL' = ```
			
			    IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			    CALCULATE([COUNT RATING],
			    ALL (E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question] )
			    ),
			    CALCULATE([COUNT RATING],
			    ALL (E10_PC_CHECKS[OE]
			    , E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question]
			    , E10_PC_CHECKS[PC_CHECK_YEAR_QUESION_ID], E10_PC_CHECKS[Number of question]
			    )
			    ))
			```
		formatString: 0
		displayFolder: Ratings
		lineageTag: a0bf2cde-8349-433f-b932-c77c7e0d5599

	measure 'DELTA L' =
			
			VAR countrating =
			    IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			    CALCULATE ([COUNT L],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question] )),
			    CALCULATE ([COUNT L],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question], E10_PC_CHECKS[PC_CHECK_YEAR_QUESION_ID] ))
			    )
			VAR percentage = countrating / [COUNT ALL]
			VAR delta = [% L rating] - percentage
			RETURN
			    delta
		formatString: 0.00
		displayFolder: Ratings
		lineageTag: dc67d189-9d42-4ffd-a57e-7692f4f2a3d2

	measure 'DELTA P' =
			
			VAR countrating =
			    IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			    CALCULATE ([COUNT P],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question] )),
			    CALCULATE ([COUNT P],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question], E10_PC_CHECKS[PC_CHECK_YEAR_QUESION_ID]))
			    )
			VAR percentage = countrating / [COUNT ALL]
			VAR delta = [% P rating] - percentage
			RETURN
			    delta
		formatString: 0.00
		displayFolder: Ratings
		lineageTag: 395929ae-935c-42e8-b228-790ed554a5e3

	measure 'DELTA N' =
			
			VAR countrating =
			    IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			    CALCULATE ([COUNT N],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question] )),
			    CALCULATE ([COUNT N],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question], E10_PC_CHECKS[PC_CHECK_YEAR_QUESION_ID]))
			    )
			VAR percentage = countrating / [COUNT ALL]
			VAR delta = [% N rating] - percentage
			RETURN
			    delta
		formatString: 0.00
		displayFolder: Ratings
		lineageTag: e3c278a9-d90f-4606-9eaa-36838616b816

	measure 'RATING NUMBER' =
			
			VAR DeltaF = [DELTA F]
			VAR DeltaN = [DELTA N]
			VAR DeltaP = [DELTA P]
			VAR DeltaL = [DELTA L]
			
			VAR WeightedSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP * 2 )
			        + IF ( DeltaL < 0, 0, DeltaL * 3 )
			        + IF ( DeltaF < 0, 0, DeltaF * 4 )
			VAR TotalSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP )
			        + IF ( DeltaL < 0, 0, DeltaL )
			        + IF ( DeltaF < 0, 0, DeltaF )
			VAR result =
			    IF ([COUNT RATING]=0,
			        0,
			        ROUND ( IFERROR ( WeightedSum / TotalSum, 4 ), 0 )
			    )
			RETURN
			    result
		formatString: 0
		displayFolder: Ratings
		lineageTag: 3e746caf-3f25-4eee-9c91-089c45ecda5f

	measure RatingComparison =
			VAR selectedyear =
			    SELECTEDVALUE ( E10_PC_CHECKS[PC_CHECK_YEAR] )
			VAR CurrentYearRatingValue = [RATING NUMBER]
			VAR CurrentYearRating = [RATING]
			VAR PreviousYearRatingValue = [PY RATING NUMBER]
			VAR RankDifference = CurrentYearRatingValue - PreviousYearRatingValue
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( selectedyear ) || ISBLANK ( CurrentYearRatingValue ), BLANK (),
			        PreviousYearRatingValue=0 || CurrentYearRatingValue = 0, "∅",
			        RankDifference = 1, "↗",
			        RankDifference = 2, "↗↗",
			        RankDifference = 3, "↗↗↗",
			        RankDifference = 4, "↗↗↗↗",
			        RankDifference = 0, "(=)",
			        RankDifference = -1, "↘",
			        RankDifference = -2, "↘↘",
			        RankDifference = -3, "↘↘↘",
			        RankDifference = -4, "↘↘↘↘"
			    )
			RETURN
			    Result
		displayFolder: Ratings
		lineageTag: 38f828e0-f0ef-402b-a0d9-54bbf4f257ec

	measure 'PY RATING NUMBER' = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E10_PC_CHECKS, E10_PC_CHECKS[RATING]
			            ,  E10_PC_CHECKS[OE], E10_PC_CHECKS[BU_CODE], E10_PC_CHECKS[COUNTRY_ISO_CODE])
			            , E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) && 
			            RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = SELECTEDVALUE(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS, E10_PC_CHECKS[RATING]
			            , E10_PC_CHECKS[OE], E10_PC_CHECKS[BU_CODE], E10_PC_CHECKS[COUNTRY_ISO_CODE])
			            , E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]))
			            
			var checknull = IF(ISINSCOPE(E10_DIM_QUESTION[TOPIC_NAME]), CALCULATE ([COUNT F] ,prevtopic), CALCULATE([COUNT F], totalpre))
			
			VAR DeltaF = [PY_DELTA_F]
			VAR DeltaN = [PY_DELTA_N]
			VAR DeltaP = [PY_DELTA_P]
			VAR DeltaL = [PY_DELTA_L]
			
			VAR WeightedSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP * 2 )
			        + IF ( DeltaL < 0, 0, DeltaL * 3 )
			        + IF ( DeltaF < 0, 0, DeltaF * 4 )
			VAR TotalSum =
			    IF ( DeltaN < 0, 0, DeltaN )
			        + IF ( DeltaP < 0, 0, DeltaP )
			        + IF ( DeltaL < 0, 0, DeltaL )
			        + IF ( DeltaF < 0, 0, DeltaF )
			VAR result =
			    IF (checknull = 0, 0
			            , ROUND ( IFERROR ( WeightedSum / TotalSum, 4 ), 0 )
			    )
			
			RETURN
			   result
			```
		formatString: 0
		displayFolder: Ratings
		lineageTag: 6042b41b-1f04-42f8-90de-1c2af607e06e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure RATING =
			VAR RatingNumber = [RATING NUMBER]
			VAR Rating =
			    SWITCH (
			        TRUE (),
			        RatingNumber = 0, "NA",
			        RatingNumber = 1, "N",
			        RatingNumber = 2, "P",
			        RatingNumber = 3, "L",
			        RatingNumber = 4, "F"
			    )
			RETURN
			    Rating
		displayFolder: Ratings
		lineageTag: b37ee32d-8fde-4f0b-8b94-4180098742ff

	measure 'COLOR RATING' = ```
			VAR SelectedValue = [RATING]
			RETURN
			    SWITCH (
			        TRUE (),
			        SelectedValue = "NA", "#C1C7CC",
			        SelectedValue = "N", "#FF5152",
			        SelectedValue = "P", "#FFAB40",
			        SelectedValue = "L", "#FFEA00",
			        SelectedValue = "F", "#67D884" 
			    )
			```
		displayFolder: Ratings
		lineageTag: c218dae8-7e7f-470d-b103-289532609a3c

	measure 'COLOR BACKGROUND' =
			VAR cf =
			    IF (
			        ISINSCOPE ( E10_DIM_QUESTION[TOPIC_ID] ) && ISINSCOPE ( E10_PC_CHECKS[OE] )
			            || ISINSCOPE ( E10_PC_CHECKS[OE] ),
			        [COLOR RATING],
			        "white"
			    )
			RETURN
			    cf
		displayFolder: Ratings
		lineageTag: 59be388f-13c0-4e0a-a432-9202558a0bf4

	measure 'COLOR TEXT' =
			VAR CurrentYearRatingValue = [RATING NUMBER]
			VAR CurrentYearRating = [RATING]
			VAR PreviousYearRatingValue = [PY RATING NUMBER]
			VAR RankDifference = CurrentYearRatingValue - PreviousYearRatingValue
			VAR Color =
			    IF (
			        ISINSCOPE (E10_DIM_QUESTION[TOPIC_ID] ) && ISINSCOPE ( E10_PC_CHECKS[OE] )
			            || ISINSCOPE ( E10_PC_CHECKS[OE] ),
			        [COLOR RATING],
			        IF (CurrentYearRatingValue = 0 || PreviousYearRatingValue = 0
			            ,"black"
			            , IF ( RankDifference >= 0, "green", "red" )
			        )
			    )
			RETURN
			    Color
		displayFolder: Ratings
		lineageTag: dcc19b99-2fb7-48e1-9661-98a008f1e223

	measure COUNT_ALL_RATING =
			CALCULATE (
			    [COUNT_RATING],
			    FILTER (
			        ALL ( E10_PC_CHECKS_L2_CATEGORIES ),
			        NOT E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 0d5f275f-7a22-440a-9d00-484d4060481a

	measure COUNT_RATING = COUNT ( E10_PC_CHECKS_L2_CATEGORIES[RID_QUESTIONID] )
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: c82180ed-34d7-450d-bda7-01e26edf17ea

	measure PERCENTAGE_RATING = DIVIDE ( [COUNT_RATING], [COUNT_TOTAL_RATING], 0 )
		displayFolder: RISK_CATEGORIES
		lineageTag: f2a311b5-5681-48a5-be4a-73a704d0eeda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PERCENTAGE_RATING_TEXT =
			IF (
			    [PERCENTAGE_RATING] >= 0.07,
			    [PERCENTAGE_RATING],
			    IF ( [PERCENTAGE_RATING] > 0, "" )
			)
		displayFolder: RISK_CATEGORIES
		lineageTag: 408c97a4-d16b-4815-aa36-52c940fb7303

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_F =
			VAR COUNT_ALL_RATING_F =
			    CALCULATE (
			        [COUNT_RATING],
			        FILTER (
			            ALL ( E10_PC_CHECKS_L2_CATEGORIES ),
			            E10_PC_CHECKS_L2_CATEGORIES[RATING] = "F"
			        )
			    )
			VAR PCT_ALL_RATING_F = COUNT_ALL_RATING_F / [COUNT_ALL_RATING]
			VAR PCT_F =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [COUNT_RATING], E10_PC_CHECKS_L2_CATEGORIES[RATING] = "F" ) + 0,
			            CALCULATE (
			                [COUNT_TOTAL_RATING],
			                NOT E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E10_PC_CHECKS_L2_CATEGORIES[RATING],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_F =
			    IF ( ISBLANK ( PCT_F ), BLANK (), PCT_F - PCT_ALL_RATING_F )
			RETURN
			    DELTA_F
		displayFolder: RISK_CATEGORIES
		lineageTag: e9a3dccb-8945-44a3-bf23-990e9f306636

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_P =
			VAR COUNT_ALL_RATING_P =
			    CALCULATE (
			        [COUNT_RATING],
			        FILTER (
			            ALL ( E10_PC_CHECKS_L2_CATEGORIES ),
			            E10_PC_CHECKS_L2_CATEGORIES[RATING] = "P"
			        )
			    )
			VAR PCT_ALL_RATING_P = COUNT_ALL_RATING_P / [COUNT_ALL_RATING]
			VAR PCT_P =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [COUNT_RATING], E10_PC_CHECKS_L2_CATEGORIES[RATING] = "P" ) + 0,
			            CALCULATE (
			                [COUNT_TOTAL_RATING],
			                NOT E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E10_PC_CHECKS_L2_CATEGORIES[RATING],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_P =
			    IF ( ISBLANK ( PCT_P ), BLANK (), PCT_P - PCT_ALL_RATING_P )
			RETURN
			    DELTA_P
		displayFolder: RISK_CATEGORIES
		lineageTag: 3ce0aa54-ed5c-4a80-aa30-4dfd02dddd1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_L =
			VAR COUNT_ALL_RATING_L =
			    CALCULATE (
			        [COUNT_RATING],
			        FILTER (
			            ALL ( E10_PC_CHECKS_L2_CATEGORIES ),
			            E10_PC_CHECKS_L2_CATEGORIES[RATING] = "L"
			        )
			    )
			VAR PCT_ALL_RATING_L = COUNT_ALL_RATING_L / [COUNT_ALL_RATING]
			VAR PCT_L =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [COUNT_RATING], E10_PC_CHECKS_L2_CATEGORIES[RATING] = "L" ) + 0,
			            CALCULATE (
			                [COUNT_TOTAL_RATING],
			                NOT E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E10_PC_CHECKS_L2_CATEGORIES[RATING],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_L =
			    IF ( ISBLANK ( PCT_L ), BLANK (), PCT_L - PCT_ALL_RATING_L )
			RETURN
			    DELTA_L
		displayFolder: RISK_CATEGORIES
		lineageTag: dbca4fda-87ef-45b2-8cf9-962894245cd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DELTA_N =
			VAR COUNT_ALL_RATING_N =
			    CALCULATE (
			        [COUNT_RATING],
			        FILTER (
			            ALL ( E10_PC_CHECKS_L2_CATEGORIES ),
			            E10_PC_CHECKS_L2_CATEGORIES[RATING] = "N"
			        )
			    )
			VAR PCT_ALL_RATING_N = COUNT_ALL_RATING_N / [COUNT_ALL_RATING]
			VAR PCT_N =
			    CALCULATE (
			        DIVIDE (
			            CALCULATE ( [COUNT_RATING], E10_PC_CHECKS_L2_CATEGORIES[RATING] = "N" ) + 0,
			            CALCULATE (
			                [COUNT_TOTAL_RATING],
			                NOT E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "NA", BLANK () }
			            ),
			            BLANK ()
			        ),
			        ALLSELECTED (
			            E10_PC_CHECKS_L2_CATEGORIES[RATING],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			            E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			        )
			    )
			VAR DELTA_N =
			    IF ( ISBLANK ( PCT_N ), BLANK (), PCT_N - PCT_ALL_RATING_N )
			RETURN
			    DELTA_N
		displayFolder: RISK_CATEGORIES
		lineageTag: 01c1d425-286b-4b30-8599-11cd50cd06bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW = ROUND ( [XS_RAW_NO_ROUND], 0 )
		displayFolder: RISK_CATEGORIES
		lineageTag: b8c58384-4d72-4f68-9f9f-4a21868b4dc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW_PREVIOUS_YEAR =
			VAR PC_YEAR = [MOST_PREVIOUS_YEAR]
			VAR DELTA_F_PY =
			    CALCULATE ( [DELTA_F], E10_PC_CHECKS[PC_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_L_PY =
			    CALCULATE ( [DELTA_L], E10_PC_CHECKS[PC_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_P_PY =
			    CALCULATE ( [DELTA_P], E10_PC_CHECKS[PC_CHECK_YEAR] = PC_YEAR )
			VAR DELTA_N_PY =
			    CALCULATE ( [DELTA_N], E10_PC_CHECKS[PC_CHECK_YEAR] = PC_YEAR )
			VAR RESULT =
			    IF (
			        ISBLANK ( DELTA_F_PY ) || ISBLANK ( DELTA_L_PY )
			            || ISBLANK ( DELTA_P_PY )
			            || ISBLANK ( DELTA_N_PY ),
			        BLANK (),
			        ROUND (
			            IFERROR (
			                (
			                    IF ( DELTA_N_PY < 0, 0, DELTA_N_PY )
			                        + IF ( DELTA_P_PY < 0, 0, DELTA_P_PY * 2 )
			                        + IF ( DELTA_L_PY < 0, 0, DELTA_L_PY * 3 )
			                        + IF ( DELTA_F_PY < 0, 0, DELTA_F_PY * 4 )
			                )
			                    / (
			                        IF ( DELTA_N_PY < 0, 0, DELTA_N_PY )
			                            + IF ( DELTA_P_PY < 0, 0, DELTA_P_PY )
			                            + IF ( DELTA_L_PY < 0, 0, DELTA_L_PY )
			                            + IF ( DELTA_F_PY < 0, 0, DELTA_F_PY )
			                    ),
			                4
			            ),
			            0
			        )
			    )
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES
		lineageTag: a12ee5f7-264e-45e1-8c67-5caab314728c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XS_RAW_COMPARE =
			VAR selectedyear =
			    SELECTEDVALUE ( E10_PC_CHECKS[PC_CHECK_YEAR] )
			VAR CurrentYear_XS_RAW = [XS_RAW]
			VAR PreviousYear_XS_RAW = [XS_RAW_PREVIOUS_YEAR]
			VAR RankDifference = CurrentYear_XS_RAW - PreviousYear_XS_RAW
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( SelectedYear ), BLANK (),
			        ISBLANK ( CurrentYear_XS_RAW ), BLANK (),
			        ISBLANK ( PreviousYear_XS_RAW ), "∅",
			        SWITCH (
			            TRUE (),
			            RankDifference = 1, "↗",
			            RankDifference = 2, "↗↗",
			            RankDifference = 3, "↗↗↗",
			            RankDifference = 4, "↗↗↗↗",
			            RankDifference = 0, "(=)",
			            RankDifference = -1, "↘",
			            RankDifference = -2, "↘↘",
			            RankDifference = -3, "↘↘↘",
			            RankDifference = -4, "↘↘↘↘",
			            BLANK ()
			        )
			    )
			RETURN
			    Result
		displayFolder: RISK_CATEGORIES
		lineageTag: 063d09a5-470b-4d0b-9426-ed1a67008eff

	measure MAX_RISK_STATEMENT_ID =
			MAXX (
			    E10_PC_CHECKS_L2_CATEGORIES,
			    RELATED (E10_DIM_RISK_CATEGORIES[L2_ID])
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 6446f43d-7bfd-41e5-b1f1-d5c23c4573b7

	measure SORT_NUM_CASES_BY_RISKSTATEMENT =
			IF (
			    SELECTEDVALUE ( E10_SORT[SORT_NAME] ) = "ASC",
			    SWITCH (
			        SELECTEDVALUE ( E10_SORT_BY[MEASURE] ),
			        "Rating", [XS_RAW_NO_ROUND],
			        [MAX_RISK_STATEMENT_ID]
			    ),
			    SWITCH (
			        SELECTEDVALUE ( E10_SORT_BY[MEASURE] ),
			        "Rating", - [XS_RAW_NO_ROUND],
			        - [MAX_RISK_STATEMENT_ID]
			    )
			)
		displayFolder: RISK_CATEGORIES
		lineageTag: 77a22204-f0f6-4eb3-ab72-3955844a11c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COUNT_TOTAL_RATING =
			CALCULATE (
			    [COUNT_RATING],
			    ALLSELECTED (
			        E10_PC_CHECKS_L2_CATEGORIES[RATING],
			        E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: ff057f4a-2943-475d-98e4-26ae75b0e3f7

	measure MOST_PREVIOUS_YEAR =
			CALCULATE (
			    MAX ( E10_PC_CHECKS[PC_CHECK_YEAR] ),
			    FILTER (
			        ALLEXCEPT (
			            E10_PC_CHECKS,
			            E10_PC_CHECKS[OE],
			            E10_PC_CHECKS[BU_CODE],
			            E10_DIM_REGION[CONTINENT],
			            E10_DIM_REGION[COUNTRY_GROUP_CODE],
			            E10_DIM_REGION[COUNTRY_DISPLAY_TEXT]
			        ),
			        AND (
			            E10_PC_CHECKS[PC_CHECK_YEAR] < SELECTEDVALUE ( E10_PC_CHECKS[PC_CHECK_YEAR] ),
			            NOT E10_PC_CHECKS[RATING] IN { "NA", BLANK () }
			        )
			    ),
			    ALLSELECTED (
			        E10_PC_CHECKS_L2_CATEGORIES[RATING],
			        E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.ORDER_ID],
			        E10_PC_CHECKS_L2_CATEGORIES[DIM_RATING.RATING_COLOR_HEX]
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES
		lineageTag: 4e95eaa9-daf9-417d-8140-e4ff779c6e81

	measure COMPARISON_YEAR =
			VAR selectedyear =
			    SELECTEDVALUE ( E10_PC_CHECKS[PC_CHECK_YEAR] )
			RETURN
			    CALCULATE (
			        MAX ( E10_PC_CHECKS[PC_CHECK_YEAR] ),
			        E10_PC_CHECKS[PC_CHECK_YEAR] < selectedyear,
			        ALLSELECTED ( E10_PC_CHECKS[OE] ),
			        ALL ( 'E10_PC_CHECKS'[Number of check] ),
			        ALL ( E10_PC_CHECKS[Number of question] ) --,ALL(E10_PC_CHECKS[TOPIC_NAME])
			        ,
			        NOT E10_PC_CHECKS[RATING] IN { "NA", BLANK () }
			    )
		formatString: 0
		displayFolder: Ratings
		lineageTag: 36e95842-dc3e-4224-b7a7-95d0bb7dba95

	measure XS_RAW_COMPARE_COLOR =
			VAR selectedyear =
			    SELECTEDVALUE ( E10_PC_CHECKS[PC_CHECK_YEAR] )
			VAR CurrentYear_XS_RAW = [XS_RAW]
			VAR PreviousYear_XS_RAW = [XS_RAW_PREVIOUS_YEAR]
			VAR RankDifference = CurrentYear_XS_RAW - PreviousYear_XS_RAW
			VAR Result =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( SelectedYear ), BLANK (),
			        ISBLANK ( CurrentYear_XS_RAW ), BLANK (),
			        ISBLANK ( PreviousYear_XS_RAW ), MAX ( ThemeFilter[Font] ),
			        SWITCH (
			            TRUE (),
			            RankDifference >= 0, "green",
			            RankDifference < 0, "red",
			            MAX ( ThemeFilter[Font] )
			        )
			    )
			RETURN
			    Result
		displayFolder: RISK_CATEGORIES
		lineageTag: b19b66f0-04eb-441a-9ad1-a8f976c28f08

	measure 'DELTA F' =
			
			VAR countrating =
			    IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			    CALCULATE ([COUNT F],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question] )),
			    CALCULATE ([COUNT F],
			    ALL ( E10_PC_CHECKS[OE], E10_PC_CHECKS[Number of check], E10_PC_CHECKS[Number of question], E10_PC_CHECKS[PC_CHECK_YEAR_QUESION_ID]))
			    )
			VAR percentage = countrating / [COUNT ALL]
			VAR delta = [% F rating] - percentage
			RETURN
			    delta
		displayFolder: Ratings
		lineageTag: b506a1f2-689e-42ee-b062-3e643dc2ffc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COUNT F PER PHASE' = ```
			
			                        CALCULATE(DISTINCTCOUNT( 'E10_UNPIVOT_PHASE'[QUESTION_ID] )
			                                ,E10_UNPIVOT_PHASE[RATING]="F"
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 79f82cd3-85cd-48cb-a13d-77f98b060ac2

	measure 'QUESTION COLOR RATING' =
			VAR SelectedValue =
			    SELECTEDVALUE ( 'E10_UNPIVOT_PHASE'[RATING] )
			RETURN
			    SWITCH (
			        TRUE (),
			        SelectedValue = "NA", "#8D9196",
			        SelectedValue = "N", "#ED0007",
			        SelectedValue = "P", "#FF9D00",
			        SelectedValue = "L", "#FFCF00",
			        SelectedValue = "F", "#00884A"
			    )
		lineageTag: 433fbfdc-68f3-4026-b2f8-800f9feec9e5

	measure '%RATING PER PHASE' =
			
			[COUNT QUESTION PER PHASE]/
			CALCULATE (
			       [COUNT QUESTION PER PHASE]
			        ,ALLEXCEPT(E10_UNPIVOT_PHASE,
			        E10_UNPIVOT_PHASE[PC_CHECK_YEAR],
			        E10_UNPIVOT_PHASE[OE],
			        E10_UNPIVOT_PHASE[BU_CODE],
			        E10_UNPIVOT_PHASE[COUNTRY_ISO_CODE],
			        E10_UNPIVOT_PHASE[PHASES],
			        E10_DIM_PHASES[Phase Name]
			        )
			        , E10_UNPIVOT_PHASE[RATING]<>BLANK()
			                )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 580101b8-1c09-4cc8-83e9-87dfdb427642

	measure XS_RAW_NO_ROUND =
			VAR ISNA =
			    IF ( MAX ( E10_PC_CHECKS_L2_CATEGORIES[RATING] ) IN { "NA" }, 0, BLANK () )
			VAR RESULT =
			    IF (
			        ISBLANK ( [DELTA_F] ) || ISBLANK ( [DELTA_L] )
			            || ISBLANK ( [DELTA_P] )
			            || ISBLANK ( [DELTA_N] ),
			        ISNA,
			        IFERROR (
			            (
			                IF ( [DELTA_N] < 0, 0, [DELTA_N] )
			                    + IF ( [DELTA_P] < 0, 0, [DELTA_P] * 2 )
			                    + IF ( [DELTA_L] < 0, 0, [DELTA_L] * 3 )
			                    + IF ( [DELTA_F] < 0, 0, [DELTA_F] * 4 )
			            )
			                / (
			                    IF ( [DELTA_N] < 0, 0, [DELTA_N] )
			                        + IF ( [DELTA_P] < 0, 0, [DELTA_P] )
			                        + IF ( [DELTA_L] < 0, 0, [DELTA_L] )
			                        + IF ( [DELTA_F] < 0, 0, [DELTA_F] )
			                ),
			            4
			        )
			    )
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES
		lineageTag: e90f3823-1f71-440f-9c00-578285185353

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COUNT_TOTAL_QUESTION =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    ALLEXCEPT (
			        E10_PC_CHECKS_L2_CATEGORIES,
			        E10_DIM_RISK_CATEGORIES[L2_VALUE],
			        E10_DIM_RISK_CATEGORIES[L2_ID]
			    )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: dbc7f6f3-ac7c-4f59-b63a-d0d796c54fd8

	measure COUNT_QUESTION_L&P =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] IN { "L", "P" }
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 47df7a49-ad3f-498b-8848-6ae883d737a2

	measure COUNT_QUESTION_L_PLUS0 =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "L"
			) + 0
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 248a9082-1a0a-417f-b199-c520dd3bbf47

	measure COUNT_QUESTION_P_PLUS0 =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "P"
			)
			    + IF ( [COUNT_QUESTION_L_PLUS0] > 0, 0, BLANK () )
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 447b800b-7007-4546-961c-59ef51446379

	measure MAX_L_PER_L2R =
			VAR COUNT_QUESTION_L_PER_L2R_TABLE =
			    SUMMARIZE (
			        E10_PC_CHECKS_L2_CATEGORIES,
			        E10_DIM_RISK_CATEGORIES[L2_ID],
			        "Count_Question", [COUNT_QUESTION_L_PLUS0]
			    )
			VAR RESULT =
			    MAXX ( COUNT_QUESTION_L_PER_L2R_TABLE, [Count_Question] ) + 1
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 351ee1aa-fb34-4b69-835a-0f7332bfb49d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MAX_P_PER_L2R =
			VAR COUNT_QUESTION_P_PER_L2R_TABLE =
			    SUMMARIZE (
			        E10_PC_CHECKS_L2_CATEGORIES,
			        E10_DIM_RISK_CATEGORIES[L2_ID],
			        "Count_Question", [COUNT_QUESTION_P_PLUS0]
			    )
			VAR RESULT =
			    MAXX ( COUNT_QUESTION_P_PER_L2R_TABLE, [Count_Question] ) + 1
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: f6901f6b-8f46-41d8-b0ee-be85b61f905c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COUNT_QUESTION_N =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "N"
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: a5406189-d297-4588-88aa-bf4672886809

	measure COUNT_QUESTION_L2_CATEGORIES_TBL = COUNT ( E10_PC_CHECKS_L2_CATEGORIES[RID_QUESTIONID] )
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: a79b7db2-43a1-48b4-a69e-ac4541cf1265

	measure BUBBLE_COLOR =
			SWITCH (
			    TRUE (),
			    [COUNT_QUESTION_N] > 0, "#ED0007",
			    MAX (E10_DIM_RISK_CATEGORIES[L1_COLOR])
			)
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 2698f1c5-2e5c-4872-926d-3eee57fdd114

	measure BUBLE_TEXT = "⬤"
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 2961246f-bb0f-4c4b-887d-4fc48e1f33ef

	measure L2_RISK_LEGEND_COLOR = SWITCH ( TRUE (), [COUNT_QUESTION_N] > 0, "#ED0007", MAX ( ThemeFilter[Font] ) )
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: e3011d71-a21d-4d8d-bed8-895be44ebd73

	measure COUNT_QUESTION_L =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "L"
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 66d8b637-3c14-43ee-b536-a65994196609

	measure COUNT_QUESTION_P =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "P"
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 72b98481-8d3b-4372-b6af-a68379fa3457

	measure COUNT_QUESTION_F =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    E10_PC_CHECKS_L2_CATEGORIES[RATING] = "F"
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 6f943bc4-33bb-4c2f-b32c-7355f0a8d538

	measure COUNT_ALL_QUESTION =
			CALCULATE (
			    [COUNT_QUESTION_L2_CATEGORIES_TBL],
			    ALL ( E10_PC_CHECKS_L2_CATEGORIES )
			)
		formatString: 0
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 5761ffa3-2cf3-4609-b429-7e342ab595e8

	measure PCT_SCALE_L = [COUNT_QUESTION_L_PLUS0] / [COUNT_ALL_QUESTION] / [COUNT_TOTAL_QUESTION] * 100/100
		formatString: 0.0000%;-0.0000%;0.0000%
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: a20ccf15-2dea-4e1e-be64-dd9dcca65b28

	measure PCT_SCALE_P = [COUNT_QUESTION_P_PLUS0] / [COUNT_ALL_QUESTION] / [COUNT_TOTAL_QUESTION] * 100/100
		formatString: 0.0000%;-0.0000%;0.0000%
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: dbbc1375-4875-47ef-bf43-9b646df07fb3

	measure MAX_%L_PER_L2R =
			VAR PCT_QUESTION_L_PER_L2R_TABLE =
			    SUMMARIZE (
			        E10_PC_CHECKS_L2_CATEGORIES,
			        E10_DIM_RISK_CATEGORIES[L2_ID],
			        "Pct_Question", [PCT_SCALE_L]
			    )
			VAR RESULT =
			    MAXX ( PCT_QUESTION_L_PER_L2R_TABLE, [Pct_Question] ) + 0.001
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: 2cdf5cfe-5a4f-4e1a-95ae-05168a8f4d9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MAX_%P_PER_L2R =
			VAR PCT_QUESTION_P_PER_L2R_TABLE =
			    SUMMARIZE (
			        E10_PC_CHECKS_L2_CATEGORIES,
			        E10_DIM_RISK_CATEGORIES[L2_ID],
			        "Pct_Question", [PCT_SCALE_P]
			    )
			VAR RESULT =
			    MAXX ( PCT_QUESTION_P_PER_L2R_TABLE, [Pct_Question] ) + 0.001
			RETURN
			    RESULT
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: b47a2027-0c6e-463c-a1df-fa61e874fe5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PCT_SCALE_L&P = [PCT_SCALE_L] + [PCT_SCALE_P]
		formatString: 0.0000%;-0.0000%;0.0000%
		displayFolder: RISK_CATEGORIES_PRIORITIES
		lineageTag: d6a5ea69-badf-42b8-8081-5d1676649933

	measure 'COUNT L PER PHASE' = ```
			
			                        CALCULATE(DISTINCTCOUNT( 'E10_UNPIVOT_PHASE'[QUESTION_ID] )
			                                ,E10_UNPIVOT_PHASE[RATING]="L"
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 920c23d0-7158-4107-8cbf-d20ceb0c11a5

	measure 'COUNT P PER PHASE' = ```
			
			                        CALCULATE(DISTINCTCOUNT( 'E10_UNPIVOT_PHASE'[QUESTION_ID] )
			                        ,E10_UNPIVOT_PHASE[RATING]="P"
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 9311ebc2-e8b6-4c81-b8dd-a13fdb87fd95

	measure 'COUNT N PER PHASE' = ```
			
			                        CALCULATE(DISTINCTCOUNT( 'E10_UNPIVOT_PHASE'[QUESTION_ID] )
			                                ,E10_UNPIVOT_PHASE[RATING]="N"
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 43e1ddd3-a92c-48ca-ba53-866e793260db

	measure 'COUNT NA PER PHASE' = ```
			
			                        CALCULATE(COUNT ( 'E10_UNPIVOT_PHASE'[RATING] ) 
			                                ,E10_UNPIVOT_PHASE[RATING]="NA"
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 351f8a15-6474-4dee-a253-eb4ba72bd0b8

	measure 'COUNT QUESTION PER PHASE' = ```
			
			                        CALCULATE(COUNT(E10_UNPIVOT_PHASE[QUESTION_ID]),
			                        E10_UNPIVOT_PHASE[RATING]<>BLANK()
			                        )
			                        + 0
			```
		formatString: 0
		lineageTag: 22b78f8b-fbe9-4f06-bffc-db31504b225e

	measure NUMBER_OF_MEASURE = ```
			
			                CALCULATE(COUNTROWS(E10_PC_CHECKS)
			                ,'E10_PC_CHECKS'[TYPE_OF_GUIDANCE]="Measure"
			              )+0
			```
		formatString: 0
		lineageTag: 6bebd525-23d3-4f8c-a622-44121cb53ab3

	measure COUNT_OPEN_MEASURE =
			
			CALCULATE(
				[NUMBER_OF_MEASURE],
				'E10_PC_CHECKS'[GUIDANCE_STATUS_DESC]="Open"
			)
		formatString: 0
		lineageTag: d681a2e8-ad51-4e91-b1e2-1f5963e703bd

	measure COUNT_COMPLETED_MEASURE =
			
			CALCULATE(
				[NUMBER_OF_MEASURE],
				'E10_PC_CHECKS'[GUIDANCE_STATUS_DESC]="Completed"
			)
		formatString: 0
		lineageTag: 3e8a519c-10f5-4d71-af0a-05d26ef8f9f0

	measure COUNT_SOONDUE_MEASURE =
			
			CALCULATE(
				[NUMBER_OF_MEASURE],
				'E10_PC_CHECKS'[GUIDANCE_STATUS_DESC]="Soon Due"
			)
		formatString: 0
		lineageTag: 5e6dfaed-be41-43a1-9cc8-51c1a1f73c84

	measure COUNT_OVERDUE_MEASURE =
			
			CALCULATE(
				[NUMBER_OF_MEASURE],
				'E10_PC_CHECKS'[GUIDANCE_STATUS_DESC]="Overdue"
			)
		formatString: 0
		lineageTag: e0e7d5a2-f1b0-4f4c-a688-d52572ea12ec

	measure OPEN_MEASURE_PERCENTAGE = ```
			
			                        [COUNT_OPEN_MEASURE]/
			                        CALCULATE([NUMBER_OF_MEASURE]
			                                ,ALL(E10_PC_CHECKS[GUIDANCE_STATUS_DESC])
			                                ,E10_PC_CHECKS[GUIDANCE_STATUS_DESC]<>BLANK()
			                        )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6d5a4816-6806-454c-9ab7-6b16b48c106c

	measure SOONDUE_MEASURE_PERCENTAGE = ```
			
			                        [COUNT_SOONDUE_MEASURE]/
			                        CALCULATE([NUMBER_OF_MEASURE]
			                                ,ALL(E10_PC_CHECKS[GUIDANCE_STATUS_DESC])
			                                ,E10_PC_CHECKS[GUIDANCE_STATUS_DESC]<>BLANK()
			                        )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 803112b7-f30f-435a-a184-9aaf94eb6e97

	measure OVERDUE_MEASURE_PERCENTAGE = ```
			
			                        [COUNT_OVERDUE_MEASURE]/
			                        CALCULATE([NUMBER_OF_MEASURE]
			                                ,ALL(E10_PC_CHECKS[GUIDANCE_STATUS_DESC])
			                                ,E10_PC_CHECKS[GUIDANCE_STATUS_DESC]<>BLANK()
			                        )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3ad903fe-3b5d-4579-aa30-2dc5555a4577

	measure OVERDUE_DAYS =
			
			VAR sts = SELECTEDVALUE(E10_PC_CHECKS[GUIDANCE_STATUS_DESC])
			VAR duedate = SELECTEDVALUE(E10_PC_CHECKS[GUIDANCE_DUE_DATE])
			VAR resolutiondate = SELECTEDVALUE(E10_PC_CHECKS[GUIDANCE_RESOLUTION_DATE])
			VAR currentdate = TODAY()
			RETURN      IF(ISBLANK(resolutiondate)
			                ,IF(DATEDIFF(duedate, currentdate, DAY) > 0, DATEDIFF(duedate, currentdate, DAY), 0)
			                ,IF(DATEDIFF(duedate, resolutiondate, DAY) > 0, DATEDIFF(duedate, resolutiondate, DAY), 0)
			                )
		formatString: 0
		lineageTag: aaca870f-9b03-487d-bd42-087160e11f7e

	measure MEASURE_STATUS_COLOR = ```
			
			VAR meausre_status = SELECTEDVALUE(E10_PC_CHECKS[GUIDANCE_STATUS_DESC])
			VAR theme = SELECTEDVALUE(E10_THEME[Theme])
			RETURN
			                    SWITCH(
			                        TRUE(),
			                        meausre_status="Open" && theme = "Light", "#000000",
			                        meausre_status="Completed" && theme = "Light", "#000000",
			                        meausre_status="Soon Due" && theme = "Light", "#FFAB40",
			                        meausre_status="Overdue" && theme = "Light", "#ED0007",
			                        meausre_status="Open" && theme = "Dark", "#FFFFFF",
			                        meausre_status="Completed" && theme = "Dark", "#FFFFFF",
			                        meausre_status="Soon Due" && theme = "Dark", "#FD9000",
			                        meausre_status="Overdue" && theme = "Dark", "#F13339"
			
			                        )
			                        
			```
		lineageTag: a72535ac-e5f1-47a1-9de0-37290a7f2c78

	measure 'COUNT RATING' = ```
			
			            CALCULATE(DISTINCTCOUNT(E10_PC_CHECKS[RID_QUESTIONID]) 
			            , NOT E10_PC_CHECKS[RATING] IN {"NA", BLANK()})
			```
		formatString: 0
		displayFolder: Ratings
		lineageTag: 03fbf6dc-16f6-4617-90d0-7ecfc55f0d0a

	measure L1_TAXONOMY =
			IF(
			    MIN(E10_DIM_RISK_CATEGORIES[L2_ID]) = CALCULATE(MIN(E10_DIM_RISK_CATEGORIES[L2_ID]), ALLSELECTED(E10_DIM_RISK_CATEGORIES[L2_VALUE])),
			    MAX(E10_DIM_RISK_CATEGORIES[L1_VALUE]),
			    ""
			)
		lineageTag: d15ae50c-fe2e-4e9f-be51-c8d28fd4c7cf

	measure PY_COUNTALL = ```
			IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			            CALCULATE([COUNT ALL]
			            , FILTER(ALLEXCEPT(E10_PC_CHECKS, E10_DIM_QUESTION[TOPIC_ID]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME])
			            )),
			            CALCULATE([COUNT ALL]
			            , FILTER(ALLEXCEPT(E10_PC_CHECKS, E10_DIM_QUESTION[TOPIC_ID]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            )))
			```
		formatString: 0
		displayFolder: Ratings
		lineageTag: e2151afe-9697-4088-812d-67ec678f8fd1

	measure PY_%F = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E10_PC_CHECKS[OE]), CALCULATE([% F rating], prevtopic),
			    IF(ISINSCOPE(E10_DIM_QUESTION[TOPIC_NAME]), CALCULATE([% F rating], totalpre),
			    CALCULATE([% F rating], 
			    FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]), E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])))))
			```
		displayFolder: Ratings
		lineageTag: e3517923-327f-42e4-8ad3-b26b1a98d88c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_%L = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E10_PC_CHECKS[OE]), CALCULATE([% L rating], prevtopic),
			    IF(ISINSCOPE(E10_DIM_QUESTION[TOPIC_NAME]), CALCULATE([% L rating], totalpre),
			    CALCULATE([% L rating], FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]), E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])))))
			```
		displayFolder: Ratings
		lineageTag: b390dd64-ec10-4631-851a-23e6c31cea44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_%N = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E10_PC_CHECKS[OE]), CALCULATE([% N rating], prevtopic),
			    IF(ISINSCOPE(E10_DIM_QUESTION[TOPIC_NAME]), CALCULATE([% N rating], totalpre),
			    CALCULATE([% N rating], FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]), E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])))))
			```
		displayFolder: Ratings
		lineageTag: bbf34373-c6b0-403c-bb84-99895bc3be4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_%P = ```
			
			VAR prevtopic = 
			            FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			RETURN IF(
			    ISINSCOPE(E10_PC_CHECKS[OE]), CALCULATE([% P rating], prevtopic),
			    IF(ISINSCOPE(E10_DIM_QUESTION[TOPIC_NAME]), CALCULATE([% P rating], totalpre),
			    CALCULATE([% P rating], FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING], E10_PC_CHECKS[OE]), E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR])))))
			```
		displayFolder: Ratings
		lineageTag: 341c50ea-02cd-4559-88bf-4f7b0a8945eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_DELTA_F = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			            CALCULATE([COUNT F], prevtopic)/ [PY_COUNTALL],
			            CALCULATE([COUNT F], totalpre)/ [PY_COUNTALL])
			
			VAR delta = [PY_%F] - percentage
			
			RETURN delta
			```
		displayFolder: Ratings
		lineageTag: 90e58602-42ec-4b77-81bb-7824e1b5777a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_DELTA_L = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			            CALCULATE([COUNT L], prevtopic)/ [PY_COUNTALL],
			            CALCULATE([COUNT L], totalpre)/ [PY_COUNTALL])
			
			VAR delta = [PY_%L] - percentage
			
			RETURN delta
			```
		displayFolder: Ratings
		lineageTag: 60d6d7a0-2229-4848-9fbb-bc59842f9afb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_DELTA_N = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			            CALCULATE([COUNT N], prevtopic)/ [PY_COUNTALL],
			            CALCULATE([COUNT N], totalpre)/ [PY_COUNTALL])
			
			VAR delta = [PY_%N] - percentage
			
			RETURN delta
			```
		displayFolder: Ratings
		lineageTag: 498eca6d-e29c-46cf-acfc-f1e91821f762

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PY_DELTA_P = ```
			
			VAR prevtopic = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            && RELATED(E10_DIM_QUESTION[TOPIC_NAME]) = MAX(E10_PC_CHECKS[PREVIOUS_TOPIC_NAME]))
			
			VAR totalpre = FILTER(ALLEXCEPT(E10_PC_CHECKS,E10_PC_CHECKS[RATING]),
			            E10_PC_CHECKS[PC_CHECK_YEAR] = MAX(E10_PC_CHECKS[PREVIOUS_YEAR]) 
			            )
			
			VAR percentage = IF(ISINSCOPE(E10_PC_CHECKS[OE]),
			            CALCULATE([COUNT P], prevtopic)/ [PY_COUNTALL],
			            CALCULATE([COUNT P], totalpre)/ [PY_COUNTALL])
			
			VAR delta = [PY_%P] - percentage
			
			RETURN delta
			```
		displayFolder: Ratings
		lineageTag: b84bb0b1-647c-4b55-bbb5-07b8de4b99cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _measure
		formatString: 0
		lineageTag: 0c772898-cf01-4564-aee6-3fe0d79a24c5
		summarizeBy: sum
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _MEASURE = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 4c5e72cc986d4a67a7ac75c17e2417b3

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

