table E10_THEME
	lineageTag: aa58689d-b33b-43ae-afba-44ac6a7a2dfb

	column ThemeID
		dataType: double
		formatString: 0
		lineageTag: e77faf01-00ae-479b-9607-09b00f560c2f
		summarizeBy: count
		sourceColumn: ThemeID

		annotation SummarizationSetBy = Automatic

	column Theme
		dataType: string
		lineageTag: 37122d08-53f9-4023-b826-14b4c5e99e46
		summarizeBy: none
		sourceColumn: Theme

		annotation SummarizationSetBy = Automatic

	column home
		dataType: string
		lineageTag: 98b50801-9f9d-4229-a896-dba767149d0a
		summarizeBy: none
		sourceColumn: home

		annotation SummarizationSetBy = Automatic

	column document-view
		dataType: string
		lineageTag: 08ddcd26-8152-4060-a59b-fef7277a6824
		summarizeBy: none
		sourceColumn: document-view

		annotation SummarizationSetBy = Automatic

	column document-search
		dataType: string
		lineageTag: c71c0a06-26ff-448a-bcaf-b35800da5e35
		summarizeBy: none
		sourceColumn: document-search

		annotation SummarizationSetBy = Automatic

	column document-test
		dataType: string
		lineageTag: 24b3b1ba-794c-43d3-b5c4-e596edc1d499
		summarizeBy: none
		sourceColumn: document-test

		annotation SummarizationSetBy = Automatic

	column document
		dataType: string
		lineageTag: 65974103-dda0-4028-92e8-822f29c10ebb
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	partition E10_THEME = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("3ZRdb9owFIb/C9dQnA9vpVI1hSYNSWNnoQnB6SoEdsg30CQQ4l8/aItWVdrVNJVWlmUd6ZyL87yv34eHjtDpdqwkiuvDG9f1prrq9ylb9eZVFdZVL9xeLMv1qk6W7QVdF/1K6p/qXriqw3JTJlXYWyZ5eGzuh63ZkOl4baTrhBQDTsSYWuJtSsSBsFiN+fRmEONJs8Oq0iBVgfZts6MjczcvJikbYWpxKh97qITzlxoX05tLjtSsRXmzs30DBj6RsRrnWI0gSZ2GcI8jToHtO4BwKhFXA4ijGrkexK7TYjUD+AZyVtBk6Vwt1hWNr26bhgkW3mUzm3lkYZOfrqSbdCaogVPyaT0m0XA+lraJbPxoElbH16IMwK8tAOI3us7X5TXoHo/wP7kFm4U+oRaAhLjBZuzm3kTbaNSDpe2y1PZxbK2wGLTm4HUrZLp0Ox/GrLcZz54ML7gbo6VVbblVyUrr24NyH/KSjiKverPVuUofJy/SU/l5jhsS8YmEeATRs/RmFuhIIKIj4dTMke5JgRtn2HdO0u9tle5R+056DPxgsMBRwoZ39k74xoogHdnhpS8obIrZUl+h78JTxpaN8nHS/wu3SX7iduwlIpGwmseYezJ2cXGwTWqrnox8Dwaq1hLf2QdqJOPUeMsN2PfvuKVbw9Ssu32omJjEzqwdLKijaAxks0i/F3VBcedJ0BsGzHvldnm+3oqaV0bwOEdS7bCzmRz8BbGvQeSaeeCy+OgtJJoZdhXR1r1DlPxhhLkm4vfeMooVrfeA72Xj6c6972kmJHBbZ0N7mG8YKDyNRRY2UTYEbz/gY/ehIx5QqfMyO1diZxvEIoTd0/0Kcfwhu33JnP4U9M4mrT8lvbPK8b/Te3z8DQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ThemeID = _t, Theme = _t, home = _t, #"document-view" = _t, #"document-search" = _t, #"document-test" = _t, document = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ThemeID", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

