table E10_DIM_DATE
	lineageTag: 9a31646e-3465-480b-87d3-d755b2387c07

	column FullDateAlternateKey
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 1f36ebd6-dda0-4e6c-9b82-a6664d49a336
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		lineageTag: eadf9177-5a47-4f67-835a-9faca2f8cfdd
		summarizeBy: none
		sourceColumn: Year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: double
		lineageTag: 1b67ceb8-0986-46e9-b40a-c032bdc5a989
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: e6209484-d694-4be2-bb54-30eb528c14e8
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Short Month Name'
		dataType: string
		lineageTag: bbe12535-e393-4abf-9397-8369bf95136d
		summarizeBy: none
		sourceColumn: Short Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: double
		lineageTag: ab077c1e-3188-43b8-89c0-5f6ce6200f85
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year'
		dataType: double
		lineageTag: 9c05a7bb-6e8e-4c71-82ed-1c60cf32bee5
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Month'
		dataType: double
		lineageTag: 044fe882-60fb-4b84-9ada-0c4f451a48c7
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: double
		lineageTag: 9960b4a7-0038-444e-8b6f-ac69c1843fd3
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: double
		lineageTag: 16968791-3995-420d-a830-d0e84c33fb3a
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Year'
		dataType: double
		lineageTag: 8c06af53-fde6-47e5-81b7-31ab09a5f5e1
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name'
		dataType: string
		lineageTag: 9adb1820-dc36-4e67-b0ab-a14e0b3d77de
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 663f3afc-df8b-4b65-9c13-2fc7223fddae
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Year Month 2'
		dataType: string
		lineageTag: 29b7bcfa-de17-4c14-bade-fccaefadce38
		summarizeBy: none
		sourceColumn: Year Month 2

		annotation SummarizationSetBy = Automatic

	column 'Month Year'
		dataType: string
		lineageTag: a3e82b49-0f10-4741-9600-10743ba7c0fb
		summarizeBy: none
		sourceColumn: Month Year
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 88e1f8f8-183e-41c1-be13-a756c001ab43
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDate
		dataType: string
		lineageTag: 9b1cc3c0-b891-497a-9bc6-291bf5b8ad37
		summarizeBy: none
		sourceColumn: FullDate

		annotation SummarizationSetBy = Automatic

	hierarchy 'FullDateAlternateKey Hierarchy'
		lineageTag: 502c2485-0d37-4768-8088-a219df8187a6

		level FullDateAlternateKey
			lineageTag: 98a75e07-b725-49e4-b7ca-713e43341b06
			column: FullDateAlternateKey

		level Year
			lineageTag: 6b858456-1f08-4f94-b69f-cba4cf496a90
			column: Year

		level 'Month Name'
			lineageTag: 3af5edc0-7f25-4fa3-9785-806f6a701757
			column: 'Month Name'

	partition E10_DIM_DATE = m
		mode: import
		source =
				let
				    StartDate = Date.From(MIN_YEAR{0}),
				    EndDate = Date.From(#"MAX_YEAR"{0}),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "FullDateAlternateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FullDateAlternateKey", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([FullDateAlternateKey]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([FullDateAlternateKey]), type number),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([FullDateAlternateKey]), type text),
				    #"Inserted Short Month Name" = Table.AddColumn(#"Inserted Month Name", "Short Month Name", each Text.Start(Date.MonthName([FullDateAlternateKey]),3), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Short Month Name", "Quarter", each Date.QuarterOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([FullDateAlternateKey]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([FullDateAlternateKey]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([FullDateAlternateKey]), type number),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([FullDateAlternateKey]), type text),
				    #"Added Custom Column" = Table.AddColumn(#"Inserted Day Name", "Year Month", each Text.Combine({Date.ToText([FullDateAlternateKey], "yyyy"), Date.ToText([FullDateAlternateKey], "MM")}), type text),
				    #"Added Custom Column 2" = Table.AddColumn(#"Added Custom Column", "Year Month 2", each Text.Combine({Date.ToText([FullDateAlternateKey], "MM"),"." , Date.ToText([FullDateAlternateKey], "yyyy")}), type text),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom Column 2",{{"Year Month", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type2",{{"Year Month", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Custom", each Text.Combine({Date.ToText([FullDateAlternateKey], "MMM"), ".", Text.From(Date.Year([FullDateAlternateKey]))}, "")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Custom", "Month Year"}}),
				    Custom1 = Table.AddColumn(#"Renamed Columns1", "Custom", each Date.Year([FullDateAlternateKey]) * 10000 + Date.Month([FullDateAlternateKey]) * 100 + Date.Day([FullDateAlternateKey]), Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(Custom1,{{"Custom", "DateKey"}}),
				    Custom2 = Table.AddColumn(#"Renamed Columns2", "FullDate", each Text.Combine({Date.ToText([FullDateAlternateKey], "dd"),"." ,Date.ToText([FullDateAlternateKey], "MM"),"." , Date.ToText([FullDateAlternateKey], "yyyy")}), type text)
				in
				    Custom2

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

