table E10_PC_CHECKS
	lineageTag: c00937cd-741e-4546-a255-015d7c2c55f4

	column RID
		dataType: string
		lineageTag: 1997c5f0-80fb-4920-bc15-35bde9904c7a
		summarizeBy: none
		sourceColumn: RID

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: cc6ce94a-7579-4aac-a7b4-bb07a9bdfcc0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column PC_CHECK_YEAR
		dataType: int64
		formatString: 0
		lineageTag: 2e305127-b857-4170-ac33-71efe50fea00
		summarizeBy: none
		sourceColumn: PC_CHECK_YEAR

		annotation SummarizationSetBy = User

	column PRODUCT_NAME
		dataType: string
		lineageTag: a17dbfcd-31f8-4118-973f-d24f1c7fd4af
		summarizeBy: none
		sourceColumn: PRODUCT_NAME

		annotation SummarizationSetBy = Automatic

	column CREATED_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 45cc3a33-6642-4919-8f07-1aad81be0d84
		summarizeBy: none
		sourceColumn: CREATED_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column INPROGRESS_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 08225ccc-3bcb-46bb-b0d1-f5689ac076f1
		summarizeBy: none
		sourceColumn: INPROGRESS_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column INREVIEW_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: ae5fb8ad-dc19-4f70-bbac-625001ab28a0
		summarizeBy: none
		sourceColumn: INREVIEW_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column INAPPROVAL_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: b304f937-caf8-4613-9192-3cdd16fd4f13
		summarizeBy: none
		sourceColumn: INAPPROVAL_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column RESOLUTION_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72293695-714b-4205-8067-7d8c7debe3b2
		summarizeBy: none
		sourceColumn: RESOLUTION_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RATING
		dataType: string
		lineageTag: fe71f6ec-38e5-4647-b400-a3be47a8e6ad
		summarizeBy: none
		sourceColumn: RATING

		annotation SummarizationSetBy = Automatic

	column TYPE_OF_GUIDANCE
		dataType: string
		lineageTag: 0b763f50-d1d0-4280-93b9-11000bac0193
		summarizeBy: none
		sourceColumn: TYPE_OF_GUIDANCE

		annotation SummarizationSetBy = Automatic

	column BU_CODE
		dataType: string
		lineageTag: 95ac91cc-27a7-4cd9-a313-00a4770c6b0a
		summarizeBy: none
		sourceColumn: BU_CODE

		annotation SummarizationSetBy = Automatic

	column PC_CHECK_NAME
		dataType: string
		lineageTag: 044c01db-a849-4fc1-855b-88d20ee9f73e
		summarizeBy: none
		sourceColumn: PC_CHECK_NAME

		annotation SummarizationSetBy = Automatic

	column PC_CHECK_STATUS
		dataType: string
		lineageTag: 65d6897a-321a-487d-875c-893160121d4b
		summarizeBy: none
		sourceColumn: PC_CHECK_STATUS

		annotation SummarizationSetBy = Automatic

	column START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: a6a2f91c-3c70-4e1c-95d4-5ade50b60d8a
		summarizeBy: none
		sourceColumn: START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column END_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 178e4dba-b428-4536-8188-08d60420222c
		summarizeBy: none
		sourceColumn: END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column EVIDENCE_DESC
		dataType: string
		lineageTag: 62c465f4-eecd-4535-9881-4904f5f6e3f0
		summarizeBy: none
		sourceColumn: EVIDENCE_DESC

		annotation SummarizationSetBy = Automatic

	column GUIDANCE_CREATED_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: c2ab8f26-2268-43e2-8205-22cc37a195ec
		summarizeBy: none
		sourceColumn: GUIDANCE_CREATED_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column GUIDANCE_DUE_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 035bd0a6-5402-4e88-b235-71dc7ef83e41
		summarizeBy: none
		sourceColumn: GUIDANCE_DUE_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column GUIDANCE_RESOLUTION_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 0d9422d4-1ff7-479d-b9aa-61442032502a
		summarizeBy: none
		sourceColumn: GUIDANCE_RESOLUTION_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TOPIC_ID
		dataType: string
		lineageTag: a649ea5c-d977-475d-82f2-aafd26a4ed20
		summarizeBy: none
		sourceColumn: TOPIC_ID

		annotation SummarizationSetBy = Automatic

	column QUESTION_ID
		dataType: string
		lineageTag: aa53699b-4638-4a02-9c55-cb19fa54f2e6
		summarizeBy: none
		sourceColumn: QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column GUIDANCE_DESC
		dataType: string
		lineageTag: 37bbcb6f-39ef-4425-8cc9-04345a26150b
		summarizeBy: none
		sourceColumn: GUIDANCE_DESC

		annotation SummarizationSetBy = Automatic

	column END_DATE_PLUS7
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: fbb84d21-3e6b-4ea5-a8e0-0504fb14a459
		summarizeBy: none
		sourceColumn: END_DATE_PLUS7

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column END_DATE_PLUS35
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: cdd03f77-a1b9-4b7a-b97f-88b4311fa9d7
		summarizeBy: none
		sourceColumn: END_DATE_PLUS35

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column GUIDANCE_STATUS_CODE
		dataType: double
		lineageTag: bad64703-390e-4cf2-896f-b3a7bfd009b4
		summarizeBy: sum
		sourceColumn: GUIDANCE_STATUS_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GUIDANCE_STATUS_DESC
		dataType: string
		lineageTag: 06b1078b-8458-426d-ab7e-6e9aac2f601c
		summarizeBy: none
		sourceColumn: GUIDANCE_STATUS_DESC

		annotation SummarizationSetBy = Automatic

	column 'Number of check'
		dataType: int64
		formatString: 0
		lineageTag: ffdb6d07-cf93-4532-b8e4-996828e12514
		summarizeBy: sum
		sourceColumn: Number of check

		annotation SummarizationSetBy = Automatic

	column 'Number of question'
		dataType: int64
		formatString: 0
		lineageTag: 3d1d2034-8033-4740-9404-5edabbcd46dc
		summarizeBy: sum
		sourceColumn: Number of question

		annotation SummarizationSetBy = Automatic

	column RID_QUESTIONID
		dataType: string
		lineageTag: 481fafdd-ee1c-47be-810c-9a8844dda4e9
		summarizeBy: none
		sourceColumn: RID_QUESTIONID

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ISO_CODE
		dataType: string
		lineageTag: 3f001f9c-cffe-468f-bccd-2e27a7528aff
		summarizeBy: none
		sourceColumn: COUNTRY_ISO_CODE

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: f33d1e92-7d7f-434e-b2d4-05da09f36148
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	column OE_DESCRIPTION_OF_EVIDENCE
		dataType: string
		lineageTag: a81d632d-b924-419e-a00d-8200ab449472
		summarizeBy: none
		sourceColumn: OE_DESCRIPTION_OF_EVIDENCE

		annotation SummarizationSetBy = Automatic

	column HLCP_PHASE_1
		dataType: string
		lineageTag: a313511e-933c-4bd8-9cb7-b65e0f7ad5a6
		summarizeBy: none
		sourceColumn: HLCP_PHASE_1

		annotation SummarizationSetBy = Automatic

	column HLCP_PHASE_2
		dataType: string
		lineageTag: 80b58087-eb83-4ffb-888e-0c21bcb69bd6
		summarizeBy: none
		sourceColumn: HLCP_PHASE_2

		annotation SummarizationSetBy = Automatic

	column HLCP_PHASE_3
		dataType: string
		lineageTag: 3007bf92-0e0e-466f-925d-949dd547698a
		summarizeBy: none
		sourceColumn: HLCP_PHASE_3

		annotation SummarizationSetBy = Automatic

	column HLCP_PHASE_4
		dataType: string
		lineageTag: 9a265183-d52f-465a-ae2a-936027ac3640
		summarizeBy: none
		sourceColumn: HLCP_PHASE_4

		annotation SummarizationSetBy = Automatic

	column HLCP_PHASE_5
		dataType: string
		lineageTag: 548355b1-18a5-43e3-8daa-2e00bd09c2e1
		summarizeBy: none
		sourceColumn: HLCP_PHASE_5

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_YEAR
		dataType: int64
		formatString: 0
		lineageTag: a4733164-e788-4237-af90-461d01bd19fc
		summarizeBy: sum
		sourceColumn: PREVIOUS_YEAR

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_TOPIC_ID
		dataType: string
		lineageTag: fec22b50-9cb5-492f-8dab-c089a65a640b
		summarizeBy: none
		sourceColumn: PREVIOUS_TOPIC_ID

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_TOPIC_NAME
		dataType: string
		lineageTag: 8a130de3-7ede-4f8b-ab63-1d1ea2cbbabc
		summarizeBy: none
		sourceColumn: PREVIOUS_TOPIC_NAME

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_QUESTION_ID
		dataType: string
		lineageTag: 5410c1c1-be03-4036-a622-0c70e0ff1acf
		summarizeBy: none
		sourceColumn: PREVIOUS_QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_QUESTION
		dataType: string
		lineageTag: de59d75e-05ed-4ea7-a1b0-9104b89f19c8
		summarizeBy: none
		sourceColumn: PREVIOUS_QUESTION

		annotation SummarizationSetBy = Automatic

	column L2_ID
		dataType: string
		lineageTag: 474df76c-93b4-4795-98d7-d6d9e7297e45
		summarizeBy: none
		sourceColumn: L2_ID

		annotation SummarizationSetBy = Automatic

	column PC_CHECK_YEAR_QUESION_ID
		dataType: string
		lineageTag: 3d2980af-8f72-42b5-bc43-e5d18bca3325
		summarizeBy: none
		sourceColumn: PC_CHECK_YEAR_QUESION_ID

		annotation SummarizationSetBy = Automatic

	partition E10_PC_CHECKS = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="
				    SELECT 
				        (PC_CHECK_YEAR || QUESTION_ID) AS PC_CHECK_YEAR_QUESION_ID,
				        RID, 
				        ID, 
				        PC_CHECK_NAME, 
				        PC_CHECK_STATUS, 
				        OE_CODE, 
				        BU_CODE,  
				        COUNTRY_ISO_CODE, 
				        START_DATE, 
				        END_DATE, 
				        PRODUCT_NAME, 
				        CREATED_DATE, 
				        INPROGRESS_DATE, 
				        INREVIEW_DATE, 
				        INAPPROVAL_DATE, 
				        RESOLUTION_DATE, 
				        PC_CHECK_YEAR, 
				        TOPIC_ID,
				        QUESTION_ID,
				        OE_DESCRIPTION_OF_EVIDENCE,
				        PREVIOUS_YEAR, 
				        PREVIOUS_TOPIC_ID, 
				        PREVIOUS_TOPIC_NAME, 
				        PREVIOUS_QUESTION_ID, 
				        PREVIOUS_QUESTION,  
				        HLCP_PHASE_1, 
				        HLCP_PHASE_2, 
				        HLCP_PHASE_3, 
				        HLCP_PHASE_4, 
				        HLCP_PHASE_5, 
				        RATING, 
				        EVIDENCE_DESC, 
				        TYPE_OF_GUIDANCE, 
				        GUIDANCE_STATUS_CODE, 
				        GUIDANCE_STATUS_DESC, 
				        GUIDANCE_DESC, 
				        GUIDANCE_CREATED_DATE, 
				        GUIDANCE_DUE_DATE, 
				        GUIDANCE_RESOLUTION_DATE,  
				        L2_ID
				    FROM MARD_PCMS.X_IFR_GRC_EPIC10_PCC"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"Pending Approval","In Approval",Replacer.ReplaceText,{"PC_CHECK_STATUS"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Approved by omission","Approved",Replacer.ReplaceText,{"PC_CHECK_STATUS"}),
				    #"Added Custom1" = Table.AddColumn(#"Replaced Value1", "END_DATE_PLUS7", each Date.AddDays([END_DATE], 7)),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "END_DATE_PLUS35", each Date.AddDays([END_DATE], 35)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom2",{{"START_DATE", type date}, {"END_DATE", type date}, {"CREATED_DATE", type date}, {"RESOLUTION_DATE", type date}, {"INPROGRESS_DATE", type date}, {"INREVIEW_DATE", type date}, {"INAPPROVAL_DATE", type date}, {"GUIDANCE_CREATED_DATE", type date}, {"GUIDANCE_DUE_DATE", type date}, {"GUIDANCE_RESOLUTION_DATE", type date}, {"END_DATE_PLUS7", type date}, {"END_DATE_PLUS35", type date}, {"PREVIOUS_YEAR", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"PC_CHECK_YEAR", "OE_CODE"}, #"Number of check", {"PC_CHECK_YEAR", "OE"}, "Number of check", JoinKind.FullOuter),
				    #"Expanded Number of check" = Table.ExpandTableColumn(#"Merged Queries", "Number of check", {"Count"}, {"Number of check.Count"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Number of check",{{"Number of check.Count", "Number of check"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"PC_CHECK_YEAR", "TOPIC_ID"}, #"Number of question", {"PC_CHECK_YEAR", "TOPIC_ID"}, "Number of question", JoinKind.FullOuter),
				    #"Expanded Number of question" = Table.ExpandTableColumn(#"Merged Queries1", "Number of question", {"Count"}, {"Number of question.Count"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Number of question",{{"Number of question.Count", "Number of question"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns1", "RID_QUESTIONID", each Text.Trim([RID]) & Text.Trim([QUESTION_ID])),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Custom3",{{"OE_CODE", "OE"}})
				in
				    #"Renamed Columns2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

