table E10_DIM_PHASES
	lineageTag: 97ab1b33-27c5-4d61-9027-7122aa353288

	column Index
		dataType: int64
		formatString: 0
		lineageTag: eebf1145-bd55-41e7-a2a6-44ffbcbd571b
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		lineageTag: f118ae1a-486c-4e87-a5d2-aec31e29f7ea
		summarizeBy: none
		sourceColumn: Phase

		annotation SummarizationSetBy = Automatic

	column 'Phase Name'
		dataType: string
		lineageTag: 7693d062-cbab-4613-b058-df0729458793
		summarizeBy: none
		sourceColumn: Phase Name
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition E10_DIM_PHASES = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bY7NCoMwEIRfZclZEP8eQGzBQsFAjhLEbpc2RZPUJH3+xvQk9LY7zMw348gKlrHOaCTrgT9nR/Hvrx2feN+K81QwmY2sjCLfzIvQg0NjKYcW30E55ZXROVw0htu83/86ytRRRfFEH1qMXUn7HATOi9KPo7dK3jqKgjZFDiL2HvCHGSxtiXLM1CnT7Bt3OAzBHw0Nk/IL", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, #"Phase Name" = _t, Phase = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Index", Int64.Type}, {"Phase", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

