table L2R_VALID_YEAR
	lineageTag: a4abddab-f058-4915-be48-84714f6499c4

	measure PRESET_VALID_YEAR = IF(MAX(E10_DIM_RISK_CATEGORIES[VALID_YEAR]) = MAX(L2R_VALID_YEAR[VALID_YEAR]) , 1 , 0)
		formatString: 0
		lineageTag: 3764b75f-917b-46ee-bc60-f5ee2716037d

	measure PRESET_VALID_YEAR_L2R = IF(MAX(E10_DIM_RISK_CATEGORIES[VALID_YEAR]) = MAX(E10_DISTINCT_PC_CHECK_YEAR[DISTINCT_PC_YEAR]) , 1 , 0)
		formatString: 0
		lineageTag: bed7beb2-235a-48ad-8dd3-b99ddd94992e

	column VALID_YEAR
		formatString: 0
		lineageTag: c20f8ffe-ccb5-42cd-bf3d-49b4ed5d2df1
		summarizeBy: sum
		isNameInferred
		sourceColumn: E10_DIM_RISK_CATEGORIES[VALID_YEAR]

		annotation SummarizationSetBy = Automatic

	partition L2R_VALID_YEAR = calculated
		mode: import
		source = VALUES(E10_DIM_RISK_CATEGORIES[VALID_YEAR])

	annotation PBI_Id = 4518742cf842454792a68161a98e080c

