table 'Number of check'
	isHidden
	lineageTag: ebbe8990-90c7-4ad8-a72d-2064548f3b26

	column PC_CHECK_YEAR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9a6cc285-9886-443e-805a-7513e0a82479
		summarizeBy: sum
		sourceColumn: PC_CHECK_YEAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b7b9e13e-d1de-4b7a-ad0f-a7213ae5422f
		summarizeBy: sum
		sourceColumn: Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OE
		dataType: string
		lineageTag: e4e45730-6aa8-44e4-afb7-ba483b3f19c9
		summarizeBy: none
		sourceColumn: OE

		annotation SummarizationSetBy = Automatic

	partition 'Number of check' = m
		mode: import
		source = ```
				let
				    Source = Oracle.Database(ServerName, [HierarchicalNavigation=true, Query="
				    SELECT 
				        RID,
				        PC_CHECK_YEAR,
				        OE_CODE 
				    FROM MARD_PCMS.X_IFR_GRC_EPIC10_PCC"]),
				    #"Grouped Rows" = Table.Group(Source, {"RID", "PC_CHECK_YEAR", "OE_CODE"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Grouped Rows1" = Table.Group(#"Grouped Rows", {"PC_CHECK_YEAR", "OE_CODE"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows1",{{"OE_CODE", "OE"}})
				in
				    #"Renamed Columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

