table _MEASURES
	lineageTag: 5ca3f630-2134-4672-a748-046364e92441

	measure SAMEPERIODPLASTYEAR_SALES = CALCULATE(SUM(FactInternetSales[SalesAmount]), SAMEPERIODLASTYEAR(DimDate[FullDateAlternateKey].[Date]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9b4af259-a9e5-496a-beb9-10360e75d82f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure PREVIOUSYEAR_SALESAMT = CALCULATE(SUM(FactInternetSales[SalesAmount]),PREVIOUSYEAR(DimDate[FullDateAlternateKey].[Date]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Group1
		lineageTag: 92d5fd7c-aeb0-4808-945d-ce8d55a80f0c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Profit = SUMX(FactInternetSales, FactInternetSales[SalesAmount] - (FactInternetSales[OrderQuantity] * RELATED(DimProduct[StandardCost])))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e70cf387-f222-4726-a6f7-c21f3dd3b5e7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Profit2 = SUM(FactInternetSales[SalesAmount]) - SUM(FactInternetSales[ProductStandardCost])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bbd3ef37-cd58-4681-9ab5-ff9584fd911d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Profit3 = SUMX(DimProduct, RELATED(DimProductSubcategory[EnglishProductSubcategoryName]))
		formatString: 0
		lineageTag: 94ea5f8b-7d7d-4227-b6ed-9da58f673779

		changedProperty = IsHidden

	measure CUR_MONTH = MONTH(TODAY())
		formatString: 0
		displayFolder: Group1
		lineageTag: fbc562ef-f28c-4c50-97a3-4eb4b6d1a719

		changedProperty = IsHidden

	measure MAX_SALESAMT = MAX(FactInternetSales[SalesAmount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b1a854f8-8e09-41bd-b9d7-c73db5b2cea9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure MAX_SALESAMT_CAN_TOTAL = SUMX(SUMMARIZE(DimProductSubcategory, DimProductSubcategory[EnglishProductSubcategoryName], "MAX_SALESAMT_2", MAX(FactInternetSales[SalesAmount])), MAX(FactInternetSales[SalesAmount]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 46cd70c0-457d-4731-a6f6-e2b07cee866d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure SELECTEDVALUE_ORG = SELECTEDVALUE(DimOrganization[OrganizationName], "chon nhieu hon 1")
		lineageTag: ef846f25-152d-4ead-bf1d-6efea4317885

		changedProperty = IsHidden

	measure MAX_FILTEREDTABLE = SUMX(FILTER(DimProductSubcategory,DimProductSubcategory[EnglishProductSubcategoryName] = "TOURING BIKES"), [MAX_SALESAMT])
		formatString: 0.00
		lineageTag: a90b8684-e397-4268-b68f-751524bd2f7b

	measure SALES_AMT_SHIPDATE = CALCULATE(SUM(FactResellerSales[SalesAmount]), USERELATIONSHIP(FactResellerSales[ShipDateKey], DimDate[DateKey]), FactResellerSales[ShipDateKey] = 20130104)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bd8b89ab-1176-4dab-9f62-b6382398786b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TODAY_ = TODAY()
		formatString: General Date
		lineageTag: 56f192f2-c5c6-47bc-a2f2-140f0d36e487

	measure NOW_ = NOW()
		formatString: General Date
		lineageTag: 134f0997-1121-4101-a27b-2b09a65c4785

	column _MEASURES
		dataType: int64
		formatString: 0
		lineageTag: 3e883265-732b-4caa-85a6-1ca447f6ff43
		summarizeBy: sum
		sourceColumn: _MEASURES

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _MEASURES-6ceff72c-69c3-45b2-9ea9-89ca7f3e3589 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [_MEASURES = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"_MEASURES", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

