table 'DimOrganization (2)'
	lineageTag: f668ec96-9844-4343-be0d-3a3d371edb6b

	column OrganizationKey
		dataType: int64
		formatString: 0
		lineageTag: d450586b-324f-467b-8712-f6ca692b2ad6
		summarizeBy: count
		sourceColumn: OrganizationKey

		annotation SummarizationSetBy = Automatic

	column ParentOrganizationKey
		dataType: int64
		formatString: 0
		lineageTag: e6e950c1-cbff-44b9-af9e-ba592ec78740
		summarizeBy: none
		sourceColumn: ParentOrganizationKey

		annotation SummarizationSetBy = Automatic

	column PercentageOfOwnership
		dataType: string
		lineageTag: 85661931-0094-411c-b97b-13ded01aeff9
		summarizeBy: none
		sourceColumn: PercentageOfOwnership

		annotation SummarizationSetBy = Automatic

	column OrganizationName
		dataType: string
		lineageTag: e03fcf03-e777-4c14-afd7-33116c7bf2b0
		summarizeBy: none
		sourceColumn: OrganizationName

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: string
		lineageTag: 263f85e8-e2d4-441d-839c-39616e3b5b22
		summarizeBy: none
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 8894e366-5e2e-48ee-a5c2-de7e25808d1f
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	partition 'DimOrganization (2)-070080c1-2259-47e3-b41c-90d2f503493c' = m
		mode: import
		source =
				let
				    Source = DimOrganization,
				    #"Added Custom" = Table.AddColumn(Source, "Custom", each [OrganizationName] & " Manh"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"OrganizationKey", "ParentOrganizationKey", "PercentageOfOwnership", "OrganizationName", "Custom", "CurrencyKey", "DimCurrency", "DimOrganization(OrganizationKey)", "DimOrganization(ParentOrganizationKey)", "FactFinance"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

