table FactResellerSales
	lineageTag: 4650ef2a-725a-4e7f-80d8-993b586df5fa

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 1d95fe3c-3f62-4f8d-8fae-2cb519b65e88
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 68b8750f-2807-4403-a5d4-cccd0a76b9fd
		summarizeBy: count
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 81ec8469-a9c8-46c3-a512-2a5b135d7e4d
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 09bd5d12-db0c-4d37-9f7c-99bba947a9dc
		summarizeBy: count
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: cbf7b862-30eb-4264-beb0-0bd7f0fa6d13
		summarizeBy: count
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 9a8913d7-4093-464c-8616-eacd4eaca18c
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 48b0f7b8-f69b-4713-bc0b-5b0e9a115a8f
		summarizeBy: none
		sourceColumn: PromotionKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 89f376ea-fbc5-409b-8c61-be7e3891bfc8
		summarizeBy: none
		sourceColumn: CurrencyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: c85229f4-df63-41e7-8019-4c937e034a56
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: e5c74fbd-b809-4219-92ac-834c9fca679d
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 34acce68-1225-4eae-9c27-ba3b62828827
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: 26235b85-aa86-431e-b01b-e0efd882cf4c
		summarizeBy: sum
		sourceColumn: RevisionNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 7dbeff93-e5b0-4379-a195-afbd1045ca8c
		summarizeBy: sum
		sourceColumn: OrderQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 37b9ae29-ab0d-4776-9ff0-c72f94208606
		summarizeBy: sum
		sourceColumn: UnitPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ExtendedAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0781bd3a-f6b2-4a7c-8823-c7bdbe39f4f3
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: 2876293d-92e6-40f8-9421-d4c07a9e24c8
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 70fb545a-89e0-4a68-9e69-82739f0fb85c
		summarizeBy: sum
		sourceColumn: DiscountAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0622e776-a38d-460a-a9b0-c939c17830cb
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TotalProductCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2c434b07-764b-495f-b5c4-04f05aa9da08
		summarizeBy: sum
		sourceColumn: TotalProductCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0d8ddb2e-51ba-40b7-b04d-6e47351716e2
		summarizeBy: sum
		sourceColumn: SalesAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e8ea5a63-780e-4de3-83d7-8d38d3bdc17d
		summarizeBy: sum
		sourceColumn: TaxAmt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Freight
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bf187e4e-56e3-47b3-a6e1-4aac488b4b38
		summarizeBy: sum
		sourceColumn: Freight

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column CarrierTrackingNumber
		dataType: string
		lineageTag: 4ab0b22d-0f8f-4273-821d-175839ad83d4
		summarizeBy: none
		sourceColumn: CarrierTrackingNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerPONumber
		dataType: string
		lineageTag: 836d6fc4-d2cb-428a-b24f-de6c40ea72a7
		summarizeBy: none
		sourceColumn: CustomerPONumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9c827171-7a75-4a86-ad07-a9532b648303
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 16dff7e3-e4c3-4eb2-ad01-392bd7daa90d
			defaultHierarchy: LocalDateTable_e95e3fdf-7c3d-473c-bcd7-259f382c32da.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c7e91ba8-bdfe-4386-a146-e40f08406f2b
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: e1f8afd2-17e8-40e9-a402-2c817b2e30c7
			defaultHierarchy: LocalDateTable_7949b730-7cc2-49fd-aca5-29e235b52c3e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a1fd2f46-708c-4265-86a7-d756601a2e71
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 37765214-cb65-43ed-881d-1a97bf9716e7
			defaultHierarchy: LocalDateTable_9e5ca266-ccb1-41f2-84da-d715bc6b347f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactResellerSales-3e932335-c241-48d7-9466-777ece3f500f = m
		mode: import
		source =
				let
				    Source = Sql.Database(PRServerName, PRDatabaseName),
				    dbo_FactResellerSales = Source{[Schema="dbo",Item="FactResellerSales"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_FactResellerSales, each [DueDate] >= RangeStart and [DueDate] <= RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

