table OneQ_Dashboard
	lineageTag: 45239804-f716-4daa-bfc0-e9efa77f1636

	column displayName
		dataType: string
		lineageTag: a73a3db6-a9d2-418e-bab5-53e68d4a979c
		summarizeBy: none
		sourceColumn: displayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.displayName'
		dataType: string
		lineageTag: 655e4b0f-5e31-4e41-8b64-7d346f29ddd7
		summarizeBy: none
		sourceColumn: group.member.displayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.mail'
		dataType: string
		lineageTag: 83235d10-a317-46fe-8cc4-d8a56151f156
		summarizeBy: none
		sourceColumn: group.member.mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.userPrincipalName'
		dataType: string
		lineageTag: e05acfba-1728-499b-9ea3-a33acc76e945
		summarizeBy: none
		sourceColumn: group.member.userPrincipalName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'securityPrincipal.sAMAccountName'
		dataType: string
		lineageTag: ef79108a-b7b8-4cee-a6fc-d3f566639183
		summarizeBy: none
		sourceColumn: securityPrincipal.sAMAccountName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column distinguishedName
		dataType: string
		lineageTag: ba49b948-0d80-4735-b845-e00db8cccc16
		summarizeBy: none
		sourceColumn: distinguishedName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'mailRecipient.mail'
		dataType: string
		lineageTag: 6a246639-9ee2-408d-9a00-1508515cdabe
		summarizeBy: none
		sourceColumn: mailRecipient.mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition OneQ_Dashboard-aa7288eb-d1c8-4699-b4d1-bdd80b68229d = m
		mode: import
		source =
				let
				    Source = ActiveDirectory.Domains("apac.bosch.com"),
				    #"de bosch com" = Source{[Domain="de.bosch.com"]}[Object Categories],
				    group1 = #"de bosch com"{[Category="group"]}[Objects],
				    #"Expanded securityPrincipal" = Table.ExpandRecordColumn(group1, "securityPrincipal", {"sAMAccountName"}, {"securityPrincipal.sAMAccountName"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded securityPrincipal", each ([securityPrincipal.sAMAccountName] = "idm2bcd_BBM-OneQ-Dashboard_enduser")),
				    #"Expanded group" = Table.ExpandRecordColumn(#"Filtered Rows", "group", {"member"}, {"group.member"}),
				    #"Expanded group.member" = Table.ExpandListColumn(#"Expanded group", "group.member"),
				    #"Expanded group.member1" = Table.ExpandRecordColumn(#"Expanded group.member", "group.member", {"displayName", "mail", "userPrincipalName"}, {"group.member.displayName", "group.member.mail", "group.member.userPrincipalName"}),
				    #"Expanded mailRecipient" = Table.ExpandRecordColumn(#"Expanded group.member1", "mailRecipient", {"mail"}, {"mailRecipient.mail"})
				in
				    #"Expanded mailRecipient"

	annotation PBI_ResultType = Table

