table Parameter
	lineageTag: bbdc3713-6602-4a41-95fb-e258cd4f0a1e

	measure 'Parameter Value' = SELECTEDVALUE('Parameter'[Parameter], 5)
		formatString: 0
		lineageTag: b67cc8f9-c663-4fdf-8c87-16d56c6cb96a

	column Parameter
		formatString: 0
		lineageTag: 0a46d5a3-591b-47d6-bec4-34234df7d445
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Parameter-94851a1c-c00f-47eb-b1af-a3ad12a4733b = calculated
		mode: import
		source = GENERATESERIES(0, 20, 1)

	annotation PBI_Id = 863a124d0e59414f96f9a2e713ed53a0

