table PCMS_PRJ_TEAM
	lineageTag: 8259cbd6-e9d2-4aec-9f42-bf0cfb43ca6a

	column displayName
		dataType: string
		lineageTag: d3afef1c-aff0-4cba-a6e3-c58b87a24853
		summarizeBy: none
		sourceColumn: displayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.displayName'
		dataType: string
		lineageTag: 226a9416-e055-49fb-970e-eb3307910ca5
		summarizeBy: none
		sourceColumn: group.member.displayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.mail'
		dataType: string
		lineageTag: 7b1d3d86-dda5-4ea4-b5af-59f31407c74e
		summarizeBy: none
		sourceColumn: group.member.mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'group.member.userPrincipalName'
		dataType: string
		lineageTag: e39fb71e-0c59-457e-911c-b4f79729df3f
		summarizeBy: none
		sourceColumn: group.member.userPrincipalName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'mailRecipient.mail'
		dataType: string
		lineageTag: 93d0e52f-5b04-45ed-96e6-3eb4237f8171
		summarizeBy: none
		sourceColumn: mailRecipient.mail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column distinguishedName
		dataType: string
		lineageTag: 820bb93d-6c2b-4817-a4bb-745ba3ab46cf
		summarizeBy: none
		sourceColumn: distinguishedName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition PCMS_PRJ_TEAM-0c4d17c8-fbf3-41dd-b3f0-82539d81cd43 = m
		mode: import
		source =
				let
				    Source = ActiveDirectory.Domains("apac.bosch.com"),
				    bosch.com = Source{[Domain="bosch.com"]}[#"Object Categories"],
				    group1 = bosch.com{[Category="group"]}[Objects],
				    #"Expanded mailRecipient" = Table.ExpandRecordColumn(group1, "mailRecipient", {"mail"}, {"mailRecipient.mail"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded mailRecipient", each ([mailRecipient.mail] = "RB_C_PCO_PCMS_Project_Team@bcn.bosch.com")),
				    #"Expanded group" = Table.ExpandRecordColumn(#"Filtered Rows", "group", {"member"}, {"group.member"}),
				    #"Expanded group.member" = Table.ExpandListColumn(#"Expanded group", "group.member"),
				    #"Expanded group.member1" = Table.ExpandRecordColumn(#"Expanded group.member", "group.member", {"displayName", "mail", "userPrincipalName"}, {"group.member.displayName", "group.member.mail", "group.member.userPrincipalName"})
				in
				    #"Expanded group.member1"

	annotation PBI_ResultType = Table

