table 'TEST_CASESENSITVE_FACT (2)'
	lineageTag: 22c7620a-6ac3-443b-8eb4-dbd7f58a0c36

	column Name
		dataType: string
		lineageTag: 8e4c6a41-e940-4c82-8fa0-0e49a8c65882
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Name_Index
		dataType: string
		lineageTag: 7fbf8d1e-2698-4d47-991f-faa3cff152a0
		summarizeBy: none
		sourceColumn: Name_Index

		annotation SummarizationSetBy = Automatic

	column gia_tri_can_tim
		dataType: string
		lineageTag: 35706956-b532-4c28-a46a-518df21da042
		summarizeBy: none
		sourceColumn: gia_tri_can_tim

		annotation SummarizationSetBy = Automatic

	partition 'TEST_CASESENSITVE_FACT (2)-1e823e7b-c5fd-461b-a485-0c5de9a96144' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8nX081CK1YlWyk3MywAzfGEMn0w4ww/CyIGJlGTAFIXAWYPOpFgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Name_Index", each List.PositionOf(TEST_CASESENSITVE[Name],[Name])),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Custom", each TEST_CASESENSITVE[Index]{[Name_Index]}),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom1",{{"Custom", "gia_tri_can_tim"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

