table TEST_CASESENSITVE_FACT
	lineageTag: 44f1e1ef-4482-4ee2-a3c7-ba41a4832c48

	column Name
		dataType: string
		lineageTag: 9477c45b-e8f1-4151-89ac-426f70a5498a
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'TEST_CASESENSITVE.Name'
		dataType: string
		lineageTag: c7934ae8-1eac-4a3f-b5fe-8477d5bc0626
		summarizeBy: none
		sourceColumn: TEST_CASESENSITVE.Name

		annotation SummarizationSetBy = Automatic

	column 'TEST_CASESENSITVE.Index'
		dataType: int64
		formatString: 0
		lineageTag: bf39a09c-76ad-4256-92ac-7afea1c53dee
		summarizeBy: sum
		sourceColumn: TEST_CASESENSITVE.Index

		annotation SummarizationSetBy = Automatic

	partition TEST_CASESENSITVE_FACT-2037ad51-8a0b-4118-96f0-17fc2ec84bbe = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8nX081CK1YlWyk3MywAzfGEMn0w4ww/CyIGJlGTAFIXAWYPOpFgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Name"}, TEST_CASESENSITVE, {"Name"}, "TEST_CASESENSITVE", JoinKind.LeftOuter),
				    #"Expanded TEST_CASESENSITVE" = Table.ExpandTableColumn(#"Merged Queries", "TEST_CASESENSITVE", {"Name", "Index"}, {"TEST_CASESENSITVE.Name", "TEST_CASESENSITVE.Index"}),
				    #"Sorted Rows" = Table.Sort(#"Expanded TEST_CASESENSITVE",{{"Name", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

