table vAssocSeqOrders
	lineageTag: 59e5d2e3-98af-4cbf-aa18-0b6c9fe0f095

	column 'OrderNumber.1'
		dataType: string
		lineageTag: 5914053a-d48f-46ff-9f70-5e8321f2109e
		summarizeBy: none
		sourceColumn: OrderNumber.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'OrderNumber.2'
		dataType: int64
		formatString: 0
		lineageTag: 82408ce8-678f-403d-ab34-664e44cdddcf
		summarizeBy: sum
		sourceColumn: OrderNumber.2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 054a28fd-db31-4ec6-8476-9d6c888954a8
		summarizeBy: count
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ef6bd368-c87e-421f-9e06-b93967357297
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IncomeGroup
		dataType: string
		lineageTag: ff2f5f57-c066-486a-83e7-d75ed4d2955b
		summarizeBy: none
		sourceColumn: IncomeGroup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Text Range'
		dataType: string
		lineageTag: f21cb317-0951-4f2c-902f-6c8bf32c7fe0
		summarizeBy: none
		sourceColumn: Text Range

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Text Range.1'
		dataType: string
		lineageTag: 9fe83c1f-4bc4-48e9-bc6a-3b0e9a22ffb8
		summarizeBy: none
		sourceColumn: Text Range.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Length
		dataType: int64
		formatString: 0
		lineageTag: dc813e65-d8a9-4798-a9a0-a427e4677eb2
		summarizeBy: sum
		sourceColumn: Length

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'First Characters'
		dataType: string
		lineageTag: 344f0f41-c1c1-4d93-a779-32635522d12a
		summarizeBy: none
		sourceColumn: First Characters

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition vAssocSeqOrders-c032c57f-c259-43b5-a5bf-7c921dba6378 = m
		mode: import
		source =
				let
				    Source = Sql.Database(PRServerName, PRDatabaseName),
				    dbo_vAssocSeqOrders = Source{[Schema="dbo",Item="vAssocSeqOrders"]}[Data],
				    #"Inserted Text Range" = Table.AddColumn(dbo_vAssocSeqOrders, "Text Range", each Text.Middle([OrderNumber], 0, 2), type text),
				    #"Inserted Text Range1" = Table.AddColumn(#"Inserted Text Range", "Text Range.1", each Text.Middle([OrderNumber], 2, 1000), type text),
				    #"Split Column by Position" = Table.SplitColumn(#"Inserted Text Range1", "OrderNumber", Splitter.SplitTextByPositions({0, 2}, false), {"OrderNumber.1", "OrderNumber.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Position",{{"OrderNumber.1", type text}, {"OrderNumber.2", Int64.Type}}),
				    #"Inserted Text Length" = Table.AddColumn(#"Changed Type", "Length", each Text.Length([OrderNumber.1]), Int64.Type),
				    #"Inserted First Characters" = Table.AddColumn(#"Inserted Text Length", "First Characters", each Text.Start([Region], 5), type text)
				in
				    #"Inserted First Characters"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

