table DIM_DATE
	lineageTag: e19b88cc-ebd2-4a31-8cff-4a6f9865e983

	column FullDateAlternateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72846f8a-212e-4854-9352-f46dc86b9b8a
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5526a605-e5b5-4e6f-8dc4-240a4595cfe4
		summarizeBy: none
		sourceColumn: Year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: double
		lineageTag: 0c52a921-1486-4973-88d3-b7478cc6c704
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: 89ff91ed-b305-4f13-9177-cc1c4a9d1932
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Short Month Name'
		dataType: string
		lineageTag: 0574e358-1d8d-4c19-a718-476365f47f42
		summarizeBy: none
		sourceColumn: Short Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: double
		lineageTag: a8caa414-cefd-480e-bc9a-77dafb0697af
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Year'
		dataType: double
		lineageTag: 2732ddc0-997e-45bc-912e-1da70c45b11d
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of Month'
		dataType: double
		lineageTag: 76c96581-5358-4fc5-8b14-a1b98b44b05e
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: double
		lineageTag: 16739855-a8df-4cd0-bef2-3cd0afa049cb
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week'
		dataType: double
		lineageTag: b47a729d-8ce5-437b-9d7f-4a5fcb6dd9d8
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Year'
		dataType: double
		lineageTag: 6c087ad6-f038-4026-b82f-8eb1fd589ea4
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name'
		dataType: string
		lineageTag: 91d2dcf4-e893-4e57-8cf0-cf8df95095b0
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: b2412f3d-d99f-4df5-a218-969f260f4a16
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Year Month 2'
		dataType: string
		lineageTag: 3cf09c1b-e139-4f50-9c66-52f551856c21
		summarizeBy: none
		sourceColumn: Year Month 2

		annotation SummarizationSetBy = Automatic

	column 'Month Year'
		dataType: string
		lineageTag: 9cbf1f11-cb68-4546-af02-89f234cf12e7
		summarizeBy: none
		sourceColumn: Month Year
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: fcb98df1-a545-413d-9d63-ea7ce9b2d159
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDate
		dataType: string
		lineageTag: e60f3dd3-3e5a-43b9-b678-8825429b9710
		summarizeBy: none
		sourceColumn: FullDate

		annotation SummarizationSetBy = Automatic

	hierarchy 'FullDateAlternateKey Hierarchy'
		lineageTag: bfa27644-dec8-4edf-896b-28eb502318be

		level FullDateAlternateKey
			lineageTag: 9e773896-3929-4bcf-84bf-6a7f8a897778
			column: FullDateAlternateKey

	partition DIM_DATE = m
		mode: import
		source =
				let
				    StartDate = Date.From(SOM_MIN_CREATION_DATE{0}),
				    EndDate = Date.From(#"EOM_MAX_CREATION_DATE"{0}),
				    NumberOfDays = Duration.Days( EndDate - StartDate ),
				    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "FullDateAlternateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FullDateAlternateKey", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([FullDateAlternateKey]), type number),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([FullDateAlternateKey]), type number),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([FullDateAlternateKey]), type text),
				    #"Inserted Short Month Name" = Table.AddColumn(#"Inserted Month Name", "Short Month Name", each Text.Start(Date.MonthName([FullDateAlternateKey]),3), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Short Month Name", "Quarter", each Date.QuarterOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([FullDateAlternateKey]), type number),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([FullDateAlternateKey]), type number),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([FullDateAlternateKey]), type number),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([FullDateAlternateKey]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([FullDateAlternateKey]), type text),
				    #"Added Custom Column" = Table.AddColumn(#"Inserted Day Name", "Year Month", each Text.Combine({Date.ToText([FullDateAlternateKey], "yyyy"), Date.ToText([FullDateAlternateKey], "MM")}), type text),
				    #"Added Custom Column 2" = Table.AddColumn(#"Added Custom Column", "Year Month 2", each Text.Combine({Date.ToText([FullDateAlternateKey], "MM"),"." , Date.ToText([FullDateAlternateKey], "yyyy")}), type text),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom Column 2",{{"Year Month", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type2",{{"Year Month", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Custom", each Text.Combine({Date.ToText([FullDateAlternateKey], "MMM"), ".", Text.From(Date.Year([FullDateAlternateKey]))}, "")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Custom", "Month Year"}}),
				    Custom1 = Table.AddColumn(#"Renamed Columns1", "Custom", each Date.Year([FullDateAlternateKey]) * 10000 + Date.Month([FullDateAlternateKey]) * 100 + Date.Day([FullDateAlternateKey]), Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(Custom1,{{"Custom", "DateKey"}}),
				    Custom2 = Table.AddColumn(#"Renamed Columns2", "FullDate", each Text.Combine({Date.ToText([FullDateAlternateKey], "dd"),"." ,Date.ToText([FullDateAlternateKey], "MM"),"." , Date.ToText([FullDateAlternateKey], "yyyy")}), type text)
				in
				    Custom2

	annotation PBI_ResultType = Table

